### ISSUE TITLE
output message is garbled

### ISSUE THREAD

**Issue by qhuman** [microsoft/vscode-cmake-tools#153] opened 2017-05-20 13:09 UTC
when I build a project, output message like this. I use vs2012 compiler
[vscode] Executing command: cmake --build d:/vscode_test/hello/build --target ALL_BUILD --config Debug -- /m /property:GenerateFullPaths=true
Microsoft(R) ��������汾 4.7.2046.0
[Microsoft .NET Framework �汾 4.0.30319.42000]
��Ȩ���� (C) Microsoft Corporation����������Ȩ����

������ʱ��Ϊ 2017/5/20 16:59:57��
     1>�ڵ� 1 �ϵ���Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(Ĭ��Ŀ��)��
     1>��Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(1)���ڽڵ� 1 �����ɡ�D:\vscode_test\hello\build\ZERO_CHECK.vcxproj��(2) (Ĭ��Ŀ��)��
     2>InitializeBuildStatus:
         ���ڴ�����Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild������Ϊ��ָ����AlwaysCreate����
       CustomBuild:
         ���������Ϊ���¡�
       FinalizeBuildStatus:
         ����ɾ���ļ���Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild����
         ���ڶԡ�Win32\Debug\ZERO_CHECK\ZERO_CHECK.lastbuildstate��ִ�� Touch ����
     2>�����������Ŀ��D:\vscode_test\hello\build\ZERO_CHECK.vcxproj��(Ĭ��Ŀ��)�Ĳ�����
     1>��Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(1)���ڽڵ� 2 �����ɡ�D:\vscode_test\hello\build\hello.vcxproj��(3) (Ĭ��Ŀ��)��
     3>InitializeBuildStatus:
         ���ڴ�����hello.dir\Debug\hello.unsuccessfulbuild������Ϊ��ָ����AlwaysCreate����
       CustomBuild:
         ���������Ϊ���¡�
       ClCompile:
         ���������Ϊ���¡�
       Link:
         ���������Ϊ���¡�
         hello.vcxproj -> D:\vscode_test\hello\build\Debug\hello.exe
       FinalizeBuildStatus:
         ����ɾ���ļ���hello.dir\Debug\hello.unsuccessfulbuild����
         ���ڶԡ�hello.dir\Debug\hello.lastbuildstate��ִ�� Touch ����
     3>�����������Ŀ��D:\vscode_test\hello\build\hello.vcxproj��(Ĭ��Ŀ��)�Ĳ�����
     1>InitializeBuildStatus:
         ���ڴ�����Win32\Debug\ALL_BUILD\ALL_BUILD.unsuccessfulbuild������Ϊ��ָ����AlwaysCreate����
       CustomBuild:
         ���������Ϊ���¡�
       FinalizeBuildStatus:
         ����ɾ���ļ���Win32\Debug\ALL_BUILD\ALL_BUILD.unsuccessfulbuild����
         ���ڶԡ�Win32\Debug\ALL_BUILD\ALL_BUILD.lastbuildstate��ִ�� Touch ����
     1>�����������Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(Ĭ��Ŀ��)�Ĳ�����

�ѳɹ����ɡ�
    0 ������
    0 ������

����ʱ�� 00:00:00.38
[vscode] cmake exited with return code 0

**Comment by vector-of-bool** [comment] 2017-06-04 19:57
That's just utterly bizarre. I've never seen something like that.

What locale and language are you using on your system?

**Comment by ytimenkov** [comment] 2017-06-21 08:56
@qhuman, @memeda, This bug may be caused by non-Latin locale and it is hard to reproduce without having non-english UI.
Could you please slightly patch the extension to check the fix?
 1. Navigate to `%USERPROFILE%\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src`
 2. Edit `util.js`
 3. Find 2 lines (282-283):
~~~
            backlog += data.toString();
            acc[acckey] += data.toString();
~~~
 4. Replace `toString` with `toLocaleString`, so they become:
~~~
            backlog += data.toLocaleString();
            acc[acckey] += data.toLocaleString();
~~~
 5. Reload window and try to build.

**Comment by memeda** [comment] 2017-06-23 07:30
@vector-of-bool  I'm using Chinese Simplified. 
@ytimenkov It seems that the problem still exits. I have checked the locale in Windows setting, it is Chinese as the default, but the message of output in console is messed like 

```
C2065: ��x1��: δ�����ı�ʶ�� 
```

the compiler output the error in Chinese and they were displayed wrongly.

**Comment by vector-of-bool** [comment] 2017-06-24 03:27
It should be possible to reproduce this in a simple test case non-ASCII characters. I'll see if I can make it work.

**Comment by uwydoc** [comment] 2017-08-11 08:22
seems a known bug with vscode itself [#974](https://github.com/Microsoft/vscode/issues/974), not resolved yet

**Comment by eksea** [comment] 2018-05-10 06:10
I encounter the same problem.
vscode version is 1.23.0
CMake Tools version is 0.11.1

![default](https://user-images.githubusercontent.com/8746029/39854751-af66fc6c-545b-11e8-8605-40bcc093a7f4.png)

**Comment by vector-of-bool** [comment] 2018-05-10 16:57
Based on a similar issue we had with vswhere, we've determined that this is related to the console programs emitting text encoded with the default system codepage, whereas CMake Tools assumes UTF-8.  Unfortunately, just _knowing_ the cause isn't sufficient, and I'm not sure how to fix it. There is no way to change the code page of a program without using the console APIs, which NodeJS does not expose.

**Comment by bobbrow** [comment] 2019-07-24 21:41
This appears to have been fixed by the `cmake.outputLogEncoding` setting.  Please let us know if this is working for you, or if there are still issues.

**Closed by bobbrow** 2019-07-24 21:41 UTC
Labels: Feature: build, bug
