### ISSUE TITLE
Unable to automatically determine debugger corresponding to compiler

### ISSUE THREAD

**Issue by jaylotw** [microsoft/vscode-cmake-tools#897] opened 2019-11-11 02:11 UTC
### Brief Issue Summary

I build my C++ code with CMake tools without any problem. However, when I try to debug the code, it output this: 
```
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /home/myname/build --config Debug --target CUDA_test -- -j 42
[build] ninja: no work to do.
[build] Build finished with exit code 0
[debugger] Unable to automatically determine debugger corresponding to compiler: {}
[main] Failed to generate debugger configuration
```
If I use the "CMake: run without debugging" option, then everything works as expected. So I guess the link to the debugger is broken?

### Expected:

1. Launch the debugger for the selected target.
2. Start debugging session.

### Apparent Behavior:

1. Launch the debugger for the selected target.
2. `[debugger] Unable to automatically determine debugger corresponding to compiler: {}`

### Platform and Versions

- **Operating System**: Ubuntu 16.04(SSH)
- **CMake Version**: 3.15
- **VSCode Version**: 1.40.0
- **CMake Tools Extension Version**: 1.2.1
- **Compiler/Toolchain**: GCC 5.5.0/Clang 6.0.0

### Other Notes/Information

I used to run the process without problem. But then I install Anaconda for Python development(and maybe other processes), and now I can't use CMake debug.
Sorry for such a beginner question, but I can't seems to find a similar question online.
Thank you in advance!

**Comment by iboB** [comment] 2019-11-11 10:22
duplicate of  https://github.com/microsoft/vscode-cmake-tools/issues/884

**Closed** 2019-11-11 11:17 UTC
