### ISSUE TITLE
Debug Button Doesn't Work

### ISSUE THREAD

**Issue by Tabrizian** [microsoft/vscode-cmake-tools#1412] opened 2020-08-17 21:28 UTC
### Brief Issue Summary

The debug button doesn't work in vscode-remote inside containers.

### Expected:
Show a list of tragets to select for debug.

### Apparent Behavior:

Show error message below:
`Failed to prepare executable target with name 'undefined'`

### Platform and Versions

- **Operating System**: 
- **CMake Version**:  3.18.1
- **VSCode Version**:  1.48.0
- **CMake Tools Extension Version**:  1.4.1
- **Compiler/Toolchain**:  gcc7.5

**Comment by definelicht** [comment] 2021-01-28 16:26
I'm also getting this when running via SSH to a remote machine:

![target_name_undefined](https://user-images.githubusercontent.com/2845320/106167873-f6925400-618d-11eb-9a54-21924c38434c.gif)

**Comment by andreeis** [comment] 2021-01-28 18:43
Thank you for opening this report. We will investigate why the quickPick with the launch targets is not automatically shown.
One possible reason is a failed configure. Do you confirm that your project configures successfully?

In the meantime, you can specifically select a launch target via the command "CMake: Set Debug Target" in the pallette. Then hopefully the debug operation will work for you. Please let us know if this workaround works.

**Comment by definelicht** [comment] 2021-01-29 09:35
Manually configuring the debug target fixed the issue for me - thank you.

The project configured and built as expected when I experienced this issue, so I don't think the cause was a failed configure.

**Comment by andreeis** [comment] 2021-01-29 16:45
Let us know if it happens again after you reload and don't manually configure anything. Make sure you don't have CMake.configureOnOpen set to false.

**Comment by paleomoon** [comment] 2021-11-19 11:57
This happened when I made a mistake in CMakeList.txt: `set(CMAKE_BUILD_TYPE DEBUG)`.
Change to `set(CMAKE_BUILD_TYPE Debug)` fixed the issue 😂.

**Comment by Eveheeero** [comment] 2023-01-28 17:04
on my case, this happened when CMakePresets.json has no cacheVariables::CMAKE_BUILD_TYPE

**Comment by gcampbell-msft** [comment] 2023-07-06 18:44
Closing this as it seems that the issue comes from when the CMAKE_BUILD_TYPE is incorrectly defined. Please let us know if it should be re-opened or revisited for any reason.

**Closed by gcampbell-msft** 2023-07-06 18:44 UTC
Labels: bug, Feature: debug/launch, investigate

**Comment by cyfex** [comment] 2023-08-11 08:16
For me, CMake: Reset Cmake Tools Extension State (For troubleshooting) works.
