### ISSUE TITLE
symlink loop causes max cpu usage

### ISSUE THREAD

**Issue by jeffr-spire** [microsoft/vscode-cmake-tools#2257] opened 2021-11-19 22:21 UTC
See https://github.com/microsoft/vscode/issues/137478#issuecomment-974509611

The problem described in that issue recurs when this extension is enabled and a `CMakeLists.txt` fie is present in the project.

**Comment by bobbrow** [comment] 2021-11-22 17:32
I was able to reproduce this issue.  It seems to be triggered when we build the list of potential folders with CMakeLists.txt in them for the case where either:
1. CMakeLists.txt is not in the root folder
2. `cmake.sourceDirectory` setting is not set

**Comment by bobbrow** [comment] 2021-11-24 15:52
We plan to release the fix for this on Monday. If you would like to verify the fix in a pre-release version of the extension, please do the following:
1. Download the VSIX here: https://github.com/microsoft/vscode-cmake-tools/suites/4455203062/artifacts/118295075
2. Unzip the VSIX file from the archive
3. Invoke the `Install from VSIX...` command in VS Code and select the VSIX file from step 2.

**Comment by bobbrow** [comment] 2021-11-29 17:56
The fix for this has been released in 1.9.2.

**Closed by bobbrow** 2021-11-29 17:56 UTC
Labels: bug, IMPORTANT, fixed (release pending), Feature: activation
