### ISSUE TITLE
"Run" menu's "Start Debugging" and "Run Without Debugging" are not using CMake

### ISSUE THREAD

**Issue by faucct** [microsoft/vscode-cmake-tools#3367] opened 2023-10-06 11:24 UTC
### Brief Issue Summary

I have opened a CMake project with `compileCommands` configured. The IntelliSense works fine, the debugging and running files via footer panel or shortcuts (Ctrl+F5 and Shift+F5) also works.
But when I go to the "Run" menu and click any of the subject actions, the VSCode tries to build the file not using CMake, but just using some default clang configuration, I guess. It fails to build and after that the file has compilation errors shown in it.
Is there any way to configure VSCode in a such way that those actions would also use CMake?
It is also weird that "Run Without Debugging" has the same shortcut Ctrl+F5 as "CMake: Debug" and when I press the shortcut with the "Run" menu open I see that "Run Without Debugging" is getting clicked, though in reality "CMake: Debug" is being run.

### CMake Tools Diagnostics

```shell
{
  "os": "darwin",
  "vscodeVersion": "1.83.0",
  "cmtVersion": "1.15.31",
  "configurations": [
    {
      "folder": "/Users/faucct/Code/cpp0",
      "cmakeVersion": "3.27.6",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/clang",
        "CXX": "/usr/bin/clang++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///Users/faucct/Code/cpp0/multiplication/test.cpp"
    ],
    "responses": [
      {
        "uri": "file:///Users/faucct/Code/cpp0/multiplication/test.cpp",
        "configuration": {
          "includePath": [
            "/users/faucct/code/cpp0/tools/util",
            "/users/faucct/code/cpp0/multiplication",
            "/users/faucct/code/cpp0/build/_deps/catch2-src/src",
            "/users/faucct/code/cpp0/build/_deps/catch2-build/generated-includes"
          ],
          "defines": [
            "CMAKE_EXPORT_COMPILE_COMMANDS=ON"
          ],
          "compilerPath": "/usr/bin/clang++",
          "compilerArgs": [],
          "compilerFragments": [
            "-g -std=gnu++20 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk",
            "-Wall -Werror -Wextra -Wpedantic"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 29,
    "executablesCount": 26,
    "librariesCount": 2,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

<img width="1624" alt="Screenshot 2023-10-06 at 15 23 19" src="https://github.com/microsoft/vscode-cmake-tools/assets/5202503/0afb3965-b3b7-4918-b4f1-e95941bba98b">

**Comment by sinemakinci1** [comment] 2023-10-10 22:37
Hi @faucct ,
Thanks for reaching out! The default shortcut command for CMake: Debug is **Ctrl**+F5, but the command for Run without Debugging is actually **Shift**+F5. As for running, the run and debug side bar isn't designed to interface with CMake and is designed for single-file runs, but we can definitely look into ways to make the distinction more clear. If you want to build the project using CMake, we'd recommend using the Build and Run icons on the bottom status bar.

**Comment by gcampbell-msft** [comment] 2023-10-13 15:50
Closing this issue since this is by design, thanks!

**Closed by gcampbell-msft** 2023-10-13 15:50 UTC
