### ISSUE TITLE
Cannot debug on Ubuntu after update

### ISSUE THREAD

**Issue by iboB** [microsoft/vscode-cmake-tools#884] opened 2019-11-08 07:49 UTC
### Brief Issue Summary

VSCode updated the plugin to the MS one

I tried launching the debugger. It fails with

> [debugger] Unable to automatically determine debugger corresponding to compiler: {}

I tried this with gcc and clang. Same result

I tried manually setting the debugger: 

```
    "cmake.debugConfig": {
        "type": "GDB",
        "debuggerPath": "/usr/bin/gdb"
    }
```

Same result

### CMake Tools Log
```
2019-11-08T07:45:56.718Z [debug] [cache] Reading CMake cache file /home/bstanimirov/prj/my/app-server/build/CMakeCache.txt
2019-11-08T07:45:56.723Z [debug] [cache] Parsing CMake cache string
2019-11-08T07:45:56.732Z [warning] [debugger] Unable to automatically determine debugger corresponding to compiler: {}
2019-11-08T07:45:56.732Z [debug] [main] Debug configuration from cache: null
2019-11-08T07:45:56.732Z [error] [main] Failed to generate debugger configuration
2019-11-08T07:45:56.733Z [debug] [extension] [8248] cmake.debugTarget finished (returned null)
2019-11-08T07:45:56.746Z [debug] [cache] Reading CMake cache file /home/bstanimirov/prj/my/app-server/build/CMakeCache.txt
2019-11-08T07:45:56.747Z [debug] [cache] Parsing CMake cache string
```

**Comment by iboB** [comment] 2019-11-08 08:16
To anyone having the same issue: I downloaded a .vsix of the old version 1.1.3, uninstalled the MS extension and installed the downloaded one and everything works now

**Comment by exu1977** [comment] 2019-11-08 09:24
I meet the same issue. @iboB where is the old version 1.1.3(.vsix)? thanks

**Comment by iboB** [comment] 2019-11-08 10:56
I talked to the author and he sent it to me. I'm attaching it here. Rename from .zip to .vsix 
[cmake-tools-1.1.3.zip](https://github.com/microsoft/vscode-cmake-tools/files/3824216/cmake-tools-1.1.3.zip)

**Comment by justnope** [comment] 2019-11-08 15:09
If I use gcc-7.4.0 I have the same issues. If I install gcc-8.3.0, I can debug with that version and everything seems to work fine.
clang-6.0.0 also works for me. I did notice when I was installing other versions of gcc & clang it would sometimes stop working. At the time I was trying to get gcc to work so I don't know the exact combinations.

In any case, it would be helpful if during the detection there would be more traces so we can see what's going on.

**Comment by bobbrow** [comment] 2019-11-08 17:21
I have a fix for this in PR.  There was an update to the regular expression that mapped compilers to the debugger that caused this regression.

You can workaround this until we release an update by opening `~/.vscode/extensions/ms-vscode.cmake-tools-1.2.1/dist/main.js` and replacing line 27378:
```
  const gcc_compiler_regex = /([cg]\+\+|g?cc)(?=\.exe$|$)/gi;
```
with
```
  const gcc_compiler_regex = /([cg]\+\+|g?cc)(?=[^\/\\]*$)/gi;
```

**Comment by Zingam** [comment] 2019-11-08 18:51
With a great sadness I can confirm this too.
[build] Starting build
[proc] Executing command: /snap/cmake/current/bin/cmake --build /home/hristo/Projects/GitHub/GunBox/GunBox/GunBox/build --config Debug --target GunBox_Game -- -j 10
[build] ninja: no work to do.
[build] Build finished with exit code 0
[debugger] Unable to automatically determine debugger corresponding to compiler: {}
[main] Failed to generate debugger configuration

**Closed** 2019-11-13 18:43 UTC
Labels: Feature: debug, IMPORTANT, bug, fixed (release pending)

**Comment by bobbrow** [comment] 2019-11-13 19:43
1.2.2 was released today.  Please give that a try and let us know if you continue to have issues.

**Comment by rmclaren** [comment] 2020-07-25 21:59
As of version 1.4.1 this is still broken. I think this is in part because of ~/.vscode/extensions/ms-vscode.cmake-tools-1.4.1/dist/main.js line 42788 "const debugger_name = platform == 'darwin' ? 'lldb' : 'gdb'". This is a really bad assumption... Just cause I'm using MacOS does not mean I'm using lldb. Should probably check the compiler to make this determination (gcc/g++ vs clang).

**Comment by bobbrow** [comment] 2020-07-27 16:06
This is interesting.  If you are setting the `miDebuggerPath` in `cmake.debugConfig`, the `debugger_name` variable shouldn't matter because a few lines down we pick the `debuggerPathOverride` which is supposed to be the value of `cmake.debugConfig.miDebuggerPath`.  If you recently changed the setting and it doesn't appear to be taking effect, try reloading the window and see if the extension picks it up on the reload.  There is currently an issue open where the extension doesn't reload the value of all settings after they change. #1127

**Comment by Zrealshadow** [comment] 2021-03-01 11:02
I still face this problem in MacOS Catalina 10.15.4
And the cmake-tool verison is 1.6.0

When i try to debug,
the log is:
[build] Starting build
[proc] Executing command: /snap/cmake/current/bin/cmake --build /home/hristo/Projects/GitHub/GunBox/GunBox/GunBox/build --config Debug --target GunBox_Game -- -j 10
[build] ninja: no work to do.
[build] Build finished with exit code 0
[debugger] Unable to automatically determine debugger corresponding to compiler: /usr/local/bin/g++-8
[main] Failed to generate debugger configuration

My cmake tool setting:
```json
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "cmake.configureOnOpen":true,
    "cmake.debugConfig": {
        "stopAtEntry": false,
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/local/bin/gdb",
    }
```

Any solution to this problem ?

**Comment by andreeis** [comment] 2021-03-01 14:03
I opened a new issue from your last comment. I have a suspicion in the implementation.
