### ISSUE TITLE
Wrong scope of `cmake.additionalKits`

### ISSUE THREAD

**Issue by OrkunTokdemir** [microsoft/vscode-cmake-tools#3607] opened 2024-02-22 11:38 UTC
### Brief Issue Summary

The current scope of `cmake.additionalKits` is `resource` which means it is synchronized with other machines. Since the paths it contains are machine-specific paths. It doesn't make sense to share them with others. I think the correct scope should be `machine-overridable` instead of `resource`.

**Comment by gcampbell-msft** [comment] 2024-02-29 19:26
I've made comments in the PR as well, but, for now, I think that actually it is by design to be shared across users, because this setting supports macros like $(workspaceFolder) which allows for sharing across machines. This can help people share additional kits with a team. 

I'll close this issue, but if you have additional feedback please follow up. Thanks.

**Closed by gcampbell-msft** 2024-02-29 19:26 UTC
Labels: bug, Feature: settings
