### ISSUE TITLE
[Feature request] Run shell script before configuration happens

### ISSUE THREAD

**Issue by Cansisti** [microsoft/vscode-cmake-tools#809] opened 2019-09-25 17:43 UTC
### Brief Issue Summary

When working in console I'm using shell script to source many environment variables required for configuration and build. I see there is a setting to add variables separately, but that's a long and often changing list - I'd love to be able to just pass the script name so it's run in the shell cmake-tools is working.

### Expected:

Some setting like "pre-configuration commands".

### Other Notes/Information

It might be worth mentioning that I'm working with SSH remote connection plugin, and cmake-tools is installed on remote machine.

**Comment by bobbrow** [comment] 2019-09-26 02:49
This might be easily doable by augmenting the Kits schema.  Something similar is done to load environment variables for the MSVC compiler, but it's internal to the extension.

**Comment by tomj-work** [comment] 2019-11-29 17:05
I would also like to see this functionality - I'm using CMake to build some quite old code, in which some build steps are performed in bash scripts.  Because I can't source the required rc file before calling CMake, these legacy steps crash the build.

**Comment by ruilvo** [comment] 2020-04-10 07:29
I'd like this feature too. My particular use case, and I bet shared by many, is to activate a Conda enviroment before building, so I build with the right Python libraries (CMake itself respects activated envs as priority in FindPython).

**Comment by bobbrow** [comment] 2020-04-10 16:51
This feature was implemented and will be released with 1.4.

**Comment by andreeis** [comment] 2020-05-15 19:07
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by lyon-fnal** [comment] 2020-05-16 02:14
This is essential for my workflow - I have to source several scripts to set up my build environment. This option worked great! Much easier than maintaining a very long list of environment variables. Thanks for adding it!!

**Comment by andreeis** [comment] 2020-05-20 21:27
This fix is available in CMake Tools #1.4.0 which has been released.

**Closed by andreeis** 2020-05-20 21:27 UTC
Labels: Feature Request, Feature: kits, fixed (release pending)

**Comment by arminms** [comment] 2020-05-25 21:11
I cannot see the settings in the CMake Tools configuration. I tried to set it manually using `    cmake.environmentVariablesShellScript` and `cmake.environmentVariablesShellScriptDirectory` to no avail.

**Comment by andreeis** [comment] 2020-05-27 21:44
From looking at the PR that introduced this functionality, it should be the "environmentSetupScript" property of a kit. Manually add that to the kit you are using, in the kits file json. Let us know how that goes.

**Comment by jheaff1** [comment] 2020-06-15 08:44
I tried setting the environmentSetupScript property of a kit in cmake-tools-kits.json and it didn't seem to work. Will the given be script be run or "sourced". My setup script contains many environment variables, therefore i would like vscode to effectively run "source <setup script>"

**Comment by cacadam89** [comment] 2020-06-18 21:01
> I tried setting the environmentSetupScript property of a kit in cmake-tools-kits.json and it didn't seem to work. Will the given be script be run or "sourced". My setup script contains many environment variables, therefore i would like vscode to effectively run "source "

I am having the same issue where this property seems to have no effect. In case it is a run instead of source, I tried making a separate script to source what I need, and though it works when I call it manually it is not called when cmake is configured.

**Comment by arminms** [comment] 2020-07-10 00:44
> From looking at the PR that introduced this functionality, it should be the "environmentSetupScript" property of a kit. Manually add that to the kit you are using, in the kits file json. Let us know how that goes.

Thank you! Actually, it works for me. I just edited `cmake-tools-kits.json` and added the following lines to enable Intel toochain:
```
  {
    "name": "Intel 19.0.5.281",
    "environmentSetupScript": "/opt/intel/bin/iccvars.sh intel64",
    "compilers": {
      "C": "/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icc",
      "CXX": "/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc",
      "Fortran": "/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort"
    }
  }
```
Then, whenever I switch to `Intel 19.0.5.281` kit,  `/opt/intel/bin/iccvars.sh intel64` script runs and setups the environment.

**Comment by duanyutong** [comment] 2020-07-22 00:02
I'm developing in a remote docker container and `environmentSetupScript` does not work. I have the following `cmake-kits.json` which is successfully picked up by the extension.
```
[
    {
        "name": "gcc7 setup environment",
        "environmentSetupScript": "export PYTHONPATH=/root/",
        "compilers": {
            "C": "/usr/bin/gcc-7",
            "CXX": "/usr/bin/g++-7"
            }
    }
]
```
I then have a line of `message(STATUS $ENV{PYTHONPATH})` in the `CMakeLists.txt` to verify it, but It's blank. Configure fails because of missing env vars.

I also tried putting the env vars in a `.sh` script and writing `"environmentSetupScript": source file.sh"`, same issue.

**Comment by jheaff1** [comment] 2020-07-22 09:04
@duanyutong Try

```
environmentSetupScript": file.sh
```

**Comment by duanyutong** [comment] 2020-07-24 03:26
@jheaff1 I tried that, too. Same thing. The path I put there points to a shell script containing the following lines.
```
export PYTHONPATH=/opt/ros/melodic/lib/python3/dist-packages/:$PYTHONPATH
source (other_scripts.sh)
...
```
Still `message(STATUS $ENV{PYTHONPATH})` shows nothing. `message(STATUS $ENV{PATH})` indicates that the `$PATH` is also different from the `$PATH` variable in the vscode integrated terminal (default `bash` in my case). It seems that it would be simpler if the cmake commands can just be executed in the same kind of shell as the vscode integrated terminal.

**Comment by rnwzd** [comment] 2020-08-03 18:11
> @jheaff1 Thanks. I tried that in various ways and here are my observations.
> 
> * the `.sh` file it points to cannot simply contain `source ~/.bashrc` or `source $HOME/.bashrc` or even the full absolute path; it has to contain the environment variable definitions itself

I can confirm that it cannot source an external file.
The feature would be essential to integrate the Intel OneApi Toolkit since they provide a script that must be sourced and would be very annoying to rewrite.
[https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-linux/top/before-you-begin.html#before-you-begin_GUID-338EB548-7DB6-410E-B4BF-E65C017389C4](url)

**Comment by ztarem** [comment] 2020-08-27 11:16
In my case the setup script must be sourced even **before** any attempt to run CMake. The CMake version installed on the remote is very old and not relevant - only the one set up by the script is. (Same is true for git and Python - only after sourcing the setup script they are of the correct version).

My manual process is:
```
cd <project-dir>
source setup.sh
cd build
cmake ..., make ..., etc.

```

**Comment by blackliner** [comment] 2020-09-22 15:50
Same here, need to `. /opt/ros/melodic/setup.bash` to get the ROS1 env setup right before the `cmake ..` call. Or else:
```
[cmake] ImportError: No module named catkin.environment_cache
```

**Comment by renyhp** [comment] 2020-10-05 12:45
I'm having issues with the parsing of environment variables. In my case the output of printenv contains these two lines
```
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
```
which causes
`[kit] Error parsing environment variable: }`

Maybe the solution to this issue should be adjusted to parse multiline environment variables, or to _actually execute_ the shell script, rather than only importing the environment...

**Comment by ishipachev** [comment] 2020-11-30 17:35
Can it be a custom command to run before build?
For an example, I'm working remotely on the server with modules: [example](http://modules.sourceforge.net/)
Every time before any build I should source a custom script which loads modules I need for my build.
The simplest way for me would be able to call a custom script which loads those variables. But I'm not sure if "source load_script.sh" will help for a kit to build with all modules sourced.

**Comment by lesomnus** [comment] 2020-12-20 14:32
For those who came for ROS.
```json
...
	"cmake.configureSettings": {
		"CMAKE_PREFIX_PATH": "/opt/ros/${ROS_DISTRO}"
	},
...
```

**Comment by pvelesko** [comment] 2021-09-02 13:49
Issue still persists - enable to change environment in which CMake will run the configuration. The use case is exactly as @ishipachev described - needing to load modules prior to CMake configuration.

**Comment by pvelesko** [comment] 2021-09-02 14:01
Can confirm that `    "environmentSetupScript": "source /home/pvelesko/HIPxx_env.sh",` does not solve the issue.

Modules do not work and sourcing Intel OneAPI setvars.sh script fails with failing to parse variables. 
Can this be reopened? 
@andreeis

**Comment by ishipachev** [comment] 2021-12-15 17:46
To be honest, I don't understand why this issue is closed?
I came here almost a one year later but now from the other side, not modules, but ROS. And it is still a problem.
I can't debug the script in VSCode as it has to source a ROS environment before running python script which relies on this ROS environment.

**Comment by ishipachev** [comment] 2021-12-15 17:59
Ok, I sort of "solved" this issue to the point that I'm able to use VSCode to run scripts related to ROS.
I start VSCode from the same console I do sourcing of ROS environment. Thus VSCode inherits a proper ROS-aware environment and my scripts work.

But in this case I have a set environment for all launches I will do in this VSCode.

I also still don't know how it can be used to run VSCode remotely on the server with [modules](http://modules.sourceforge.net/). Probably, the only case will be to add sourcing of [modules](http://modules.sourceforge.net/) into .bashrc and hope that when VSCode will try to connect to remote server it will also swallow all this sourcing from .bashrc

Both ways are ugly and defenitely something I would like to avoid, but at least it gave me working environment I was looking for.
