### ISSUE TITLE
Is this extension still actively maintained?

### ISSUE THREAD

**Issue by tomasiser** [microsoft/vscode-cmake-tools#665] opened 2019-03-28 08:28 UTC
Hello @vector-of-bool, @lygstate, @Randshot and possibly other contributors,

First of all, I would like to thank you for this nice extension!

Sorry for asking this annoying question, but there is a lot of issues reported here that I have also encountered and it seems like the last commit was 3 months ago and last release 5 months ago.

Is there still anyone actively maintaining this repository or is the help wanted from #315 still going on?

**Comment by dcourtois** [comment] 2019-03-29 11:24
Wondering the same thing. I did contribute a few things last year and the author was quite active, but since January there doesn't seem to anything going on here :/

**Comment by Novakov** [comment] 2019-04-03 15:35
On @vector-of-bool patreon page there is a not that he is taking a break from OSS. I guess we will have to wait

**Comment by Randshot** [comment] 2019-04-03 16:07
Hey, as far as I know, @vector-of-bool is still looking for help for this extension.
I don't know about his current circumstances though. I wouldn't mind helping with maintaining this extension, but I don't have enough time to do that myself, and this also not being my project.
The problem is that some pretty big changes were started in separate branches from the maintainer and various contributors, but never finished, so I don't know which direction @vector-of-bool is envisioning.

**Comment by dcourtois** [comment] 2019-04-04 07:42
Hi, thanks for the answers !
I perfectly understand that sometime people no longer have time/motivation for OSS and that's fine ! If there is any way to contact the author, maybe he could take a few minutes to explain how he envision the future of the addon, explain a bit what the big changes are/should be, and then give access to one or more trusted contributors ?
There's currently more than 680k installations of this addon, and it's the current "goto" addon for anyone working on C/C++ projects, so it would be nice if this addon could still be actively maintained :)

**Comment by dcourtois** [comment] 2019-04-04 15:07
@Randshot you seem to have some rights on this repository; do you also have the rights to release a new version of the addon on the Visual Studio Code marketplace ?

**Comment by Randshot** [comment] 2019-04-04 15:08
Nope, that is completely separate.

**Comment by dcourtois** [comment] 2019-04-04 15:10
Thought so, but wanted to be sure. Thanks

**Comment by vector-of-bool** [comment] 2019-04-07 19:57
Hello, all.

I still get emails for everything that goes on in this repo, but I've been terrible about being active in the repo beyond that. I saw the email for this issue and feel like I should respond directly.

I feel pretty terrible about how much I've let this repo sit unattended for so long. Why has it sat? I'm not sure. After I changed positions at my job, I've been doing much less development work than I had before, and using CMake within VSCode has become rare for me simply by virtue of rarely doing C++ development. There is also a lot of time pressure as I'm active on several other projects at the moment. Add on some real-life time issues, and I'm fairly preoccupied.

I still have so many ideas of what I would like to do with this ext, but spouting them all immediately right now isn't prudent. With the release of CMake 3.14 and its new File API, as well as VSCode's upcoming custom task execution engine, I think it may be prudent for a refreshing of this extension (or possibly a new one :thinking:).

And @Randshot is correct: I am still looking for help with maintenance, up to and including handing off repository ownership (and possibly the VSCode Marketplace publication rights), but not to the extent that I want to become completely un-involved. (This will be tricky, though. You may recall a recent event in which handing off the publication rights of a popular project didn't go very well...)

I haven't yet sorted through the many, many, many backlog items that have gone unaddressed for months. I feel bad about being so inactive in here, and I can't promise that I'm yet ready to return, but I felt that I should at least follow-up on this ticket so that there isn't abject radio silence.

Thank you all for your patience.

**Comment by vector-of-bool** [comment] 2019-05-20 00:21
I've created #691. Rationale and reasoning will be posted elsewhere soon.

**Comment by vector-of-bool** [comment] 2019-07-12 18:45
I'm pleased to announce that this repository and extension has now been transferred to Microsoft, and I'm looking forward to see this code receive the attention that it deserves and that I have been unable to provide the past few months.

Thank you all for your tremendous patience!

**Closed by vector-of-bool** 2019-07-12 18:45 UTC
Labels: IMPORTANT, org

**Comment by bobbrow** [comment] 2019-07-12 20:04
A big thank you to @vector-of-bool for all of your hard work on this extension. 👏

In the coming days/weeks we will be spending time reviewing the existing issues and PR's and coming up with schedules for the work we plan to do with this extension. As always, community contributions are accepted and encouraged!
