### ISSUE TITLE
Use CMAKE_CONFIGURATION_TYPES for build variants

### ISSUE THREAD

**Issue by notzain** [microsoft/vscode-cmake-tools#1356] opened 2020-07-07 15:08 UTC
Right now, the CMake build variants defaults to Debug, Release, MinSizeRel and RelWithDebInfo.

In my CMakeLists, I have manually added more types:
`
set(CMAKE_CONFIGURATION_TYPES "Debug;Debug_ARM;Release;Release_ARM" CACHE STRING "" FORCE)
`

I would like these options to be selectable when picking a build variant (sidenote: CLion has this behaviour).

**Comment by andreeis** [comment] 2020-07-07 17:51
Duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/128

**Closed** 2020-07-07 17:51 UTC
Labels: duplicate
