### ISSUE TITLE
Suppress cmake options in Build command when no cmake project is configured

### ISSUE THREAD

**Issue by fischman-bcny** [microsoft/vscode-cmake-tools#3257] opened 2023-07-25 18:33 UTC
### Brief Issue Summary

Repro:
- Create new directory, cd into it
- code .
- hit ctrl-shift-B

Expected:
- No build systems are available/offered

Actual/Observed:
- CMake build is offered even though the workspace directory is empty (it was created above and nothing placed in it):
![image](https://github.com/microsoft/vscode-cmake-tools/assets/94327711/6cddc1d1-4963-4643-80bf-014bd822a8ec)

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.80.1",
  "cmtVersion": "1.14.34",
  "configurations": [
    {
      "folder": "c:\\Users\\Ami\\src\\x2",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by benmcmorran** [comment] 2023-07-28 16:19
Thanks for the report! I'm marking this as a bug and we will investigate for our 1.16 release.

**Comment by gcampbell-msft** [comment] 2023-12-20 18:03
@fischman-bcny Does this still reproduce for you? I just tested your repro steps and don't see this bug anymore. For now, I'm going to close this bug and mark it as completed since it is no longer reproducing, but please comment here to let me know if it still reproduces for you!

Thanks.

**Closed by gcampbell-msft** 2023-12-20 18:03 UTC
Labels: bug, Feature: tasks
