### ISSUE TITLE
"Scan kits" does not remove old kits

### ISSUE THREAD

**Issue by jeffrson** [microsoft/vscode-cmake-tools#2861] opened 2022-11-21 17:43 UTC
### Brief Issue Summary

There was an issue (https://github.com/microsoft/vscode-cmake-tools/issues/393) that looks similar.

I'm running on Windows with llvm (install llvm*win64.exe from https://github.com/llvm/llvm-project/releases). Scanning for kits after installation detects the new version, but does not remove the old one. So I have now 15.0.3, 15.0.4, 15.0.5 (just because 15.0.3 had been the first llvm I installed on Windows).

Sure, I could edit cmake-tools-kits.json, but this isn't the best user experience.

### Additional Information

If you think, any debug log would be helpful, I could attach it later.

**Comment by bobbrow** [comment] 2022-11-21 17:51
Thank you for opening this issue.  I believe it is a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/2570.  If you can go add a 👍 reaction to that issue, that helps us rank issues by priority.  If there is something else to this issue that that one does not cover, please let us know and we can reopen this one.

**Closed by bobbrow** 2022-11-21 17:51 UTC
