### ISSUE TITLE
Output and terminal windows charset problem

### ISSUE THREAD

**Issue by xzzh999** [microsoft/vscode-cmake-tools#267] opened 2017-11-29 01:46 UTC
Hi, bigcow! Great work! 

When i build msvc c++ project, the output window always print garbled, 
i tried follow issue's suggestion but they were complicated and didn't work.

https://github.com/Microsoft/vscode/issues/3550

https://github.com/OmniSharp/omnisharp-vscode/issues/1775

can you add some charset encoding settings to make this easy?

![](https://github.com/xzzh999/markdown-pictures/blob/master/vscode-wrong-charset.png?raw=true)

**Comment by xzzh999** [comment] 2017-11-29 01:49
vscode version: 1.18.1, shell: 1.7.9, node: 7.9.0

**Comment by vector-of-bool** [comment] 2017-11-30 17:48
I've had a few troubles with character encoding. This is on the backlog.

**Comment by feng-ye** [comment] 2017-12-04 07:46
I am using the following work around:
1. create a bat file contains
`chcp 65001 && cmake %*`
2. set cmake.cmakePath to the bat file

I hope this will help.

**Comment by xzzh999** [comment] 2017-12-08 01:36
For now i wrote some python scripts to generate and build the project myself, and every charset encoding is under control in vscode, but i hope this extension will improved later, then  i will change back.

**Comment by EternalPhane** [comment] 2018-01-20 12:36
Maybe you can temporary patch it by adding an option in `settings.json` to let user manually set their preferred output encoding, and provide a permanent solution later.

**Comment by pengbins** [comment] 2018-09-19 11:26
> I am using the following work around:
> 
> 1. create a bat file containing
>    `chcp 65001 && cmake %*`
> 2. set cmake.cmakePath to the bat file
> 
> I hope this will help.
@feng-ye  I tried your work around, but got following error. It seems .bat can't run.
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Impossible: CMake driver died immediately after successful configure {}

**Comment by bobbrow** [comment] 2019-07-24 21:25
This looks like a duplicate of #153 which may have been fixed by PR #550. Is this still an issue for you?

**Closed by bobbrow** 2019-07-24 21:25 UTC
Labels: bug, duplicate
