### ISSUE TITLE
New version of cmake fails to launch debug mode

### ISSUE THREAD

**Issue by wyatthuckaby** [microsoft/vscode-cmake-tools#2491] opened 2022-04-10 21:25 UTC
### Brief Issue Summary

When upgrading to the latest version of cmake from 1.9.2, my debug capability broke with the following error:

```
ERROR: Unable to start debugging. Unexpected GDB output from command "-interpreter-exec console "set env BASH_FUNC_which%% () {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot \"$@\"
}"". Problem parsing arguments: interpreter-exec console "set env BASH_FUNC_which%% () {  ( alias;
```

How i can reproduce the bug:
Load cmake project with g++ and GDB on fedora linux
entering debug mode yields a strange error, im able to rectify the error by switching back to older version

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.66.0",
  "cmtVersion": "1.10.5",
  "configurations": [
    {
      "folder": "/home/renegadepanther/Documents/Dev/RenderingEngine",
      "cmakeVersion": "3.22.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "explodeit",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by elahehrashedi** [comment] 2022-04-11 16:35
Thank you for reporting this issue, this is a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/2442, we are working on a fix for this issue.

**Closed** 2022-04-11 16:35 UTC
Labels: bug, duplicate, Feature: debug/launch
