### ISSUE TITLE
CMakePresets.json macros are not expanded properly in inheritance

### ISSUE THREAD

**Issue by KyleFromKitware** [microsoft/vscode-cmake-tools#1802] opened 2021-04-22 13:41 UTC
### Brief Issue Summary

I'm using `CMakeUserPresets.json` for local CMake development, and I have several presets which inherit from a common base preset. The base preset defines `binaryDir` to be `${sourceParentDir}/build/${presetName}`. This macro is supposed to be dependent upon the name of the preset that actually gets used (https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#macro-expansion), but always defaults to `build/base`. Here is an abridged version of my `CMakeUserPresets.json`:

```json
{
  "version": 2,
  "configurePresets": [
    {
      "name": "base",
      "hidden": true,
      "binaryDir": "${sourceParentDir}/build/${presetName}"
    },
    {
      "name": "build-base",
      "inherits": "base",
      "hidden": true,
      "generator": "Ninja",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug",
        "CMAKE_C_COMPILER_LAUNCHER": "ccache",
        "CMAKE_CXX_COMPILER_LAUNCHER": "ccache",
        "BUILD_QtDialog": "ON",
        "CMake_TEST_GUI": "ON",
        "CMake_TEST_JSON_SCHEMA": "ON"
      }
    },
    {
      "name": "ninja",
      "inherits": "build-base",
      "displayName": "Ninja",
      "cacheVariables": {
        "CMAKE_CXX_STANDARD": "11",
        "SPHINX_HTML": "ON"
      }
    }
  ]
}
```

### Expected:

1. Paste above into `CMakeUserPresets.json`
2. Build with `ninja` preset
3. Build happens in `build/ninja`

### Apparent Behavior:

1. Paste above into `CMakeUserPresets.json`
2. Build with `ninja` preset
3. Build happens in `build/base`

**Comment by KyleFromKitware** [comment] 2021-04-22 14:06
Cc: @esweet431

**Comment by bobbrow** [comment] 2021-04-22 15:59
Hey @KyleFromKitware, thanks for reporting this issue.  I believe it's a duplicate of #1787 which we have a PR out for right now.  If all goes well, we'll release 1.7.1 with the fix today.

**Closed by bobbrow** 2021-04-22 15:59 UTC

**Comment by andreeis** [comment] 2021-04-22 16:41
The PR was merged in the GitHub repository and, if you'd like, you can validate the fix for this problem by installing this custom vsix before we release the official 1.7.1.
https://github.com/microsoft/vscode-cmake-tools/actions/runs/774916180
