### ISSUE TITLE
Unable to find GDB in default search path and /usr/local/bin/lldb-9

### ISSUE THREAD

**Issue by sochooligan** [microsoft/vscode-cmake-tools#1060] opened 2020-02-11 07:21 UTC
When I use CMake Tools's Debug It says "Unable to find GDB in default search path and /usr/local/bin/lldb-9."
I don't know where to set gdb path for the CMake Tools Plugin. I think this is an issue.

My Env:
----------------------
macos: 10.15.3
Xcode: 11.3.1
/usr/local/opt/llvm/bin/lldb -v: 9.0.0
cmake: 3.15.3
make:4.3
gdb: 8.3
g++: 9.2.0_3
vs code: 1.42.0
cmake tools: 1.3.0
----------------------

When I add in settings.json:
"cmake.debugConfig": {
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/local/bin/gdb",
}
it does not take effect.

**Comment by sochooligan** [comment] 2020-02-11 07:33
When I add in setting.json:

"cmake.debugConfig": {
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/local/bin/gdb",
}

it does not take effect.

**Comment by andreeis** [comment] 2020-02-12 01:05
On Windows and Ubuntu I am not able to get any "cmake.debugConfig" settings to be ignored. I will try on MAC shortly, although I don't think something may reproduce only because of this.
I wonder what else is specific to your situation. 
You tried CMake Tools 1.3.0, right?

**Comment by sochooligan** [comment] 2020-02-12 01:37
> On Windows and Ubuntu I am not able to get any "cmake.debugConfig" settings to be ignored. I will try on MAC shortly, although I don't think something may reproduce only because of this.
> I wonder what else is specific to your situation.
> You tried CMake Tools 1.3.0, right?

Reply:
1. The Output When I push CMake Tool's Debug located on the middle bottom of Vs Code.
------
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /Users/jzwang/Documents/localrepos/codes/CppCmakeGettingStarted/build --config Debug --target CppCmakeGettingStarted -- -j 6
[build] make[1]: Entering directory '/Users/Documents/localrepos/codes/CppCmakeGettingStarted/build'
[build] make[2]: Entering directory '/Users/Documents/localrepos/codes/CppCmakeGettingStarted/build'
[build] make[3]: Entering directory '/Users/Documents/localrepos/codes/CppCmakeGettingStarted/build'
[build] make[3]: Leaving directory '/Users/Documents/localrepos/codes/CppCmakeGettingStarted/build'
[build] [100%] Built target CppCmakeGettingStarted
[build] make[2]: Leaving directory '/Users/Documents/localrepos/codes/CppCmakeGettingStarted/build'
[build] make[1]: Leaving directory '/Users/Documents/localrepos/codes/CppCmakeGettingStarted/build'
[build] Build finished with exit code 0
[proc] Executing command: /usr/local/bin/lldb-9 --version

I don't know what the last message means.
2. I tried CMake Tools 1.3.0, 1.1.3.

**Comment by sochooligan** [comment] 2020-02-13 07:40
Finally, I find the lldb path in macOS: /usr/local/opt/llvm/bin.

**Comment by sochooligan** [comment] 2020-02-13 13:22
Make CMake Tools Debug **breakstop** Success on Xcode 11.3.1!!!
**Question:** 
We have lldb under /Applications/Xcode.app/Contents/Developer/usr/bin/, but we don't have lldb-mi.
**Solution:** 
Compile **lldb-mi** for Xcode 11.3.1
**Steps:**
(1) sudo vim /etc/paths
/usr/local/Cellar/llvm/9.0.0/bin
/usr/bin  (this dir must before /usr/local/bin so that compile lldb-mi will use /usr/bin/clang tools)
/usr/local/bin
/bin
/usr/sbin
/sbin
(2) git clone  https://github.com/lldb-tools/lldb-mi.git
(3) cd lldb-mi
cmake .
cmake --build .
(4) sudo cp ./src/lldb-mi /Applications/Xcode.app/Contents/Developer/usr/bin/

**Comment by bobbrow** [comment] 2020-02-19 01:16
Unfortunately Apple doesn't distribute lldb-mi anymore.  The cpptools extension is almost ready to start distributing a copy of it with the extension.  At that point we can start pointing to that one by default.

**Comment by sochooligan** [comment] 2020-02-25 07:55
> Unfortunately Apple doesn't distribute lldb-mi anymore. The cpptools extension is almost ready to start distributing a copy of it with the extension. At that point we can start pointing to that one by default.
https://github.com/microsoft/vscode-cmake-tools/issues/1060#issuecomment-585751508

**Comment by bobbrow** [comment] 2020-03-02 18:46
I believe I have a fix for this in PR #1102

**Comment by andreeis** [comment] 2020-05-15 19:08
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment] 2020-05-20 21:25
This fix is available in CMake Tools #1.4.0 which has been released.

**Closed by andreeis** 2020-05-20 21:25 UTC
Labels: Feature: debug/launch, bug, fixed (release pending)

**Comment by EzioZz** [comment] 2021-01-01 08:46
How to configure if I need to compile the program using GCC and debug with GDB. 
"cmake.debugConfig": {
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/local/bin/gdb"
    }
using the configuration above the debugger doesn't go to the breakpoint.

**Comment by andreeis** [comment] 2021-01-08 23:57
That should work. Double check if the source code file where you want to hit the breakpoint is compiled with debug information (-g flag). As an experiment, also add "stopAtEntry" inside cmake.debugConfig and set it to true, see if that generates any breakpoint hit at startup.

**Comment by BH1SCW** [comment] 2021-10-13 02:20
> Make CMake Tools Debug **BREAKSTOP** Success on Xcode 11.3.1!!!
> 
> ### **Question:**
> We have lldb under /Applications/Xcode.app/Contents/Developer/usr/bin/, but we don't have lldb-mi.
> 
> ### **Solution:**
> Compile **lldb-mi** for Xcode 11.3.1
> 
> ### **Steps:**
> (1) sudo vim /etc/paths /usr/local/Cellar/llvm/9.0.0/bin **/usr/bin** /usr/local/bin /bin /usr/sbin /sbin **notes:** /usr/bin before /usr/local/bin so when step(3) compile lldb-mi will use /usr/bin/clang tools) (2) git clone https://github.com/lldb-tools/lldb-mi.git (3) cd lldb-mi cmake . cmake --build . (4) sudo cp ./src/lldb-mi /Applications/Xcode.app/Contents/Developer/usr/bin/
> 
> ### **Set soft link(no need to set cmake.debugConfig anymore)**
> cd /usr/local/bin ln -s /Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi lldb-9
> 
> ### **Others:**
> Because I Use g++ under /usr/local/bin/, so after compiling, I modified /etc/paths as: **/usr/local/bin** /usr/bin /bin /usr/sbin /sbin
> 
> ### **refs:**
> https://forums.developer.apple.com/thread/125482 https://github.com/lldb-tools/lldb-mi

works for me , Great thanks~
