### ISSUE TITLE
cmake-tools does not use the chosen python interpreter from the vscode python extension

### ISSUE THREAD

**Issue by freol35241** [microsoft/vscode-cmake-tools#1652] opened 2021-02-07 19:08 UTC
### Brief Issue Summary

When using cmake targets which make use of external python scripts I would expect vscode-cmake-tools to invoke the cmake binary within the python virtual environment that is the currently chosen interpreter by the python extension. Currently, It doesnt meaning that any python dependencies in a cmake workflow must be installed in the global python environment when using vscode-cmake-tools. Or the user needs to step outside vscode-cmake-tools and run the cmake commands manually in a regular terminal.

**Comment by andreeis** [comment] 2021-02-08 11:13
Thank you for opening this report. You can try to use the environmentSetupScript of a kit to point to a script that is setting all the environment variables (path for example) as your python environment. Then when the kit is active (after a project reload or after changing to a kit that has environmentSetupScript defined) the operations like configure or build should have access to that environment.
Let us know if this isn't working for you or if you had a different scenario in mind.

**Comment by freol35241** [comment] 2021-02-10 05:59
Thanks for the quick response @andreeis  and thanks for the suggestion!

I find myself unsure how to use `environmentSetupScript`, is this a cmake-native thing or a vscode thing or a vscode-cmake-tools thing? I struggle to find any docs regarding `environmentSetupScript` [here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md). Most probably looking in the wrong place, would appreciate a hint!

**Comment by andreeis** [comment] 2021-02-10 07:31
Good questions :). It is a CMake Tools concept. You edit the kit you want to load from cmake-tools-kits.json (you can open it with the command "CMake: Edit user level kits" in the pallette) or your project local .vscode subfolder like below:
{
  "name": "Your kit",
   "environmentSetupScript": "path/to/script",
   ... any other attributes you need for your kit ... like preferredGenerator, or visualStudio versions or compilers C/CXX pairs...
}

**Comment by freol35241** [comment] 2021-02-19 20:49
So, after some initial trial-n-error I ended up with creating a project-specific `cmake-kits.json` with the following content:
```
[
    {
      "name": "GCC 9.3.0 in virtualenv",
      "compilers": {
        "C": "/bin/gcc-9",
        "CXX": "/bin/g++-9"
      },
      "environmentSetupScript": "${workspaceFolder}/venv/bin/activate"
    }
]
```

This works relatively well and solves the "problem" even though there still is no actual integration with the vscode python extension.

Thanks for your help @andreeis !

**Comment by andreeis** [comment] 2021-02-22 17:28
Glad to hear this works for you now. I am closing the report.
Just to brainstorm for the future, what support exactly would you like to see in CMake Tools to integrate better with the Python extension, besides having the script in a kit? Feel free to comment on this at any time. It will be low priority to implement for sure but it never hurts to think ahead.

**Closed by andreeis** 2021-02-22 17:28 UTC
Labels: Feature: build, Feature: configure, more info needed

**Comment by yannidd** [comment] 2021-06-02 22:41
Hi, I hope you don't mind me posting on this closed issue. I was setting up a CMake project and stumbled upon a similar problem.

> Just to brainstorm for the future, what support exactly would you like to see in CMake Tools to integrate better with the Python extension, besides having the script in a kit?

I think the problem is that when you configure the project using CMake Tools, whenever CMake is looking for Python (e.g. using [FindPython3](https://cmake.org/cmake/help/latest/module/FindPython3.html)), it finds the global Python interpreter, not the one that has been set using `Python: Select Interpreter`. It would be nice if CMake Tools would activate the environment selected in the Python extension before configuring the project.

> what support exactly would you like ... besides having the script in a kit?

Using kits and `environmentSetupScript` seems like a reasonable workaround to the problem above, despite it not being automatic (i.e. you have to manually set the path to the environment activation script). But what about projects that use CMake presets instead of kits and variants? According to the documentation:

> We recommend CMakePresets.json as an alternative to kits and variants files. 

Is there a way to have an `environmentSetupScript` in that case?

**Comment by andreeis** [comment] 2021-06-08 16:26
@yannidd , regarding this:

> Is there a way to have an environmentSetupScript in that case?

We don't support yet a similar concept like environmentSetupScript in the presets scenario. Considering this kitware issue https://gitlab.kitware.com/cmake/cmake/-/issues/21619, such approach was intentionally avoided.
We looked at what environmentSetupScript achieves (sets environment, performs various operations like registry, fileIO, process execution) and brainstormed some alternatives. For various operations, one can use a toolchain file, custom targets, custom commands or CMake scripting commands (https://cmake.org/cmake/help/latest/manual/cmake-commands.7.html#scripting-commands). For capturing the environment, one can use #execute_process(https://cmake.org/cmake/help/latest/command/execute_process.html) and #set(https://cmake.org/cmake/help/latest/command/set.html#set-environment-variable).
