### ISSUE TITLE
No suitable generator is found without MinGW in the PATH

### ISSUE THREAD

**Issue by csorvagep** [microsoft/vscode-cmake-tools#1354] opened 2020-07-06 09:00 UTC
### Brief Issue Summary
With settings cmake.mingwSearchDirs properly set, the Scan for Kits command is able to find the available build tools, but no suitable generator is found. If MinGW is in the PATH, there is no problem, but I don't like to clutter the path, and other tools might complain because of this. Also it can cause weird issues with linking different libraries with frequently changing kits.

### Platform and Versions

- **Operating System**: Windows 10 1909
- **CMake Version**: 3.17.3
- **VSCode Version**: 1.46.1
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**:  Visual C++ 2019, GCC 10.1 (MinGW), Clang 10.0 (MinGW)

**Comment by bobbrow** [comment] 2020-07-06 17:30
Thank you for reporting this issue.
This is looks like a duplicate of #1064

**Closed by bobbrow** 2020-07-06 17:30 UTC
