### ISSUE TITLE
Weird status logs regression, never 100%

### ISSUE THREAD

**Issue by jkammerland** [microsoft/vscode-cmake-tools#4100] opened 2024-09-29 07:48 UTC
### Brief Issue Summary

Weird status logs regression, no longer becomes 100%

### CMake Tools Diagnostics

```shell
[build] [3/4  75% :: 0.137] Linking CXX executable test/tests
[driver] Build completed: 00:00:00.148
[build] Build finished with exit code 0

It always completes at (N-1)/N, in the case above 3/4 or 75%. This never happened before, but it still build though
```

### Debug Log

```shell
N/A
```

### Additional Information

N/A

**Comment by v-frankwang** [comment] 2024-09-30 07:34
@jkammerland We can't reproduce the problem using a simple project, can you provide the project where you reproduced the problem?
![image](https://github.com/user-attachments/assets/41e49e30-abbf-4e20-8ea3-eab1028245f3)

**Comment by jkammerland** [comment] 2024-09-30 10:04
@v-frankwang hmm, take a look at this (I made a branch without high cmake version requirement):

https://github.com/jkammerland/cbor_tags/tree/cmake-tools-regression

in case "main" doesn't work.

I get the following with cmake 3.30.3

[proc] Executing command: /opt/cmake-3.30.3/bin/cmake --build /mypath/.../cbor_tags/build --config Debug --target all --
[build] [1/2   0% :: 0.001] Re-checking globbed directories...
[build] [4/7  14% :: 0.009] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/os.cc.o
[build] [4/7  28% :: 0.011] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/format.cc.o
[build] [5/7  42% :: 0.013] Building CXX object test/CMakeFiles/tests.dir/test_cbor_tags.cpp.o
[build] [5/7  57% :: 0.020] Building CXX object test/CMakeFiles/tests.dir/test_cbor.cpp.o
[build] [5/7  71% :: 0.042] Linking CXX static library _deps/fmt-build/libfmtd.a
[build] [6/7  85% :: 0.176] Linking CXX executable test/tests
[driver] Build completed: 00:00:00.188
[build] Build finished with exit code 0

**Comment by jkammerland** [comment] 2024-09-30 10:07
It is the globbing that is the issue, when I remove this 

```cmake
file(GLOB_RECURSE TEST_SOURCES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
target_sources(tests PRIVATE ${TEST_SOURCES})
```

And replace with

```cmake
target_sources(tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/test_cbor_tags.cpp ${CMAKE_CURRENT_SOURCE_DIR}/test_cbor.cpp)
```

it works

**Comment by gcampbell-msft** [comment] 2024-09-30 11:12
@jkammerland Interesting! Thanks for the investigation. It sounds like there may be an edge case with how CMake prints it's output and how we parse it. 

In the two different scenarios, could you inform us as to how the command-line behaves? You can attempt this by performing all steps in the CMake extension, but then, instead of building with our extension, open a terminal in VSCode and run the same build command you see in your screenshot: 
![image](https://github.com/user-attachments/assets/ed78639e-f547-42b6-93f6-46dbcc4000dd)


This information can help us ascertain more about what is happening. Thanks!

**Comment by jkammerland** [comment] 2024-09-30 12:03
hmm, looks like weird output here too, maybe that is why? I built with cmake tools and then ran in terminal:

/opt/cmake-3.30.3/bin/cmake --build .

[0/2] Re-checking globbed directories...
[6/7] Linking CXX executable test/tests

**Comment by gcampbell-msft** [comment] 2024-09-30 12:07
@jkammerland Ah, it's possible this is an issue with the executable from Kitware itself, is it possible for you to test with an older cmake.exe version?

**Comment by jkammerland** [comment] 2024-09-30 18:12
@gcampbell-msft Tried and same result (3.20)

I tried switching generator to Unix Makefiles, that works. So it is when using Ninja this happens, idk why.

cmake .. -G "Unix Makefiles" 

/opt/cmake-3.30.3/bin/cmake --build .
[ 16%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/format.cc.o
[ 33%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/os.cc.o
[ 50%] Linking CXX static library libfmtd.a
[ 50%] Built target fmt
[ 66%] Building CXX object test/CMakeFiles/tests.dir/test_cbor.cpp.o
[ 83%] Building CXX object test/CMakeFiles/tests.dir/test_cbor_tags.cpp.o
[100%] Linking CXX executable tests
[100%] Built target tests
[driver] Build completed: 00:00:00.250
[build] Build finished with exit code 0

With `cmake .. -G Ninja `

you get my problem. So globbing and Ninja with cmake is the recipe so far. Something with ninja executable then, or cmake generation output?

**Comment by gcampbell-msft** [comment] 2024-10-01 14:29
Interesting! This sounds like it's an external issue with CMake+Ninja, could you create an issue on Kitware directly since it seems to not be due to our CMake Tools extension, but rather to the executable itself. https://gitlab.kitware.com/cmake/cmake/-/issues

We'll close this issue in preference to solving this there. Thanks.

**Closed by gcampbell-msft** 2024-10-01 14:29 UTC
Labels: more info needed
