### ISSUE TITLE
CMake Tools prompts to configure even when not working with C++ project

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-cmake-tools#1623] opened 2021-01-20 23:03 UTC
### Brief Issue Summary

I'm working in a Codespace both in the browser and in desktop VS Code. I have the CMake Tools extension installed. I am working in the following repo in the Codespace, which uses an Azure Functions and Node.js container: https://github.com/bamurtaugh/gh-static-e2e/tree/Update-container. 

In the browser-based Codespace when I started the function runtime (“Attach to Node Functions” debug configuration​​), I was shown a quick pick in the command palette to configure my C++ environment (I believe it was to select a kit).

In the desktop Codespace when I started the function runtime, I was also prompted to configure my environment, with the following notification: 

![image](https://user-images.githubusercontent.com/25310137/105210313-bda80e80-5aff-11eb-88ba-21865db35773.png)

Since I don't believe my app relates to CMake Tools at all, this felt unexpected/unnecessary to me.

### Expected:

No interactions with the CMake Tools extension.

### Other Notes/Information

The prompt seems to be coming from here, which looks like it runs on every workspace open if some configuration is set to do so, which looks like it might be the default: https://github.com/microsoft/vscode-cmake-tools/blob/92f045f67ea1bb04de4991be48783afefba53af8/src/extension.ts#L366 I think the default for the extension should be to not prompt unless they detect it's a CMake workspace somehow rather than always prompting by default.

**Comment by bobbrow** [comment] 2021-01-20 23:56
Thank you for your bug report.  This appears to be a duplicate of #1578.

**Closed by bobbrow** 2021-01-20 23:56 UTC
