### ISSUE TITLE
run in terminal should execute each time in a new terminal

### ISSUE THREAD

**Issue by shimondoodkin** [microsoft/vscode-cmake-tools#2277] opened 2021-12-03 15:57 UTC
### Brief Issue Summary

![image](https://user-images.githubusercontent.com/314464/144632417-91e2bf91-a46c-41f8-9b21-096ed56aec6f.png)

when clicking run in terminal, the second time it just writes the run filename as stdin to an exiting terminal of the previously launched program (in the same way).

it should open each time in a new terminal.

I have CMake Tools v1.9.2

**Comment by bobbrow** [comment] 2021-12-06 16:41
Thank you for reporting this issue.  I believe the root cause of this issue is the same as #2240 which should be addressed by PR #2266 in v1.10.

**Closed by bobbrow** 2021-12-06 16:41 UTC
