### ISSUE TITLE
Require Pass -iframework Options to C/C++ Extension

### ISSUE THREAD

**Issue by julee** [microsoft/vscode-cmake-tools#1178] opened 2020-04-16 06:48 UTC
See this issue:
https://github.com/microsoft/vscode-cpptools/issues/3323#issuecomment-614446896

macOS needs iframework option to help head files search, but with `"configurationProvider": "vector-of-bool.cmake-tools"` ,cmake tool doesn't pass this option.

I can only remove `"configurationProvider": "vector-of-bool.cmake-tools"`, and add `"compileCommands": "${workspaceFolder}/build/compile_commands.json"` to work around.

**Comment by JSchneidler** [comment] 2021-02-25 18:42
What are the implications of the workaround (using compileCommands instead of configurationProvider)? Does this affect the extension's functionality at all?

**Comment by andreeis** [comment] 2021-02-26 18:02
CMake Tools functionality is not affected at all, you can use this extension the same. What will be different is that with compile_commands.json, depending the C/C++ source code complexity and the operations you are running on what symbols, IntelliSense may work less accurate than when configurationProvider is used, because the las one is designed to store more information that CppTools can use. But depending the source code and operations performed on it, they may both work the same.

Another advantage for using configurationProvider is that it updates automatically when you change any CMake configure parameter (kit, variant, etc...). With compile_commands.json, you have to make sure you have an up-to-date one. Various settings or events may inhibit the creation of compile_commands. But you seem pretty experienced with it so I think you'll know how to ensure compile_commands.json is used properly here.

I think this workaround should be good enough for now. Let us know if you experience any inconvenience because of this.

**Comment by ABBAPOH** [comment] 2021-06-14 20:14
I encountered the same issue. The workaround works except for the other problem - I had to set "cppStandard": "c++17" in c_cpp_properties.json despite the fact the "-std=c++17" flag is present in "compile_commands.json". Without the flag all Qt headers are parsed incorrectly.
It would be really great if cmake-tools support frameworks on Mac correctly.
Thanks in advance!

**Comment by ggreco** [comment] 2023-03-27 15:21
... still not working in 2023, the compile_commands workaround works, but it's something that cannot really be pushed to a repo (changing the build directory for instance will break it and it does not work with cppStandard and other cmake set variables)...

**Comment by bobbrow** [comment] 2023-03-27 16:20
CMake doesn't provide us the information we need to make it work.  There's an issue open that you can go upvote.  https://gitlab.kitware.com/cmake/cmake/-/issues/19897.

I'm going to close this as a duplicate of #2324 where this was also discussed.

**Closed by bobbrow** 2023-03-27 16:20 UTC
Labels: bug, Feature: cpptools integration
