### ISSUE TITLE
Selecting CMake Tools as configuration provider has error squiggles for all standard library includes

### ISSUE THREAD

**Issue by dropTableUsers42** [microsoft/vscode-cmake-tools#3772] opened 2024-05-18 08:45 UTC
### Brief Issue Summary

When I select CMake Tools (v1.18.39) as configuration provider, I get error squiggles in all standard library includes.

MWE:
Project structure is
root
\|_ main.cpp
\|_ CMakeLists.txt

![image](https://github.com/microsoft/vscode-cmake-tools/assets/26690571/42588ac4-2688-48fe-90e8-73bdb4e68c31)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/26690571/05af5ba0-09ea-402f-b7c0-4ccb439b2799)

My generator is Visual Studio Community 2022 Release - amd64

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.90.0-insider",
  "cmtVersion": "1.18.39",
  "configurations": [
    {
      "folder": "c:\\Users\\rwita\\Data\\Acads\\Programming\\C++\\New folder",
      "cmakeVersion": "3.28.0",
      "configured": true,
      "generator": "Visual Studio 17 2022",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug",
      "Release",
      "MinSizeRel",
      "RelWithDebInfo"
    ],
    "requests": [
      "file:///c%3A/Users/rwita/Data/Acads/Programming/C%2B%2B/New%20folder/main.cpp"
    ],
    "responses": [
      {
        "uri": "file:///c%3A/Users/rwita/Data/Acads/Programming/C%2B%2B/New%20folder/main.cpp",
        "configuration": {
          "includePath": [],
          "defines": [],
          "compilerPath": "c:/program files/microsoft visual studio/2022/community/vc/tools/msvc/14.39.33519/bin/hostx64/x64/cl.exe",
          "compilerArgs": [],
          "compilerFragments": [
            "/DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 3,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "ALL_BUILD",
        "type": "UTILITY"
      },
      {
        "name": "ZERO_CHECK",
        "type": "UTILITY"
      },
      {
        "name": "main",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[main] Building folder: New folder 
[expand] expanding cmake
[main] Saving open files before configure/build
[expand] expanding cmake
[expand] expanding cmake
[expand] expanding cmake
[build] Starting build
[driver] Start build ALL_BUILD
[expand] expanding --build
[expand] expanding c:/Users/rwita/Data/Acads/Programming/C++/New folder/build
[expand] expanding --config
[expand] expanding Debug
[expand] expanding --target
[expand] expanding ALL_BUILD
[expand] expanding -j
[expand] expanding 18
[expand] expanding --
[proc] Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --build "c:/Users/rwita/Data/Acads/Programming/C++/New folder/build" --config Debug --target ALL_BUILD -j 18 --
[proc]   with environment: {"ALLUSERSPROFILE":"C:\\ProgramData","AMDRMSDKPATH":"C:\\Program Files\\AMD\\RyzenMasterSDK\\","APPDATA":"C:\\Users\\rwita\\AppData\\Roaming","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"1","CHROME_CRASHPAD_PIPE_NAME":"\\\\.\\pipe\\crashpad_3556_FAHITFVQDTMCLTYR","COMPUTERNAME":"PHYSWIZHP","ComSpec":"C:\\windows\\system32\\cmd.exe","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","ELECTRON_RUN_AS_NODE":"1","HOME":"C:\\Users\\rwita","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\rwita","LOCALAPPDATA":"C:\\Users\\rwita\\AppData\\Local","LOGONSERVER":"\\\\PHYSWIZHP","NUMBER_OF_PROCESSORS":"16","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","OneDrive":"C:\\Users\\rwita\\OneDrive","OneDriveConsumer":"C:\\Users\\rwita\\OneDrive","OnlineServices":"Online Services","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD","PROCESSOR_LEVEL":"25","PROCESSOR_REVISION":"4401","PSModulePath":"%ProgramFiles%\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","Path":"C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22000.0\\x64;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\VC\\VCPackages;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\bin\\Roslyn;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Team Tools\\DiagnosticsHub\\Collector;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22000.0\\\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\\\x64;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\\\MSBuild\\Current\\Bin\\amd64;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\Microsoft\\jdk-11.0.16.101-hotspot\\bin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\Program Files\\WindowsPowerShell\\Scripts;C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\Program Files (x86)\\gnupg\\bin;C:\\Program Files\\HP\\HP One Agent;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Users\\rwita\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\rwita\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\rwita\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\batcat\\bat-v0.23.0-i686-pc-windows-msvc;C:\\Users\\rwita\\AppData\\Local\\Microsoft\\WinGet\\Packages\\junegunn.fzf_Microsoft.Winget.Source_8wekyb3d8bbwe;C:\\Program Files\\ripgrep\\ripgrep-13.0.0-x86_64-pc-windows-msvc;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Users\\rwita\\vcpkg;C:\\Program Files\\Graphviz\\bin;C:\\Users\\rwita\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\VC\\Linux\\bin\\ConnectionManagerExe","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","RegionCode":"APJ","SystemDrive":"C:","SystemRoot":"C:\\windows","TEMP":"C:\\Users\\rwita\\AppData\\Local\\Temp","TMP":"C:\\Users\\rwita\\AppData\\Local\\Temp","USERDOMAIN":"PHYSWIZHP","USERDOMAIN_ROAMINGPROFILE":"PHYSWIZHP","USERNAME":"rwita","USERPROFILE":"C:\\Users\\rwita","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_CODE_CACHE_PATH":"C:\\Users\\rwita\\AppData\\Roaming\\Code - Insiders\\CachedData\\f209ce35ef894bd32c12057724e8d1f1139c433f","VSCODE_CRASH_REPORTER_PROCESS_TYPE":"extensionHost","VSCODE_CWD":"C:\\windows\\system32","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_IPC_HOOK":"\\\\.\\pipe\\d7fe34fa-1.90.0-insider-main-sock","VSCODE_L10N_BUNDLE_LOCATION":"","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"osLocale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_PID":"3556","platformcode":"M7","windir":"C:\\windows","DevEnvDir":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\","Framework40Version":"v4.0","FrameworkDir":"C:\\Windows\\Microsoft.NET\\Framework64\\","FrameworkDIR64":"C:\\Windows\\Microsoft.NET\\Framework64\\","FrameworkVersion":"v4.0.30319","FrameworkVersion64":"v4.0.30319","INCLUDE":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\include;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\ATLMFC\\include;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\VS\\include;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22000.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\um;C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\winrt;C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\cppwinrt","LIB":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\ATLMFC\\lib\\x64;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.22000.0\\ucrt\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\\\lib\\10.0.22000.0\\\\um\\x64","LIBPATH":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\ATLMFC\\lib\\x64;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\lib\\x64;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\lib\\x86\\store\\references;C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.22000.0;C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.22000.0;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319","UCRTVersion":"10.0.22000.0","UniversalCRTSdkDir":"C:\\Program Files (x86)\\Windows Kits\\10\\","VCIDEInstallDir":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\VC\\","VCINSTALLDIR":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\","VCToolsRedistDir":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Redist\\MSVC\\14.38.33135\\","VisualStudioVersion":"17.0","VSINSTALLDIR":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\","WindowsLibPath":"C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.22000.0;C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.22000.0","WindowsSdkBinPath":"C:\\Program Files (x86)\\Windows Kits\\10\\bin\\","WindowsSdkDir":"C:\\Program Files (x86)\\Windows Kits\\10\\","WindowsSDKLibVersion":"10.0.22000.0\\","WindowsSDKVersion":"10.0.22000.0\\","VS170COMNTOOLS":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools","CC":"cl.exe","CXX":"cl.exe","NINJA_STATUS":"[%s/%t %p :: %e] "}
[expand] expanding cmake
[expand] expanding cmake
[expand] expanding cmake
[build] MSBuild version 17.9.8+b34f75857 for .NET Framework
[build] 
[build]   1>Checking Build System
[build]   Building Custom Rule C:/Users/rwita/Data/Acads/Programming/C++/New folder/CMakeLists.txt
[build]   main.cpp
[build]   main.vcxproj -> C:\Users\rwita\Data\Acads\Programming\C++\New folder\build\Debug\main.exe
[build]   Building Custom Rule C:/Users/rwita/Data/Acads/Programming/C++/New folder/CMakeLists.txt
[driver] Build completed: 00:00:02.841
[cmakefileapi-parser] Read reply folder: c:\Users\rwita\Data\Acads\Programming\C++\New folder\build\.cmake\api\v1\reply
[cmakefileapi-parser] Found index files: ["cache-v2-e0ec436a20f253efec50.json","cmakeFiles-v1-bc5313df1c5f7e5ebdb2.json","codemodel-v2-2a29104ea686e81a8186.json","directory-.-Debug-d0094a50bb2071803777.json","directory-.-MinSizeRel-d0094a50bb2071803777.json","directory-.-Release-d0094a50bb2071803777.json","directory-.-RelWithDebInfo-d0094a50bb2071803777.json","index-2024-05-18T08-43-10-0724.json","target-ALL_BUILD-Debug-26f43c8a8230e42424ad.json","target-ALL_BUILD-MinSizeRel-26f43c8a8230e42424ad.json","target-ALL_BUILD-Release-26f43c8a8230e42424ad.json","target-ALL_BUILD-RelWithDebInfo-26f43c8a8230e42424ad.json","target-main-Debug-073da97708c743b84922.json","target-main-MinSizeRel-473c76ee0362bd240ae1.json","target-main-Release-8ce4b66667568f3e8129.json","target-main-RelWithDebInfo-da4f12c16c337cc7bf53.json","target-ZERO_CHECK-Debug-3b83dd049c5eefc5aea1.json","target-ZERO_CHECK-MinSizeRel-3b83dd049c5eefc5aea1.json","target-ZERO_CHECK-Release-3b83dd049c5eefc5aea1.json","target-ZERO_CHECK-RelWithDebInfo-3b83dd049c5eefc5aea1.json","toolchains-v1-6c90ce5d48e350a15dba.json"]
[expand] expanding cmake
[expand] expanding C:/Users/rwita/Data/Acads/Programming/C++/New folder
[expand] expanding ${workspaceFolder}/build
[build] Build finished with exit code 0
[expand] expanding cmake
[cache] Reading CMake cache file c:/Users/rwita/Data/Acads/Programming/C++/New folder/build/CMakeCache.txt
[cache] Parsing CMake cache string
[expand] expanding cmake
[extension] [4953] cmake.build finished (returned 0)
[expand] expanding cmake
[expand] expanding cmake
[expand] expanding cmake
```

### Additional Information

Output for C/C++: Log Diagnostics
```
-------- Diagnostics - 5/18/2024, 2:14:02 PM
Version: 1.20.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:/Users/rwita/Data/Acads/Programming/C++/New folder/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22000.0",
    "compilerPath": "cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerPathInCppPropertiesJson": "cl.exe",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "c:/Users/rwita/Data/Acads/Programming/C++/New folder/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:/users/rwita/data/acads/programming/c++/new folder/build/cmakefiles/8f1717bcebdc2240e7395f58833f31f3",
        "c:/users/rwita/data/acads/programming/c++/new folder"
    ],
    "compilerPath": "c:/program files/microsoft visual studio/2022/community/vc/tools/msvc/14.39.33519/bin/hostx64/x64/cl.exe",
    "compilerArgs": [],
    "compilerFragments": [
        "/DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1"
    ]
}
cpptools version (native): 1.20.5.0
Translation Unit Mappings:
[ C:\Users\rwita\Data\Acads\Programming\C++\New folder\main.cpp - source TU]:
Translation Unit Configurations:
[ C:\Users\rwita\Data\Acads\Programming\C++\New folder\main.cpp ]:
    Process ID: 6988
    Memory Usage: 51 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe
    Includes:
        C:\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\cppwinrt
    Defines:
        WIN32
        _WINDOWS
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --rtti
Total Memory Usage: 51 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4758
Number of files parsed: 2
```

I can see that Includes does not contain the compiler standard includes folder

**Comment by v-frankwang** [comment] 2024-05-21 02:22
@dropTableUsers42 I'm very sorry I can't reproduce the problem, can you give me some advice as well as provide me with the program you used to reproduce the problem?

![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/bb27216c-ac19-4d09-b6d5-33f37e0d393b)

**Comment by SAquarius** [comment] 2024-05-24 12:47
Use the extension "C/C++" with version 19.9 will fix this!

**Comment by v-frankwang** [comment] 2024-05-30 00:43
@dropTableUsers42 Can we close it now that this issue is not reproducing?

**Closed** 2024-10-30 15:08 UTC
Labels: more info needed
