### ISSUE TITLE
Creating weird folders within workspace directory

### ISSUE THREAD

**Issue by ThexXTURBOXx** [microsoft/vscode-cmake-tools#2827] opened 2022-10-28 18:19 UTC
### Brief Issue Summary

When configuring any CMake project using the default configuration of the extension, weird folders keep appearing:
![grafik](https://user-images.githubusercontent.com/12763829/198704309-5ff069d8-ff6a-4f0b-8cf4-7844034a052d.png)

The folder corresponds to the path where my workspace is located on the disk, i.e., `${workspaceFolder}`.
However, this folder is created within the `${workspaceFolder}` directory for some reason.
So, if my workspace is located under
`D:/Uni/Masterarbeit/ECC`, then the extension tells CMake to create the folders `D:\Uni\Masterarbeit\ECC\d\Uni\Masterarbeit\ECC\build`
The weird character after the `d` comes from limitations within the charset of folder names under Windows (i.e., it would be a colon `:` normally).
I have tried many different configurations, but none of them do what the default configuration should do.

The issue is existent on both my computers. Both running CMake from CygWin, so that could be a culprit?

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.72.2",
  "cmtVersion": "1.12.27",
  "configurations": [
    {
      "folder": "d:\\Uni\\Masterarbeit\\ECC",
      "cmakeVersion": "3.23.2",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[main] Configuring folder: ECC 
[main] Saving open files before configure/build
[driver] Start configure 
[driver] Running pre-configure checks and steps
[cmakefileapi-driver] Configuring using kit
[cmakefileapi-driver] Invoking CMake D:\cygwin64\bin\cmake.EXE with arguments ["--no-warn-unused-cli","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_BUILD_TYPE:STRING=Debug","-Sd:/Uni/Masterarbeit/ECC","-Bd:/Uni/Masterarbeit/ECC/build","-G","Unix Makefiles"]
[proc] Executing command: D:\cygwin64\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -Sd:/Uni/Masterarbeit/ECC -Bd:/Uni/Masterarbeit/ECC/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The CXX compiler identification is unknown
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] CMake Error at /usr/share/cmake-3.23.2/Modules/CMakeDetermineCompilerABI.cmake:79 (file):
[cmake]   file STRINGS file
[cmake]   "d:/Uni/Masterarbeit/ECC/d:/Uni/Masterarbeit/ECC/build/CMakeFiles/3.23.2/CMakeDetermineCompilerABI_CXX.bin"
[cmake]   cannot be read.
[cmake] Call Stack (most recent call first):
[cmake]   /usr/share/cmake-3.23.2/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
[cmake]   CMakeLists.txt:2 (project)
[cmake] 
[cmake] 
[cmake] -- Check for working CXX compiler: /usr/bin/c++.exe - skipped
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: D:\cygwin64\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -Sd:/Uni/Masterarbeit/ECC -Bd:/Uni/Masterarbeit/ECC/build -G "Unix Makefiles" exited with code: 1 and signal: null
[extension] [9495] cmake.configureAll finished (returned 1)
```

### Additional Information

I could not help but notice the lower case drive name in the CMake command: `d:/Uni/Masterarbeit/ECC`. I do not know if that creates an issue, but it would be worth fixing anyways, just to see...

**Comment by ThexXTURBOXx** [comment] 2022-10-28 18:46
Addendum: After some searching, I have found #389 which explains the same weird behavior and they provided a workaround for this issue.
I changed the build directory setting to `/cygdrive/d/Uni/Masterarbeit/ECC/build` and it worked for now.
However, I will leave this issue open since there still seems to be an underlying problem with properly detecting the right CygWin settings and converting paths to POSIX.

**Comment by bobbrow** [comment] 2022-10-28 21:54
> However, I will leave this issue open since there still seems to be an underlying problem with properly detecting the right CygWin settings and converting paths to POSIX.

#389 is still open.  It appears that this issue is a duplicate of that one.  Is there something else we should be tracking here?

**Comment by ThexXTURBOXx** [comment] 2022-10-29 10:36
I don't think there is anything new in this issue right here. However, the original issue should have pretty high priority as it seems to affect every CygWin user

**Comment by bobbrow** [comment] 2022-10-31 17:20
Thanks for confirming.  We will close this issue as a duplicate then.  We prioritize issues based on reactions and issue #389 doesn't appear to have any 👍 reactions yet.  Could you please go click on the ![image](https://user-images.githubusercontent.com/12818240/199069449-73469a3a-3c52-4dda-bec3-7008dc6da919.png) in that issue and add a 👍 for yourself?

**Closed by bobbrow** 2022-10-31 17:20 UTC
