### ISSUE TITLE
Unable to start debugging in version 1.10.5 Unexpected GDB output from command

### ISSUE THREAD

**Issue by joervargas** [microsoft/vscode-cmake-tools#2489] opened 2022-04-09 14:26 UTC
### Brief Issue Summary

Upon upgrading my CMake Tools extenstion to version 1.10.5, I am no longer able to run the debugger.  Downgrading to a previous version 1.9 solves the issue, however I write this to bring it to your attention in hopes that the next version resolves the issue. 

OS: Linux
Distro: Fedora

I get the following output on my debug console from trying to run the debugger.

![CMakeTools Error](https://user-images.githubusercontent.com/65709651/162577944-b34efe14-d15c-4505-bf15-ccfe5ea038a8.png)

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.66.1",
  "cmtVersion": "1.10.5",
  "configurations": [
    {
      "folder": "/home/joe/Projects/Cpp/sdl_vk/vkproj2",
      "cmakeVersion": "3.22.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/lib64/ccache/clang",
        "CXX": "/usr/lib64/ccache/clang++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///home/joe/Projects/Cpp/sdl_vk/vkproj2/src/DescriptorPool.cpp"
    ],
    "responses": [
      {
        "uri": "file:///home/joe/Projects/Cpp/sdl_vk/vkproj2/src/DescriptorPool.cpp",
        "configuration": {
          "defines": [],
          "standard": "gnu++17",
          "includePath": [
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/libs/VkMemAllocator/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/libs/VkMemAllocator/src",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/libs/STB_Image/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/libs/STB_Image/src",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/libs/TinyObjLoader/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/libs/TinyObjLoader/src",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/VkContext/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/VkContext/src",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Constants/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Globals/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Commands/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Commands/src",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Buffers/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Buffers/src",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Images/include",
            "/home/joe/Projects/Cpp/sdl_vk/vkproj2/src/Images/src"
          ],
          "compilerPath": "/usr/lib64/ccache/clang++",
          "compilerArgs": [
            "-g",
            "-std=gnu++17"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 9,
    "executablesCount": 1,
    "librariesCount": 8,
    "targets": [
      {
        "name": "Buffers",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "Commands",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "Globals",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "Images",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "STB_Image",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "TinyObjLoader",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "VkContext",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "VkMemAllocator",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "vkproj2",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[main] Building folder: vkproj2 
[main] Saving open files before configure/build
[build] Starting build
[driver] Start build all
[proc] Executing command: /usr/bin/cmake --build /home/joe/Projects/Cpp/sdl_vk/vkproj2/build --config Debug --target all --
[build] ninja: no work to do.
[cmakefileapi-parser] Read reply folder: /home/joe/Projects/Cpp/sdl_vk/vkproj2/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-99046c594f269432aec2.json","codemodel-v2-f1d3eceb6c780374e2c6.json","directory-.-Debug-f5ebdc15457944623624.json","directory-libs.STB_Image-Debug-9aca48ee461cc58b5541.json","directory-libs.TinyObjLoader-Debug-8fffb054d6ca8e95d721.json","directory-libs.VkMemAllocator-Debug-18421b2f9bc6b15921f6.json","directory-src.Buffers-Debug-de4b750ec72f04d44817.json","directory-src.Commands-Debug-e502f3c7c715a68ca444.json","directory-src.Constants-Debug-c77a7bf1635368314cd1.json","directory-src.Globals-Debug-d3c8c21e22e66a67ca5b.json","directory-src.Images-Debug-2959e3beaa2fbf7676c8.json","directory-src.VkContext-Debug-5e8947d964d157106525.json","index-2022-04-09T14-20-16-0498.json","target-Buffers-Debug-f4e4b5fa3db2657fa979.json","target-Commands-Debug-585702b1d5a360ad93bd.json","target-Globals-Debug-52bb5f278e089bdb71aa.json","target-Images-Debug-a5e8870c53a2aac2cc04.json","target-STB_Image-Debug-64e3ca901437e3835bd0.json","target-TinyObjLoader-Debug-f657f960b6fe651a09f0.json","target-VkContext-Debug-c1d45a8c8bf31a39759f.json","target-VkMemAllocator-Debug-31b4ad447289cf2fe7e8.json","target-vkproj2-Debug-05bc9045a3373fdb35fb.json","toolchains-v1-232cb3f94aaecd1cab91.json"]
[build] Build finished with exit code 0
[cache] Reading CMake cache file /home/joe/Projects/Cpp/sdl_vk/vkproj2/build/CMakeCache.txt
[cache] Parsing CMake cache string
[extension] [7800] cmake.build finished (returned 0)
```

### Additional Information

Not sure what to make of these errors. I believe these are set behind the scenes from an extension-user point of view.  I'm assuming there's maybe an extra quotation mark somewhere.  The popup comes up at the same time my debug console fails to start debugging.  I just want to reiterate that downgrading to version 1.9 of the extension makes debugging run fine again.

![CMake Tools Error2](https://user-images.githubusercontent.com/65709651/162578259-c5c41394-8a50-4a92-b7c9-7140be517b0d.png)
![CMakeTools Error](https://user-images.githubusercontent.com/65709651/162578273-25a72b4b-ab4c-4764-9f59-119cfd11d1b3.png)

**Comment by elahehrashedi** [comment] 2022-04-11 16:54
Thank you for reporting this issue, this seems to be 
a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/2442. we are working on a fix for this

**Closed** 2022-04-11 16:55 UTC
Labels: bug, duplicate, Feature: debug/launch
