### ISSUE TITLE
Regression with CMake Tools v1.19.28 (pre-release) : it enforces Ninja as generator even if the Ninja tool is not installed

### ISSUE THREAD

**Issue by ebouteillon** [microsoft/vscode-cmake-tools#3936] opened 2024-07-25 08:13 UTC
### Brief Issue Summary

New versions v1.19.28 (pre-release) and v1.19.27 (pre-release) enforces "Ninja" as generator instead of detecting "Unix Makefiles".

Ninja is not installed on my environment and I am using GNU make. It results in errors in CMake configure step. See errors in "Debug log" section.

### CMake Tools Diagnostics

```shell
v1.19.28 (pre-release):

{
  "os": "linux",
  "vscodeVersion": "1.91.1",
  "cmtVersion": "1.19.28",
  "configurations": [
    {
      "folder": "/home/axis/workspace/map-core",
      "cmakeVersion": "3.29.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
______________

v1.19.26 (pre-release):

{
  "os": "linux",
  "vscodeVersion": "1.91.1",
  "cmtVersion": "1.19.26",
  "configurations": [
    {
      "folder": "/home/axis/workspace/map-core",
      "cmakeVersion": "3.29.4",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "/opt/rh/devtoolset-12/root/usr/bin/gcc",
        "CXX": "/opt/rh/devtoolset-12/root/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 97,
    "executablesCount": 32,
    "librariesCount": 36,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
Opening a project with v1.19.28 (pre-release), I get the following error.


[proc] Executing command: /opt/cmake/bin/cmake --version
[proc] Executing command: /opt/cmake/bin/cmake -E capabilities
[kit] Successfully loaded 5 kits from /home/axis/.local/share/CMakeTools/cmake-tools-kits.json
[variant] Loaded new set of variants
[proc] Executing command: /opt/rh/devtoolset-12/root/usr/bin/gcc -v
[cmakefileapi-driver] Removing /home/axis/workspace/map-core/build/CMakeCache.txt
[main] Configuring project: map-core 
[proc] Executing command: /opt/cmake/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/opt/rh/devtoolset-12/root/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/opt/rh/devtoolset-12/root/usr/bin/g++ --no-warn-unused-cli -S/home/axis/workspace/map-core -B/home/axis/workspace/map-core/build -G Ninja
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: /opt/cmake/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/opt/rh/devtoolset-12/root/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/opt/rh/devtoolset-12/root/usr/bin/g++ --no-warn-unused-cli -S/home/axis/workspace/map-core -B/home/axis/workspace/map-core/build -G Ninja exited with code: 1


Equivalent issue with v1.19.27 (pre-release).

But no issue with v1.19.26 (pre-release):

[main] Configuring project: map-core 
[proc] Executing command: /opt/cmake/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/opt/rh/devtoolset-12/root/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/opt/rh/devtoolset-12/root/usr/bin/g++ --no-warn-unused-cli -S/home/axis/workspace/map-core -B/home/axis/workspace/map-core/build -G "Unix Makefiles"
... snip ...
[cmake] ~/workspace/map-core/build
[cmake] -- Configuring done (6.9s)
[cmake] -- Generating done (0.5s)
[cmake] -- Build files have been written to: /home/axis/workspace/map-core/build
```

**Comment by gcampbell-msft** [comment] 2024-07-25 12:56
@ebouteillon What settings do you have set for `cmake.generator`? I notice that in your CMake Tools diagnostics output, it says that your generator is selected as "Ninja".

**Comment by ebouteillon** [comment] 2024-07-25 14:18
Hi @gcampbell-msft ,

This key is not set. Here is the screenshot of the Settings tab:

![image](https://github.com/user-attachments/assets/f311bc19-0b30-45e4-b629-0ee036dc204b)

In addition this is all the `cmake.*` keys in file `setting.json`:

```json
    "cmake.parallelJobs": 6,
    "cmake.showOptionsMovedNotification": false,
    "cmake.pinnedCommands": [
        "workbench.action.tasks.configureTaskRunner",
        "workbench.action.tasks.runTask"
    ],
    "cmake.ctest.allowParallelJobs": true,
    "cmake.preferredGenerators": [],
```

**Comment by jophippe** [comment] 2024-07-25 20:05
Thanks for your feedback @ebouteillon!
This was an unintended regression of removing the requirement of Ninja or Make to be on PATH, which was a side effect of a fix to the generator fallback mechanism. We agreed that checking the PATH for Ninja or Make is indeed the right thing to do, since most customers will have their preferred generator on their PATH. PR #3938 has been merged to fix this and should be available in the next release.
Thanks again!

**Closed by jophippe** 2024-07-25 20:05 UTC
Labels: bug
