### ISSUE TITLE
Duplicate build tasks in quick pick list

### ISSUE THREAD

**Issue by jurf** [microsoft/vscode-cmake-tools#4064] opened 2024-09-13 12:29 UTC
### Brief Issue Summary

With `cmake.buildTask` active and a build task configured, CMake also shows the template build tasks.

![quick pick list screenshot](https://github.com/user-attachments/assets/ba425141-d895-4c05-9aaa-360b8f32fb1d)

Only one of the tasks in the screenshot is configured manually, but two other build tasks are present. This behaviour did not happen a few weeks back.

Possibly duplicate of the closed and locked #2936.

### CMake Tools Diagnostics

```shell
Some details omitted as this is a work machine.

{
  "os": "win32",
  "vscodeVersion": "1.93.1",
  "cmtVersion": "1.19.51",
  "configurations": [
    {
      "folder": "c:\\projects\\cmake_project",
      "cmakeVersion": "3.30.2",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

Relevant task in `tasks.json`:

```json
        {
            "type": "cmake",
            "label": "CMake: build (manually configured in tasks.json)",
            "command": "build",
            "preset": "${command:cmake.activeBuildPresetName}",
            "group": {
                "kind": "build",
                "isDefault": false
            },
            "problemMatcher": "$gcc",
            "presentation": {
                "revealProblems": "onProblem"
            },
            "detail": "CMake template build task"
        }
```

**Comment by v-frankwang** [comment] 2024-09-14 09:46
@jurf I'm very sorry that we can't reproduce the problem you mentioned, can you provide us with the detailed procedure? So that we can quickly go and investigate the issue. Here are my results, can you give some suggestions?
![image](https://github.com/user-attachments/assets/48ed15cb-b3cb-4670-aa74-ee53757b8acc)

**Comment by jurf** [comment] 2024-09-17 09:01
Hi, thanks for the reply.

Perhaps there is a misunderstanding. IIRC before, when one manually defined the task, it overrode the automatically generated build tasks. Now one has to pick one in the list, with no option to select a default, adding a step to every build. First there was only the manually-defined task in the list, now I see four, two of which are duplicates. That is the bug I am reporting.

Why the task with the name `build` is not present in your project, I have no idea. In my project it behaves the same as `CMake: build`.

If there is any more information I can provide, I would gladly be of assistance.

**Comment by v-frankwang** [comment] 2024-09-20 07:22
@gcampbell-msft 
I tried to reproduce the issue on the previous version: v1.17.17 still got the same result as https://github.com/microsoft/vscode-cmake-tools/issues/4064#issuecomment-2350933655. Can you give me some advice?

![image](https://github.com/user-attachments/assets/a4f2c337-e1f8-42dc-8aa6-f9b2aa833f83)

**Comment by jurf** [comment] 2024-09-20 09:44
Could you send me the test project that you used? I would be curious if I get the same behaviour.

**Comment by v-frankwang** [comment] 2024-09-20 10:03
@jurf Here are the items I use, I hope you can tell me if anything is incorrect and I look forward to hearing from you!
[4064.zip](https://github.com/user-attachments/files/17073387/4064.zip)

**Comment by gcampbell-msft** [comment] 2024-09-20 10:47
I just tested and even on v1.16.32, we see this: 
![image](https://github.com/user-attachments/assets/364b67a9-010a-4e71-81b6-0864d0cfe6f1)

Again, this is because the default tasks are provided to VS Code, and then VS Code separately parses the tasks.json. Closing as by design.

**Closed by gcampbell-msft** 2024-09-20 10:47 UTC
Labels: more info needed
