### ISSUE TITLE
Can't select generator ninja/make

### ISSUE THREAD

**Issue by aelray** [microsoft/vscode-cmake-tools#1224] opened 2020-05-08 12:52 UTC
### Brief Issue Summary

I'm running a project in a container and want to use ninja but CMakeTools default to Unix Makefiles.

Neither setting 
`"cmake.generator": "Ninja"` nor

`"cmake.preferredGenerators": [
    "Ninja",
    "Unix Makefiles"
]`
in settings.json leads to the desired effect of using ninja.

### Expected:

CMake configures project with Ninja

### Apparent Behavior:

CMake configures project with Unix Makefiles

### Platform and Versions

- **Operating System**: Windows/Ubuntu container
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.45.0
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: ARMClang

**Comment by andreeis** [comment] 2020-05-08 16:10
Closing as dupe of https://github.com/microsoft/vscode-cmake-tools/issues/1084. We will release a fix soon with CMake Tools 1.4.

**Comment by aelray** [comment] 2020-05-08 16:22
How is that related? My problem is actually inverted. I do want Ninja but get make instead.

**Comment by andreeis** [comment] 2020-05-08 16:53
Ok, maybe I closed too soon. Reopening for investigation. Double check that you have Ninja installed and that it is on the path. 
Maybe the container creates some interesting situation, we will try to repro this.

**Comment by aelray** [comment] 2020-05-08 18:26
Ninja is definitely installed and on the path. I used it to configure directly from command line.

**Comment by aelray** [comment] 2020-05-11 11:13
I think there must have been an error in my configuration. After rebuilding the container it now picks Ninja, as desired. So I think you can close this

**Closed** 2020-05-11 11:13 UTC
Labels: more info needed
