### ISSUE TITLE
Debug not works if build output path of excutable is outside of CMake build directory

### ISSUE THREAD

**Issue by tymmkang** [microsoft/vscode-cmake-tools#1089] opened 2020-02-23 14:59 UTC
1. CMake project specified output directory via 'set_target_properties' and 'RUNTIME_OUTPUT_DIRECTORY'

2. The directory is not under CMake build directory

3. Debug works on version 1.2.3 but not in 1.3.0

Below links is my CMake template project.
[cpp-cmake-skeleton](https://github.com/tymmkang/cpp-cmake-skeleton)

Please build and debug with version 1.2.3
After then remove 'build' and 'outputs' folder and build and debug with version 1.3.0

This is the error message. It looks like a path problem.
![image](https://user-images.githubusercontent.com/7869441/75114311-65228400-5698-11ea-842a-6589d9aa948d.png)

**Comment by KoeMai** [comment] 2020-02-23 16:13
This is a duplicate of #1067.

**Closed** 2020-02-24 17:24 UTC
Labels: Feature: debug, bug, duplicate

**Comment by tymmkang** [comment] 2020-03-02 10:05
On version 1.3.1 still not working

**Comment by KoeMai** [comment] 2020-03-02 17:13
Does it work if you change `cmake.cmakeCommunicationMode` setting back to `ServerAPI`?

**Comment by tymmkang** [comment] 2020-03-03 13:33
After reset setting, it works. thank you.

**Comment by KoeMai** [comment] 2020-03-03 17:06
I tried your example project but I am not able to reconstruct the problem.
Could you provide us the CMake Tools Log file for `cmake.cmakeCommunicationMode`=`FileAPI`?

**Comment by tymmkang** [comment] 2020-03-03 18:47
[Uploading build.zip…]()

Those files are CMake build output with the error message above.
