### ISSUE TITLE
How to set running parameters when I click on the "launch" button provided by cmake-tool?

### ISSUE THREAD

**Issue by monage2018** [microsoft/vscode-cmake-tools#1449] opened 2020-09-21 10:01 UTC
Hi,
    My executable file(test) has a parameters, for exmaple:
    ./test "config.yaml"
    The cmake-tool can detect all executables file, when i choose "test" and click on the "launch" button, there will be an error because there are not enough parameters.
    I know that creating a "launch.json" in ".vscode" file will help, but Is there any way to add parameters by cmake-tool?

**Comment by bobbrow** [comment] 2020-09-21 15:58
Thank you for your feedback.  This is a duplicate of #1395.
PR #1444 addresses this and will be in the next release.

**Closed by bobbrow** 2020-09-21 15:58 UTC
