### ISSUE TITLE
Clickable file links in output window not working

### ISSUE THREAD

**Issue by alan-davies-se** [microsoft/vscode-cmake-tools#2167] opened 2021-10-12 09:15 UTC
### Brief Issue Summary

In settings.json I have:

"cmake.buildDirectory": "${workspaceFolder}/build/${buildKit}",

Compiling some code with errors in produces output in both the 'Output' and 'Problems' tabs. The links in the 'Problems' tabs are clickable and work. The relative paths in the output window are relative to the cmake.buildDirectory; clicking them brings up an error dialog that the file cannot be found.

**Comment by andreeis** [comment] 2021-10-13 16:29
@alan-davies-se, thank you for creating this report. It is related to (or even a duplicate of) two other issues we are tracking. Read through them especially towards the end, you may find some workarounds that apply to you. And let us know if any info from there was useful for your scenario, it will help us triage this report properly (or close it).

https://github.com/microsoft/vscode-cmake-tools/issues/1401

https://github.com/microsoft/vscode-cmake-tools/issues/495

**Comment by Delgan** [comment] 2021-10-30 09:46
Hi!

Clickable link for relative path would be very convenient! I switched to this extension recently and this is the only feature I truly miss compared to manual builds using integrated terminal.

I made a video to illustrate the problem: 

https://user-images.githubusercontent.com/4193924/139528005-043940af-57f6-4a3d-a988-689184535e32.mp4

I don't know how feasible it is, I hope it can eventually be integrated to the "Output" tab without requiring the `tasks.json` workaround. :+1:

**Comment by Delgan** [comment] 2023-10-25 08:00
Update regarding this ticket: I'm no longer able to reproduce this issue because the `ninja` commands now outputs absolute paths (in my case at least). I don't remember which `ninja` version I was using 2 years ago. Therefore, I don't know if the bug is actually solved within `vscode-cmake-tools` or if it just disappeared in appearance.

**Comment by gcampbell-msft** [comment] 2023-10-25 14:31
@Delgan Thanks for clarifying. Based on your comment and this comment: https://github.com/microsoft/vscode-cmake-tools/issues/2167#issuecomment-942663249, this issue seems like it can be closed. Please notify us if this is incorrect.

**Closed by gcampbell-msft** 2023-10-25 14:31 UTC
Labels: Feature: build

**Comment by dzid26** [comment] 2024-04-04 21:16
I have absolute path but they are still not clickable.
