### ISSUE TITLE
Project Outline not showing targets

### ISSUE THREAD

**Issue by ei06125** [microsoft/vscode-cmake-tools#2956] opened 2023-01-21 01:14 UTC
### Brief Issue Summary

For the past few days, whenever I configure a project, the Project Outline panel does not show the targets.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.74.3",
  "cmtVersion": "1.13.40",
  "configurations": [
    {
      "folder": "c:\\dev\\src\\company\\team\\project",
      "cmakeVersion": "3.24.3",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe",
        "CXX": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Additional Information

I am using CMakePresets and CMakeUserPresets and the tool loads the presets properly; it also completes the configuration, build and test targets properly. Just the Project Outline panel is empty. This was tested both in Windows and WSL.

**Comment by bobbrow** [comment] 2023-01-23 17:45
Thank you for reporting this.  Based on the description, we think this might be a duplicate of #2952 which we are currently working on a fix for.  Could you please take a look at that issue and see if the repro steps match what you are doing?  Repro: https://github.com/microsoft/vscode-cmake-tools/issues/2952#issuecomment-1399081231.  There is also a workaround described in that issue.

**Closed** 2023-01-23 17:46 UTC
Labels: bug, duplicate
