### ISSUE TITLE
After running CMake: debug it prompts that GDB cannot be found on macos

### ISSUE THREAD

**Issue by v-frankwang** [microsoft/vscode-cmake-tools#3942] opened 2024-07-26 02:40 UTC
### Brief Issue Summary

**ENV：**
CMake Tools:v1.19.26(pre-release)
C/C++:v1.21.2
vscode：1.91.1(user setup)

**Repro steps:**
1. Create a new folder named 'CMakequickstart' and open it with vscode.
2. Open the command palette(Press F1 or Ctrl+Shift+P).  
2. Enter and select the command '**CMake: Quick Start** '.
3. Enter a name for new project :'**Helloworld**'. 
4. Select '**C++**' 
5. Select '**Executable**' 
6. Select "**CPack**"and click OK.
7. Select "**Add a New Preset…**"
8. Select "**Custom**"
9. Enter a "preset name"："**Mypreset**"
10. Open the Command Palette (Ctrl+Shift+P) and run '**CMake: Debug**'

**Expected result:**
Successful debugging

**Actual result:**
Debugging Failure pops up an error box 
![image](https://github.com/user-attachments/assets/afaa1397-56e1-4b14-89db-2778e691a195)

### CMake Tools Diagnostics

```shell
{
  "os": "darwin",
  "vscodeVersion": "1.91.1",
  "cmtVersion": "1.19.26",
  "configurations": [
    {
      "folder": "/Users/beyondtest/Desktop/Frank/CMakequickstart",
      "cmakeVersion": "3.29.2",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

**Comment by gcampbell-msft** [comment] 2024-08-23 18:47
Duplicate of #3908

**Closed by gcampbell-msft** 2024-08-23 18:47 UTC
Labels: bug
