### ISSUE TITLE
Variable substitution in launch.json for build directory path

### ISSUE THREAD

**Issue by nsubtil** [microsoft/vscode-cmake-tools#564] opened 2018-10-15 16:30 UTC
As a follow-on to the discussion in #559, it would be useful to enable variable substitution for `${cmake.buildDirectory}` in launch.json.

The intended use case would be applications that require cwd to be somewhere inside the build directory, or that require a path within the build directory to be passed in as a command-line argument (e.g., for loading data generated during the build).

**Comment by HorstBaerbel** [comment] 2018-12-14 10:53
This is very much needed for e.g. cwd

**Comment by andreeis** [comment] 2020-05-01 07:25
Closing as dupe of https://github.com/microsoft/vscode-cmake-tools/issues/1165. Reactivate with more details if the solutions presented there don't work for you.

**Closed by andreeis** 2020-05-01 07:25 UTC
Labels: Feature: build, Feature: debug/launch
