### ISSUE TITLE
Change of `binaryDir` in `CMakePresets.json` not respected

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-cmake-tools#3971] opened 2024-08-10 14:44 UTC
### Brief Issue Summary

When I change  `binaryDir` in `CMakePresets.json` it is not respected.

Notice how it builds to /home/tobias/code/c-test/out/build/foo/, even though I changed to "binaryDir": "${sourceDir}/build/test".

The generation happens when I press `ctrl+s` in the CMakeLists.txt, which triggers the generation of the config.

CMakeLists.txt
```CMake
cmake_minimum_required(VERSION 3.5.0)
project(helloworld VERSION 0.1.0 LANGUAGES C)

add_executable(helloworld src/helloworld.c src/main.c)
```

CMakePresets.json
```json
{
    "version": 8,
    "$schema": "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json",
    "configurePresets": [
        {
            "name": "foo",
            "displayName": "GCC 9.4.0 x86_64-linux-gnu",
            "description": "Using compilers: C = /usr/bin/gcc, CXX = /usr/bin/g++",
            "binaryDir": "${sourceDir}/build/test",
            "cacheVariables": {
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/build/install/${presetName}",
                "CMAKE_C_COMPILER": "/usr/bin/gcc",
                "CMAKE_CXX_COMPILER": "/usr/bin/g++",
                "CMAKE_BUILD_TYPE": "Debug"
            }
        }
    ]
}
```

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.92.0",
  "cmtVersion": "1.18.44",
  "configurations": [
    {
      "folder": "/home/tobias/code/c-test",
      "cmakeVersion": "3.30.2",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": true,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "helloworld",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
[main] Configuring project: c-test 
[main] Saving open files before configure/build
[driver] Start configure 
[driver] Running pre-configure checks and steps
[cmakefileapi-driver] Configuring using preset
[cmakefileapi-driver] Invoking CMake /usr/bin/cmake with arguments ["-DCMAKE_INSTALL_PREFIX=/home/tobias/code/c-test/out/install/foo","-DCMAKE_C_COMPILER=/usr/bin/gcc","-DCMAKE_CXX_COMPILER=/usr/bin/g++","-DCMAKE_BUILD_TYPE=Debug","-S/home/tobias/code/c-test","-B/home/tobias/code/c-test/out/build/foo"]
[proc] Executing command: /usr/bin/cmake -DCMAKE_INSTALL_PREFIX=/home/tobias/code/c-test/out/install/foo -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Debug -S/home/tobias/code/c-test -B/home/tobias/code/c-test/out/build/foo
[proc]   with environment: {"FZF_CD_WITH_HIDDEN_COMMAND":"fd --type d --no-ignore-vcs --exclude .git --hidden","FZF_CD_COMMAND":"fd --type d --no-ignore-vcs --exclude .git","USER":"tobias","VSCODE_WSL_EXT_LOCATION":"/mnt/c/Users/siniz/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.2","FZF_PREVIEW_DIR_CMD":"ls","FZF_DEFAULT_OPTS":"--reverse --height 20% --inline-info","SSH_AGENT_PID":"19","HOME":"/home/tobias","NODE_VERSIONS":"/home/tobias/.local/share/nvm","WSL_DISTRO_NAME":"Ubuntu","NODE_VERSION_PREFIX":"v","WAYLAND_DISPLAY":"wayland-0","FZF_TMUX_HEIGHT":"40%","LOGNAME":"tobias","FZF_DISABLE_KEYBINDINGS":"0","PULSE_SERVER":"unix:/mnt/wslg/PulseServer","WSL_INTEROP":"/run/WSL/28368_interop","NAME":"DESKTOP-00IP01M","TERM":"xterm-256color","PATH":"/home/tobias/code/c-test/build:/home/tobias/.vscode-server/bin/b1c0a14de1414fcdaa400695b4db1c0799bc3124/bin/remote-cli:/home/tobias/.pyenv/bin:/home/tobias/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/WinMerge:/mnt/c/Users/siniz/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/siniz/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin","SSH_ENV":"/home/tobias/.ssh/environment","XDG_RUNTIME_DIR":"/mnt/wslg/runtime-dir","DISPLAY":":0","LANG":"C.UTF-8","SSH_AUTH_SOCK":"/tmp/ssh-FWTuAmlH4Yhy/agent.17","SHELL":"/usr/bin/fish","FZF_PREVIEW_FILE_CMD":"head -n 10","FZF_LEGACY_KEYBINDINGS":"0","FZF_FIND_FILE_COMMAND":"fd --type f --hidden --no-ignore-vcs --exclude .git","PWD":"/home/tobias/code","FZF_DEFAULT_COMMAND":"fd --type f --hidden --no-ignore-vcs --exclude .git","PIPENV_VENV_IN_PROJECT":"true","PYENV_ROOT":"/home/tobias/.pyenv","XDG_DATA_DIRS":"/usr/local/share:/usr/share:/var/lib/snapd/desktop","WSL2_GUI_APPS_ENABLED":"1","HOSTTYPE":"x86_64","WSLENV":"VSCODE_WSL_EXT_LOCATION/up","EDITOR":"code","VSCODE_CWD":"/home/tobias/code","VSCODE_NLS_CONFIG":"{\"userLocale\":\"en\",\"osLocale\":\"en\",\"resolvedLanguage\":\"en\",\"defaultMessagesFile\":\"/home/tobias/.vscode-server/bin/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/nls.messages.json\",\"locale\":\"en\",\"availableLanguages\":{}}","VSCODE_HANDLES_SIGPIPE":"true","SHLVL":"1","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","ELECTRON_RUN_AS_NODE":"1","VSCODE_IPC_HOOK_CLI":"/mnt/wslg/runtime-dir/vscode-ipc-49a0389a-1a1f-483a-9105-c54b83690872.sock","DIRENV_DIFF":"eJzsU9tyujwQf5VOrqURxCrcodjPY6VSRXvDQFiVNiQ0CYp2-u7fYM_Ov9MX6BX5HXaBzf6eUY7sZ-Q5d31kI7zlGWDF4zSS-HInCU9AkyB2IHCcMhzrpB7pZgK6qZtrkkSRWa9fWc3YTCqpZVkxaeiGeTILyLgCjdDU_t43PwDbVZYznnIS0Ve-kAK_QnmGP-CncDq8wg9uE2Ugv9Z9JdIY7yWtnjbOmMIEB4Mbdxr4WB6kgqxhnPHnNv_NhoMYsp_FlCV8Lz2-B-FvgVK80y_r-Ef_NAfm-_0Pgyf4RkTZxXVKQVbdJiA28K7OJQiJZcrSI3by3I1UhMenX52kRHDJ1-r9C5w8l7-Xvb1OftZfLPyLLk_gbcIsyqsTeqkhVi2NO5j1bhahO5ghG2nf7rJaHEw0BVKh2rsxcO66_Z6PbATDUh6FPuq4vVtn2mlkyyfrkFjKmNZVZ1mU2ZBOjJ5bOI-P7c66n7RWlrVZhTuzXEM0u9o7ZUvlD5v4uuR87LPRwbot29G4MSuTlTkyaBCYo8JsTMHwZHN7b4Y-fXDVloXWKGwuDi29ez8ns-P8euHlwNobPXnSHslxMVzOs4CaLmkNmlt5u9WydHhjtNWTEQdjNxsSL46brDEh1BguXUewq1a3romjt3ecMLRG__VSimr_TNOXieC4SGli_4XtL2y_h62GvIFXpWd1So4SBaCXl_8DAAD__1G28VM=","DIRENV_DIR":"-/home/tobias/code/c-test","DIRENV_WATCHES":"eJxszr1KBDEQAOB3mXq9yd9t2O0tBXuxmJlM2EDuAkk8BfHd7Y99gY_v4xfeaR6wAx7tpjgbFxooLSnKy9Qx8aL3RxdY4K2lWW4Ku43Oe2Ps5hZ4_SljDthn_9K_5Vy71CZUcRzUFVPpen8g1dq-kczVJXUmWl4Dc7I5hsQh-miJN28tq2bWLDmJcPbb5n3Mcl2JXDArn67C0-rzPwAA__9KGEil","PIPENV_YES":"true","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"1","VSCODE_L10N_BUNDLE_LOCATION":""}
[cmake] -- Configuring done (0.0s)
[cmake] -- Generating done (0.0s)
[cmake] -- Build files have been written to: /home/tobias/code/c-test/out/build/foo
[cmakefileapi-parser] Read reply folder: /home/tobias/code/c-test/out/build/foo/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-2be09f2d7752dd05721c.json","cmakeFiles-v1-f27be08af34e2cdc2959.json","codemodel-v2-d7b61e3922b0cc03ab64.json","directory-.-Debug-f5ebdc15457944623624.json","index-2024-08-10T14-41-29-0941.json","target-helloworld-Debug-e13caa876d582b512ac2.json","toolchains-v1-4071897e80daad5f46f4.json"]
[cache] Reading CMake cache file /home/tobias/code/c-test/out/build/foo/CMakeCache.txt
[cache] Parsing CMake cache string
[cache] Reading CMake cache file /home/tobias/code/c-test/out/build/foo/CMakeCache.txt
[cache] Parsing CMake cache string
```

**Comment by Yingzi1234** [comment] 2024-08-15 09:57
@thernstig According to the information you provided we are unable to reproduce your problem, in order to better solve your problem, could you provide us with the complete reproduction steps and the reproduction of the recorded screen? Thank you in advance!

**Comment by thernstig** [comment] 2024-08-19 08:10
I will reopen this when I am able to consistently reproduce this. My _guess_ is that it is a caching issue somewhere, but I have no solid proof till I have a good repro.

**Comment by thernstig** [comment] 2024-08-21 08:33
This is definitely a new bug.

I had a previous project where I had this:

```json
{
    "version": 8,
    "configurePresets": [
        {
            "name": "Test",
            "displayName": "GCC 9.4.0 x86_64-linux-gnu",
            "description": "Using compilers: C = /usr/bin/gcc, CXX = /usr/bin/g++",
            "binaryDir": "${sourceDir}/build/",
            "cacheVariables": {
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}",
                "CMAKE_C_COMPILER": "/usr/bin/gcc",
                "CMAKE_CXX_COMPILER": "/usr/bin/g++",
                "CMAKE_BUILD_TYPE": "Debug"
            }
        }
    ]
}
```

I then followed these to the point. First https://code.visualstudio.com/docs/cpp/cmake-quickstart and then https://code.visualstudio.com/docs/cpp/cmake-linux.

When I selected from the menu `CMake: Configure` and it put the files in `build/` in the project dir. Even though the CMakePresets.json looks like below after having followed the guide:

```json
{
    "version": 8,
    "configurePresets": [
        {
            "name": "Test",
            "displayName": "GCC 9.4.0 x86_64-linux-gnu",
            "description": "Using compilers: C = /usr/bin/gcc, CXX = /usr/bin/g++",
            "binaryDir": "${sourceDir}/out/build/${presetName}",
            "cacheVariables": {
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}",
                "CMAKE_C_COMPILER": "/usr/bin/gcc",
                "CMAKE_CXX_COMPILER": "/usr/bin/g++",
                "CMAKE_BUILD_TYPE": "Debug"
            }
        }
    ]
}
```

There must be some incorrect caching logic somewhere?

**Comment by gcampbell-msft** [comment] 2024-08-21 10:15
@thernstig When does this change happen? For example, do you know what specific version of the extension it started happening on? 

Also, what happens if you reload the extension, does it then pick up the correct `binaryDir`?

**Comment by thernstig** [comment] 2024-08-21 11:15
@gcampbell-msft I just started using the CMake Tools extensions for the first time 2-3 weeks ago. The version I am working on as of today is `v1.18.44`. Been playing around a lot, and noticing that things I change at time does not "bite" when doing the CMake _configure_ part.

Reloading did work, After reloading, even changing things like `configuration` under `buildPresets` then does stick when I do a new `CMake: Build`.

**Comment by gcampbell-msft** [comment] 2024-08-21 14:24
Could you switch to the pre-release version of the extension? 
![image](https://github.com/user-attachments/assets/c1339703-6f20-4627-8efd-acdebfb259a2)

I am attempting to reproduce your issue now and haven't been successful, it is working as expected. For the record, I'm also not reproducing this on 1.18.44. When I manually modify the configure preset and then save the file, then try the `CMake: COnfigure` or `CMake: Build` command, it behaves as expected

**Comment by thernstig** [comment] 2024-08-21 14:31
@gcampbell-msft I cannot reproduce it currently after I reloaded VS Code. But the problem happened 2 weeks ago and I restarted  VS Code a few time since, and seen this a few times. Hence the pre-release version did not help to test as it works right now.

I will just have to make sure I can repro this 100%.

I assume just looking at the code shows no glaring issues.

I apologize taking time from you on this, but I will try to take a video next time it happens to prove it.

**Comment by gcampbell-msft** [comment] 2024-08-21 15:06
@thernstig No worries! It's now on our radar and we can keep an eye out for it, as it's definitely a bug we'd want to solve, if there is a bug. Thanks! I'll close this again until there is a reliable repro.

**Closed by gcampbell-msft** 2024-08-21 15:06 UTC
Labels: more info needed, triage

**Comment by vlovich** [comment] 2024-12-04 18:19
I have a reliable repro I think. I loaded without user presets set, selected a default suggestion (system clang) & built & configured the project. Then I added a CMakeUserPresets with a `binaryDir` setting and even though I'd selected the new profile in the UI it kept trying to build the old profile (I think) until I reloaded the VSCode window.

**Comment by gcampbell-msft** [comment] 2024-12-04 19:31
@vlovich Could you share the repro?
