### ISSUE TITLE
Disable auto popup to select CMakeLists.txt

### ISSUE THREAD

**Issue by sogartar** [microsoft/vscode-cmake-tools#3278] opened 2023-08-03 16:44 UTC
### Brief Issue Summary

Every time I open VScode for each project I get a popup to select the `CMakeLists.txt`.

![vscode-cmake-popup](https://github.com/microsoft/vscode-cmake-tools/assets/3050579/3867bfaa-764f-4af4-9dde-6ab7391f5f76)

How can you disable this popup?

**Comment by benmcmorran** [comment] 2023-08-09 15:41
Can you check the value of [`cmake.configureOnOpen`](https://github.com/microsoft/vscode-cmake-tools/blob/d3dc5d1dc3cd03ba97fae3cf291cd9e7ef32de0e/docs/cmake-settings.md#cmake-settings) in your workspace-level `settings.json`? This setting should default to `null`, which will not show this prompt, but it's possible the value was changed in your settings file. You can also try explicitly setting it to `null` or `false`.

**Comment by sogartar** [comment] 2023-08-09 22:05
I have these in my user config:
```
"cmake.buildDirectory": "${workspaceFolder}/build/ninja/${buildType}",
"cmake.sourceDirectory": "${workspaceFolder}/repo",
"cmake.generator": "Ninja",
"cmake.configureOnOpen": false,
"cmake.automaticReconfigure": false,
"cmake.autoSelectActiveFolder": false,
"cmake.configureOnEdit": false,
"cmake.buildBeforeRun": false,
```

workspace config:
```
"cmake.autoSelectActiveFolder": false,
"cmake.automaticReconfigure": false,
"cmake.configureOnEdit": false,
```

**Comment by sogartar** [comment] 2023-11-07 21:18
@gcampbell-msft, Sorry, for the late reply.
These projects use CMake, but for most of them I am not using CMake through the VS code extension. Only for one I have configured it. I think it is prompting for a `CMakeLists.txt` for the projects that are not configured yet.

`CMake: Log Diagnostics` output:
```
{
  "os": "linux",
  "vscodeVersion": "1.84.0",
  "cmtVersion": "1.15.31",
  "configurations": [
    {
      "folder": "/home/petkantchin/ws/iree",
      "cmakeVersion": "3.26.3",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "clang-12",
        "CXX": "clang++-12"
      }
    },
    {
      "folder": "/home/petkantchin/ws/shark",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/scratchpad",
      "cmakeVersion": "3.26.3",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/vscode-ws",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/sd-training",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/home",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/jax",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/openxla/xla",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/openxla/openxla-pjrt-plugin",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/openxla/stablehlo",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/bert-training",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/iree-jax",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/torch-mlir",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/bytedance/byteir",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/tensorflow",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/SHARK-Turbine",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/llvm",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/petkantchin/ws/iree2",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by gcampbell-msft** [comment] 2024-04-11 18:41
@sogartar Following up on this, you can set the `cmake.ignoreCMakeListsMissing` setting to true for your workspace (or at the user level) and this will fix your issue!

Please confirm that this fixes your issue, but since I've confirmed with others that this is mitigated with this setting, I am going to close this issue. Please follow up by pinging me if this doesn't resolve your issue.

**Closed by gcampbell-msft** 2024-04-11 18:41 UTC
Labels: bug, question, Feature: activation, investigation needed
