### ISSUE TITLE
cmake.mingwSearchDir not work

### ISSUE THREAD

**Issue by henjue** [microsoft/vscode-cmake-tools#1223] opened 2020-05-08 04:01 UTC
the settings.json
```json
{
    "C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools",
    "cmake.cmakePath": "C:\\msys64\\mingw32\\bin\\cmake.exe",
    "cmake.mingwSearchDirs": [
        "C:\\msys64\\mingw32"
    ],
    "cmake.configureSettings": {},
}
```
the  output
```
[cmake] -- Found SQLite3: C:/msys64/mingw64/include (found version "3.31.1") 
[cmake] -- SQLite3_INCLUDE_DIRS = C:/msys64/mingw64/include.
[cmake] -- SQLite3_LIBRARIES = C:/msys64/mingw64/lib/libsqlite3.dll.a.
```
### Platform and Versions

- **Operating System**: Windows 10 2004
- **CMake Version**: 3.17.2
- **VSCode Version**:  1.45.0
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: i686-w64-mingw32-gcc.exe

**Comment by andreeis** [comment] 2020-05-08 15:58
Closing as duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/1064.

**Closed by andreeis** 2020-05-08 15:58 UTC
