### ISSUE TITLE
Unhandled exception error when IntelliSense is disabled

### ISSUE THREAD

**Issue by reporter123** [microsoft/vscode-cmake-tools#2197] opened 2021-10-21 17:22 UTC
### Brief Issue Summary
My CMake/Build output is being polluted with the fallowing message:

[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools Error: Do not activate the extension when IntelliSense is disabled. {} 

This message usually appears twice during the build process. cpptools InteliSense is intentionally off.
Turning it on prevents this message from appearing but is not on ideal state.

### CMake Tools Diagnostics

```
{
  "os": "linux",
  "vscodeVersion": "1.61.2",
  "cmtVersion": "1.9.0",
  "configurations": [
    {
      "folder": "/usr/src/kdesrc/kdiff3",
      "cmakeVersion": "3.18.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/cc",
        "CXX": "/usr/bin/c++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": true,
    "requests": [],
    "responses": [],
    "targetCount": 61,
    "executablesCount": 10,
    "librariesCount": 2,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

```
[main] Building folder: kdiff3 
[main] Saving open files before configure/build
[build] Starting build
[driver] Start build all
[proc] Executing command: /usr/bin/cmake --build /usr/src/kdesrc/kdiff3/build --config Debug --target all -j 3 --
[build] ninja: no work to do.
[cmakefileapi-parser] Read reply folder: /usr/src/kdesrc/kdiff3/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-610c588daca6171b955b.json","codemodel-v2-fc65f40a77b22bad97a5.json","index-2021-10-21T17-12-25-0098.json","target-CompositeIgnoreListTest-Debug-d56c432f885793676618.json","target-CompositeIgnoreListTest_autogen-Debug-86ed68aa0cddebd39459.json","target-CompositeIgnoreListTest_autogen_timestamp_deps-Debug-939425aea434a6a213d4.json","target-GitIgnoreListTest-Debug-94c72c5213c84ac22eb8.json","target-GitIgnoreListTest_autogen-Debug-26986b842e6c8ec1ea77.json","target-GitIgnoreListTest_autogen_timestamp_deps-Debug-38266c1b51adb4eabf59.json","target-KF5Auth_QCH-Debug-00bd6b407e58ead9f8ee.json","target-KF5Bookmarks_QCH-Debug-f131d74b5fb36f55d155.json","target-KF5Codecs_QCH-Debug-90f30dd25fdd5f005c61.json","target-KF5Completion_QCH-Debug-c60642a8247d13b3ede0.json","target-KF5ConfigWidgets_QCH-Debug-e8a0cee5bf03e26ab989.json","target-KF5Config_QCH-Debug-e21c23bcdcc0c717ec7d.json","target-KF5CoreAddons_QCH-Debug-3eeda7dca91fa39bd339.json","target-KF5Crash_QCH-Debug-5a165bce2820eab3906a.json","target-KF5I18n_QCH-Debug-8c2e5babd214fc658877.json","target-KF5ItemViews_QCH-Debug-4791164e5369ae461140.json","target-KF5JobWidgets_QCH-Debug-17fd9c2287bc927d9a5f.json","target-KF5KIO_QCH-Debug-3bf67301c237c4834b90.json","target-KF5Parts_QCH-Debug-c50fe1f1add53478b428.json","target-KF5Service_QCH-Debug-adb541c7aa038d3533f1.json","target-KF5Solid_QCH-Debug-eaadbeae539bd5dbfc6c.json","target-KF5SonnetCore_QCH-Debug-ec9a4fe38a27d91bdb23.json","target-KF5SonnetUi_QCH-Debug-2b9a26663247fe655202.json","target-KF5TextWidgets_QCH-Debug-53ee16dfda28fd7067e1.json","target-KF5WidgetsAddons_QCH-Debug-5ebc4ca5bdb1a6fcbd19.json","target-KF5WindowSystem_QCH-Debug-bdcf6633674ab9c59c88.json","target-KF5XmlGui_QCH-Debug-0addae40bf8f58320c66.json","target-combinertest-Debug-d6c99eb674651eda7ec9.json","target-combinertest_autogen-Debug-9c599874d0f82bacad05.json","target-combinertest_autogen_timestamp_deps-Debug-e7d1bfde4152d224cd41.json","target-commentparser-Debug-93b6f8c75b46695a7178.json","target-commentparser_autogen-Debug-99839d55a97883d7a7d5.json","target-commentparser_autogen_timestamp_deps-Debug-5b616f969c5d8b421cf1.json","target-connectiontest-Debug-6562e50ae205a921ca1f.json","target-connectiontest_autogen-Debug-18459cd6e6de600d101e.json","target-connectiontest_autogen_timestamp_deps-Debug-d01050d6d976e1b5333e.json","target-cvsignorelisttest-Debug-27282e2ddf7d2584d8f7.json","target-cvsignorelisttest_autogen-Debug-58e7756d97fb7bc94d6b.json","target-cvsignorelisttest_autogen_timestamp_deps-Debug-d8b3c2354ff9d9109986.json","target-diff3linetest-Debug-7718a7ea4dcf0f19ccbb.json","target-diff3linetest_autogen-Debug-18acbdfa9b421bd87413.json","target-diff3linetest_autogen_timestamp_deps-Debug-3b634c47a8186f7d29cf.json","target-difftest-Debug-6476162a136b36f50f29.json","target-difftest_autogen-Debug-6e81f846159ff44541aa.json","target-difftest_autogen_timestamp_deps-Debug-b58c31ce77ec929d0530.json","target-doc-en-index-cache-bz2-Debug-c383a15fab0473c7aa9a.json","target-doc-en-kdiff3-1-Debug-e197c4c2ceb015520043.json","target-fetch-translations-Debug-734fa1c3d69fa635c76e.json","target-fileaccesstest-Debug-6cc067ba963dfebed378.json","target-fileaccesstest_autogen-Debug-edebea0fd524c4701f3b.json","target-fileaccesstest_autogen_timestamp_deps-Debug-75503b7c4f934c0eb869.json","target-kdiff3-Debug-7f42a7e19ad4aacbd593.json","target-kdiff3_autogen-Debug-77e2f4f74a8ba40e8933.json","target-kdiff3_autogen_timestamp_deps-Debug-7460d134c130b0e148f3.json","target-kdiff3fileitemaction-Debug-e6504f4acf5a2ee28ab1.json","target-kdiff3fileitemaction_autogen-Debug-f204cdaa71f4c62c03dc.json","target-kdiff3fileitemaction_autogen_timestamp_deps-Debug-784a1c9e5aa81300db8c.json","target-kdiff3part-Debug-b1b94c34dd9238b7f455.json","target-kdiff3part_autogen-Debug-c14733ad085408c0ac18.json","target-kdiff3part_autogen_timestamp_deps-Debug-506ed662fc0bbe20d92a.json","target-uninstall-Debug-e08c774944443453362f.json"]
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[build] Build finished with exit code 0
[cache] Reading CMake cache file /usr/src/kdesrc/kdiff3/build/CMakeCache.txt
[cache] Parsing CMake cache string
[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools Error: Do not activate the extension when IntelliSense is disabled. {}
[extension] [6728] cmake.build finished (returned 0)
```

**Comment by bobbrow** [comment] 2021-10-21 17:31
Thanks for reporting this. It appears to be a duplicate of #2188.  We merged PR #2189 to work around the bug in cpptools and plan to release 1.9.1 with this fix soon.

**Closed as completed by bobbrow** 2021-10-21 17:31 UTC
Labels: bug, duplicate, upstream
