### ISSUE TITLE
1.19.49 Deletes Cache on Folder Open

### ISSUE THREAD

**Issue by DanKing-dev** [microsoft/vscode-cmake-tools#4018] opened 2024-08-29 00:13 UTC
### Brief Issue Summary

In Visual Studio Code, on opening a folder, the CMakeCache.txt file is summarily deleted.

I am using a cross-compiler and this behavior immediately breaks my ability to build my projects.

This did not happen in the previous version.

```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --version
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -E capabilities
[kit] Successfully loaded 7 kits from C:\Users\Foo\AppData\Local\CMakeTools\cmake-tools-kits.json
[variant] Loaded new set of variants
[cmakefileapi-driver] Removing c:/Users/Foo/project/code/build/CMakeCache.txt
```

**Comment by gcampbell-msft** [comment] 2024-08-29 12:29
This is likely due to the `cmake.configureOnOpen` setting being set to `true`. Therefore, the extension should be configuring on open. If this is something you don't want, please change the `cmake.configureOnOpen` setting. Please let us know if this solves your issue, and if not, please provide a repro project, thanks!

**Comment by the-programmer** [comment] 2024-08-29 13:48
It seems I have a similar issue. In version v1.18.44 everything was fine and in C1.19.49 somehow the Visual studio C compiler is selected (instead of my cross-compile chain).

I have `cmake.configureOnOpen` set to `true`, however with v1.18.44 this doesn't give any issues.

The startup log at v1.18.44
```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" --version
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" -E capabilities
[variant] Loaded new set of variants
[main] Configuring project: [...] 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Wno-dev -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON --no-warn-unused-cli -SC:/Development/[...] -Bc:/Development/[...]/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 12.3.1
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.3 rel1/bin/arm-none-eabi-gcc.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Configuring done (1.3s)
[cmake] -- Generating done (0.2s)
[cmake] -- Build files have been written to: C:/Development/[...]/build
```

And the startup log with v1.19.49
```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" --version
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" -E capabilities
[variant] Loaded new set of variants
[cmakefileapi-driver] Removing c:/Development/[...]/build/CMakeCache.txt
[main] Configuring project: [...] 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Wno-dev -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON --no-warn-unused-cli -SC:/Development/[...] -Bc:/Development/[...]/build
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Building for: Visual Studio 17 2022
[cmake] -- The C compiler identification is MSVC 19.40.33813.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Configuring done (13.7s)
[cmake] -- Generating done (0.3s)
[cmake] -- Build files have been written to: C:/Development/[...]/build
```

**Comment by gcampbell-msft** [comment] 2024-08-29 14:05
@the-programmer @DanKing-dev This is expected, the `cmake.configureOnOpen` is defaulted to `true` so it will automatically reconfigure when you open your project to ensure that everything is up to date. If you don't want this, you can simply turn that setting off. Thanks!

I'll close this issue since it's expected and controllable by a setting. Thanks for posting it!

**Closed by gcampbell-msft** 2024-08-29 14:05 UTC
Labels: more info needed, triage

**Comment by the-programmer** [comment] 2024-08-29 14:11
I'm sorry but setting `cmake.configureOnOpen` to `false` didn't fix the underlying issue. 

Now I have to press "Clean Reconfigure All Projects" in order to trigger the issue. (Shall I make a new issue for this?)

**Comment by gcampbell-msft** [comment] 2024-08-29 15:56
@the-programmer I'm not sure I'm understanding your issue. Running `Clean Reconfigure All Projects` means that it will certainly delete the files and reconfigure, this is expected behavior. 

Is there something I'm misunderstanding about your expectaions?

**Comment by the-programmer** [comment] 2024-08-29 16:56
Hi @gcampbell-msft, yes there seems to be different issues in play.

As seen in this https://github.com/microsoft/vscode-cmake-tools/issues/4018#issuecomment-2317714867 comment from me cmake tools 1.19 seems to select a different compiler than with 1.18. On both versions the cmakefile is the same.

Note that I and @DanKing-dev are both cross compiling.

So a better title would be "cmake tools selects on 1.19 a different compiler than on 1.18 when reconfiguring"

**Comment by gcampbell-msft** [comment] 2024-08-29 17:13
Okay, to fully be able to understand and investigate your issue, could you please create a new issue with a detailed repro project, repro steps, and the output of the cmake "Log Diagnostics" output?

**Comment by gcampbell-msft** [comment] 2024-08-30 12:42
@DanKing-dev I wonder if your issue is actually #4005. It's using a different generator and so it's grabbing a different compiler? Are you using kits? 

Either way, follow the steps from my last comment in order to get the best help. Thanks.

**Comment by roelandschoukens** [comment] 2026-05-25 03:57
I think with `cmake.configureOnOpen` set to true, it should do a _configure_ on open, not a _clean configure_ on open.

**Comment by yanghhhhhhh** [comment] 2026-05-27 07:45
Hi @roelandschoukens , thank you for your comment. When "cmake.configureOnOpen" is set to "true", it runs "configure" instead of "clean configure". Please refer to the video below. If we missed something, please let us know. Thank you.

<img width="1436" height="837" alt="Image" src="https://github.com/user-attachments/assets/ddce836e-760e-4952-ac7b-9beefff4e48b" />

**Comment by roelandschoukens** [comment] 2026-05-27 21:41
Hi @yanghhhhhhh 

I also get the "[cmakefileapi-driver] Removing .../CMakeCache.txt" line when I just close and open the folder. This is the start of my CMake/Build output on opening a folder with a simple hello world toy example:

```
[bookmarks] Loaded 0 bookmarks
[proc] Executing command: /opt/homebrew/bin/cmake --version
[proc] Executing command: /opt/homebrew/bin/cmake -E capabilities
[kit] Successfully loaded 1 kits from /Users/roeland.schoukens/.local/share/CMakeTools/cmake-tools-kits.json
[variant] Loaded new set of variants
[cmakefileapi-driver] Removing /Users/roeland.schoukens/Desktop/cmake-test/build/CMakeCache.txt
[main] Configuring project: cmake-test 
```

(followed by cmake being called for configuring the project)

This is on macOS 15.6, and see [cmake-diagnostics.json](https://github.com/user-attachments/files/28324335/cmake-diagnostics.json)

The CMakeLists.txt is simple:

```cmake
# Set the minimum required version of CMake
cmake_minimum_required(VERSION 3.10)

# Define the project name and programming language
project(HelloWorld LANGUAGES CXX)

# Tell CMake to create an executable named 'my_program' from 'main.cpp'
add_executable(main main.cpp)
```

**Comment by yanghhhhhhh** [comment] 2026-05-28 08:06
Hi @roelandschoukens , thanks for the detailed information. When the VS Code CMake Tools extension detects that the current cache state does not match the expected build environment, it will delete the CMakeCache.txt file. 
If you still believe this issue is a bug, please report a new issue to track it, as this issue has been closed for a long time. Thank you.
