### ISSUE TITLE
Is it possible to run commands like `cmake.build` from tasks.json?

### ISSUE THREAD

**Issue by ce3a** [microsoft/vscode-cmake-tools#1264] opened 2020-05-26 08:22 UTC
### How to run the `cmake.build` command as a vscode task (from tasks.json)?

I would like to run the `cmake.build` command as a vscode task. My `task.json` looks like this:

```jsonc
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "command": "${command:cmake.build}",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [ ... ],  //  ... for a proprietary compiler
        }
    ]
 ```

### Expected:

1. Tasks: Run Build Task
2. The `cmake-tools` cammand `cmake.build` shall be executed.

### Apparent Behavior:

Error message popup appers:

 > "Cannot read property 'fsPath' of undefined"

### CMake Tools Log

```
2020-05-26T08:05:28.964Z [debug] [extension] [6236] cmake.build gestartet
2020-05-26T08:05:28.965Z [fatal] [rollbar] Ausnahmefehler: Unbehandelte Promise-Ablehnung: build TypeError: Cannot read property 'fsPath' of undefined {}
```

### Developer Tools Log

```
[2020-05-26 10:05:28.977] [renderer1] [error] Cannot read property 'fsPath' of undefined: TypeError: Cannot read property 'fsPath' of undefined
	at CMakeToolsFolderController.get (c:\<HOME>\.vscode\extensions\ms-vscode.cmake-tools-1.4.0\dist\main.js:41014:48)
	at ExtensionManager.mapCMakeToolsFolder (c:\<HOME>\.vscode\extensions\ms-vscode.cmake-tools-1.4.0\dist\main.js:13673:59)
	at ExtensionManager.build (c:\<HOME>\.vscode\extensions\ms-vscode.cmake-tools-1.4.0\dist\main.js:13692:39)
	at c:\<HOME>\.vscode\extensions\ms-vscode.cmake-tools-1.4.0\dist\main.js:13833:35
	at c:\<HOME>\.vscode\extensions\ms-vscode.cmake-tools-1.4.0\dist\main.js:13844:15
	at e._executeContributedCommand (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:627:894)
	at e.$executeContributedCommand (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:628:295)
	at e._doInvokeHandler (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:788:757)
	at e._invokeHandler (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:788:449)
	at e._receiveRequest (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:120)
	at e._receiveOneMessage (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:970)
	at c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:784:213
	at e.fire (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:615)
	at c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:957:179
	at e.fire (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:615)
	at t.PersistentProtocol._receiveMessage (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:237:17)
	at c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:234:155
	at e.fire (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at p.acceptChunk (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:230:129)
	at c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:229:483
	at Socket.t (c:\opt\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:238:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

### Platform and Versions

- **Operating System**:  Windows 10
- **CMake Version**: 3.13.3-win64-x64
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.4.0
- **Compiler/Toolchain**: proprietary

### Other Notes/Information

Using a multi workspace setup.

**Comment by vptrbv** [comment] 2020-05-26 11:46
I guess [this patch](https://github.com/microsoft/vscode-cmake-tools/pull/1263/files#diff-442f85e1e9c19393d27260696ba32be8) will fix the problem. I can only make it separate pull request, if needed.

**Comment by bobbrow** [comment] 2020-06-05 18:34
I'm going to close this as a duplicate of #1234

**Closed by bobbrow** 2020-06-05 18:34 UTC
