### ISSUE TITLE
`CMAKE_EXPORT_COMPILE_COMMANDS` not added when CMake Presets are used

### ISSUE THREAD

**Issue by mpusz** [microsoft/vscode-cmake-tools#2670] opened 2022-08-03 10:41 UTC
### Brief Issue Summary

It seems that `CMAKE_EXPORT_COMPILE_COMMANDS` is not added to the command line during CMake configuration stage when CMake Presets are used even though `cmake.exportCompileCommandsFile` is turned on.

**Comment by bobbrow** [comment] 2022-08-03 16:42
Thanks for reporting this.  This is a duplicate of #1835.  One of the underlying goals of Presets is to create a configuration that is consistent across the several environments where they may be used (e.g. VS, VS Code, command line).  As such, we made a conscious decision not to let our extension add arguments to the configuration command that weren't in the CMakePresets.json file.  The recommended way to achieve this is to add `CMAKE_EXPORT_COMPILE_COMMANDS` to the `cacheVariables` of your  configurePreset or one of the presets that it inherits from.

It might be good for us to detect that some of these settings are set and log a warning.  We have a bit of settings clean up to do as part of the linked issue that will hopefully make this more clear to our users.

**Closed by bobbrow** 2022-08-03 16:42 UTC

**Comment by mpusz** [comment] 2022-08-08 09:52
I think that it is useful to provide some additional configure options on top of CMake Presets. As long as it is not some "magical" action originating from the IDE but parameters provided by the user in the settings, I think they should be used in the configure command line. This is about not only `cmake.exportCompileCommandsFile` but also `cmake.configureArgs`. Not using parameters specified explicitly by the user for a specific workspace is at least confusing.

If the user wants to have raw configuration from CMake Presets then he/she should leave those settings empty.
