### ISSUE TITLE
Problems not transferred from error output produced by clang-cl

### ISSUE THREAD

**Issue by skhrshin** [microsoft/vscode-cmake-tools#1537] opened 2020-11-09 05:18 UTC
### Brief Issue Summary

Whereas errors produced by compiler should be transferred to the problems window, this feature doesn't work properly with clang-cl.

### Expected:

1. Make sure you have installed Visual C++ 2017 Desktop Express and Clang 9.0.0
2. Create a directory
3. Put test.cpp in the directory
```
int main() {
    return nullptr;
}
```
4. Put CMakeLists.txt in the directory
```
cmake_minimum_required (VERSION 3.0.0)
project (test)
add_executable (test test.cpp)
```
5. Put .vscode/settings.json in the directory
```
{
    "cmake.generator": "Ninja",
    "cmake.configureSettings": {
        "CMAKE_MAKE_PROGRAM": "C:/your/path/to/ninja.exe"
    }
}
```
6. Open the directory with VSCode
7. Select "Clang 9.0.0 for MSVC with Visual Studio 2017 Desktop Express Release" kit
8. Build
9. The compiler produces the following error
```
[build] ..\test.cpp(2,12): error: cannot initialize return object of type 'int' with an rvalue of type 'nullptr_t'
[build]     return nullptr;
[build]            ^~~~~~~
[build] 1 error generated.
```
10. The error should be also shown in the problems window

### Apparent Behavior:

The compile error isn't shown in the problems window. If you open test.cpp by the editor, an error appears but the message is different. It works fine with "Visual Studio 2017 Desktop Express Release" kits.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.18.0
- **VSCode Version**: 1.51.0
- **CMake Tools Extension Version**: 1.5.1
- **Compiler/Toolchain**: Clang 9.0.0 with Visual C++ 2017 Express

**Comment by andreeis** [comment] 2020-11-09 12:55
Thank you for reporting this issue. We reproduce it and we will let you know if we need anything else for the investigation.
Possibly related to https://github.com/microsoft/vscode-cmake-tools/issues/517.

**Comment by bobbrow** [comment] 2020-11-09 16:16
Yes, I believe this is a duplicate of #517.  Closing...

**Closed by bobbrow** 2020-11-09 16:16 UTC
Labels: Feature: build, bug
