### ISSUE TITLE
Missing quote when preprocessor macro contains expression. 

### ISSUE THREAD

**Issue by Hadatko** [microsoft/vscode-cmake-tools#2002] opened 2021-07-11 06:54 UTC
OS: Kubuntu 21.04
VSC:1.58.0
extension: 1.5.1

Hello,
in my CMakeList i have this configuration: 
`set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -D__FILENAME__='\"$(notdir $(abspath $<))\"'")`
I can build applicaiton with gcc 10. In PROBLEMS section i see "errors" with missing end quoting ". This is due to you parser is reading above option as `"$(notdir`. 

Disabling this worked `"C_Cpp.errorSquiggles"`. But is it the only option? Are you able to support this case better? 
![Screenshot_20210711_085209](https://user-images.githubusercontent.com/13130700/125185491-602a8a00-e225-11eb-885b-8002fe1a5aed.png)
![image](https://user-images.githubusercontent.com/13130700/125185507-7a646800-e225-11eb-9ebc-809ee2ae52ef.png)
![image](https://user-images.githubusercontent.com/13130700/125185515-8b14de00-e225-11eb-9d03-000ffb18a5a3.png)

**Comment by Colengms** [comment] 2021-07-19 17:26
Hi @Hadatko This looks like an issue with CMake Tools, so I've transferred it to the CMake Tools repo.

The custom configuration provided by CMake Tools contains:
`"__FILENAME__='\"$(notdir"`

I assume the resulting value of the macro should be `"$(notdir $(abspath $<))"`, so there may be a combination of issues here related to quote matching and handling of escaping.

**Comment by Colengms** [comment] 2021-07-19 17:35
@Hadatko Can you confirm what the macro is defined as when built using CMake?  If CMake is processing the `notdir` and `abspath` functions, that could be an issue (in addition to quote and space parsing).

What version of CMake are you using, and what generator are you using?  I noticed this issue that may be related: https://discourse.cmake.org/t/base-filename-gets-set-to-compiler-depend-ts-after-update-to-cmake-3-20/3075

**Comment by Hadatko** [comment] 2021-07-19 19:04
Hi, sorry for bothering you. I didn't know it is Cmake issue as it looked like yours.
As mentioned above, in CMakeList i have `set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -D__FILENAME__='\"$(notdir $(abspath $<))\"'")`. `notdir` and `abspath` are gcc functions. So Cmake cannot parse it same way as gcc (because value is different for each source code) but at least they could use full origin description `__FILENAME__="$(notdir $(abspath $<))"`
Cmake version: `cmake version 3.18.4`

Thank you for your link. Definitely it looks related. But they wrote that 3.18 should be fine :/
Maybe they have a bit different issue and this one is a bit different. 

COuld you point me to the issue you created in cmake repository? Thank you.

**Comment by Colengms** [comment] 2021-07-19 19:29
> COuld you point me to the issue you created in cmake repository?

Hi @Hadatko .  I transferred your original issue (this one) to the CMake Tools repo.  Your last response was in the CMake Tools repo.  :)

If I understand correctly, the issue is that CMake Tools is not properly parsing quoted strings containing spaces (or perhaps escaped quotes) when reading defines from the CMake build, and the value of that macro should be: `"$(notdir $(abspath $<))"`.

(Note that parsing of arg strings within single-quotes is not supported by the shell on Windows.  Some related info is here: https://github.com/microsoft/vscode-cpptools/issues/6773).

**Comment by Hadatko** [comment] 2021-07-19 19:35
Thank you very much :) Windows is not supported in our application so it is fine. And you are understanding me correctly.

**Comment by Colengms** [comment] 2022-05-19 23:30
>I assume -I and -D arguments are being parsed in order to populate the includePath and defines

Actually, it looks like this assumption was incorrect.  Most includes and defines are provided by CMake without any shell escaping.  But `CMAKE_C_FLAGS_RELEASE` (etc) is actually processed as a compiler argument, so the adoption of cpptools-api v6 and passing fragments via `compilerFragment` will implicitly fix this issue.

**Comment by elahehrashedi** [comment] 2022-05-20 16:24
This issue will be resolved after adding support for CppTools API V6: https://github.com/microsoft/vscode-cmake-tools/pull/2563

**Closed** 2024-10-30 14:51 UTC
