### ISSUE TITLE
`cmake.configureSettings` appends `:STRING`¶

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cmake-tools#1747] opened 2021-04-07 07:45 UTC
In my `settings.json`:

```
    "cmake.configureSettings": {
        "AGENT_ARCHITECTURE:STRING" : "universal",
        "CONAN_CHANNEL:STRING" : "stable",
        "UCLOG_TO_CONSOLE_ENABLED:BOOL" : "ON"
    },
```

In the `Output`:

`[proc] Executing command: /usr/local/bin/cmake --no-warn-unused-cli -DAGENT_ARCHITECTURE:STRING:STRING=universal -DCONAN_CHANNEL:STRING:STRING=stable -DUCLOG_TO_CONSOLE_ENABLED:BOOL:STRING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang`

I expect to be able to use the following syntax:
https://cmake.org/cmake/help/latest/manual/cmake.1.html
>`-D <var>:<type>=<value>, -D <var>=<value>`
>Create or update a CMake CACHE entry.

The documentation doesn't say anything about that either: https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html

Is this on purpose or is an omission? In the CMake cache the extra *parameter* is stripped. I wonder if the situation is a problem.

**Comment by andreeis** [comment] 2021-04-08 00:07
Thank you for creating this report. I am closing it as a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/1457.
That work item also describes a workaround you can use, to pass the variables that you need not via configureSettings but via configureArgs. Let us know if you encounter any issues.

**Closed by andreeis** 2021-04-08 00:07 UTC
