### ISSUE TITLE
GCC linker errors not showing up in Problems window

### ISSUE THREAD

**Issue by RolfNoot** [microsoft/vscode-cmake-tools#2864] opened 2022-11-22 16:24 UTC
### Brief Issue Summary

I am not sure whether this is an issue or expected behavior. Compiler errors are shown correctly.

![Schermafbeelding 2022-11-22 om 17 17 27](https://user-images.githubusercontent.com/44534542/203367027-2be51661-eec0-4057-bf9a-1b04850bbccd.png)

**Comment by bobbrow** [comment] 2022-11-22 17:39
This would be a bug/feature request.  We have a regular expression that matches compiler errors, but the linker errors don't match that pattern.  Thanks for reporting it.  We may not get to this immediately, but will accept a PR from the community if someone is able to address it before we do.

**Comment by RolfNoot** [comment] 2022-11-22 19:12
Thanks for the quick reply. Where (in code?) can I find this regex? I might change it according my needs.

**Comment by bobbrow** [comment] 2022-11-22 19:30
It is here: https://github.com/microsoft/vscode-cmake-tools/blob/a00c339cef191fb9bae64922713189bf64d994b0/src/diagnostics/gcc.ts#L9

**Comment by RolfNoot** [comment] 2022-11-23 21:22
Changing the regex doesn't affect the output. I changed the one in `vscode-cmake-tools/src/diagnostics/msvc.ts` which seems to affect the output.

How can I select the problemMatcher when starting build programmatically (not using Tasks) `vscode.commands.executeCommand('cmake.build')`?

**Comment by bobbrow** [comment] 2022-11-23 21:52
I believe that all the problem matchers are active when you build with our commands (not tasks).  You can control which ones are active with the `cmake.enabledOutputParsers` setting.

**Comment by evakili** [comment] 2023-01-04 07:02
This issue also exists in MSVC builds. MSVC link errors are not matched by the problem matcher.

**Comment by denis-shienkov** [comment] 2023-02-03 16:28
It is because the VSCode does not provide an API to show the problems without of a file path. I meant, that usually, the linker errors does not a file paths at all.

**Comment by RolfNoot** [comment] 2023-02-03 20:26
It can show problems using a 'null' path. Besides that, the file path is provided by the linker and should be matched by the regex (/Volumes/.../main.c:105 in this case).

I am currently using an additional problemmatcher for linker errors which works fine.

This should be implemented in the extension IMHO.

```
"problemMatcher": [
        {
            "base": "$gcc",
            "fileLocation": ["relative", "${workspaceFolder}/build" ]
        },
        {
            "owner": "linker0",
            "severity": "error",
            "fileLocation" : "absolute",
            "pattern": {
            "regexp": "((error): ld returned (-?\\d+) exit status)",
            "message": 1,
            "file" : 2
            }
        },
        {
            "owner": "linker1",
            "severity": "error",
            "fileLocation" : "absolute",
            "pattern": {
            "regexp": "(\\S*\\..{0,2}):(\\d*):\\s(undefined reference to `\\S*')",
            "file": 1,
            "line": 2,
            "message": 3
            }
        },
        {
            "owner": "linker2",
            "severity": "error",
            "fileLocation" : "absolute",
            "pattern": {
            "regexp": "((.*\\..{0,2}):(\\d+): (multiple definition of .+);.+:(.*\\..{0,2}):(\\d+): first defined here)",
            "message": 4,
            "file": 5,
            "line": 3
            }
        },
        {
            "owner": "linker3",
            "severity": "error",
            "fileLocation" : "absolute",
            "pattern": {
            "regexp": "((cannot open linker script file (.+.ld): No such file or directory))",
            "message": 1,
            "file": 3
            }
        },
        {
            "owner": "linker4",
            "severity": "error",
            "fileLocation" : "absolute",
            "pattern": {
            "regexp": "((region `\\S+' overflowed by \\d+ bytes))",
            "message": 1
            }
        }
```

**Comment by denis-shienkov** [comment] 2023-02-04 08:24
>  Besides that, the file path is provided by the linker 

This is a special case that there is a path to the file. In most cases, linking errors do not contain any paths. This will not only affect GCC but also other compilers (eg MSVC, IAR, KEIL, SDCC and etc).

So, in a common case you can't extract the `file` property for the problem matcher... And, what's to do in such case is unknown..

I even created an issue about that: https://github.com/microsoft/vscode-cpptools/issues/6643 but all was unsucessfull.

**Comment by RolfNoot** [comment] 2023-02-04 11:44
What you can do in such a case is use a 'null' path for the file.
![No file path](https://nooteboom.biz/downloads/vscode_null.png)

In my opinion, this is currently the best way to report linker errors without file reference. Not reporting linker errors is really not a good option for most users. In the future, I hope VS Code will implement a way to implement error reporting without file reference.

**Comment by denis-shienkov** [comment] 2023-02-04 16:41
Hmm.. It is possible at all to set a null path? Because the [vscode.DiagnosticCollection](https://code.visualstudio.com/api/references/vscode-api#DiagnosticCollection) expects the the method `set(uri: Uri, diagnostics: readonly Diagnostic[]): void` use an `vscode.Uri` type. I'm not sure that it is possible to assign a `null` to the `Uri` (I'm not a typescript expert at all).

**Comment by RolfNoot** [comment] 2023-02-04 17:39
I am assuming it's a 'null' path or it's an empty string, the screenshot above shows that it's possible at least. Not sure how the problemmatcher internally works and I am not typescript expert either.

**Comment by kuch3n** [comment] 2024-02-17 20:44
> It is here:
> 
> https://github.com/microsoft/vscode-cmake-tools/blob/a00c339cef191fb9bae64922713189bf64d994b0/src/diagnostics/gcc.ts#L9

Maybe the regex fails because there is a `[build]` in front of the actual error message, e.g.:
`[build] C:\project_dir\user_code.c:45:23: error: CAN_BUS_0 not declared (or typename)`

Following regex will match above line: `^\[build\] (.*):(\d+):(\d+):\s+(?:fatal )?(\w*)(?:\sfatale)?\s?:\s+(.*)`

**Comment by 0xemgy** [comment] 2024-03-16 16:19
I tinkered with the gcc parser because showing the linker errors in the Problems panel is really helpful.

What I basically did is I added some more regex cases and modified the handling of the additional matches. If there is no column, 1 is set as column, if there is no severity, error is set as severity, etc.

[Here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgDwIYFsAOAbOBlKAnASzAHMIYBeGAbQCgZ6YAiAYQC4B6JAIwhAwFcocdmiRQAFuygh2AMwJYAdMFYBGVgCZWMAO5I8YIsW2h0CuHl37DJXQQkxQAlGEYAaOgxYduvAUJExSWk5c2U1bT0DIxMQMyxLKJtiOwkQQUc+fhd3T3pvTh4sgNEJKRl5JRUAZm0MIgBrC3g8PBBE+3F02CdssBgkMAATVK6MiDgANwt7AE9cvJh2dhgAGUbmiza8MiJdOAI8Edl2lDEIRcZS4JkMIcVEOG1r8tClOAxZGAngKAJwGAAA0UAH1+BM8CDoEhgA0AOR2DAYGBgECweSwPZ4ODEf79QEAJQAggBZOG5BhMF4hO4PBBPGDY3EAwmkhEgaZ4WQYEA6OAjLizGCqAAMqgALDBBUIIAtKcslitsPViOJYEMpgQxHiyBIxN8xncUWjdO0GjAABSomCyJAYCYwNAgCD2AjTCAASkWCoKvmKwmpFTCKnUGis0RIsXizSSRlGmWcrg88pWvqK-gDQVelTg4VU4eSUbQ5kS1jjOk63QTfQpDB9bEKfkEmbKIRz4WqMHqYCali27VGVd6LgGw0H4ymMyg82TddT2Iw2umgVbQaqETDscjmWjpYjKQrDmHSe984+S5bNzeuZDBZiO+LCTvtkPYx6WRyHgAugBuGg0UBIFgJlEAABTEIQDAoFE4B0GACRxABRBA0AtGhGAAPQtAB+VgLUUAAqD08IAHRIoYAGpiItMjKOIj0yIgCicNYW0oDtGAPWwmiSJ0IiWMYti7TgLjGNwxjmMIj0AB9GBgCi50dLM23MVhuyeY9tAmTk5m0FA4AgCAkGIOB0Kw3D8KI0jyKo1gGJIpiWKE5EuJ4viPQEhznJE7CxNYCTLJkuSFMpUKFUDa81KIBltKnWY9IMoyTLMljAusui7ICqTZPk0K8vygrCqKsKVginMorABl9MM4zTMYNLLRYqSYEIn4-nAQjLVw5rCIrJFjXRewYCxHE8Wy4LipTJTV0ilrFEUb44F+PE5oWvrkVRQbMX6JkVvmxR0Iayzdo6giutYHqCI5CxuV5fkpVmKS5Mml7CvC5S1wZE7+n2mBrq5Hk+QFIV9poD0-xoE5LAtQDoHgZB0CwXBCFsEAvkQVBMBwfAjE9GAAG9Flh2AzigYBxGgjHEexlHiEUUnyYtECEHAqBILAcH-0pAgvgtBmKYAMgFmB+aoEUvxgABCShGEYD0CcWSlYb4XMeWIC1GBJMRyZgEUYAAWhtfgkVYdwRe18Qxa-TmCp5y1RdUa2Fcm5WlDVjWtbJin80NnN1DNh3rb-F3wD8VWQHVzWLZgMNDfU1F-bcc2vaoDQg8V-LXfDyPPZ1ztDePBPTaT0XqnTkPIBVxR3ajr2YElQ3YsIadE+T8mqHFcviqz6uI496OAFYDZFxLatb0WB67vKAF94HtOBhtkPmLaoAA2J3CYrsPe5z6PV5tcwtADlf15t7vQ6rmvc4pgB2LtotRI+S5Xm+p8Knur+jgAORadOnJ+26Wy-m-AqH8+61x1gAThHjVEyADRaQJAQwWeHwHQ82XinUUG8M55TAbvOuooD5YFqMfTB4sz5FTwf3Ah+Z44gBIc-TBjsKHvwvm7cB19hRhmqklOADDAFUFUGnFhlIUHz0Xhg9uqgy7y03ufSu7D8E62kUQuA4pi4COkUg3BbDs7UOUZKHhtV1GkKkZ3ERyC55oKXg7SesicGhSoRA72Q8cwDw0bY7RjjdE730d7feRiTLuNMZbVQp8IaiKsQvOROiFF6MYAAORAIAm06QxxQw0VTLGyMjAsOnkTHx7tObTyAA) are the Typescript Regex trial and errors is used, if anyone wants to add some more special cases.

Here is the modified gcc parser:
```
/**
 * Module for handling GCC diagnostics
 */ /** */
Object.defineProperty(exports, "__esModule", ({ value: true }));
exports.Parser = exports.REGEX = void 0;
const vscode = __webpack_require__(89496);
const util_1 = __webpack_require__(52919);
exports.REGEX = /^(?:(.*):(\d+):(\d+):)\s+(?:fatal )?(\w*)(?:\sfatale)?\s?:\s+(.*)|^(?:(.*):(\d+):)\s+(?:fatal )?(\w*)(?:\sfatale)?\s?:\s+(.*)|^(?:(.*):(\d+):)\s+(.*)|(.*): ((?:.*) .*section.* (?:.*) .*will not fit in region.*)|(.*): (.*region.* (?:.*) .*overflowed by.*)/;

class Parser extends util_1.RawDiagnosticParser {
    doHandleLine(line) {
        let mat = /(.*): (In instantiation of.+)/.exec(line);
        if (mat) {
            const [, , message] = mat;
            this._pendingTemplateError = {
                rootInstantiation: message,
                requiredFrom: []
            };
            return util_1.FeedLineResult.Ok;
        }
        if (this._pendingTemplateError) {
            mat = /(.*):(\d+):(\d+):(  +required from.+)/.exec(line);
            if (mat) {
                const [, file, linestr, column, message] = mat;
                const lineNo = (0, util_1.oneLess)(linestr);
                this._pendingTemplateError.requiredFrom.push({
                    file,
                    location: new vscode.Range(lineNo, parseInt(column), lineNo, 999),
                    message
                });
                return util_1.FeedLineResult.Ok;
            } else {
                mat = /(.*):(\d+):(  +required from.+)/.exec(line);
                if (mat) {
                    const [, file, linestr, message] = mat;
                    const lineNo = (0, util_1.oneLess)(linestr);
                    this._pendingTemplateError.requiredFrom.push({
                        file,
                        location: new vscode.Range(lineNo, parseInt("1"), lineNo, 999),
                        message
                    });
                    return util_1.FeedLineResult.Ok;
                }
            }
        }
        // Early-catch backtrace limit notes
        mat = /note: \((.*backtrace-limit.*)\)/.exec(line);
        if (mat && this._prevDiag && this._prevDiag.related.length !== 0) {
            const prevRelated = this._prevDiag.related[0];
            this._prevDiag.related.push({
                file: prevRelated.file,
                location: prevRelated.location,
                message: mat[1]
            });
            return util_1.FeedLineResult.Ok;
        }
        // Test if this is a diagnostic
        mat = exports.REGEX.exec(line);
        if (!mat) {
            // Nothing to see on this line of output...
            return util_1.FeedLineResult.NotMine;
        }
        else {
            const [full, file1, lineno1, columnno1, severity1, message1, file2, lineno2, severity2, message2, file3, lineno3, message3, file4, message4, file5, message5] = mat;
            if ((file1 && lineno1 && columnno1 && severity1 && message1) || (file2 && lineno2 && severity2 && message2) || (file3 && lineno3 && message3) || (file4 && message4) || (file5 && message5)) {
                let file, lineno, columnno, severity, message;
                
                if(file1) {
                    file = file1;
                    lineno = (0, util_1.oneLess)(lineno1);
                    columnno = (0, util_1.oneLess)(columnno1);
                    severity = severity1;
                    message = message1;
                }
                else if(file2) {
                    file = file2;
                    lineno = (0, util_1.oneLess)(lineno2);
                    columnno = (0, util_1.oneLess)("1");
                    severity = severity2;
                    message = message2;
                }
                else if(file3) {
                    file = file3;
                    lineno = (0, util_1.oneLess)(lineno3);
                    columnno = (0, util_1.oneLess)("1");
                    severity = 'error';
                    message = message3;  
                }
                else if(file4) {
                    file = file4;
                    lineno = (0, util_1.oneLess)("1");
                    columnno = (0, util_1.oneLess)("1");
                    severity = 'error';
                    message = message4;  
                }
                else if(file5) {
                    file = file5;
                    lineno = (0, util_1.oneLess)("1");
                    columnno = (0, util_1.oneLess)("1");
                    severity = 'error';
                    message = message5;  
                }

                if (severity === 'note' && this._prevDiag) {
                    this._prevDiag.related.push({
                        file,
                        location: new vscode.Range(lineno, columnno, lineno, 999),
                        message
                    });
                    return util_1.FeedLineResult.Ok;
                }
                else {
                    const related = [];
                    const location = new vscode.Range(lineno, columnno, lineno, 999);
                    if (this._pendingTemplateError) {
                        related.push({
                            location,
                            file,
                            message: this._pendingTemplateError.rootInstantiation
                        });
                        related.push(...this._pendingTemplateError.requiredFrom);
                        this._pendingTemplateError = undefined;
                    }
                    return this._prevDiag = {
                        full,
                        file,
                        location,
                        severity,
                        message,
                        related
                    };
                }
            }
            return util_1.FeedLineResult.NotMine;
        }
    }
}
```

To use this parser instead of the original one, you have to modify the main.js in your vscode-cmake-tools, which is located here:
C:\Users\your_username\\.vscode\extensions\ms-vscode.cmake-tools-1.17.17\dist\main.js

The parser code starts at line L52199.

Just replace the code, perform Reload Window if vscode is opened, and the modified version should be running without further ado.

Output looks like this now:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/139615394/8d875010-7c0b-4f09-aa92-4635fd7b45d0)

The first undefined reference error is a linker error without a column and without a severity. I is not parsed without the modifications.
The ld.exe errors are special linker errors without a proper gcc warninig format. using 'null' or '/' as suggested by @RolfNoot did not generate a proper non-file-URI, so I left it at the ld.exe.
The empty_test warning is a gcc compiler warning without a column.  I is not parsed without the modifications.

This has not been thoroughly tested. It is a work in progress. It will probalby need some refinements, it might even detect some false positives, or not work for Linux developers etc.

I probably did not handle the `if (this._pendingTemplateError)` part correctly since I did not use all new regex cases. I don't care for now because it appears to be an error case.

Hope this helps somebody.

Cheers

**Comment by gcampbell-msft** [comment] 2024-03-26 13:44
@0xemgy Thanks for the investigation and comments.

This seems like a GREAT opportunity for you to improve the extension for everyone by making an Open Source Contribution! Is this something you feel confident would work for everyone and would be willing to PR?

**Comment by 0xemgy** [comment] 2024-03-27 09:00
> @0xemgy Thanks for the investigation and comments.
> 
> This seems like a GREAT opportunity for you to improve the extension for everyone by making an Open Source Contribution! Is this something you feel confident would work for everyone and would be willing to PR?

I agree that this seems like a great opportunity and I would be willing to contribute. 

But right now I don't feel confident that this would work for everyone. Because:
1. I basically ignored the `if (this._pendingTemplateError)` part, where the original regex pattern is used too and might be enhanced to use all of the new regex patterns instead. I don't even know what that error is and how to test this. 
2. I did not test on Linux, I'm a windows only user and have little to no experience with Linux.
3. After just 1 week of using my first version at work I encountered 2-3 further linker warnings/errors, one of them being accidentally parsed by one of the new regex patterns in an incorrect way. 
4. There are probably a few more linker warnings in weird formats.

Definitely no insurmountable problem there, but quite a few aspects to consider.

So I'd say I will test this further, edit my original comment if I have added/fixed something, and do some research for Linux, the template error case, and further common linker errors.

And then I will attempt to contribute, which would be my first contribution ever, so I would need to see how that works too.

Depending on my spare time this might take a few weeks or months.

Does that sound like a plan or do you have a better suggestion?

**Comment by gcampbell-msft** [comment] 2024-03-27 17:19
@0xemgy Thank you for all of that context. 

That sounds like a great plan! If we end up deciding to prioritize this issue such that we also start investigating and working on it, we will make sure to follow up here so that we can sync and make sure that no work is duplicated. Thank you!

**Comment by v-frankwang** [comment] 2024-07-03 09:10
@0xemgy Thank you so much for your response and your contribution to the community! If you make any progress, we'll follow up on this here as well after you update the comment or add a new one.

**Comment by 0xemgy** [comment] 2024-07-27 10:17
@gcampbell-msft @v-frankwang 
I was able to test my solution throughout the last months (using it almost every day at work). 

Regarding my previous concerns:
1. I left the pending error code unchanged. Hence nothing should have been broken.
2. I did not test on Linux. I'm a pure Windows user, but I wouldn't know why it should not work on Linux.
3. I tested it extensively as mentioned above (I did not find any false positives, and all the warnings I was able to generated seemed to be parsed successfully).
4. I did find a few more warnings and added them.

So now I'm confident in my solution and I am willing to PR. 

I already created a branch locally, modified the gcc.ts and was able to build it, test the parsing with my local software project, and ran the unit tests without an error.

But I am not allowed to push: `You don't have permission to push to "microsoft/vscode-cmake-tools" on GitHub`.

**Comment by v-frankwang** [comment] 2024-07-29 02:16
@gcampbell-msft The user has created a branch of his own with his changes, but cannot push to the corresponding branch of microsoft/vscode-cmake-tools, can you give the user some advice?

**Comment by gcampbell-msft** [comment] 2024-07-30 15:05
@v-frankwang @0xemgy Thanks for all of your work and your updates! Let's get it such that you can contribute. 

The reason that you are getting the permission errors is because in order to create a PR, you should first create a fork of the cmake-tools repository, and then you can create a PR from that into this repository. Does that make sense? Please let me know if you need/want any help with this.

**Comment by 0xemgy** [comment] 2024-08-01 05:35
@gcampbell-msft @v-frankwang I think I got it: Forked the repo, created a PR, agreed to the CLA: https://github.com/microsoft/vscode-cmake-tools/pull/3950

**Comment by 0xemgy** [comment] 2024-08-03 13:26
@gcampbell-msft @v-frankwang

It turns out there already is a GNU linker error parser in your code base. 

The CI unit test in my PR [#3950](https://github.com/microsoft/vscode-cmake-tools/pull/3950) failed because the unit test for this linker error parser failed. It now fails because my GCC error parser already finds linker errors, which resulsts in the linker error parser not being executed, 

It turns out you guys have a bug that causes errors that are detected by the linker error parser to not be pushed to the Problems View (short description of the bug: default configuration string for linker parser is "gnuld", but code uses "link", so linker errors are ignored in the function `resolveDiagnostics`) .
If fixed this bug locally by changing the string "link" to "gnuld". 

Then errors detected by the linker error parser are shown in the Problems View. But the parsing does not work properly. It is too simplistic. It only detects 6 out of the 12 linker errors I use for testing, and 3 out of these 6 findings are parsed incorrectly (e.g. `path/to/ld.exe:path/to/file:138: syntax error` is detected, but the file name `path/to/ld.exe:path/to/file` is parsed instead of `path/to/file`). 

So I suggest I fix the described bug and move the linker errors that I implemented in the GCC parser to the linker parser, and also add some unit tests for all the error strings I use for testing. 

I also would like to test this new solution at work for a few weeks to make sure I did not break anything. 
I think I need to test it for a while because the parsing order is actually relevant. E.g. a linker error of type `path/to/ld[.exe]:path/to/file:line: warning: memory region ... not declared` would be falsely detected as a GCC compiler error of type `path/to/file:line:` severity: message` if the compiler errors are parsed prior to the linker errors. I already regarded this in my local fix by changing the parser execution order (linker parser is now executed before the compiler parser). But I prefer to test this a little further.

Are you guys fine with that or do you prefer my current solution with linker error parsing in the GCC parser and want to delete the separate linker error parser?

**Comment by RolfNoot** [comment] 2024-08-03 17:37
I like to test as well, working a lot with gcc. Is there a repo or .vsix to test it?

**Comment by 0xemgy** [comment] 2024-08-04 14:31
@RolfNoot I created a new branch in my forked repo, see branch `dev/0xemgy/FixGnuLdProblemsViewPrompt` [here](https://github.com/0xemgy/vscode-cmake-tools/tree/dev/0xemgy/FixGnuLdProblemsViewPrompt), with the solution I'm confident @gcampbell-msft will prefer (keeping the gnu ld parser).

I generated a vsix (with local changes to the version in package.json to 99.99.0):
[cmake-tools-99.99.0.vsix.zip](https://github.com/user-attachments/files/16487853/cmake-tools-99.99.0.vsix.zip)

I tested it rudimentarily:
1. Installed the extension manually, overwriting the latest release: 
![grafik](https://github.com/user-attachments/assets/efc781e9-337f-44b6-886c-7d1458bc78e7)
2. Made sure my code is really in the main.js of the extension now running (see "C:\Users\my_username\.vscode\extensions\ms-vscode.cmake-tools-99.99.0\dist\main.js":
![grafik](https://github.com/user-attachments/assets/0cb58bc9-d1c1-4099-9e27-6732d5c51d49)

4. Tested it with just one warning (will test it extensively in the following weeks):
![grafik](https://github.com/user-attachments/assets/9276cd7f-4f66-4b4a-a272-1d9e62a94ac5)
Undefined reference is detected successfully.

I also updated the typescript playground code where I tested the regex stuff over the last couple of months (see [here](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBApgDwIYFsAOAbOBlKAnASzAHMIYAuGaQkgbQF0YBeGWgKBk5gHpuYAiAMLluSAEYQQGAK5Q43NEigALblBDcAZgSwA6YOQCM5AEyUA7kjxgixSqHQ64eGJeu3XBFTFAyUYfgAaDi5eAWFRCSlZeUUVNQ1tPQNjVysbEnsQRywXNwziTxUQWR9o-yCYEM4w-mBgQ11EOEpNJSQMeDw8EDxKcUkZOQUlVXUtJ31KADkQKmlgZRgkuBhemAATAjw4YHU8AE9Kqq4ePn44sY0rFABaMHA4W7hxAlvieqaEFuX2zucen0YANosNLgkJskZnMIAslis1i4tjs9r0joFOGxqmcYAAZIgAa2cXUBZCIrjg2w2y16KCUEGxtXB4xWpjMMGkYA2cG0YDg1J2mmccDAwFW6hgAAMIAcUGIpAByIKM87MjQYDZfH5qyFwJoYTRUXZQAjgKW6AD60ggzgt0CQwAJCs8GE6D1g2lg5J2xFNYClACUAIIAWSVwVOTNGEI1lB1K31hptez95qtNrwdqgDqdLrdIA9Xhg3rgvrNkuDYeVkdV0fGGq1lB9qYroedIAAbs5NBgQOZ+TAxAcYIYAAyGAAsg4Ocgg1dCtfiLKcxgno8oKGkGBNmFW3N5XlTIEN0tl8owCoA3DAdhglAQuyMlxoQGIAFYrEz6XSvt-keNOGYADsQGtNs0CbDyRADsowrzjUi5XNwDbNP+daJE4RhjhY6S2BucAoGiN6li2lbOu6kHAHeOwbPBOIXOhyEbGhz66lh65pO4mQwCgBFEc25ZkTAFHclRVj8nRUasSh3wsUhrKGAAzAAHJQMpgNmCAkr0kmITGzEAVgRgqWpBwaUgWkAjpEYLgIOoyT8VlAsRd4mo+Oq-gmwA-u+HI2mQABqABiAAKxG+tAxJWMQ0i8RpEAYi597uYxYhEFYByJpsIBwGQ7q6XZjEOa0SBONSEq8XgxDitFcCwBAaC7AQ2jAJs7RrIaCJJW5sSMZ5kzeb+BUMdJzHac5t7Jb1rH9ckPlvn5uUwMFYXNpFLjRbFIpQAlnCTT1T5IWlYAZVlGw5XlBbDfZY1tGVMAVc41UPbV9WNcAzUEK1GztceyxOHtcCuQ+01IbNeqDe+dEqji2AYAQxDKLA3IdgQ97gGQKhKFQyglBqwkFq4vQEjAAAUDy-BgNowGgIAQIeXYQAAlDDI1IcV3Ug4dELg9+v6UOSmicim5ZC6KJpmidvEKuQ11FWN+1cx575efNAv+mLIv+pKmsS-6UtwDLdFCCI6hSIspVgNwKC2OY3AEAAbMpDu3EpuiNKOty3i8Nq3OYRCKSYtwbG4mi3AseBQF7UAWh2hiGF7cBx9wx3cLoujIQQYjcB8wD207LvmA7E63DbJDmIH3Bux7acZ+ntcN47zt+8Xpe25Xqcc7OUDcIIIZIESQVOBAai5THsg6BavEoMAaCZcio-QFaJoYFPBGzwci-jyva8z3PfPvuryzC3rUp0kQRusxEIJDKDEJeUYpicQUWQ5MS+QeP73i+LFAQ2Qh4QRA3xiNzZcUJDDPzwmUN+eRcIkCKLjUoP8Kj-3otfKIt9QEYShIpGA8MwBEhcE5BBJRYDIP9EgLkJDSg2i7IQKA6JWaKxSqxB+xgTCQO4g4NAThYFcUKF-JY5DhrMLvmAiGRhOF2GgTw3IUjqFkPKH-Ng9BLxYhFLFGA-coCLAACoHEajAAA3tiIKW4MCoKHlgVB+I+SoMEEo1B2Ak7OC8AcVBIZcoQCQNVNgABfLEoBICwG0XogxOB8C2AgGpSJdBGAsHYKcfgZjXTGysXAY2tiMmoKEEo42zi6FuONp4iA3jqr8BUWotgRA5B4DaGKGAAZSyIBCkoWp-oTGnB9C0tpzgwCUCacQAAoggNAajTh0h0cofRjVolaKUGExqDA1EBLYEEiC3SECtKgO0uZgyek7L6QwZgrAYYAHFpgAFU8QABFsRGNsjdWgWp6ByXvphfBPwP7cWnvxEiZp066AJsjXY1F+TYi6c0rZvTrCUG4AAPVJgAfnIMi1FKLdAACoNQAB1yBMwAD5oqxbirUeKmZM1JlipmqKcUbAANQ0qZjiiA9KqWYppWTX5hxwqpixcCyiYKNhM24KgiZCzpnhLmbQUJkrGq6BSRY+ZUyZl6nSRiWVqrdBZI1RKrVBTXEMN1Sq8JugSllLgPQbEfjUEPIAU8l5bzxHkE+aZcyllui9AhVwTZ2z2lwsRSitFxLsUbHJUSjFoacVkvxZS6ltKGVMrJupTS40RViq4JMxZuVKAyr1aaxVxrs0KqcEWuVeodXKuLeanxlrrW2sefLRsRpCkMPwqU2t3rAbVWhYc2FPBA2opJWGrUTKWVspRW0bMnQmZItJji8wHK0UsqnR0OAs6WUovHey9NXaeL5tmbmzVBbzFlq1eqqt5bdAGvoe4y9Wqa3VUYPW+5jbRpqRcbe9tFq92+phf0gdwbh1jtZWi1dM650LqXVuiA4H11Is3eQbd1LRV7qzeW6Vx75WFvvQW0tuH5U3rcWe01j7LUnC4Da199qm2oR4l4ztpxIU9r9X0gNQGo2jvxch6DAAeAAhPigAJKhpjmaD05tYFhtVp6CNqvw9Js1DGn0Uc4FR04dqcQ3W-YxsT4UDn+sA0G4D3HQPUuRQJ4Tom9PodVZhiTCrZOKYvYpsjz7Tjqa4JpsIhkWiuo5FyKCfIBQ8mFKKcUIBf1QtY-2hFHGaXzsTaZtlnJ9zQRC0KHY4WHpzBQxmzgtmpVHoczh5zCmHOVtc8putHmG00dYZhGAgKjRaya+nPMArPTFn9AJf0gKossf-ex+NZMQ1Mya5i5Met+VjYm-7V0nWiwljLGAPLaGJP2ZNdhpzJXytbb1G5l9Gm33yQ+dBDcW4dxYEggeU+f1mvaDwBBNLwWYCwR2ANgzbGjNDo5QmxlyXSabm3AQXcN2iCHjNPdzF-0nsgt5DBYUu69P7v25t4tpXdvWLk9q6CJH5WHdq1iGsMAzmCEENRrTjFWSuvIR+1tBwdO+JR3+vtAG4vGb+4lgH3OQMTvIOBmAs752LspTBuDG6IAwbZWtlHhXD1SZKzt-bJbseKcqw5hxfgwD471ERo1OPCeUbq1ThrRl-O0MNYz+jHbmd6dZ4Zjnv2Et0oB8y0Dk6-hC8g6L5dsG-jwcQzx5HNmNvFZV5jiPe3i0a5V-ru9VXbc1eN5TnzjF6iNDo5br9Nuf0s+i0Nn77KM-RuaHzsDXvhdQbF0h-307A9S9rzLjl1mxPy8k3miPyuMfR6vfH3XSmk9WqJ8d+rSEbj3EeM8V47xPhZ8-W4pncBPu9sd4O9lE+Hh8mn2lWfwBS-fHL576d3uRfQdrxLhDjfg+t6Y+39HV7I897Vw5-vhvqvD8o5UrEmh1ik3WbAIgKgLuLgDQIUH9EAegFgKAVEuNp0lwFgLAOhrlOMlwL-ngP-hjLALQEQNyAgBiA7n0owH9IQdYBAE0BpIQLlKTBSsYutlMktCwJASAbEsQLoOhqTKQatlwUzKgWJnus1FyhKktPxkwCwGAOYnAXuqcOslIHqL2MQKTJKLKggjTP+jAEJkYrgYgH4pKLwcTijmgX-ogcWCcqONeAQDALxqjosLlLoFgCQCoBYfSoynQYYXprIXoAoUoSoZoQQH4jALcBoUYtJjASQBALQFwewRtjgfQPQH4pQJocgREQQPEXoXwYYQEu4ZwGIDsAPBkR5tatiNiM1EDsIWQGIcJJIW4R4RjHIfYSAIofwLMDYfCCUFQugbLBiMwdAawfoYUQEkAA).

So at first glance looking good, but since I am not proficient at all with typescript and desktop applications in general, I might have overlooked something. Looking forward to your feedback!

**Comment by gcampbell-msft** [comment] 2024-08-05 09:33
@0xemgy Thanks for all of your work! Yes, I agree that we should solve that bug and am happy for you to implement and continue testing,

**Comment by 0xemgy** [comment] 2024-08-25 13:24
@gcampbell-msft I was able to test my changes extensively over the last 3 weeks at work. I also added a few unit tests and cleaned up the regex expressions. For my use cases it is working properly. It is commited in the PR [3950](https://github.com/microsoft/vscode-cmake-tools/pull/3950) and is ready for review.

Of course, feedback of @RolfNoot would be much appreciated.

**Comment by v-frankwang** [comment] 2024-08-29 08:17
@gcampbell-msft The user made some changes to the PR: https://github.com/microsoft/vscode-cmake-tools/pull/3950 based on the survey and asked you to review it.

**Comment by gcampbell-msft** [comment] 2024-11-05 19:58
Fixed in #3950. 

Please open new issues if errors still remain. Thanks everyone and thanks to @0xemgy for their contribution!

**Closed by gcampbell-msft** 2024-11-05 19:58 UTC
Labels: bug, help wanted, Feature: diagnostics

**Comment by Yingzi1234** [comment] 2025-02-14 09:57
@RolfNoot We're in the process of verifying this issue, but we're not sure if the issue has been fixed, can you help us determine this by looking at the information below? If it's not correct, would you be able to provide us with a reproduction project?

**Repro steps：**
1. Download and unzip this folder 
2. Open it with VSCode and configure this folder
3. Build this folder and check if the error info occurs on Problem window

**Actual result:**
Build failed but no error message occurs on Problem window
![Image](https://github.com/user-attachments/assets/0422d7a0-b44e-48eb-8a4e-9f93d76dff63)

**Comment by 0xemgy** [comment] 2025-03-08 09:04
@Yingzi1234 I implemented the fix, so I hope it's ok if I just respond here.

The error message provided by @RolfNoot occurs in the Problem window after the fix. 
Its is _/Volumes/Data/VScode/Gatewise_AddOn01/source/main.c:105: undefined reference to 'no_reference'_.

The message you get in the gif has a different format:
_C:/Users/v-cathyzhang/Desktop/CMAKE/main.cpp:4:**(.text+0xe):** undefined reference to 'someFunction()'_.
The difference is marked in bold. After the line number, you additionally get section and offset of the line.
This format is currently not supported, so the message does not get parsed.

Running your example zip, I get the message format without the section, which is correctly parsed:
![Image](https://github.com/user-attachments/assets/3eb1a7d5-f202-485b-9817-585bca70429e)
![Image](https://github.com/user-attachments/assets/8ea51c05-a929-400c-a043-ef8db958c607)

Since you are using mingw version 14.2.0, and I use 13.1.0, I assume the output format might have changed.

Support for such formats could easily be added to the error parser if desired.

**Comment by 0xemgy** [comment] 2025-03-09 17:37
@gcampbell-msft, while looking into the issue @Yingzi1234 mentioned, I ran into a couple of other things:

1. Even after updating gcc to version 14.2.0, I don't get the linker error format with the extra section info.
2. When I used Unix Makefiles as a generator, I found that my gnuld modifications caused false positive make errors. I only used Ninja before, and the unit test that was already there only checks for false positives with the gcc parser, not the gnuld parser, so I didn't run into this problem then.
3. When I use Ninja as the generator again, the "undefined reference" error doesn't get parsed anymore, even without the extra section info. This is due to a trailing "\r". I'm not sure if this was the case before. 
4. After some more messing around, it turns out that another linker error, the one for "multiple definitions", is still detected, but parsed incorrectly now. It looks like the format has changed, or maybe I manually tested with the wrong format a few months ago and did not try to provoke the error with a build.

I've got 2, 3, and 4 sorted in #4341.

If we're going to fix 1, I'd probably need some settings to get those output formats with the extra section info. Otherwise, I could just assume the format seen in the GIF. 

Hope that works for now. How do you want to proceed?
