### ISSUE TITLE
CMake Tools doesn't send --target to C/C++ tools

### ISSUE THREAD

**Issue by thunderstorm010** [microsoft/vscode-cmake-tools#1896] opened 2021-05-21 14:54 UTC
See microsoft/vscode-cpptools#7519 for more info.

[TL;DR](https://github.com/microsoft/vscode-cmake-tools/issues/1896#issuecomment-954878454)

**Comment by andreeis** [comment] 2021-05-21 16:16
@thunderstorm010, this could be the same as https://github.com/microsoft/vscode-cmake-tools/issues/1879. We are almost done with a fix for that and once it's merged in, we will send you a vsix to install and try. If that will not solve your scenario then we will investigate further.

**Comment by Colengms** [comment] 2021-06-09 03:52
Hi @thunderstorm010 .  Would you be able to provide a simplified repro that we might use to validate a potential fix?  Perhaps a minimal project configured with the same target, using the same toolset, as a github repo, with setup instructions?

**Comment by andreeis** [comment] 2021-06-09 07:04
@thunderstorm010, can you try the CMake Tools vsix from [here](https://github.com/microsoft/vscode-cmake-tools/actions/runs/920800165) and confirm if it solves anything for you?

**Comment by Colengms** [comment] 2021-06-15 22:18
@thunderstorm010 When you build with CMake, it should generate 'target' files under a `.cmake\api\v1\reply` path, under the build directory.  CMake Tools collects compiler arguments from these files.  If you could provide one of these files from your repro, we may be able to determine why the `--target` arg was not picked up.  Otherwise, we seem to be in need of a repro we can use to investigate further.

**Comment by yuxinyuan** [comment] 2021-07-07 07:40
@andreeis I'm having pretty much the same issue. I'm not sure if I completely followed all the discussions, but the vsix you mentioned didn't solve the issue.

@Colengms I didn't see a .cmake/api/v1 path under the build directory

**Comment by andreeis** [comment] 2021-07-07 16:47
@yuxinyuan, there is no .cmake/api/v1 path under the build directory not even after you have a successful configure?
Also, maybe you can share with us a standalone project where we can reproduce this problem on our side, for easier debugging and investigating?

**Comment by bobbrow** [comment] 2021-07-07 17:05
@andreeis @yuxinyuan that path is created when you have cmake version 3.15 and newer as well as the `cmake.cmakeCommunicationMode` set to `automatic` or `fileApi`

**Comment by yuxinyuan** [comment] 2021-07-08 04:01
@andreeis @bobbrow I was using cmake version 3.10. After upgrading to version 3.18, I can now see the .cmake/api/v1 path. However, there is still no "target" field in the generated files. It seems to me that the extension has parsed --sysroot option from the compile commands, but fail to parse --target option.

[https://github.com/yuxinyuan/test-cmake-target](url)
I created a minimum project with vscode and cmake-tools. But I think you will need to install android ndk by yourself, since I'm using android toolchain files to do cross compiling. Also, you need to change the paths in all the .json files under .vscode.

**Comment by yuxinyuan** [comment] 2021-08-17 07:27
@andreeis I've spent some time on this and I'm able to find a work around for this issue.

First, I think the issue happened because of the following. If I inspect my compile_commands.json generated by cmake, I see something like:

`clang++.exe --target=... --gcc-toolchain=... --sysroot=... ...rest of the command...`

Somehow, c/c++ tools needs the --target option to correctly configure intellisense. However, the cache (or whatever) generated by cmake will not contain the --target option (I guess this has little to do with the cmake tools extension). Hence, the issue happened

What I do as a work around now is to add the following in my CMakeLists.txt:

```
if(ANDROID)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --target=${ANDROID_LLVM_TRIPLE}")
endif(ANDROID)
```

This will not hurt the actual compilation and it can also let the --target option be passed to c/c+ tools. The `${ANDROID_LLVM_TRIPLE}"` variable is defined by the toolchain file shipped with android ndk, so it should be safe to use that.

Hope this would help.

**Comment by andreasWallner** [comment] 2021-12-15 23:52
@bobbrow Not sure it's cmake's "fault", they are at least consistent with their documentation (even though I have to admit it seems a bit inconsistent). I don't really have a stake in either tool though...

**Closed** 2022-10-20 21:17 UTC
Labels: Feature: cpptools integration, Feature: configure

**Comment by bobbrow** [comment] 2022-10-20 21:25
We have a fix for this.  It should be in the 1.13.17 release tomorrow morning (PDT).
