### ISSUE TITLE
Bug with cmake.buildDirectory

### ISSUE THREAD

**Issue by sabudilovskiy** [microsoft/vscode-cmake-tools#4038] opened 2024-09-02 16:35 UTC
### Brief Issue Summary

cmake.buildDirectory override build directory from preset. This behavior is most annoying. I would like an option so that everything is taken only from the preset.

**Comment by gcampbell-msft** [comment] 2024-09-03 10:10
@kuch3n @sabudilovskiy Could you help us understand where this issue reproduces? Does it reproduce in v1.18.44? Thanks.

**Comment by gcampbell-msft** [comment] 2024-09-03 10:13
@sabudilovskiy Also, could you share a repro for this? I don't see this reproducing, if I define a `binaryDir` in my preset, then that directory is used rather than any cmake.buildDirectory from the settings. 

Thanks.

**Comment by kuch3n** [comment] 2024-09-04 07:54
Currently i assume the described bug is mainly caused by #1376 

Additionaly it makes a difference if you call the same command from the vscode console or via the plugin itself. E.g., the odd `c?` directory is missing. Maybe it's a problem how the executable is run from the cmake-tools plugin.

As for reproducability, you just need a cygwin environment and use CMake from cygwin. A plain `CMakeList.txt` is enough.

For now i'm trying to run CMake via a hook, but the command output is missing if run via the plugin:

```bat
@echo off
setlocal enableextensions
set TERM=
set CYGWIN=winsymlinks:sys
cd /d "%~dp0bin" && .\bash -c "cmake %*"
```

**Comment by sabudilovskiy** [comment] 2024-09-04 15:13
> @sabudilovskiy Also, could you share a repro for this? I don't see this reproducing, if I define a `binaryDir` in my preset, then that directory is used rather than any cmake.buildDirectory from the settings.
> 
> Thanks.

1) 1.19.50
2) I think I've figured out what the problem is, and honestly, the mistake is on my side on the one hand, but on the other... In general, as I understand it, the extension parses the preset and overturns all options manually? If in the end there is something crooked in the options (in my case "binaryDir": "${SourceDir}/build_debug"), then it takes the default option. I don't quite understand, but why don't you just use cmake --preset if the user specifies to always use it?

**Comment by gcampbell-msft** [comment] 2024-09-04 15:33
@sabudilovskiy Does it reproduce in any other versions prior to 1.19.50? This information is important to know so that we can understand when the issue may have been introduced

**Comment by kuch3n** [comment] 2024-09-06 13:38
It would be nice to specify source/binary directories in presets, while ignoring those out of the settings. E.g., if using cygwins cmake, it needs to be called with cygwin style paths, otherwise non obvious problems will occur while building/configuring (see #1376). Though such options needs to be handled correctly by this plugin if a cygwin style is used. 

On the other hand, `cygpath` could be used to translate given direcotries from and to Cygwins CMake, before doing the actual call:
`C:/cygwin64/bin/cmake -S(C:/cygwin64/bin/cygpath -u -a ".")  -B(C:/cygwin64/bin/cygpath -u -a "./build")`

**Comment by kuch3n** [comment] 2024-09-10 08:52
Handling windows paths should be done by CMake and not any IDE out there. Therefore i created an issue and example implementation to fix it: https://gitlab.kitware.com/cmake/cmake/-/issues/26277

Thus this issue can be closed

**Comment by v-frankwang** [comment] 2024-09-30 02:03
@kuch3n Thank you very much for the fix. We'll verify and close this issue after this PR merge

**Comment by gcampbell-msft** [comment] 2024-10-01 14:37
Refreshing my context after being OOF and it seems like this issue can be closed basedon @kuch3n recent comments. I'll close this issue and it seems like both items have been resolved or understood. Please let me know or create a new issue if there are still things needed. Thanks!

**Closed by gcampbell-msft** 2024-10-01 14:37 UTC
Labels: more info needed
