### ISSUE TITLE
Necessary buttons/selections are gone on newest version (v1.16.29)

### ISSUE THREAD

**Issue by TaeZStkyoht** [microsoft/vscode-cmake-tools#3442] opened 2023-11-15 10:24 UTC
### Brief Issue Summary

I was using 1.15.31 and it was working fine. Here is the bar on VS code:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/3801692/c3e96ec9-2ddb-4767-9c83-41f848b741c5)
Today I upgraded to v1.16.29 and all necessary things are gone:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/3801692/f4fff344-0ba2-4226-86de-98979af090ea)
Could you please fix it?

**Comment by TaeZStkyoht** [comment] 2023-11-15 10:38
![image](https://github.com/microsoft/vscode-cmake-tools/assets/3801692/7bece381-28a8-4f66-bccc-fbf30a1f2052)
Yeah, I found settings. This is by default `hidden` on the new version. You have to select as `visible` for previous style. By default hidden is not a wise choose.

**Comment by alex1234567890123456789** [comment] 2023-11-15 15:44
PLEASE revert this.  This was a terrible change to make, even with the helpful popup.

**Comment by sinemakinci1** [comment] 2023-11-15 17:30
Thank you all for your feedback. Like @TaeZStkyoht said, you can set the Status Bar Visibility to "visible" to revert to the prior experience. 

This was our proposed solution to consolidate those who prefer the prior experience and give them an option to continue to use that view, with the push for a simplified default status bar (especially when you have multiple extensions installed). That being said, we are still working to improve the UI, and if there is anything you'd like to see to enhance this new experience, please let us know on #3423.

**Comment by benmcmorran** [comment] 2023-11-15 17:32
Closing as duplicate of #3423.

**Closed by benmcmorran** 2023-11-15 17:32 UTC
Labels: duplicate, Feature: UI
