### ISSUE TITLE
Failed to use clang-cl x64

### ISSUE THREAD

**Issue by codehz** [microsoft/vscode-cmake-tools#1398] opened 2020-08-06 07:15 UTC
### Brief Issue Summary

1. The CMake Tools does not discovered the clang-cl x64
2. So I duplicated the clang-cl x86 and change it to x64 
3. But it doesn't success

### Expected:

1. Configure project with clang-cl x64
2. Success configure

### Apparent Behavior:

1. Configure project with clang-cl x64
2. Failed due to lld-link: error: <root>: undefined symbol: _mainCRTStartup

### CMake Tools Log

```
[main] 正在生成文件夹: **
[main] 正在配置文件夹: **
[proc] 执行命令: D:\VisualStudio\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=D:\VisualStudio\Community\VC\Tools\Llvm\bin\clang-cl.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:\VisualStudio\Community\VC\Tools\Llvm\bin\clang-cl.exe -Hd:/Project/** -Bd:/Project/**/Build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is Clang 10.0.0 with MSVC-like command-line
[cmake] -- The CXX compiler identification is Clang 10.0.0 with MSVC-like command-line
[cmake] -- Check for working C compiler: D:/VisualStudio/Community/VC/Tools/Llvm/bin/clang-cl.exe
[cmake] -- Check for working C compiler: D:/VisualStudio/Community/VC/Tools/Llvm/bin/clang-cl.exe - broken
[cmake] CMake Error at D:/VisualStudio/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "D:/VisualStudio/Community/VC/Tools/Llvm/bin/clang-cl.exe"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: D:/Project/**/Build/CMakeFiles/CMakeTmp
[cmake]     
[cmake]     Run Build Command(s):D:/VisualStudio/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_1ec55 && [1/2] Building C object CMakeFiles\cmTC_1ec55.dir\testCCompiler.c.obj
[cmake]     [2/2] Linking C executable cmTC_1ec55.exe
[cmake]     FAILED: cmTC_1ec55.exe 
[cmake]     cmd.exe /C "cd . && D:\VisualStudio\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_1ec55.dir --rc=D:\WINDOW~1\10\bin\100183~1.0\x64\rc.exe --mt=D:\WINDOW~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- D:\VisualStudio\Community\VC\Tools\Llvm\bin\lld-link.exe /nologo CMakeFiles\cmTC_1ec55.dir\testCCompiler.c.obj  /out:cmTC_1ec55.exe /implib:cmTC_1ec55.lib /pdb:cmTC_1ec55.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
[cmake]     LINK Pass 1: command "D:\VisualStudio\Community\VC\Tools\Llvm\bin\lld-link.exe /nologo CMakeFiles\cmTC_1ec55.dir\testCCompiler.c.obj /out:cmTC_1ec55.exe /implib:cmTC_1ec55.lib /pdb:cmTC_1ec55.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_1ec55.dir/intermediate.manifest CMakeFiles\cmTC_1ec55.dir/manifest.res" failed (exit code 1) with the following output:
[cmake]     lld-link: error: <root>: undefined symbol: _mainCRTStartup
[cmake]     ninja: build stopped: subcommand failed.
[cmake]     
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:3 (project)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/Project/**/Build/CMakeFiles/CMakeOutput.log".
[cmake] See also "D:/Project/**/Build/CMakeFiles/CMakeError.log".
```

### Developer Tools Log

Not a ui bug

### Platform and Versions

- **Operating System**: Windows 
- **CMake Version**: 3.17.2 (bounded with visual studio) 
- **VSCode Version**: 1.47.3 
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: clang-cl x64

**Comment by bobbrow** [comment] 2020-08-06 16:14
When you use CMake on the command prompt, how do you configure your project?  Do you get the same error?

**Comment by codehz** [comment] 2020-08-08 10:51
> When you use CMake on the command prompt, how do you configure your project? Do you get the same error?

I use visual studio 2019 before, and it seems didn't print command line...
BTW, this custom kit works

```json
{
    "name": "clang-cl x64",
    "compilers": {
      "C": "D:\\VisualStudio\\Community\\VC\\Tools\\Llvm\\bin\\clang-cl.exe",
      "CXX": "D:\\VisualStudio\\Community\\VC\\Tools\\Llvm\\bin\\clang-cl.exe"
    },
    "environmentSetupScript": "D:\\VisualStudio\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat",
    "cmakeSettings": {
      "CMAKE_C_FLAGS": "/DWIN32 /D_WINDOWS /W3 -m64",
      "CMAKE_CXX_FLAGS": "/DWIN32 /D_WINDOWS /W3 -m64",
      "CMAKE_EXE_LINKER_FLAGS": "/machine:X64",
      "CMAKE_MODULE_LINKER_FLAGS": "/machine:X64",
      "CMAKE_SHARED_LINKER_FLAGS": "/machine:X64",
      "CMAKE_STATIC_LINKER_FLAGS": "/machine:X64"
    }
  }
```
but it is hard-coded path

**Comment by elahehrashedi** [comment] 2022-11-04 18:25
This is a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/2798.

**Closed by elahehrashedi** 2022-11-04 18:25 UTC
Labels: duplicate, more info needed, Feature: configure
