### ISSUE TITLE
"Set as Launch/Debug Target" seems only to work with buildType set to Debug.

### ISSUE THREAD

**Issue by Mohawi** [microsoft/vscode-cmake-tools#1405] opened 2020-08-10 11:42 UTC
### Short description:

The context menu item "Set as Launch/Debug Target" as well as the status bar setting of the launch target seem only to work when the buildType is set within the cmake-variants.json to "Debug". When the buildType is set to other CMAKE_BUILD_TYPE or self defined settings, a click on fthe "Set as Launch/Debug Target" or the corresponding status bar button has no effect.

### Expected:

Pre:
Within cmake-variants.json set buildType to "RelWithDebug" or "Release" or "MinSizeRel" or something user definded and configure and generate project.

A)
1. Right click on wanted target to open context menu and click on "Set as Launch/Debug Target"
2. Target is set as launch/debug target (marked with rocket)
3. Target can be build, executed and (if debug information is available also) debugged.

B)
1. [Cntrl + Shift + P] -> CMake: Set Debug Target
2. Targets are listed to choose from -> Choose target wanted
2. Target is set as launch/debug target (marked with rocket)
3. Target can be build, executed and (if debug information is available also) debugged.

C)
1. Right click on wanted target to open context menu and click on "Run in Terminal"
2. Target is (if necessary build and) launched in terminal

D) When setting buildType to "Debug" all cases A to C are behaving as expected.

### Apparent Behavior:

A) on click on "Set as Launch/Debug Target" nothing happens.
     Debug print: 
```
[extension] [3971] cmake.selectLaunchTarget started
[extension] [3971] cmake.selectLaunchTarget finished (returned null)
```
B) on executing: CMake: Set Debug Target nothing happens.
    Debug print:
```
[extension] [7239] cmake.selectLaunchTarget started
[extension] [7239] cmake.selectLaunchTarget finished (returned null)
```

C) on click on "Run in Terminal" nothing happens.
   Debug print:
```
[extension] [8419] cmake.launchTarget started
[extension] [8419] cmake.launchTarget finished (returned null)
```

D) When setting buildType to "Debug" all cases A to C are behaving as expected.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.17.2
- **VSCode Version**: 1.47.3
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: GCC 10.1 or CLang 10

### Other Notes/Information

All targets are created successfully though and can be successfully run manually via shell.

The build directory is out of source ("${workspaceFolder}/build/${buildType}").

I use the generator for "Unix Makefiles"

Can you please have a look into this? I would like to segregate my build directories according to the build type in order to make better use of the incremental builds. Also I would like to be able to run my executable targets via the CMakeTools GUI and not be forced to run them manually via shell, even if they are not build with buildType "Debug".

**Comment by snehara99** [comment] 2024-07-08 17:01
Hi @Mohawi I'm not able to reproduce this issue, are you still able to? If so, would you be able to provide me either a zip or a link to a repo of a sample project that can repro this issue? Thanks!

**Comment by gcampbell-msft** [comment] 2024-07-17 18:29
Closing this issue as no repro. Please open a new issue if you are still facing trouble @Mohawi. Thanks!

**Closed by gcampbell-msft** 2024-07-17 18:29 UTC
Labels: bug, more info needed, Feature: debug/launch, repro needed
