### ISSUE TITLE
Launch button in status bar not launching the selected target

### ISSUE THREAD

**Issue by ruben-fuerst** [microsoft/vscode-cmake-tools#3215] opened 2023-06-20 10:45 UTC
Type: <b>Bug</b>

Hello,
since a month, we are neither able to launch the "Selected target" from the launch button (CMake) in the status bar of VS Code, nor from the CMake project outline sidebar, when we click "Run in terminal" from the context menu of the designated executable target. VS Code just triggers the build but no execution is followed.
Our codebase is stored on a high performance cluster (Linux) to which we connect using the standard Remote-SSH connection. We are still able to execute the binary by using the terminal and going to CMakes build directory.
If you need any more information (regarding our configuration, especially our CMakeLists.txt) please contact me. :)

Extension version: 1.14.33
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.18.0-425.19.2.el8_7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3410)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (9.27GB free)|
|Process Argv|--crash-reporter-id 08b48010-3a26-4650-a28e-fe565d1c2d6a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: HPC-3|
|OS|Linux x64 4.18.0-425.19.2.el8_7.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (48 x 2713)|
|Memory (System)|376.35GB (241.26GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
e440d664:30770001
pythonnocebcf:30771284

```

</details>

**Comment by snehara99** [comment] 2023-07-10 18:10
Hi @ruben-fuerst, I'm having trouble reproducing the issue. Is there a sample project you could share with us that encounters this issue?

**Comment by snehara99** [comment] 2023-07-27 16:52
Hi @ruben-fuerst, I'm going to go ahead and close this issue since I cannot reproduce it. Please try the latest pre-release and see if it is fixed. If you encounter this issue again, please open a new issue, thanks!

**Closed as not planned by snehara99** 2023-07-27 16:52 UTC
Labels: bug, more info needed
