### ISSUE TITLE
Consider absorbing twxs's CMake extension

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#738] opened 2019-08-14 21:00 UTC
Currently we need to install twsx's CMake extension https://github.com/twxs/vs.language.cmake to get proper CMake support. Please, consider absorbing/implementing the respective functionality into vscode-cmake-tools too to make the extension feature complete and more convenient and better supported.

**Comment by bobbrow** [comment] 2019-08-15 19:02
Thank you for the feedback.  This is a duplicate of #93.  Can you please go add your 👍 to that issue so we can track the demand?

**Closed by bobbrow** 2019-08-15 19:02 UTC
