### ISSUE TITLE
Command 'CMake: Quick Start' resulted in an error

### ISSUE THREAD

**Issue by mingxingren** [microsoft/vscode-cmake-tools#3239] opened 2023-07-17 01:26 UTC
Type: <b>Bug</b>

I run vscode and open empty project. run cmake-tools 'Quick Start'. But it report error: Command 'CMake: Quick Start' resulted in an error!

Extension version: 1.14.34
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i3-12100 (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.32GB free)|
|Process Argv|--crash-reporter-id 94b9fda2-15f5-44d7-98ac-e1e7dd8d42b3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30789497
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013:30789517
cmakestatusbarv2:30779594

```

</details>

**Comment by gcampbell-msft** [comment] 2023-07-18 15:21
@mingxingren Could you provide some additional information about what error returned? Any screenshot or gif could help. 

I attempted to open a project and run the CMake Quick Start and didn't notice any action happen, so I do believe there is a bug somewhere, but having your feedback about what error you hit would help us reproduce and diagnose. 

Thanks!

**Comment by wusonglin12138** [comment] 2023-10-27 07:57
I have met the problems too.

The operation is familiar with first bro.

I open a new vscode windows and change direction into a empty folder. And then click the button 'CMake: Quick Start'.

Although the project seems to be created successfully, some error happened after selecting current build variant.

OS: CentOS Linux release 7.9.2009 (Core)（VMware Virtual Machine via vscode ssh external）project is created in this os

VScode:  Version: 1.83.1 (user setup) Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc OS: Windows_NT x64 10.0.22621 vscode is installed in this os

Error message is:

`[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant SyntaxError: Unexpected token S in JSON at position 3 {}`

![1698392991938](https://github.com/microsoft/vscode-cmake-tools/assets/39580967/9e7137be-95cf-4170-a75f-263288fcce56)

**Comment by gcampbell-msft** [comment] 2024-04-24 12:51
@qarni FYI, related to quick start.

**Comment by qarni** [comment] 2024-07-16 17:27
Hi @mingxingren @wusonglin12138! Could you please provide us with a minimal repro to help investigate this issue? Thank you.

**Comment by qarni** [comment] 2024-07-23 17:49
Closing from lack of info/repro. If you have further issues, please file a new bug! Thanks

**Closed** 2024-07-23 17:48 UTC
Labels: bug, Feature: quick start, repro needed, suggested
