### ISSUE TITLE
Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description

### ISSUE THREAD

**Issue by mihailim** [microsoft/vscode-cmake-tools#3616] opened 2024-02-27 11:57 UTC
### Brief Issue Summary

For a while now (at least 3 months), the `cmake-tools` extension has been spamming the shared log with the warning message reproduced below. This happens on startup, and then periodically throughout the session, regardless of whether or not anything cmake-related is open or running; the presence of the installed extension is sufficient to reproduce. Changing the logging level to debug doesn't affect anything in any direction.

This is with vscode-cmake-tools v1.17.16 running on the latest MS-published vscode build (1.86.2) on Linux (repros on Ubuntu noble daily, Ubuntu jammy, Ubuntu bionic with the older still-compatible vscode 1.85.whatnot). No idea about other OS-es, sorry.

The locale environment is `LANGUAGE=en_US` and `LANG=en_US.UTF-8` and it also reproduces with `LANG=C` .

```
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.606 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.607 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.607 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.607 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
2024-02-27 13:42:56.607 [warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
```

### CMake Tools Diagnostics

```shell
I'd love to be able to provide this, but I can't seem to find this command at all.
```

**Comment by bobbrow** [comment] 2024-02-27 19:45
It looks like the correct key is `cmake-tools.configuration.cmake.options.advanced.statusBarLength.markdownDescription`.  Needs to be updated in `package.json`.

**Comment by gcampbell-msft** [comment] 2024-02-28 15:19
@mihailim @bobbrow Thanks for pointing this out, I have a PR open here: #3618

**Comment by IkeCuizhihui** [comment] 2024-03-28 03:39
How do I resolve the issue if I don't have a package.json file?

**Comment by mihailim** [comment] 2024-03-28 13:38
@IkeCuizhihui If you don't want to wait for the next extension release and it bothers you that much, you can switch to the prerelease version of the extension -- open the extension's page (go to Extensions and click on CMake Tools) then click the "Switch to Pre-Release Version" button under the extension description, next to the "Disable" and "Uninstall" buttons. Then after it switches, click Reload, and then you may need to close and reopen vscode once to fully get rid of the warning spam.

But, to be honest, I wouldn't risk it if it's a prod environment you need to be sure the extension is stable and working. After all, it's not that big of a deal, more or less an aesthetic annoyance.

**Comment by notpeter** [comment] 2024-05-02 05:14
It's been two months since this was merged.

Any chance someone can cut a release that includes this?

**Comment by georglauterbach** [comment] 2024-05-03 13:18
I'm seeing this as well - can we have a new release, please? :)

**Comment by notpeter** [comment] 2024-06-04 05:42
This went out with microsoft/vscode-cmake-tools#v1.18.41 so there's no need to run pre-release anymore. Thanks all.

**Comment by zhongxiang117** [comment] 2024-08-15 15:16
Any updates on it? Release version `v1.18.44` and pre-release `v1.19.40` both have this problem too.

**Comment by mihailim** [comment] 2024-08-15 15:18
@zhongxiang117 This has been fixed for a while. You may be referring to the similar but _different_ issue with `[warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.deleteBuildDirOnCleanCconfigure.description` which is issue #3865 . That one isn't released yet, annoyingly.

**Comment by zhongxiang117** [comment] 2024-08-15 15:29
@mihailim thanks for your reply, it is the same issue.

![image](https://github.com/user-attachments/assets/b52d9a3e-ea3a-483c-af97-94fe5f5096e7)

**Comment by zhongxiang117** [comment] 2024-08-15 15:31
Also, another version:

![image](https://github.com/user-attachments/assets/2977c93c-350d-4663-b72b-da692e7347c9)

**Comment by mihailim** [comment] 2024-08-15 15:33
You're right, my apologies. I can confirm it's happening with the pre-release version `v1.19.40`, but _not_ with the release version `v1.18.44`. On the other hand, the release version suffers from the #3865 issue, but not from _this_ issue. So the fix for this issue was probably lost for the pre-release version, and currently both of them are annoying for different reasons :)

**Comment by zhongxiang117** [comment] 2024-08-15 15:36
@mihailim , OK, I will switch back to `v1.18.44`. Also, my apologies for the wrong screenshot, I was using the same picture for twice (as you will see the time stamp are the same).

**Comment by zhongxiang117** [comment] 2024-08-15 15:37
For version `v1.18.44`, this issue is gone, thanks for that!

**Comment by gcampbell-msft** [comment] 2024-08-15 15:45
@mihailim @zhongxiang117 I'm not sure I fully understand from your comments, which error is happening where?

**Comment by gcampbell-msft** [comment] 2024-08-15 15:47
With a quick test and viewing the source code, these issues are fixed in the most recent code. If you could tell me any steps you take to see this output, it'd be great so that I can test and see for myself. Thanks!

**Comment by gcampbell-msft** [comment] 2024-08-15 15:49
@zhongxiang117 Are you doing anything specific to get this output? I'm opening the extension on the most recent release and I don't see the issue

**Comment by zhongxiang117** [comment] 2024-08-15 15:50
Quick question, is `cmake-tools` has any dependencies? Like this extension `CMake`?
![image](https://github.com/user-attachments/assets/c1cb4a9d-bc9c-4cd9-bae8-d5e65ef53400)

**Comment by gcampbell-msft** [comment] 2024-08-15 15:53
> @zhongxiang117 Are you doing anything specific to get this output? I'm opening the extension on the most recent release and I don't see the issue

Could you provide any steps? Are you using any other display language than English? 



> Quick question, is `cmake-tools` has any dependencies? Like this extension `CMake`? ![image](https://private-user-images.githubusercontent.com/28009328/358290300-c1cb4a9d-bc9c-4cd9-bae8-d5e65ef53400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzczNTIsIm5iZiI6MTcyMzczNzA1MiwicGF0aCI6Ii8yODAwOTMyOC8zNTgyOTAzMDAtYzFjYjRhOWQtYmM5Yy00Y2Q5LWJhZTgtZDVlNjVlZjUzNDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE1NTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMmIzMmUxYmFkNGNmNzk4ZjJkNTBlZjBkZjgxY2VlYjMzODFiZGNhZjY0YjRmN2RlMGRhM2Q2OGQ1ZjAxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hWjjD0BCjZAi470JQjPisfwxYsPRggtv7ds-opdTia0)

Yes, currently there is an extension dependency on the one that you have in your screenshot. We hope to remove that at some point as we implement and improve our own language services for CMake files.

**Comment by bobbrow** [comment] 2024-08-15 15:54
@gcampbell-msft it's not actually a dependency. It is just bundled with this extension. Anyone can uninstall it if they want to use a different language server for `CMakeLists.txt`.

**Comment by gcampbell-msft** [comment] 2024-08-15 15:55
@bobbrow Good clarification, you are correct, it's not a dependency but a bundle. Thanks. I'll update my comment as well

**Comment by bobbrow** [comment] 2024-08-15 15:57
Yeah, the top-level readme has a link to another language server extension.

**Comment by gcampbell-msft** [comment] 2024-08-15 15:58
> @zhongxiang117 This has been fixed for a while. You may be referring to the similar but _different_ issue with `[warning] [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.deleteBuildDirOnCleanCconfigure.description` which is issue #3865 . That one isn't released yet, annoyingly.

@mihailim We have released this in the most recent pre-release. Additionally, we no longer use the key `cmake-tools.configuration.cmake.deleteBuildDirOnCleanCconfigure.description`, as it has a typo, it was fixed to be `cmake-tools.configuration.cmake.deleteBuildDirOnCleanConfigure.description`.

**Closed by gcampbell-msft** 2024-08-15 15:58 UTC
Labels: bug, triage

**Comment by zhongxiang117** [comment] 2024-08-15 16:00
OK, I got it, thanks for you two.

The steps is: I installed `v1.19.40` and then removed `CMake` extension, then happened to have this issue.

Now, it seems I cannot reproduce them, `v1.19.40` and `v1.18.44` both work well.
