### ISSUE TITLE
CMake Tools doesn't work with multi-root folders with non-CMake folders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#1097] opened 2020-02-26 03:24 UTC
1. Open a workspace with folders configured for CMake and other folders that don't use CMake.

Bug: "Configuring project" gets stuck and the CMake extension incorrectly tries to configure the non-CMake workspace folders.

I'm using the pending 0.27.0-insiders of C/C++ and 1.3.1 of CMake Tools.

It works if both folders use CMake.

**Comment by sean-mcmanus** [comment] 2020-02-26 03:29
The Configuring project but doesn't repro if the 1st workspace folder uses CMake, but the "Select a Kit" and "configure" popup shows up still.

**Comment by bobbrow** [comment] 2020-02-26 18:27
This is a duplicate of #1042.

**Closed by bobbrow** 2020-02-26 18:27 UTC
