### ISSUE TITLE
Compile active file does not work

### ISSUE THREAD

**Issue by bad-ed** [microsoft/vscode-cmake-tools#971] opened 2019-12-13 10:59 UTC
### Brief Issue Summary

Compiling one file pops up terminal and that's it, nothing else happens.

### Expected:

1. Click "Compile Active File" or select file in project outline, and then click "Compile File"
2. File is being compiled

### Apparent Behavior:

1. Click "Compile Active File" or select file in project outline, and then click "Compile File"
2. Integrated terminal pops up

### CMake Tools Log

[extension] [5395] cmake.compileFile started
[extension] [5395] cmake.compileFile finished (returned 
```json
    {
    "_proxy": {},
    "_disposed": false,
    "_queuedRequests": [],
    "_idPromise": {},
    "_creationOptions": {
        "name": "File Compilation",
        "cwd": "E:/build/cmake2/Debug",
        "env": {
            "ALLUSERSPROFILE": "C:\\ProgramData",
            "AMD_ENTRYPOINT": "vs/workbench/services/extensions/node/extensionHostProcess",
            "ANDROID_HOME": "E:\\android-sdk-windows",
            "APPDATA": "C:\\Users\\poroshok\\AppData\\Roaming",
            "APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL": "true",
            "ASL.LOG": "Destination=file",
            "BUILD_ROOT": "e:\\project",
            "BUILD_TOOLS_OUTDIR": "e:\\bin\\debug_web",
            "CHOCOLATEYINSTALL": "C:\\ProgramData\\chocolatey",
            "CHOCOLATEYLASTPATHUPDATE": "Чт сен  8 17:45:26 2016",
            "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
            "COMMONPROGRAMFILES(X86)": "C:\\Program Files (x86)\\Common Files",
            "COMMONPROGRAMW6432": "C:\\Program Files\\Common Files",
            "COMPOSE_CONVERT_WINDOWS_PATHS": "true",
            "COMPUTERNAME": "BOO",
            "COMSPEC": "C:\\windows\\system32\\cmd.exe",
            "CONFIGSETROOT": "C:\\windows\\ConfigSetRoot",
            "DOCKER_CERT_PATH": "C:\\Users\\poroshok\\.docker\\machine\\machines\\default",
            "DOCKER_HOST": "tcp://192.168.99.102:2376",
            "DOCKER_MACHINE_NAME": "default",
            "DOCKER_TLS_VERIFY": "1",
            "DOCKER_TOOLBOX_INSTALL_PATH": "C:\\Program Files\\Docker Toolbox",
            "DXSDK_DIR": "C:\\Program Files (x86)\\Microsoft DirectX SDK (February 2010)\\",
            "ELECTRON_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_29276_WNTXKAOQWNSDOEQA",
            "ELECTRON_RUN_AS_NODE": "1",
            "FP_NO_HOST_CHECK": "NO",
            "GENICAM_CACHE_V2_3": "C:\\Users\\poroshok",
            "GENICAM_LOG_CONFIG_V2_0": "C:\\Program Files\\IMI Tech\\Neptune\\GeniCam",
            "GENICAM_ROOT_V2_3": "C:\\Program Files\\IMI Tech\\Neptune\\Genicam",
            "GETTEXTCLDRDIR": "C:\\Program Files\\gettext-iconv\\lib\\gettext",
            "GOPATH": "C:\\Users\\poroshok\\go",
            "GOROOT": "C:\\Go\\",
            "HOMEDRIVE": "C:",
            "HOMEPATH": "\\Users\\poroshok",
            "INTELMEDIASDK_DSHOWBASECLASSES_PATH": "C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Samples\\Multimedia\\DirectShow\\BaseClasses",
            "INTELMEDIASDK_WINSDK_PATH": "C:\\Program Files (x86)\\Windows Kits\\8.0",
            "INTEL_LICENSE_FILE": "C:\\Program Files (x86)\\Common Files\\Intel\\Licenses",
            "JAVA_HOME": "C:\\Program Files\\Java\\jdk1.8.0_111",
            "LOCALAPPDATA": "C:\\Users\\poroshok\\AppData\\Local",
            "LOGONSERVER": "\\\\BOO",
            "NODE_PATH": "C:\\Users\\poroshok\\AppData\\Roaming\\npm\\node_modules",
            "NO_PROXY": "192.168.99.100,192.168.99.101,192.168.99.102",
            "NUMBER_OF_PROCESSORS": "8",
            "O2K_THIRD_PARTY_BUILD_ROOT": "E:\\project\\3rd_party_build",
            "O2K_THIRD_PARTY_DIR": "E:\\project\\3rd_party",
            "OS": "Windows_NT",
            "PATH": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\VC\\VCPackages;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\MSBuild\\15.0\\bin\\Roslyn;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Team Tools\\Performance Tools\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Team Tools\\Performance Tools;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6.1 Tools\\x64\\;C:\\Program Files (x86)\\HTML Help Workshop;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\\\MSBuild\\15.0\\bin;C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\Tools\\;C:\\windows\\system32;C:\\Program Files\\nodejs;C:\\Program Files\\Git\\bin;C:\\Program Files\\gettext-iconv\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\Collaborator Client;C:\\Program Files (x86)\\q264\\;C:\\Users\\poroshok\\AppData\\Local\\atom\\bin;C:\\Users\\poroshok\\AppData\\Local\\Yarn\\bin;C:\\Users\\poroshok\\AppData\\Local\\Pandoc\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\poroshok\\AppData\\Local\\hyper\\app-2.0.0\\resources\\bin;C:\\Program Files\\CMake\\bin;C:\\Program Files\\Docker Toolbox;C:\\Users\\poroshok\\go\\bin;C:\\Users\\poroshok\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja",
            "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PL",
            "PIPE_LOGGING": "true",
            "PROCESSOR_ARCHITECTURE": "AMD64",
            "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 42 Stepping 7, GenuineIntel",
            "PROCESSOR_LEVEL": "6",
            "PROCESSOR_REVISION": "2a07",
            "PROGRAMDATA": "C:\\ProgramData",
            "PROGRAMFILES": "C:\\Program Files",
            "PROGRAMFILES(X86)": "C:\\Program Files (x86)",
            "PROGRAMW6432": "C:\\Program Files",
            "PSMODULEPATH": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
            "PUBLIC": "C:\\Users\\Public",
            "RANDFILE": "C:\\Program Files (x86)\\NTP\\etc\\.rnd",
            "SESSIONNAME": "Console",
            "SYSTEMDRIVE": "C:",
            "SYSTEMROOT": "C:\\windows",
            "TEMP": "C:\\Users\\poroshok\\AppData\\Local\\Temp",
            "THIRD_PARTY_BUILD_ROOT": "e:\\project\\3rd_party_build",
            "TMP": "C:\\Users\\poroshok\\AppData\\Local\\Temp",
            "ULTRAMON_LANGDIR": "C:\\Program Files\\UltraMon\\Resources\\en",
            "USERDOMAIN": "BOO",
            "USERNAME": "poroshok",
            "USERPROFILE": "C:\\Users\\poroshok",
            "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox\\",
            "VERBOSE_LOGGING": "true",
            "VP_PATH": "C:\\Program Files (x86)\\Nexus\\Nexus Common",
            "VS110COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\",
            "VS120COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\",
            "VS140COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
            "VS150COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\Tools",
            "VSCODE_CWD": "C:\\Program Files\\Microsoft VS Code",
            "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
            "VSCODE_IPC_HOOK": "\\\\.\\pipe\\a74fc8b6ce1ff38bcec2a37f8b39cfdf-1.41.0-main-sock",
            "VSCODE_IPC_HOOK_EXTHOST": "\\\\.\\pipe\\vscode-ipc-df4c5aca-5802-4ee3-bc9c-7173579a2fa1-sock",
            "VSCODE_LOGS": "C:\\Users\\poroshok\\AppData\\Roaming\\Code\\logs\\20191128T115234",
            "VSCODE_LOG_STACK": "false",
            "VSCODE_NLS_CONFIG": "{\"locale\":\"en\",\"availableLanguages\":{},\"_languagePackSupport\":true}",
            "VSCODE_NODE_CACHED_DATA_DIR": "C:\\Users\\poroshok\\AppData\\Roaming\\Code\\CachedData\\9579eda04fdb3a9bba2750f15193e5fafe16b959",
            "VSCODE_PID": "29276",
            "VSSDK110INSTALL": "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VSSDK\\",
            "VSSDK120INSTALL": "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VSSDK\\",
            "WINDIR": "C:\\windows",
            "CL": "",
            "_CL_": "",
            "INCLUDE": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\include;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\include;C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\winrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\cppwinrt",
            "LIBPATH": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\lib\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x86\\store\\references;C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.17763.0;C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.17763.0;C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319;",
            "LINK": "",
            "_LINK_": "",
            "LIB": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\lib\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\ucrt\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64;",
            "FRAMEWORKDIR": "C:\\windows\\Microsoft.NET\\Framework64\\",
            "FRAMEWORKDIR64": "C:\\windows\\Microsoft.NET\\Framework64",
            "FRAMEWORKVERSION": "v4.0.30319",
            "FRAMEWORKVERSION64": "v4.0.30319",
            "UCRTCONTEXTROOT": "",
            "UCRTVERSION": "10.0.17763.0",
            "UNIVERSALCRTSDKDIR": "C:\\Program Files (x86)\\Windows Kits\\10\\",
            "VCINSTALLDIR": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\",
            "VCTARGETSPATH": "",
            "WINDOWSLIBPATH": "C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.17763.0;C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.17763.0",
            "WINDOWSSDKDIR": "C:\\Program Files (x86)\\Windows Kits\\10\\",
            "WINDOWSSDKLIBVERSION": "10.0.17763.0\\",
            "WINDOWSSDKVERSION": "10.0.17763.0\\",
            "VISUALSTUDIOVERSION": "15.0",
            "CC": "cl.exe",
            "CXX": "cl.exe"
        },
        "shellPath": "cmd.exe"
    },
    "_name": "File Compilation",
    "isOpen": true,
    "_pidPromise": {},
    "_id": 1,
    "_cols": 162,
    "_rows": 28
}
```
)

### Developer Tools Log

I've also traced started processes with `procmon` during that file compilation:

```
13:24:02,5156459	cmake.exe	12472	Process Start		SUCCESS	Parent PID: 20412, Command line: "C:\Program Files\CMake\bin\cmake.exe" --version, Current directory: C:\Program Files\Microsoft VS Code\
13:24:02,5186619	conhost.exe	35692	Process Start		SUCCESS	Parent PID: 652, Command line: \??\C:\windows\system32\conhost.exe "-1621102362335767873-15184416271228987098167250030-348826973-8352161251908273495", Current directory: C:\windows\system32\
13:24:02,8125837	cmake.exe	39052	Process Start		SUCCESS	Parent PID: 20412, Command line: "C:\Program Files\CMake\bin\cmake.exe" --version, Current directory: C:\Program Files\Microsoft VS Code\
13:24:02,8154430	conhost.exe	29908	Process Start		SUCCESS	Parent PID: 652, Command line: \??\C:\windows\system32\conhost.exe "-1897540264-1143090993248989531-202532132111032889701004431786895323137-1605210701", Current directory: C:\windows\system32\
13:24:03,1161106	winpty-agent.exe	27152	Process Start		SUCCESS	Parent PID: 16000, Command line: "\\?\c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-16000-1-1d5b19f710149b9-f8cd7730aaf9f5dd0549a226a636025a 0 1 80 24, Current directory: C:\Program Files\Microsoft VS Code\
13:24:03,1196603	conhost.exe	62876	Process Start		SUCCESS	Parent PID: 652, Command line: \??\C:\windows\system32\conhost.exe "1029523432192468600-8788334182405298211291800669-236508831429064534-1889664096", Current directory: C:\windows\system32\
13:24:03,1863988	cmd.exe	55232	Process Start		SUCCESS	Parent PID: 27152, Command line: cmd.exe, Current directory: E:\build\cmake2\Debug\
```

### Platform and Versions

- **Operating System**: Windows 7
- **CMake Version**: 3.12.0
- **VSCode Version**: 1.41.0 (also experienced in previous versions)
- **CMake Tools Extension Version**: 1.2.3 (also experienced in previous versions)
- **Compiler/Toolchain**: Visual C++ 2017, Ninja

**Comment by andreeis** [comment] 2020-01-24 20:24
Thank you for reporting this issue. I am not able to reproduce the problem. Let's find what is special in your scenario that is triggering the popup.
Can you share a standalone repro with us?
Could you be hitting this other known bug? https://github.com/microsoft/vscode-cmake-tools/issues/969

**Comment by bad-ed** [comment] 2020-01-29 10:05
Tested it with the simplest project.
`CMakeLists.txt`:
```CMake
project(bugtest CXX)
cmake_minimum_required(VERSION 3.12)

add_executable(bugtest main.cpp)
```
`main.cpp`:
```c++
int main() {}
```

And it does work, really!
As for suspected bug #969: I cannot find definitions with quoted text in real project's `CMakeLists.txt` files

**Comment by bad-ed** [comment] 2020-01-29 10:12
However, I've found stuff like this (escaped double quotes) in our CMakeLists:
```CMake
set(analyze_flags "/analyze /analyze:ruleset \"${PROJECT_SOURCE_DIR}/Common/common.ruleset\"")
```
Or this (quotes in comments):
```CMake
string(CONCAT MSVC_WARNING_FLAGS
	"/wd4464 " # relative include path contains '..'
	"/wd4668 " # 'x' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
	"/wd4100 " # unreferenced formal parameter
	"/wd4355 " # 'this': used in base member initializer list
)
```

**Comment by KoeMai** [comment] 2020-01-29 11:53
The action `Compile Active File` use the build instruction from cmake provided compilation database (`compile_commands.json` ). Does the file builds successful when the command from conpilation database is used on commandline?

**Comment by bad-ed** [comment] 2020-01-29 12:04
I am not able to paste command line from "compile_commands.json" into vscode's integrated terminal.
However command works fine in "x64 Native Tools Command Prompt for VS 2017".

**Comment by bad-ed** [comment] 2020-01-29 12:32
Seems like this bug happens when command string is too long. I've created CMake file to reproduce this bug:
```CMake
project(bugtest CXX)
cmake_minimum_required(VERSION 3.12)
set(spam "-DS")
set(repeated_spam "")
foreach(i RANGE 0 200) # change this to something like 300 and higher, and compile active file will stop working
	string(APPEND repeated_spam " ${spam}")
endforeach()
string(APPEND CMAKE_CXX_FLAGS
	" ${repeated_spam}"
)
add_executable(bugtest main.cpp)
```

**Comment by andreeis** [comment] 2020-04-02 04:04
Duplicate of 605 and 969.

**Closed by andreeis** 2020-04-02 04:04 UTC
Labels: Feature: build, bug, duplicate
