### ISSUE TITLE
configure vscode to include CMakeLists.txt file of multiple sub-project

### ISSUE THREAD

**Issue by atifkarim** [microsoft/vscode-cmake-tools#2742] opened 2022-09-12 18:40 UTC
I would like to configure correctly project's `settings.json` file to use `CMakeLists.txt` file of multiple sub-project.

##### My approach is given below

The structure of the project is as like as follows.
```cpp
vscode_build_cmake/
`-- task
    |-- add
    |   |-- CMakeLists.txt
    |   |-- include
    |   |   `-- foo.h
    |   `-- src
    |       |-- foo.cpp
    |       `-- main.cpp
    `-- print
        |-- CMakeLists.txt
        |-- include
        |   `-- foo.h
        `-- src
            |-- foo.cpp
            `-- main.cpp
```

Here, `add` & `print` are completely isolated sub-project of the main project `task`. Each sub-project has their own build recipe which is written in their own `CMakeLists.txt` file. Usual steps to build sub-project is :

```sh
cd task/add
mkdir build
cd build
cmake .. && make
```

Same steps is for `task/print`.

Right now I would like to perform this `build task` using VSCode Cmake tool. What I have found that I only need to make a `vscode_build_cmake/.vscode/settings.json` file where I can point to the directory of `CMakeLists.txt` file. I am now working with 

```xml
{
    "cmake.configureOnOpen": false,
    "cmake.sourceDirectory": "${workspaceFolder}/task/add"
}
```

I just press `ctrl+shift+p` and write in the command box `run build task` and press `Enter`. That one do the job for me and I can see `build, bin, lib` directories inside `task/add` directory.

But the problem, I am facing now is that if I need to build `print` sub-project I have to manually edit the `settings.json` file as like as follows

```xml
{
    "cmake.configureOnOpen": false,
    "cmake.sourceDirectory": "${workspaceFolder}/task/print"
}
```
After that, I have to `delete cache and reconfigure` and `build task` which perform now the build task only for `print` project. This one is very tedious to me.

#### My desire is to know
- Is there any way to point out the both `CMakeLists.txt` file of `add` and `print` in `cmake.sourceDirectory`? Which can tell me which build task I would like to perform? Eg:
```xml
{
    "cmake.configureOnOpen": false,
    "cmake.sourceDirectory": ["${workspaceFolder}/task/add", "${workspaceFolder}/task/print"]
}
```

Or ,

- Is there any way to perform build task of both sub-project.(this one is optional. Previous one is important for my case).

**Comment by elahehrashedi** [comment] 2022-09-13 19:53
Currently, in order to have multiple `sourceDirectory`s, you need to create a multi-root project and set up every project in its own root. You will need to have a copy of `settings.json` in every root as well. Using this approach, you don't need to change the `settings.json` for every build.

However, having multiple CMake projects in the same folder is a requested feature that is being followed here:  https://github.com/microsoft/vscode-cmake-tools/issues/1374. I will mark this as a duplicate of that feature request.

**Comment by bobbrow** [comment] 2022-09-14 22:02
This feature request is covered by #1374.

**Closed by bobbrow** 2022-09-14 22:02 UTC
Labels: duplicate
