### ISSUE TITLE
FIXED: Unable to resolve cmake-tools-schema:/schemas...

### ISSUE THREAD

**Issue by aremmell** [microsoft/vscode-cmake-tools#3108] opened 2023-04-12 11:27 UTC
I have reproduced this, and through sheer stubbornness, finally figured it out.

You're passing the *location* for the schema JSON files to `vscode.Url.file`, which VS Code internally translates as a path on disk. And it's the wrong path.

Unfortunately, sometimes a path like, `folder/and/another1` doesn't always mean "relative to my current working directory–but `./folder/and/another1` does.

I found the rogue path construction code in `dist/main.js` (around line 50080), and as you can see by the attached screenshot, all I've done is add `./` in front of the paths, and everything's working fine now.

You do also need to empty `CMakePresets.json, and then invoke the "Delete Cache" / "Reset Extension State" actions from the command palette. Then quit VS code, restart it, and it should be gtg.

I am  not 100% sure this applies to locales that exist and have a separate path constructed, so you'll want to check that too.

Please re-open and fix this one! It's difficult to navigate the JSON without a schema to help you along.

Thanks for listening, and thanks for the cool extension.

<img width="715" alt="Screenshot 2023-04-12 at 04 55 28" src="https://user-images.githubusercontent.com/812759/231443369-f347451c-d371-430b-96f2-4d16c2e94937.png">

**Comment by xisui-MSFT** [comment] 2023-04-25 20:45
@gcampbell-msft This is affecting us too. Looks like can be fixed easily though, can you help?

**Comment by bobbrow** [comment] 2023-04-25 21:28
I am prepping a PR for it.  Duplicate of #2587.  Thank you for locating the problem @aremmell!

**Closed** 2023-04-26 17:52 UTC
Labels: bug
