### ISSUE TITLE
Cannot check the current "Build Target" in the "Project Status".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-cmake-tools#3088] opened 2023-03-29 11:28 UTC
### Brief Issue Summary

After upgrading to `v1.14.21`, the buttons displayed in the status button are moved to "Project Status". However, I found that we cannot check the current **"Build Target"** in the **"Project Status"**.

![image](https://user-images.githubusercontent.com/71438617/228521160-9ee13f04-605a-4127-a304-fefb72fe058d.png)

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.76.2",
  "cmtVersion": "1.14.21",
  "configurations": [
    {
      "folder": "d:\\Code\\Cpp\\Qt-Examples",
      "cmakeVersion": "3.25.1",
      "configured": true,
      "generator": "Ninja Multi-Config",
      "usesPresets": true,
      "compilers": {
        "C": "cl.exe",
        "CXX": "cl.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug",
      "Release",
      "RelWithDebInfo"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

**Comment by hwhsu1231** [comment] 2023-03-29 17:52
Besides, I noticed that in "Project Status":

* **"Configure"** takes the **"displayName"** field of configurePreset.
* **"Build"** takes the **"name"** field of buildPreset.

I wondered whether cmake-tools should take the same field for both configurePresets and buildPresets? (That is **"displayName"**)

![image](https://user-images.githubusercontent.com/71438617/228625270-2a35e35c-de0a-40e0-a595-99c9af034864.png)

**Comment by snehara99** [comment] 2023-07-12 18:09
Hi @hwhsu1231, can you see if the issue is fixed with the latest release please?

**Comment by hwhsu1231** [comment] 2023-07-12 18:51
Still not see the "Build Target" in the Project Status View, even though I select the Build Target after executing the `CMake: Set Build Target` command:

<details><summary>Click to expand Log Diagnostics</summary>

```json
{
  "os": "win32",
  "vscodeVersion": "1.80.0",
  "cmtVersion": "1.15.19",
  "configurations": [
    {
      "folder": "d:\\Code\\Cpp\\Qt-Examples",
      "cmakeVersion": "3.26.4",
      "configured": true,
      "generator": "Visual Studio 16 2019",
      "usesPresets": true,
      "compilers": {
        "C": "cl.exe",
        "CXX": "cl.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug",
      "Release",
      "MinSizeRel",
      "RelWithDebInfo"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 40,
    "executablesCount": 29,
    "librariesCount": 1,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

</details>

![image](https://github.com/microsoft/vscode-cmake-tools/assets/71438617/720e4e1a-c1a3-4034-bf26-96903b95c946)

**Comment by snehara99** [comment] 2023-07-12 21:46
Thanks for the info. The build target does seem to be set as `Build - Debug`. Were you trying to set a different target?

**Comment by snehara99** [comment] 2023-07-12 22:43
Oh I see the issue sorry, it is that `Debug` and `Launch` targets don't match the `Build` target and cannot be selected either, correct?

**Comment by hwhsu1231** [comment] 2023-07-14 18:26
> Oh I see the issue sorry, it is that `Debug` and `Launch` targets cannot be selected, correct?

No, the situation is as follows:

* `Debug`/`Launch`/`Build` targets can be selected by Command Palette
* `Debug` and `Launch` targets can show up in the "Project Status" View
* But only `Build` target **cannot** show up in the "Project Status" View

**Comment by snehara99** [comment] 2023-07-14 19:09
Thanks for clarifying, I can reproduce the issue. I will look into adding an option for selecting the build target. In the meantime, you can select your build target in the `Project Outline` area or you can switch back to having the same options in the status bar in the settings.

**Comment by hwhsu1231** [comment] 2023-07-19 20:09
@snehara99 - It works!

![image](https://github.com/microsoft/vscode-cmake-tools/assets/71438617/7fe3a054-46ba-40aa-8218-42de4149ca56)

**Comment by gcampbell-msft** [comment] 2023-07-21 14:40
@hwhsu1231 Thanks for confirming! Closing this issue.

**Closed by gcampbell-msft** 2023-07-21 14:40 UTC
Labels: bug, Feature: UI
