### ISSUE TITLE
Support expanding kit environment variables in settings.json / launch.json

### ISSUE THREAD

**Issue by gvcallen** [microsoft/vscode-cmake-tools#1312] opened 2020-06-16 09:46 UTC
I believe, for many people, it will be useful to set environment variables for a kit e.g. under "cmake-tools-kits.json" and then to be able to expand this variable in the "settings.json" and "launch.json" files.

The environment variable substitution of "${env:VARNAME}" seems to only be for VS Code environment variables, as I have tried to expand one of my kit's variables but to no avail.

This is a general request and I think it would be very useful feature.

**Comment by bobbrow** [comment] 2020-06-22 17:10
I believe this is a duplicate of feature request: #1250

**Closed by bobbrow** 2020-06-22 17:10 UTC
