### ISSUE TITLE
No compile_commands.json in workspace folder

### ISSUE THREAD

**Issue by thunderstorm010** [microsoft/vscode-cmake-tools#1887] opened 2021-05-19 09:33 UTC
I can't see a compile_commands.json file in my workspace. Where is it located?

**Comment by andreeis** [comment] 2021-05-19 15:32
It should be generated in the build folder. Note that not all generators create one. VS doesn't, Ninja does. What generator do you use?

**Comment by thunderstorm010** [comment] 2021-05-19 16:08
I use Ninja, but I can't find a compile_commands.json file in my directory structure even after I build it.

**Comment by andreeis** [comment] 2021-05-19 19:13
Set "cmake.loggingLevel" to "Debug" in your .vscode/settings.json and share with us the content of the "CMake/Build" output channel after you configure your project.
The setting "cmake.exportCompileCommandsFile" normally defaults to "true", maybe you have set it to false somewhere that gets inherited (like from the user settings)? Double check on that, even set it to true explicitly just in case (although again, it defaults to true, so most probably it won't matter).

**Comment by thunderstorm010** [comment] 2021-05-19 20:51
CMake/Build
```
[main] Safe constructing new CMakeTools instance
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[variant] Loaded new set of variants
[main] CMakeTools instance initialization complete.
[kit] Reading kits file C:\Users\crypto\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 8 kits from C:\Users\crypto\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Not reading non-existent kits file: c:\Users\crypto\Desktop\New folder\MonoLoader\.vscode\cmake-kits.json
[presetController] Reading presets file c:\Users\crypto\Desktop\New folder\MonoLoader\CMakePresets.json
[presetController] Successfully validated presets in c:\Users\crypto\Desktop\New folder\MonoLoader\CMakePresets.json
[main] Resolving the selected configure preset
[main] Starting new CMake driver
[main] Starting CMake driver
[main] Using generator from user configuration: Ninja
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using preset
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[driver] Setting new variant Debug
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[driver] No build preset selected
[main] Loading new configure preset into CMake driver
[driver] Switching to configure preset: Quest
[driver] CMakeDriver configure preset set to Quest
[main] Resolving the selected build preset
[main] Loading new build preset into CMake driver
[driver] Switching to build preset: Quest
[driver] CMakeDriver build preset set to Quest
[extension] Configuring workspace on open file:///c%3A/Users/crypto/Desktop/New%20folder/MonoLoader
[main] Configuring folder: MonoLoader 
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[driver] Start configure 
[driver] Runnnig pre-configure checks and steps
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[cmakefileapi-driver] Configuring using preset
[cmakefileapi-driver] Invoking CMake C:\Program Files\CMake\bin\cmake.EXE with arguments ["-DCMAKE_BUILD_TYPE=Debug","-DCMAKE_TOOLCHAIN_FILE=Q:/android-ndk-r22b/build/cmake/android.toolchain.cmake","-DANDROID_ABI=arm64-v8a","-DCMAKE_POSITION_INDEPENDENT_CODE=OFF","-DANDROID_NATIVE_API_LEVEL=24","-DANDROID_TOOLCHAIN=clang","-Hc:/Users/crypto/Desktop/New folder/MonoLoader","-Bc:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest","-G","Ninja"]
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=Q:/android-ndk-r22b/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DCMAKE_POSITION_INDEPENDENT_CODE=OFF -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_TOOLCHAIN=clang "-Hc:/Users/crypto/Desktop/New folder/MonoLoader" "-Bc:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest" -G Ninja
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: C:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest
[cmakefileapi-parser] Read reply folder: c:\Users\crypto\Desktop\New folder\MonoLoader\build\Quest\.cmake\api\v1\reply
[cmakefileapi-parser] Found index files: ["cache-v2-6a01bfe966becdfb9bb0.json","codemodel-v2-cc44a870ef63918efa14.json","index-2021-05-19T20-48-45-0342.json","target-monoloader-Debug-d4321d185817385889a7.json","toolchains-v1-9d08ae840bab1ffd8b5d.json"]
[cache] Reading CMake cache file c:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest/CMakeCache.txt
[cache] Parsing CMake cache string
[cache] Reading CMake cache file c:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest/CMakeCache.txt
[cache] Parsing CMake cache string
```
I've set the cmake.exportCompileCommandsFile both globally and in the workspace but still can't find compile_commands.json in my workspace structure. I'ven't set a specific option that disables the creation of compile_commands.json file in my presets file.

**Comment by andreeis** [comment] 2021-05-19 21:04
Oh, I forgot to double check whether this is with presets on or off. I think this is a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/1835. Reopen if I am mistaken.

You need to define the compile commands setting as a cache variable in the configure preset that you use: 
"cacheVariables": {
"CMAKE_EXPORT_COMPILE_COMMANDS": "ON"
}

Let us know how this works.

**Closed by andreeis** 2021-05-19 21:04 UTC
Labels: Feature: configure, question
