### ISSUE TITLE
Bug: `"${config:cmake.buildDirectory}/compile_commands.json"` not parsed properly

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-cmake-tools#4065] opened 2024-09-14 13:48 UTC
### Brief Issue Summary

With this config:

```json
{
    "version": 8,
    "$schema": "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json",
    "configurePresets": [
        {
            "name": "Debug",
            "displayName": "Debug: GCC 9.4.0 x86_64-linux-gnu",
            "description": "Using compilers: C = /usr/bin/gcc, CXX = /usr/bin/g++",
            "binaryDir": "${sourceDir}/build/${presetName}",
            "cacheVariables": {
                "CMAKE_RUNTIME_OUTPUT_DIRECTORY": "${sourceDir}/bin",
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/build/install/${presetName}",
                "CMAKE_C_COMPILER": "/usr/bin/gcc",
                "CMAKE_BUILD_TYPE": "Debug",
                "CMAKE_C_STANDARD": "90",
                "CMAKE_C_STANDARD_REQUIRED": "TRUE",
                "CMAKE_EXPORT_COMPILE_COMMANDS": "YES"
            }
        }
    ],
    "buildPresets": [
        {
            "name": "Debug helloworld app",
            "displayName": "Debug helloworld",
            "configurePreset": "Debug",
            "targets": [
                "helloworld"
            ]
        }
    ]
}
```

and this `c_cpp_properties.json` config:

```json
{
    "configurations": [
        {
            "name": "CMake as IntelliSense provider",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c99",
            "intelliSenseMode": "linux-gcc-x64",
            "compileCommands": "${config:cmake.buildDirectory}/compile_commands.json",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

The `"compileCommands": "${config:cmake.buildDirectory}/compile_commands.json"` is not finding the proper `"binaryDir": "${sourceDir}/build/${presetName}",` as defined in the CMakePresets.

![image](https://github.com/user-attachments/assets/89d35e3f-a860-4b03-9afc-9b79e50b0959)

### CMake Tools Diagnostics

```json
{
  "os": "linux",
  "vscodeVersion": "1.93.0",
  "cmtVersion": "1.19.51",
  "configurations": [
    {
      "folder": "/home/tobias/code/c-test",
      "cmakeVersion": "3.30.2",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": true,
      "compilers": {
        "C": "/usr/bin/gcc"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///home/tobias/code/c-test/src/main.c"
    ],
    "responses": [
      {
        "uri": "file:///home/tobias/code/c-test/src/main.c",
        "configuration": {
          "includePath": [],
          "defines": [],
          "compilerPath": "/usr/bin/gcc",
          "compilerArgs": [],
          "compilerFragments": [
            "-g -std=gnu90"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "helloworld",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by v-frankwang** [comment] 2024-09-20 08:18
@gcampbell-msft We have reproduced the issue using the information provided by the user, here are the steps to reproduce it:
ENV：
CMake Tools: v1.20.9(pre-release)
vscode: v1.93.1
c/c++: v1.21.6
Repro steps：

1. Create a folder and open it with vscode
2. Add a file named **main.cpp** and add the  Add a file named **CMakeLists.txt** and add the following code:
```
cmake_minimum_required(VERSION 3.5.0)
project(Helloworld)
add_executable(Helloworld main.cpp)
```
6. Add a file named **CMakePresets.json** and add the following code:
```
{
    "version": 8,
    "$schema": "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json",
    "configurePresets": [
        {
            "name": "Debug",
            "displayName": "Debug: GCC 9.4.0 x86_64-linux-gnu",
            "description": "Using compilers: C = /usr/bin/gcc, CXX = /usr/bin/g++",
            "binaryDir": "${sourceDir}/build/${presetName}",
            "cacheVariables": {
                "CMAKE_RUNTIME_OUTPUT_DIRECTORY": "${sourceDir}/bin",
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/build/install/${presetName}",
                "CMAKE_C_COMPILER": "/usr/bin/gcc",
                "CMAKE_BUILD_TYPE": "Debug",
                "CMAKE_C_STANDARD": "90",
                "CMAKE_C_STANDARD_REQUIRED": "TRUE",
                "CMAKE_EXPORT_COMPILE_COMMANDS": "YES"
            }
        }
    ],
    "buildPresets": [
        {
            "name": "Debug helloworld app",
            "displayName": "Debug helloworld",
            "configurePreset": "Debug",
            "targets": [
                "helloworld"
            ]
        }
    ]
}
```
8. Add a file named **c_cpp_properties.json** and add the following code:
```
{
    "configurations": [
        {
            "name": "CMake as IntelliSense provider",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c99",
            "intelliSenseMode": "linux-gcc-x64",
            "compileCommands": "${config:cmake.buildDirectory}/compile_commands.json",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

10. Run the CMake:Configure command.
11. Open c_cpp_properties.json and mouse over the line labeled “compileCommands”.

![image](https://github.com/user-attachments/assets/6998d66b-b862-4b9e-8432-40a52027589d)

[CMake Tools Diagnostics.txt](https://github.com/user-attachments/files/17072128/CMake.Tools.Diagnostics.txt)

**Comment by gcampbell-msft** [comment] 2024-10-02 11:28
@thernstig This is primarily because of the fact that the `cmake.buildDirectory` setting is primarily used for Kits, and the `{config:cmake.buildDirectory}` only directly grabs the settings value from the settings store. 

To get the build directory that the extension is actually using from presets, you can use the `cmake.buildDirectory` command. This can be used in tasks like this `{command:cmake.buildDirectory}`. 

Unfortunately, I don't think that the c_cpp_properties file supports the `{command:<command>}` syntax. @sean-mcmanus Could you confirm?

**Comment by v-frankwang** [comment] 2024-10-12 02:56
@sean-mcmanus We need your help on this one, for this https://github.com/microsoft/vscode-cmake-tools/issues/4065#issuecomment-2388415210 hopefully I can get some advice from you!
@gcampbell-msft Users want to know if this question can be changed to a feature request?

**Comment by sean-mcmanus** [comment] 2024-10-12 03:05
@v-frankwang Yeahk, we don't support ${command} in c_cpp_properties.json. You could file a feature request. And it's possible the support could be added via our open source TypeScript.

**Comment by gcampbell-msft** [comment] 2024-10-14 11:14
@thernstig I'm going to close this, as from our side this is implemented and supported. If you want this feature, you'll need to create a feature request on the https://github.com/Microsoft/vscode-cpptools repository and if you're willing you could add the support yourself as @sean-mcmanus pointed out. 

Thanks!

**Closed by gcampbell-msft** 2024-10-14 11:14 UTC
Labels: bug, more info needed

**Comment by thernstig** [comment] 2024-10-14 15:17
@gcampbell-msft Thanks for the answer. I will create an issue on https://github.com/Microsoft/vscode-cpptools.

Just to make sure I understand when I describe the issue. 

The problem at hand is that the CMake extension lets one use many `configurePresets`. Each preset is chosen in the CMake sidebar. Each preset can have a different `"binaryDir": "${sourceDir}/build/${presetName}"`, which is how most would use it when building for various target systems e.g. Linux and Windows. The `compile_commands.json` would get put in this `binaryDir`.

To set `"compileCommands": "${config:cmake.buildDirectory}/compile_commands.json"` in `c_cpp_properties.json` there needs to be a way to get the path to `compile_commands.json` depending on the CMake preset used.

In what part of this chain is the vscode-cpptools missing a functionality to get this path?

I am asking because to me when writing it down like this it sounds to me to be a CMake extension thing, but since I do not know the inner details it would be good with some info about how to write this ticket and why it should go into the vscode-cpptools repo.

**Comment by thernstig** [comment] 2024-10-21 10:10
@gcampbell-msft would greatly appreciate a comment to the above, so I can write the issue properly.

**Comment by gcampbell-msft** [comment] 2024-10-21 16:32
@thernstig Thanks for the ping, yes you have everything right so far in your description. The key part of what you're missing is that you don't actually want to call `${config:cmake.buildDirectory}`, what you should be doing is `${command:cmake.buildDirectory}`. 

The reason this doesn't work currently, is because the vscode-cpptools doesn't support `${command:<name-of-command>}`. 

For this specific issue, the reason you want to do `${command:cmake.buildDirectory}` is becuase we have a command with that name that gets that information. If the cpptools extension supported command substitution, then this would work for you. 

Does that clear things up?

**Comment by thernstig** [comment] 2024-10-22 07:49
Makes perfect sense, thanks @gcampbell-msft!

**Comment by thernstig** [comment] 2024-10-24 10:54
Would it also not be problematic having `c_cpp_properties.json` try to list a `command`? At which point in time should it invoke the command? My gut feel is that a generally better approach overall would be that there was a `${file:cmake.compileCommands}` config that points to the `compile_commands.json` file, where it is a symlink to the real file. That way, the C/C++ extension could have a file watcher on this file and update whenever it changes when a CMake preset regenerates it (which at the same time CMake updates the symlink). That way IntelliSense would get refreshed each time a new preset is built.

**Comment by gcampbell-msft** [comment] 2024-10-24 16:45
@thernstig I don't disagree, I think you make good points. However, I think this will be up to the Cpptools extension, so I would paste that context into the issue you created there.
