### ISSUE TITLE
CMake Tools overwrites pre-existing build directory

### ISSUE THREAD

**Issue by spinicist** [microsoft/vscode-cmake-tools#1390] opened 2020-07-31 07:38 UTC
### Brief Issue Summary

If I initially configure a project externally, e.g. using `ccmake`, then the first time I run a configure & build with CMake Tools, the existing build directory is overwritten/cleared and the CMake Cache is empty.

If I initially run a configure with CMake Tools, then swap to `ccmake` to configure, and then back to CMake Tools, everything works.

I have a couple of projects that require specific configuration variables. I don't really want to add these to the CMake Tools settings, because they are project specific. Hence I need to be able to run either `cmake` or `ccmake` at least once to pass those variables in.

### Expected:

1. Configure project externally with `cmake` or `ccmake` in the same build directory that CMake Tools expects.
2. Use CMake Tools with VS Code

### Apparent Behavior:

1. Configure project externally with `cmake`
2. Switch to VS Code and try to build
3. CMake Tools deletes the existing cache and tries to configure the project
4. Configuration fails because of undefined variables

### CMake Tools Log

Not sure what to put here - it would be a standard Configuration log that fails with
```
[cmake] -- Configuring incomplete, errors occurred!
```
due to project specific missing variables etc.

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.17.2
- **VSCode Version**: 1.47.3 (This has been happening for a long time)
- **CMake Tools Extension Version**: v1.4.1
- **Compiler/Toolchain**: Apple Clang

**Comment by bobbrow** [comment] 2020-08-03 15:38
Possible duplicate of #1373

**Comment by spinicist** [comment] 2020-08-03 17:55
Hello @bobbrow, yes this very much looks like a duplicate of #1373. I missed that when looking through the issues. Feel free to close this one and I will join in watching on the other issue.

**Comment by bobbrow** [comment] 2020-08-03 18:15
Sounds good.  Thanks for confirming!

**Closed by bobbrow** 2020-08-03 18:15 UTC
Labels: Feature: configure, bug, duplicate
