### ISSUE TITLE
cmake-tools expects CMakeLists.txt in project root folder

### ISSUE THREAD

**Issue by andyinno** [microsoft/vscode-cmake-tools#510] opened 2018-08-06 10:04 UTC
### Brief Issue Summary

My scenario:
Using GPM (Git Project Manager) for opening a project root.
The Project root contains documentation, sources that compile with different tools (different target architecture) using different toolchain and software pieces.

When opening up the project cmake-tools complains that it cannot find a CMakeLists.txt file in the directory. I have to edit the preferences file and add the line:

    "cmake.sourceDirectory": "${workspaceRoot}/Src"

In order to compile the software.
In my opinion it would be nice if cmale-tools is not able to find a CMakeLists.txt file in the root directory to recursively try to find a CMakeLists.txt in any subfolder of the project. Then asks to the user which CMakeLists.txt to use.

As a plus feature if the extension can looks inside the CMakeLists.txt in order to find a Project directive it would allow to get only the main CMakeLists.txt that drives the compilation of all the sources.

The main case is:

Using CMake for cross compile the software that runs on a custom board with different microprocessors.
The software of the different microprocessors must be in sync so it is common to use a single git repository for the sources of the different processors.

The CMakeLists could be different as could be different the toolchain file used for cross compiling.

Allowing an easy to do configuration and switch between the toolchains and the main projects would be a great thing.

In any case I think that prompting for which CMakeLists.txt to use, if present in a sub folder, allow to better interact with other plugins.

would love to ear your comments 
thank you
Andrea

**Comment by vector-of-bool** [comment] 2018-08-14 05:02
Sorry for the late response. I've been busy for a few weeks.

This is entirely implementable, and can be useful to those with more complex project layouts. I'll take a look.

**Comment by cybik** [comment] 2018-11-30 15:43
Voting this up. My CMakeLists.txt is in a subdir 3 levels down from the root of the whole project (sources, resources and all). Using vscode requires a couple of hoops to jump through just to get it to compile my project.

**Comment by Zingam** [comment] 2019-02-16 15:39
https://github.com/vector-of-bool/vscode-cmake-tools/issues/533

**Comment by Zingam** [comment] 2019-02-16 19:04
If "cmake.sourceDirectory": "${workspaceRoot}/Src" the extension misbehaves. It won't configure the project automatically sometimes.

**Comment by aleksas** [comment] 2021-07-22 13:14
+1

**Comment by bobbrow** [comment] 2021-07-26 23:39
This feels somewhat like a duplicate of #533 which will be released with version 1.8 relatively soon.  If you want a sneak peek, you can download and install any of our daily builds from the [Build VSIX](https://github.com/microsoft/vscode-cmake-tools/actions/workflows/build-vsix.yml) workflow.

If there is something else that you would like to see as part of the startup experience, please let us know.

**Closed by bobbrow** 2021-07-26 23:39 UTC
Labels: Feature Request, Feature: configure
