### ISSUE TITLE
1.13.31 to 1.13.32 IntelliSense regression

### ISSUE THREAD

**Issue by atsju** [microsoft/vscode-cmake-tools#2922] opened 2023-01-05 08:53 UTC
### Brief Issue Summary

I'm using C/C++v1.13.9
Cmaketool broken from 1.13.31 to 1.13.32 by not providing IntelliSense anymore
I'm using `"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",`

good:
![image](https://user-images.githubusercontent.com/4628382/210735318-c0186786-0840-42db-9e55-84b17a381747.png)
bad:
![image](https://user-images.githubusercontent.com/4628382/210736292-bd5067f7-b859-45ec-8a11-151b65996222.png)
 The symbol `CB110_V0_DATA_LOGGER` is added with `add_compile_definitions()` in CMakeLists.txt

for information compile_commands.json is about 800 lines long

And there is also a new error message in "PROBLEMS" view: 
![image](https://user-images.githubusercontent.com/4628382/210739793-360e4474-191f-473c-b7f5-4398f318f16f.png)

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.74.2",
  "cmtVersion": "1.13.33",
  "configurations": [
    {
      "folder": "c:\\GIT\\A\\B",
      "cmakeVersion": "3.21.5",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[main] Saving open files before configure/build
[build] Starting build
[driver] Start build all
[proc] Executing command: C:\GIT\FW_Toolchain\cmake\bin\cmake.EXE --build c:/GIT/A/B/build_CB110_V0_DATA_LOGGER_Debug --config Debug --target all --
[proc]   with environment: {"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\me\\AppData\\Roaming","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"1","CHROME_CRASHPAD_PIPE_NAME":"\\\\.\\pipe\\LOCAL\\crashpad_8332_LYLKVNCGTCVIYJRI","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"name","ComSpec":"C:\\WINDOWS\\system32\\cmd.exe","CUDA_PATH":"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2","CUDA_PATH_V11_2":"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2","CUDA_PATH_V11_5":"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.5","curl_ca_bundle":"C:/_zscaler_cert/cacert_certifi_zscaler.crt","DEFLOGDIR":"C:\\ProgramData\\McAfee\\Endpoint Security\\Logs","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","ELECTRON_RUN_AS_NODE":"1","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","FPS_BROWSER_USER_PROFILE_STRING":"Default","FW_TOOLCHAIN":"C:\\GIT\\FW_Toolchain","HOME":"C:\\Users\\me","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\me","NUMBER_OF_PROCESSORS":"12","NVCUDASAMPLES11_2_ROOT":"C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v11.2","NVCUDASAMPLES11_5_ROOT":"C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v11.5","NVCUDASAMPLES_ROOT":"C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v11.2","NVTOOLSEXT_PATH":"C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\","OneDrive":"C:\\Users\\me\\OneDrive - Schneider Electric","OneDriveCommercial":"C:\\Users\\me\\OneDrive - Schneider Electric","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","Path":"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\libnvvp;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Windows Imaging\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PuTTY\\;C:\\Program Files (x86)\\STMicroelectronics\\STM32 ST-LINK Utility\\ST-LINK Utility;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2020.3.1\\;C:\\Program Files\\otii;C:\\Program Files\\dotnet\\;C:\\Program Files\\1E\\Client\\Extensibility\\NomadBranch;C:\\Users\\me\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\\Users\\me\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\me\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\GIT\\FW_Toolchain\\GNU Tools ARM Embedded\\10.3-2021.10\\bin;C:\\GIT\\FW_Toolchain\\Utils;C:\\GIT\\FW_Toolchain\\cmake\\bin;C:\\Program Files (x86)\\GitHub CLI\\;C:\\Users\\me\\OneDrive - Schneider Electric\\Documents\\Dossier personnel\\memoiresPepe\\poppler-0.68.0\\bin;C:\\Program Files\\SEGGER\\JLink;C:\\Users\\me\\AppData\\Local\\Box\\Box Edit\\;C:\\GIT\\FW_Toolchain\\GNU Tools ARM Embedded\\10.3-2021.10\\bin","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"Intel64 Family 6 Model 165 Stepping 2, GenuineIntel","PROCESSOR_LEVEL":"6","PROCESSOR_REVISION":"a502","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft Azure Information Protection\\Powershell","PUBLIC":"C:\\Users\\Public","SESSIONNAME":"Console","USERDOMAIN":"EUR","USERDOMAIN_ROAMINGPROFILE":"EUR","USERNAME":"ME","USERPROFILE":"C:\\Users\\me","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_CODE_CACHE_PATH":"C:\\Users\\me\\AppData\\Roaming\\Code\\CachedData\\e8a3071ea4344d9d48ef8a4df2c097372b0c5161","VSCODE_CWD":"C:\\Users\\me\\AppData\\Local\\Programs\\Microsoft VS Code","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_IPC_HOOK":"\\\\.\\pipe\\772aa4370665abc4805ac2a019148514-1.74.2-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_PID":"8332","windir":"C:\\WINDOWS","ZES_ENABLE_SYSMAN":"1","__PSLockDownPolicy":"0","NINJA_STATUS":"[%s/%t %p :: %e] "}

//stripped build part

[build] ------------------------------------------------------------------------------
[cmakefileapi-parser] Read reply folder: c:\GIT\A\B\build_CB110_V0_DATA_LOGGER_Debug\.cmake\api\v1\reply
[cmakefileapi-parser] Found index files: ["cache-v2-d52b3a89bcec7457c7cb.json","cmakeFiles-v1-40999a0c2ab4a8400bee.json","codemodel-v2-942e6adb4d7dceac23ee.json","directory-.-Debug-d0094a50bb2071803777.json","directory-01_application-Debug-8d3af0683a151226b0c6.json","directory-02_service-Debug-71528b3999e0a67554f2.json","directory-03_support-Debug-c038b83607a4d4e8237e.json","directory-04_driver-Debug-dc3b773d885f8861ffbe.json","directory-05_MAL-Debug-444b54aaff545198b639.json","index-2023-01-05T08-36-20-0884.json","target-alwaysGetGitSha-Debug-1e283d7bdb73991ddc16.json","target-app_customer_app-Debug-848a648a85836bc45aea.json","target-app_data_logger-Debug-bef072ae799272d4f044.json","target-CB110_V0_DATA_LOGGER.axf-Debug-53a51bc0be17676708b9.json","target-cmsis_math-Debug-c2575ef6633a8b244bc4.json","target-do_always-Debug-6473fd25726f951e8fc5.json","target-drv_ADC-Debug-ee86ea10f07adfdb2bdf.json","target-drv_adxl372-Debug-001a1a86033e602ccbe1.json","target-drv_cryotimer-Debug-aae47033f6e391900207.json","target-drv_flashCounter-Debug-d2c068240d3cfe75bff4.json","target-drv_kx13x-Debug-43e90ab422d45738ff22.json","target-drv_RTCC-Debug-c444d8d24ea7b1b84c10.json","target-drv_RTT-Debug-3a0f6d47cb5433ad7a57.json","target-drv_SHTC3-Debug-99f2d0eb41f29800034a.json","target-klocwork-Debug-676bd3c659e8eacb3997.json","target-mal_adc-Debug-98d179d977664138458e.json","target-mal_crc-Debug-0fcee6143d832a319202.json","target-mal_delay-Debug-e5594f31c5aabd8d4550.json","target-mal_i2c-Debug-83a2ed51ac574c65acf9.json","target-mal_ldma-Debug-adf4262bc1331fcc6fca.json","target-mal_spi-Debug-66d479cfba9f6dbb0e43.json","target-sdk-Debug-8b6240b4ee0d572f78a5.json","target-spp_adxl372-Debug-50862cd6f43ccf7dc113.json","target-spp_ambiant-Debug-542b3cfa08a2fd362839.json","target-spp_clockCalib-Debug-1c4c19fbb78d6b165463.json","target-spp_inter_MCU_com-Debug-fe2571bd1dc9ec1afdcb.json","target-spp_kx134-Debug-a6fdc3decafdbee0578c.json","target-spp_mapping-Debug-1380ad955a2e17177448.json","target-spp_nv_params-Debug-1b6a5da72ac163d872d0.json","target-spp_send_log-Debug-c866686737da56c6d095.json","target-spp_vbatt-Debug-000958f9ac79845418d4.json","target-spp_version-Debug-e6d774daee7805c4bfa8.json","target-srv_ambiant-Debug-9d7a10fe437d681cd8d9.json","target-srv_gpio-Debug-b0389a1901ac2eeffac8.json","target-srv_inter_MCU_com-Debug-ccc5bfa7fae820c1abb7.json","target-srv_vibration-Debug-3172037163823489643b.json","target-stackZGP-Debug-a272cdc75c8aadd5c545.json","toolchains-v1-d368736a74505c2f9226.json"]
[build] Build finished with exit code 0
[extension] [3533] cmake.build finished (returned 0)
```

### Additional Information

C/C++ infos:

```
-------- Diagnostics - 05/01/2023, 09:40:17
Version: 1.13.9
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:/git/a/b/01_application/data_logger",
        "c:/git/a/b/01_application/common/init",
        "c:/git/a/b/06_sdk/autogen",
        "c:/git/a/b/efr32-silabs-sdk-gcc/hardware/kit/common/bsp",
        "c:/git/a/b/efr32-silabs-sdk-gcc/hardware/kit/common/drivers",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/bootloader/api",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/cmsis/include",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/common/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/common/toolchain/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/common/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/dmadrv/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/dmadrv/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/gpiointerrupt/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/spidrv/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/spidrv/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/tempdrv/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/tempdrv/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/uartdrv/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/uartdrv/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/ustimer/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/ustimer/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emlib/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/halconfig/inc/hal-config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/radio/rail_lib/common",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/radio/rail_lib/hal",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/radio/rail_lib/hal/efr32",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/radio/rail_lib/plugin/pa-conversions",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/radio/rail_lib/protocol/ble",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/radio/rail_lib/protocol/ieee802154",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/cli/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/mpu/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/sleeptimer/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/sleeptimer/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/sleeptimer/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/power_manager/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/device_init/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/power_manager/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/system/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/protocol/bluetooth/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/protocol/bluetooth/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/silicon_labs/silabs_core/memory_manager",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/mbedtls/library",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/mbedtls/include",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_alt/include",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_mbedtls_support/config",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_mbedtls_support/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_protocol_crypto/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_psa_driver/inc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/mbedtls/include/mbedtls",
        "c:/git/a/b/03_support/configuration",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/device/siliconlabs/efr32mg12p/include",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/radio/rail_lib/chip/efr32/efr32xg1x",
        "c:/git/a/b/03_support/sdk_config/cb110_v0",
        "c:/git/a/b/zigbee-efr32-soc-applications/stack/exported",
        "c:/git/a/b/zigbee-efr32-soc-applications/stack/private/network/inc",
        "c:/git/a/b/03_support/gpd_nvm",
        "c:/git/a/b/04_driver/flash_counter",
        "c:/git/a/b/02_service/ambiant",
        "c:/git/a/b/03_support/ambiant",
        "c:/git/a/b/03_support/mapping",
        "c:/git/a/b/03_support/mapping/cb110_v0",
        "c:/git/a/b/04_driver/shtc3",
        "c:/git/a/b/05_mal/i2c",
        "c:/git/a/b/05_mal/delay",
        "c:/git/a/b/02_service/gpio",
        "c:/git/a/b/02_service/inter_mcu_com",
        "c:/git/a/b/02_service/vibration",
        "c:/git/a/b/03_support/adxl372",
        "c:/git/a/b/04_driver/adxl372",
        "c:/git/a/b/05_mal/spi",
        "c:/git/a/b/03_support/kx134",
        "c:/git/a/b/04_driver/kx13x",
        "c:/git/a/b/03_support/inter_mcu_com",
        "c:/git/a/b/cb110_communication_registers/algo_results",
        "c:/git/a/b/cb110_communication_registers/comregs",
        "c:/git/a/b",
        "c:/git/a/b/05_mal/crc",
        "c:/git/a/b/03_support/clockcalib",
        "c:/git/a/b/03_support/send_log",
        "c:/git/a/b/03_support/nv_params",
        "c:/git/a/b/03_support/vbatt",
        "c:/git/a/b/05_mal/adc",
        "c:/git/a/b/03_support/version",
        "c:/git/a/b/04_driver/cryotimer",
        "c:/git/a/b/01_application",
        "c:/git/a/b/build_cb110_v0_data_logger_debug/01_application/cmakefiles/app_data_logger.dir/data_logger",
        "c:/git/a/b/build_cb110_v0_data_logger_debug/01_application/cmakefiles/app_data_logger.dir/common",
        "c:/git/a/b/build_cb110_v0_data_logger_debug/01_application/cmakefiles/app_data_logger.dir/common/init",
        "c:/git/a/b/build_cb110_v0_data_logger_debug/cmakefiles",
        "c:/git/a/b/01_application/customer_app",
        "c:/git/a/b/01_application/common/lowpowerconfig",
        "c:/git/a/b/01_application/common",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/cmsis/dsp_lib/source/basicmathfunctions",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/cmsis/dsp_lib/source/commontables",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/cmsis/dsp_lib/source/complexmathfunctions",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/cmsis/dsp_lib/source/statisticsfunctions",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/cmsis/dsp_lib/source/supportfunctions",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/cmsis/dsp_lib/source/transformfunctions",
        "c:/git/a/b/04_driver/adc",
        "c:/git/a/b/04_driver/rtcc",
        "c:/git/a/b/04_driver/rtt",
        "c:/git/a/b/05_mal/ldma",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/common/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/common/toolchain/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emdrv/ustimer/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/emlib/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/device_init/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/power_manager/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/service/system/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/protocol/bluetooth/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_alt/source",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_mbedtls_support/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/util/third_party/crypto/sl_component/sl_psa_driver/src",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/device/siliconlabs/efr32mg12p/source/gcc",
        "c:/git/a/b/efr32-silabs-sdk-gcc/platform/device/siliconlabs/efr32mg12p/source",
        "c:/git/a/b/zigbee-efr32-soc-applications/stack/private/gp/inc",
        "c:/git/a/b/zigbee-efr32-soc-applications/stack/private",
        "c:/git/a/b/zigbee-efr32-soc-applications/stack/private/gp/src",
        "c:/git/a/b/zigbee-efr32-soc-applications/stack/private/network/src"
    ],
    "compilerPath": "c:/git/fw_toolchain/gnu tools arm embedded/10.3-2021.10/bin/arm-none-eabi-g++.exe",
    "compilerFragments": [
        "-g",
        "-mcpu=cortex-m4",
        "-mthumb",
        "-mfpu=fpv4-sp-d16",
        "-mfloat-abi=softfp",
        "--specs=nano.specs",
        "-ffunction-sections",
        "-fdata-sections",
        "-fno-builtin",
        "-Wall",
        "-Wfatal-errors",
        "-O0",
        "-g3",
        "-DDEBUG=1",
        "-DDEBUG_EFM",
        "-std=gnu99"
    ],
    "compilerArgsLegacy": []
}
Translation Unit Mappings:
[ C:\GIT\A\B\01_application\main.c ]:
    C:\GIT\A\B\01_application\main.c
Translation Unit Configurations:
[ C:\GIT\A\B\01_application\main.c ]:
    Process ID: 2320
    Memory Usage: 43 MB
    Compiler Path: C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\bin\arm-none-eabi-g++.exe
    Includes:
        C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\arm-none-eabi\include\newlib-nano
        C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\arm-none-eabi\include\c++\10.3.1
        C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\arm-none-eabi\include\c++\10.3.1\arm-none-eabi\thumb\v7e-m+fp\softfp
        C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\arm-none-eabi\include\c++\10.3.1\backward
        C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\lib\gcc\arm-none-eabi\10.3.1\include
        C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\lib\gcc\arm-none-eabi\10.3.1\include-fixed
        C:\GIT\FW_Toolchain\GNU Tools ARM Embedded\10.3-2021.10\arm-none-eabi\include
    Standard Version: c17
    IntelliSense Mode: windows-gcc-arm
    Other Flags:
        --g++
        --gnu_version=100301
Total Memory Usage: 43 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5137
```

**Comment by atsju** [comment] 2023-01-06 07:04
After deeper research, maybe duplicate of #2915 ?

**Comment by elahehrashedi** [comment] 2023-01-06 14:12
Thank you for reporting this issue. I will close this issue as a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/2915.

**Closed** 2023-01-06 16:44 UTC
Labels: duplicate
