### ISSUE TITLE
cmake 3.18 support 

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#1378] opened 2020-07-21 14:40 UTC
[cmakefileapi-parser] cmake-file-api 的代码模型版本(2.1)不是预期版本。应为 (2.0)。IntelliSense 配置可能不正确。

### Expected:

1. Push button
2. Thing happens

### Apparent Behavior:

1. Push button
2. Nothing happens

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**:

**Comment by bobbrow** [comment] 2020-07-21 17:24
This is a duplicate of #1341 which has been fixed (but not yet released)

**Closed by bobbrow** 2020-07-21 17:24 UTC
