### ISSUE TITLE
Edit CacheUI broken since last release?

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#3786] opened 2024-05-21 22:13 UTC
### Brief Issue Summary

I thought some of the latest PRs broke something then I saw the last release reproduces as well.
Run the command "Edit CMake Cache (UI)" and instead of seeing the table, there is an error popup on bottom-right with this message:
"Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..."
I debugged a little and so far I didn't notice anything outstanding in CMake Tools code base, I'll investigate more. It's possible this may end up sent to another team related to VSCode.

**Comment by v-frankwang** [comment] 2024-05-23 07:06
@andreeis According to your description I can't reproduce the problem you are talking about, here are my steps to reproduce it can you give some suggestions?

ENV:
VS Code: 1.89.1
CMake tools: 1.18.39
C/C++:1.20.5

Repro steps recording:
         1. Create a new folder and open it with vscode.
         2. Create a CMakeLists.txt file and add the following code:
                cmake_minimum_required(VERSION 3.5) 
                project(Test) 
                add_executable(Test main.cpp) 
         3. Create a main.cpp file and add the following code:
                #include <iostream> 
                auto main() -> int { std::cout << "hello world" << std::endl; } 
         4. Run command:"CMake:Configure"
         5. Run command:"CMake:Edit CMake Cache(UI)"

Actual results：
        
![3786](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/ae7ef80d-256f-47b5-970a-2d2fc330c889)

**Comment by gcampbell-msft** [comment] 2024-06-24 16:10
I tested with the most recent version of the extension and this doesn't reproduce, closing.

**Closed by gcampbell-msft** 2024-06-24 16:10 UTC
Labels: bug, more info needed, Feature: cache editor
