### ISSUE TITLE
CMake extension is not loaded if source folder is not workspaceFolder

### ISSUE THREAD

**Issue by KoeMai** [microsoft/vscode-cmake-tools#376] opened 2018-04-07 07:06 UTC
### Brief Issue Summary

I have a project which has the CMakeLists.txt inside a sub folder. Visual studio code
does not activates the extension for this projects. I have to activate it by using a command.

### Expected:

Extension starts if the project contains one CMakeLists.txt in any folder of workspaceFolder.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.10.0
- **VSCode Version**: 1.21.1
- **CMake Tools Extension Version**: 0.11-beta5

**Comment by bobbrow** [comment] 2019-07-24 16:13
Duplicate of #533 (I know. This one was first, but there's already a PR out that links to #533 which will address this one since we're triaging issues from newest to oldest.)

**Closed by bobbrow** 2019-07-24 16:13 UTC
Labels: tweak
