### ISSUE TITLE
Driver seems no longer work any more after killed vscode-sever several times

### ISSUE THREAD

**Issue by scruel** [microsoft/vscode-cmake-tools#2797] opened 2022-10-17 04:23 UTC
### Brief Issue Summary

I want to use `environmentSetupScript` to set up running environment with conda, tried the example from here: https://github.com/microsoft/vscode-cmake-tools/issues/1592, and it works fine for me.

However, `environmentSetupScript` seems can't activate other conda environment after I activated once as I mentioned here https://github.com/microsoft/vscode-cmake-tools/issues/1445#issuecomment-1280250522, so I tried to kill the `vscode-server` related process to do the test.

After killed several times, the `environmentSetupScript` won't be executed anymore.
To fix this, I already tried to reboot my server and delete the `.vscode-server` to reset related files, but the issue still exists…

I think the issue is caused by plugin driver settings, because before this issue occurred, when I try to switch the kit, I will get the following log:
[driver] Switching to kit: TestKit

After this issue occurred, no more [driver] logs while switching the kit.

To reproduce this issue might be hard, and I have no time for debugging this, so if you want more info to pin the issue to do the fix, feel free to ask more.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.72.2",
  "cmtVersion": "1.12.27",
  "configurations": [
    {
      "folder": "clang-plugins-demo",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
[main] Safe constructing new CMakeTools instance
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[variant] Loaded new set of variants
[main] CMakeTools instance initialization complete.
[kit] Reading kits file /home/scruel/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Successfully loaded 1 kits from /home/scruel/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Reading kits file /home/scruel/Code/clang-plugins-demo/.vscode/cmake-kits.json
[kit] Successfully loaded 1 kits from /home/scruel/Code/clang-plugins-demo/.vscode/cmake-kits.json
[main] Injecting new Kit into CMake driver
[extension] Configuring workspace on open file:///home/scruel/Code/clang-plugins-demo
[main] Configuring folder: clang-plugins-demo 
[main] Saving open files before configure/build
[extension] [4763] cmake.selectKit started
[kitsController] Start selection of kits. Found 4 kits.
[kitsController] Opening kit selection QuickPick
[kitsController] User selected kit {"label":"TestKit","description":"Unspecified (Let CMake guess what compilers and environment to use)","kit":{"name":"TestKit","environmentSetupScript":"${workspaceFolder}/envsetup.sh"}}
[main] Injecting new Kit into CMake driver
[extension] [4763] cmake.selectKit finished (returned true)
```

### Additional Information

Sever Ubuntu 22.04.1 LTS
Host Windows 11

Connected with SSH Remote plugin.

**Comment by bobbrow** [comment] 2022-10-20 16:54
Is the problem with killing the server or just that the environment doesn't ever get updated once the environmentSetupScript has been run?  It seems that if I change the value in `envsetup.sh`, it doesn't update even with `Delete Cache and Reconfigure`.  And that is the case without using SSH at all.

**Comment by scruel** [comment] 2022-10-21 03:53
> Is the problem with killing the server or just that the environment doesn't ever get updated once the environmentSetupScript has been run?

Before the killing server action, the script will run and the environment will get updated.
For changing, I am talking about change the kit, not `envsetup.sh`:
![image](https://user-images.githubusercontent.com/16933298/197092639-fabc2c16-e533-4d1c-8e16-d51c15aa5983.png)

**Comment by gcampbell-msft** [comment] 2024-06-24 15:57
@scruel If the environment is correctly getting updated after running the script, I don't think the issue is with the CMake Tools repo, it's will the killing of the server. If you feel I'm incorrect about this, please create a new issue, for now I'm closing this one. THanks!

**Closed by gcampbell-msft** 2024-06-24 15:57 UTC
Labels: bug, Feature: kits
