### ISSUE TITLE
CMake is not loading pyenv correctly, fails to find correct conan

### ISSUE THREAD

**Issue by Lorac** [microsoft/vscode-cmake-tools#1864] opened 2021-05-11 14:40 UTC
### Brief Issue Summary

I'm using `conan` with `cmake` integration. It is paired with a pyenv inside the workspaceFolder. When launching CMake through the command panel, it will fail to find `conan` because the shell PWD is not the workspaceFolder.

### Apparent Behavior:

CMake is being executed in my $HOME directory with the parameters `-S` and the argument must be the workspaceFolder. Which doesn't seems to load the pyenv correctly to find conan.

### CMake Tools Log

```
[cmake] -- Conan: Automatic detection of conan settings from cmake
[cmake] -- Conan: Settings= -s;arch=x86_64;-s;build_type=Release;-s;compiler=gcc;-s;compiler.version=7;-s;compiler.libcxx=libstdc++11
[cmake] -- Conan: checking conan executable
[cmake] -- Conan: Found program $HOME/.pyenv/shims/conan
[cmake] -- pyenv: conan: command not found
[cmake] 
[cmake] The `conan' command exists in these Python versions:
[cmake]   3.8.8/envs/mono
[cmake]   mono
[cmake] 
[cmake] Note: See 'pyenv help global' for tips on allowing both
[cmake]       python2 and python3 to be found.
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "$HOME/devel/monorepo-cmake/build/x64/CMakeFiles/CMakeOutput.log".
[cmake] CMake Error at build/x64/conan.cmake:806 (message):
[cmake]   Conan --version failed='127
```
I don't want to set a global versions, that's the point of the pyenv.

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.20
- **VSCode Version**: 1.57.0-insiders
- **CMake Tools Extension Version**: 1.7.2
- **Compiler/Toolchain**: GCC 7

**Comment by andreeis** [comment] 2021-05-12 17:39
Thank you for opening this report. For the future (1.8 we hope), we will offer the possibility to set a working folder for the configure process and everything that it spawns.
We track https://github.com/microsoft/vscode-cmake-tools/issues/1731 for that.
If this is something that would address your scenario, I will close your report as a duplicate. Let us know if there is anything additional that issue 1731 is not covering or anything that we missed in your report.

**Comment by Lorac** [comment] 2021-05-13 02:06
It seems to be the same issue. The only thing I'm not sure if it's opening a login shell or not. It might affect how `pyenv` runs if the shell that you are opening if it's not a login one. That being said, I don't think your extension can modify how that works though. I think it's more related to the ssh remote extension.

Hopefully changing the cwd of where cmake is executed will fix my issue.

**Comment by andreeis** [comment] 2021-05-13 08:25
Ok, closing as a duplicate. When we have a fix for something, we provide a vsix for any impacted users to try. I'll reopen this if the vsix with the fix will not solve this for you.
For now, duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/1731.

**Closed by andreeis** 2021-05-13 08:25 UTC
Labels: Feature Request, Feature: configure, duplicate
