### ISSUE TITLE
CMake-Tools does not (re)configure on CMakeLists.txt change/save

### ISSUE THREAD

**Issue by vbspam** [microsoft/vscode-cmake-tools#634] opened 2019-01-16 15:09 UTC
### CMake-Tools does not (re)configure on CMakeLists.txt change/save.

When the project gets successfully configured either by manual invocation or when configured for the first time, then any saved change of related CMakeLists.txt does not trigger automatic reconfiguration of the project. 

### How to reproduce
1. Setup simple project with single CMakeLists.txt and single main.cpp. Fill both files with minimal contents to build dummy TestA.exe
2. Lets have a VSCode with CMake-Tools installed
3. Open the project in VSCode
4. After successful configuration change the CMakeLists.txt e.g. by adding another executable target TestB.exe and save the file

### Expected:

The CMake-Tools should automatically reconfigure the project and adjust the CMake-Tools tree/view accordingly (in this case by adding TestB executable target).

### Apparent Behavior:

The CMake-Tools does not automatically reconfigure the project.

### CMake Tools Log

Does not log any issues.

### Developer Tools Log

Does not log any issues.

### Platform and Versions

- **Operating System**: Windows 10 , Ubuntu 18.04
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.30.2
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017, Clang 6.x

### Other Notes/Information

- Before I studied the source code I would bet the behavior I described in this bug was working ok
- I tested my projects (one where I noticed the issue, the other minimal case described in this bug) with the pure CMake in server mode (cmake -E server --debug) and the server notifies properly about changes in CMakeLists.txt
- When I studied the source code, it looks the functionality was never there ! :-). The place which should trigger (by my opinion) the configure is [here](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/src/cms-client.ts#L460)

**Comment by vbspam** [comment] 2019-01-16 16:50
As not being VSCode extension specialist, I found fast, clear, simple and likely wrong solution :-)

Adding following before the return statement brings me the missing functionality.
`
vscode.commands.executeCommand('cmake.configure');
`
At first look it makes the driver dependent on vscode, but the vscode module has been already imported, so I took advantage of this and fix it for me. Looking forward for 'real' solution.

**Comment by marcpawl** [comment] 2019-03-13 16:07
+1 
workaround is select folder, right click, remove folder from workspace, then add folder.

**Comment by andreeis** [comment] 2020-04-28 16:48
Fixed for CMake Tools upcoming 1.4 release.
Closing as duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/1187.

**Closed by andreeis** 2020-04-28 16:48 UTC
Labels: Feature: configure

**Comment by janbajana** [comment] 2020-10-02 16:00
Hello, I have the opposite problem. VSCode re-configures cmake always I save something new in a `CMakaLeist.txt`. This is very annoying mainly for big projects where you spend more time on cmake configurations. 
How could I disable this behaviour? I want VSCode re-configure only when I need to.
Thank you.
