### ISSUE TITLE
Please configure CMake to build and run the tests I'm running

### ISSUE THREAD

**Issue by ArnoGW1** [microsoft/vscode-cmake-tools#3838] opened 2024-06-17 13:10 UTC
### Brief Issue Summary

Using a `launch.json` file, if I have selected target A for build and debug in the CMake tools UI then run test target B, VSCode builds and runs target A with B's arguments.

This makes frequently switching between a library's tests and an executable very tedious, I have to click 7 times (click CMake, click the build icon, type and select B, click the debug icon, type and select B, click on test tab, click on debug test). And it's a mouse workflow which is worse than keyboard.

It doesn't seem to cause any problems to auto-configure CMake to build and run the test target corresponding to the tests the user asked to run?

**Comment by v-frankwang** [comment] 2024-06-21 08:06
@ArnoGW1 Thank you for reporting this issue. Regarding this issue, we tried to reproduce it using a simple demo project but were not able to reproduce it, in order to investigate further, could you please provide us with a simple project that can reproduce this issue, we look forward to your feedback.

**Comment by gcampbell-msft** [comment] 2024-12-17 19:46
Closing after a couple of months with no repro project. @ArnoGW1 If this is still affecting you, please open a new issue with a repro project and we'd love to investigate it for you. THanks.

**Closed by gcampbell-msft** 2024-12-17 19:46 UTC
Labels: more info needed, Feature: debug/launch
