### ISSUE TITLE
Should create correct intelli Sense config based on toolchain file

### ISSUE THREAD

**Issue by lal12** [microsoft/vscode-cmake-tools#546] opened 2018-09-21 13:59 UTC
### Brief Issue Summary
I am using toolchain file for CMake, which I added in the `cmake_tools.json`, this specifies a custom compiler and custom include paths (and custom defines).

### Expected:
On Project configuration and clicking "Yes" when being asked "Would you like to use ${workspaceFolder}/build/compile_commands.json to auto-configure IntelliSense for this folder?" should generate a `compile_commands.json` based on the values set in the toolchain file.

### Apparent Behavior:

The following code is generated:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```
while the compile_commands seem to be correct, the content of `defines` and `includePath` is not.

### Developer Tools Log

```
[Extension Host] [CMakeTools] 2018-09-21T13:54:38.848Z [debug] [rollbar] Updated Rollbar payload {"environment":"production","packageJSON":{"name":"cmake-tools","version":"1.1.1"},"client":{"code_version":"1.1.1"},"platform":"linux"}
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] activating extension
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] starting language server
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:38.951Z [debug] [kit] Reading kits file /home/ll/.local/share/CMakeTools/cmake-tools.json
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:38.952Z [debug] [kit] Not reading non-existent kits file: /home/ll/git/dhcpc/.vscode/cmake-kits.json
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.106Z [info] [kit] Successfully loaded 7 kits from /home/ll/.local/share/CMakeTools/cmake-tools.json
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.107Z [debug] [main] Safe constructing new CMakeTools instance
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.108Z [debug] [variant] Constructing VariantManager
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.109Z [debug] [main] Constructing new CMakeTools instance
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.110Z [debug] [main] Starting CMakeTools second-phase init
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.110Z [debug] [rollbar] Checking Rollbar permissions
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.110Z [debug] [rollbar] Rollbar enabled?  false
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.179Z [info] [variant] Loaded new set of variants
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.182Z [debug] [main] CMakeTools instance initialization complete.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.183Z [debug] [main] Injecting new Kit into CMake driver
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.185Z [debug] [kit] Reading kits file /home/ll/.local/share/CMakeTools/cmake-tools.json
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.193Z [info] [kit] Successfully loaded 7 kits from /home/ll/.local/share/CMakeTools/cmake-tools.json
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.193Z [debug] [kit] Not reading non-existent kits file: /home/ll/git/dhcpc/.vscode/cmake-kits.json
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.194Z [debug] [rollbar] Updated Rollbar payload {"kit":{"name":"GCC armv7 (W&T)","toolchainFile":"~/cmake-toolchains/wut-armv7"}}
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.195Z [debug] [main] Injecting new Kit into CMake driver
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.200Z [debug] [extension] Configuring workspace on open  file:///home/ll/git/dhcpc
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.201Z [debug] [main] Run configure  
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.201Z [debug] [main] Saving open files before configure/build
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] cmake-tools-helper.cmake_download_path:/home/ll/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/cmake_download
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Fehler beim Aktivieren der Erweiterung "maddouri.cmake-tools-helper": Cannot read property 'reconfigured' of undefined.
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Activating extension `maddouri.cmake-tools-helper` failed:  Cannot read property 'reconfigured' of undefined
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'reconfigured' of undefined
	at new CMakeToolsHelper (/home/ll/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/state.js:13:33)
	at activate (/home/ll/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/extension.js:10:28)
	at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:808:839)
	at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:808:518)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:807:572
	at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:77:971)
	at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:82:559)
	at c (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:85:1011)
	at $.then.o.(anonymous function) (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:86:205)
	at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:77:971)
	at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:82:559)
	at c (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:85:1011)
	at $.then.o.(anonymous function) (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:86:205)
	at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:77:971)
	at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:82:559)
	at e.resolveOk (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:573:721)
	at e._receiveReply (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:316)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:609)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3225 Fehler beim Aktivieren der Erweiterung "maddouri.cmake-tools-helper": Cannot read property 'reconfigured' of undefined.
w._logMessageInConsole @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3225
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.560Z [debug] [main] Starting new CMake driver
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.560Z [debug] [main] Starting CMake driver
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.561Z [debug] [driver] CMakeDriver Kit set to GCC armv7 (W&T)
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.562Z [debug] [driver] Run _refreshExpansions
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.562Z [debug] [cms-driver] Run doRefreshExpansions
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.563Z [debug] [driver] Run _refreshExpansions cb
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:39.575Z [debug] [cms-client] Started new CMake Server instance with PID 10604
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:40.579Z [debug] [cache] Reading CMake cache file /home/ll/git/dhcpc/build/CMakeCache.txt
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:40.580Z [debug] [cache] Parsing CMake cache string
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:40.601Z [debug] [driver] Setting new variant , Emit debug information without performing optimizations
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:40.601Z [debug] [driver] Run _refreshExpansions
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:40.602Z [debug] [cms-driver] Run doRefreshExpansions
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:40.602Z [debug] [driver] Run _refreshExpansions cb
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:40.625Z [debug] [cms-client] Started new CMake Server instance with PID 10606
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.627Z [debug] [cache] Reading CMake cache file /home/ll/git/dhcpc/build/CMakeCache.txt
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.629Z [debug] [cache] Parsing CMake cache string
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.693Z [debug] [driver] Start configure  
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.693Z [debug] [driver] Runnnig pre-configure checks and steps
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.694Z [debug] [driver] Using CMake toolchain GCC armv7 (W&T) for configuring
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.695Z [debug] [driver] Run _refreshExpansions
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.695Z [debug] [cms-driver] Run doRefreshExpansions
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.695Z [debug] [driver] Run _refreshExpansions cb
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.699Z [info] [cmake] BUILD_TYPE was set to Release since, nothing else was specified. Pass -DBUILD_TYPE=Debug to get a debug build.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.700Z [info] [cmake] BUILD_TYPE was set to Release since, nothing else was specified. Pass -DBUILD_TYPE=Debug to get a debug build.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.700Z [info] [cmake] /home/ll/svn/operation
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.703Z [info] [cmake] Configuring done
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.717Z [info] [cmake] Generating done
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:41.775Z [debug] [cache] Reading CMake cache file /home/ll/git/dhcpc/build/CMakeCache.txt
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:42.217Z [debug] [cache] Parsing CMake cache string
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:42.235Z [error] [rollbar] Unable to automatically determine compiler {"lang":"C","fileGroup":{"compileFlags":"-fmessage-length=0 -mtune=marvell-pj4 -march=armv7-a -mfloat-abi=softfp -DSYSTEMD -Os -DRELEASE   -std=gnu90","defines":["USE_MYSQL"],"includePath":[{"path":"/usr/local/arm-pkg_v7/include"},{"path":"/usr/local/arm-pkg_v7/usr/include"},{"path":"/home/ll/git/dhcpc/."},{"path":"/home/ll/git/dhcpc/wut_include"}],"isGenerated":false,"language":"C","sources":["dhcpclient_wut.c"]}}
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272
2/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] [CMakeTools] 2018-09-21T13:54:42.237Z [error] [rollbar] Unable to automatically determine compiler {"lang":"C","fileGroup":{"compileFlags":"-fmessage-length=0 -mtune=marvell-pj4 -march=armv7-a -mfloat-abi=softfp -DSYSTEMD -Os -DRELEASE -fPIC   -std=gnu90","defines":["USE_MYSQL","wut_util_EXPORTS"],"includePath":[{"path":"/usr/local/arm-pkg_v7/include"},{"path":"/usr/local/arm-pkg_v7/usr/include"},{"path":"/home/ll/git/dhcpc/."},{"path":"/home/ll/git/dhcpc/wut_include"},{"path":"/home/ll/git/dhcpc/wut_include/."}],"isGenerated":false,"language":"C","sources":["db_init.c","gpio_helper.c","mysql_query.c","wbm_io.c","webio_com.c","wt_gis_20.c","wt_log.c"]}}
```

### Platform and Versions
- **Operating System**: Debian
- **CMake Version**: 3.7.2
- **VSCode Version**: 1.26.1
- **CMake Tools Extension Version**: 1.1.1
- **Compiler/Toolchain**: arm-linux-gcc 6.3.0  (from buildroot)

**Comment by vector-of-bool** [comment] 2018-09-22 01:57
Generating `compile_commands.json` correctly is outside of CMake Tools' purview. It may be a bug in CMake itself.

**Comment by lal12** [comment] 2018-09-22 21:10
Hmm maybe we mistunderstand each other. The `compile_commands.json` is correctly generated, and its content seem to be ok, too. But in my opinion CMake Tools should set the correct values when creating `c_cpp_properties.json`, too. 

So instead of a `c_cpp_properties.json` containing:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```
I would expect something like this:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/local/arm-pkg_v7/include"
            ],
            "defines": ["I-AM-A-DEFINE-FROM-A-CMAKE-TOOLCHAIN-FILE"],
            "compilerPath": "/usr/local/bin/arm-linux-gcc
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```
Which are all informations I put in the toolchain file.

**Comment by vector-of-bool** [comment] 2018-09-24 06:39
Any preprocessor definitions that are used when compiling a particular file will be detected when the file is processed by cpptools. This comes from both the extension integrations and/or `compile_commands.json`.

**Comment by bobbrow** [comment] 2019-07-22 21:51
Hi there,

I work on the cpptools extension (and now we maintain this extension too).  If you are still having trouble with this, please share the entry from your `compile_commands.json` file that is not working for you.  (e.g. if foo.cpp is not being configured properly, please share the corresponding entry for foo.cpp from your compile_commands.json file)

When the `compileCommands` property is used in the `c_cpp_properties.json` file, we do not look at the `includePath` and `define` properties because we expect `compile_commands.json` to be the source of truth for configuration.

Thank you.

**Comment by zrno** [comment] 2019-11-13 02:02
Is it possible to use some CMake Tools generated variables inside the `compileCommands` field? In our project we have several cmake kits and configurations(in `cmake_configurations.json` ). Lets say we switch the configuration from Debug to Release and that also changes our build directory. Currently we have to manually change the path to `compile_commands.json`. Is there a way to make this automatic? 

Maybe something like 
`"compileCommands": "${cmake.buildDirectory}/compile_commands.json"` 
or 
`"compileCommands": "${workspaceFolder}/../${buildKit}/${buildType}/compile_commands.json"`

**Comment by bobbrow** [comment] 2019-11-13 17:42
properties in `c_cpp_properties.json` are unaware of CMake-defined variables like `${buildKit}` and `${buildType}`, but they can read settings with the following syntax: `${config:cmake.buildDirectory}`.

Another option is to have 2 configs:

"configurations": [
  {
    "name": "Debug",
    "compileCommands": "/path/to/debug/compile_commands.json"
  },
  {
    "name": "Release",
    "compileCommands": "/path/to/release/compile_commands.json"
  }
]

Though the best option, in my opinion, is to use CMake Tools as a "configurationProvider" (which is automatic and doesn't require 2 configurations).  Run the "C/C++: Change Configuration Provider" command and select CMake Tools as the provider.

**Comment by zrno** [comment] 2019-11-13 19:58
Thanks for the fast response. If I only choose CMake Tools as the configuration provider than all my include paths that are outside the workspace don't get resolved (like Qt includes). The CMake Tools is correctly chosen as the configuration provider. (When I go to "C/C++: Change Configuration Provider" cmake is listed as active)
Do you know what could be the reason for that?

**Comment by bobbrow** [comment] 2019-11-13 20:49
Perhaps there is a bug in the CMake Tools provider?

Help me understand your scenario better.  Can you provide more information about how your project is structured?  cpptools logs the configurations sent by CMake Tools if you [enable language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp), so can you confirm that the configurations are correct (or non-existent)?  Search for the word "custom" in the log and you will find the configurations quickly.

**Comment by zrno** [comment] 2019-11-19 02:46
The issue has magically solved itself. It was probably caused by the update of the extension. I have manually changed the `configurationProvider` setting to the new name `"ms-vscode.cmake-tools"` but it seems that a PC restart was needed for the new settings to be accepted. Restarting vs-code didn't help.

**Comment by bobbrow** [comment] 2019-11-19 16:49
@zrno, ok?  `ms-vscode.cmake-tools` only works with cpptools@0.26.2-insiders as of right now.  My guess is that you installed the Insiders version of cpptools and that fixed your problem.

I'm going to close this issue now, because I think all points have now been addressed.  If you have any further feedback for the extension, please open a new issue and we can start from there.

**Closed by bobbrow** 2019-11-19 16:49 UTC
Labels: Feature: cpptools integration, more info needed, upstream
