### ISSUE TITLE
Chinese is not displayed correctly

### ISSUE THREAD

**Issue by tim37021** [microsoft/vscode-cmake-tools#245] opened 2017-10-31 18:21 UTC
I use visual studio 2017. The build output does not display correctly.

![image](https://user-images.githubusercontent.com/5507113/32241500-40fb519c-beab-11e7-8e7e-b63b7e6154a2.png)

However, if I use task.json to build it works perfectly
![image](https://user-images.githubusercontent.com/5507113/32241517-55239d1e-beab-11e7-9e31-f3ec855c9f64.png)

**Comment by xdray** [comment] 2018-04-13 03:02
I get same question

**Comment by vector-of-bool** [comment] 2018-04-15 20:55
@Randshot Look familiar? I bet its the same output code page issue. I want to move the build logs to an integrated terminal, and then maybe this issue would be easy to fix.

If not that, it may be enough to use the same technique for launching `vswhere` as here when running `--build`?

**Comment by Randshot** [comment] 2018-04-24 17:11
It certainly looks familiar. Moving to the integrated terminal may fix this issue, assuming that it doesn't use code pages.

**Comment by bobbrow** [comment] 2019-07-16 16:46
This looks like a duplicate of #153 which may have been fixed by PR #550.  Is this still an issue for you?

**Closed by bobbrow** 2019-07-16 16:46 UTC
Labels: bug, duplicate, help wanted
