### ISSUE TITLE
Support Multiple CMakeLists.txt without Requiring a Multi-Root Workspace

### ISSUE THREAD

**Issue by MBetters** [microsoft/vscode-cmake-tools#1374] opened 2020-07-17 18:41 UTC
### Brief Issue Summary

I maintain a repo in which there are multiple target architectures. For the most part, the executables being built for the different architectures have separate code, build dirs, and CMakeLists.txt files, because the processes running on the different archs do completely separate things (think a multi-component system made up of RTOS devices, beefier "cortex" boards, etc). There are some libs and include dirs shared commonly between these exec dirs, but not many. The ideal solution would be for CMake Tools to build these separate architectures independently. I tried a multi-root workspace + symlinks for the common code, but ran into issues with that (see https://github.com/microsoft/vscode-cmake-tools/issues/1371). Since symlinks are clunky and not great for developers who don't want to use Unix, ideally there'd be a way to just give CMake Tools a list of `CMakeLists.txt` files for it to build- something like `cmake.cmakelist_files`. Maybe such a setting could default to `[]` so that CMake Tools would carry on using  `${cmake.sourceDirectory}/CMakeLists.txt` like it normally does, but if `cmake.cmakelist_files` is set to multiple `CMakeLists.txt` files, it would build them all separately with different `build-*` dirs. Obviously it'd also be ideal that intellisense is supported from using the `compile_commands.json` from all the resulting `build-*` dirs, and auto-switches context depending on what file you're looking at.

A few potential ways to do this:

- Run multiple CMake Tools processes? Can VSCode even do that?
- Run CMake Configuration on all the CMakeLists.txt files listed in `cmake.cmakelist_files` (thus producing multiple `build-*` dirs), then merge all the `compile_commands.json` files into a single such file?

This request might sound a little far fetched, but I could see it being quite valuable and crucial to this extension's long-term success. Having to run CMake multiple times is quite common, not just for repos with multiple components. For example, building third-party libs that don't support `add_subdirectory(path/to/some-third-party-lib)`. It'd be AMAZING to have full intellisense support on such third-party libs.

Thanks for the awesome extension!

### Expected:

N/A

### Apparent Behavior:

N/A

### CMake Tools Log

N/A

### Developer Tools Log

N/A

### Platform and Versions

- **Operating System**: Win10 Remote-SSH'd into Ubuntu 20.04
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.47.1
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: Multiple (hence the issue as described lol)

### Other Notes/Information

N/A

**Comment by ryanwinter** [comment] 2020-08-23 22:45
I was surprised to learn this feature didnt exist today ;(

**Comment by TheJCAB** [comment] 2020-11-23 19:19
I'd like to pile up on this request.

It should be possible to open a single folder with multiple sub-folders holding CMake projects, without requiring a VSCode workspace listing each folder separately.

If there's a root CMakeLists.txt, then that's fine. Otherwise, a quick scan (perhaps configurably depth-limited) looking for root CMakeLists.txt would be much appreciated.

**Comment by ragnarruutel** [comment] 2020-12-28 12:22
Same here. Got different CMakeLists.txt files for different platforms.

**Comment by ladislas** [comment] 2021-01-04 15:35
Count me in as well! Would love to see this feature.

**Comment by Maxzor** [comment] 2021-12-21 11:42
Bump

**Comment by bobbrow** [comment] 2021-12-27 16:17
The way to bump the priority of this is to click the 👍 on the first comment.

**Comment by nicolas-van** [comment] 2022-04-16 09:15
I upvote too. Additionally I would like to add that multi-architecture projects are not the only use case, monorepos are also impacted. This extension is basically unusable with monorepos.

Frankly the whole extension could just work by scanning all CMakeLists.txt in all subfolders and just consider each on of them is a separate project. That means completely removing all logic that depend upon root folders, which maybe should never have been there in the first place. That would completely do the job and I don't see why it would cause any kind of problem. (I may be wrong on this, maybe some dependency managers tend to checkout a lot of CMakeLists.txt. But that could also be fixed by ignoring ignored folders in .gitignore, like some other extensions do.)

**Comment by hongshui3000** [comment] 2022-06-08 02:26
Looking forward to this feature

**Comment by jx2014** [comment] 2022-06-26 22:51
What is the minimum number of thumb ups required to catch the attention of vscode and cmake developers?

**Comment by hongshui3000** [comment] 2022-07-01 06:51
+1

**Comment by hongshui3000** [comment] 2022-07-01 06:59
2 years later...

**Comment by jx2014** [comment] 2022-07-03 22:47
Well, since it is free, we just have to be patient.

**Comment by hongshui3000** [comment] 2022-07-10 05:17
This is my most wanted feature and would be really excited if it gets noticed and implemented

**Comment by david-fong** [comment] 2022-08-08 21:37
This isn't one of my use-cases, but I'm just curious to know if anyone has investigated workarounds for this. For example, assuming you have a monorepo with multiple cmake projects each in their own subdirectory, how viable would it be to create a cmake project at the root of the repo that does `add_subdirectory` for each of the sub-projects? Would it address this problem? What other implications would there be, and what are the pros and cons?

I'm also curious if there are other IDEs which implement this functionality. I've only ever used VS Code, but does Visual Studio have such functionality? Assuming it can only have one cmake-generated visual studio project open at a time, it would also not have the feature that is being requested here, right? Does anyone here know?

**Comment by elahehrashedi** [comment] 2022-08-18 19:07
There is a proposal on how to change the design to support this feature. PLease follow from here: https://github.com/microsoft/vscode-cmake-tools/issues/2696

**Comment by MBetters** [comment] 2022-08-18 19:14
To solve my particular use case in lieu of this feature being added, what I did as a temporary workaround is use CMakePresets.json (which CMake Tools [supports](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets.md)) that lists different presets, one for each architecture. I have the presets using different `toolchainFile` settings where the toolchain files set global CMake vars, then I have a top-level CMakeLists.txt that checks which var is set and calls the appropriate `add_subdirectory(...)` commands.

**Comment by elahehrashedi** [comment] 2022-08-18 20:09
This is a proposal on how to change the design of the extension to accept multiple CMake projects in the same workspace folder. 
Currently, we are supporting the multi-root case, in which there is only one Cmake project in every root.

**1. The case where there is only one project per workspacefolder (the current design):**
	
In this scenario the `sourceDirectory` and `buildDirectory` are defined as  below:
```json
"cmake.sourceDirectory": "${workspaceFolder}",
"cmake.buildDirectory": "${workspaceFolder}/build",
```

The `buildDirectory`, if not defined, will default to `"${workspaceFolder}/build"`.

**2. The case where there are multiple project folders in the same workpaceFolder  (the future design):** 

In this scenario, the `sourceDirectory `will be defined as below:

```json
    "cmake.sourceDirectory" : [
        "D:/tests/multiroot/root1",
        "D:/tests/multiroot/root1/subroot1",
        "D:/tests/multiroot/root1/subroot2"
    ],
```
Now we need to decide how to define the `buildDirectory`, here are few approaches:

**2.1.** defining an array of `buildDirectory`, …
```json
	"cmake.buildDirectory" : [
	    "D:/tests/multiroot/root1/build",
	    "D:/tests/multiroot/root1/subroot1/build",
	    "D:/tests/multiroot/root1/subroot2/build"
	]
```
**Cons:**
• In this approach, we will need to define install directory, and etc. as an array too.
• User would have to match the paths across arrays, which is error-prone


**2.2.** Keeping the default as below, but change the way we resolve `${workspaceFolder}`:
```json
"cmake.buildDirectory": "${workspaceFolder}/build"
```
In this approach, we resolve the `workspaceFolder` using the source directory path.
**Cons:** 
• This will break the current users that their source directory was not the same as their workspace folder, e.g. the `CMakeLists.txt` is not located in the root of their workspace folder, or is even located outside of the workspace folder. 

**2.3.** Creating a new variable `${sourceDirectory}` and encouraging the user to use this as their `buildDirectory`:
```json
"cmake.buildDirectory": "${sourceDirectory}/build"
```

- In this approach, when the user is adding the `"cmake.buildDirectory"` for the first time in their settings.json, we will default to  `"${sourceDirectory}/build"`. This will work in both situations where the user is defining a single or multiple source directories. 
- If the user hasn't defined the `buildDirectory` and has defined only one source directory, we will default to `"${workspaceFolder}/build"` as before. This behavior is currently in place and we don't want to change it.
- If the user has defined multiple source directories, and has not defined a `buildDirectory`, we will default to `"${sourceDirectory}/build"`. 
- If the user has defined multiple source directories, and has defined the `buildDirectory` as `"${workspaceFolder}/build"` we will show a warning explaining that this will create an issue for them, as there are multiple projects in the same workspaceFolder, and as a result, all will try to write the build files in the same folder.

**Comment by hongshui3000** [comment] 2022-08-19 10:24
It is best to support ignoring cmake projects under a certain folder, so as to avoid too many projects being included in a single workspace and it(build) is difficult to choose

**Comment by bobbrow** [comment] 2022-08-19 20:51
> It is best to support ignoring cmake projects under a certain folder, so as to avoid too many projects being included in a single workspace and it(build) is difficult to choose

What do you mean?  It's up to you to tell us which projects you care about by setting the `cmake.sourceDirectory` setting.  If you don't want to include a project, you wouldn't put it in the setting.

**Comment by bobbrow** [comment] 2023-01-09 17:00
This is available starting in 1.13.33.  We are fixing a regression it introduced with PR #2926 and will release 1.13.35 with the fix.

**Closed by bobbrow** 2023-01-09 17:00 UTC
Labels: Feature Request, Feature: multiroot, embedded

**Comment by YXL76** [comment] 2023-01-10 06:49
In a ROS2 project, using the `sourceDirectory` variable doesn't work well.

**Comment by bobbrow** [comment] 2023-01-19 16:04
@YXL76 can you please open an issue and describe the problem for us?

**Comment by tothedistance** [comment] 2023-02-16 12:08
@YXL76 set buildDirectory to "${sourceDirectory}/build" and delete all existing build leftover and run command "reset cmake tools" might help.
