### ISSUE TITLE
Possible Line Ending issue in test output

### ISSUE THREAD

**Issue by TheKayneGame** [microsoft/vscode-cmake-tools#3274] opened 2023-08-01 13:54 UTC
### Brief Issue Summary

I am using CMake 3.22.2 in a podman container en connected using the VSCode Dev Container with CMake Tools v1.14.33

As a testing framework i am using [GUnit](https://github.com/cpp-testing/GUnit) which is an extension on top of [Google Test](https://github.com/google/googletest).

When i run a test the test succeeds and fails when it should, this is correctly viewed on the test explorer.
I issue get apparent when i open the `Test Result` . 

# CMake Tools
My test results are formatted by the test explorer like this:
```
Running main() from /workspaces/hello-world-app-docker/out/build/Linux-gcc/_deps/gunit-src/libs/googletest/googletest/src/gtest_main.cc
                                                                                                                                       [==========] Running 1 test from 1 test suite.
                    [----------] Global test environment set-up.
                                                                [----------] 1 test from Example
                                                                                                [ RUN      ] Example.Showing off
                                                                                                                                Set Up
                                                                                                                                      File: /workspaces/hello-world-app-docker/GUnit_HelloWorld/test/GSteps.feature
                                                  Feature: Example
                                                                  Scenario: Showing off
                                                                                       Step: 

                                                                                             Tear Down
                                                                                                      File: /workspaces/hello-world-app-docker/GUnit_HelloWorld/test/GSteps.feature
                  Feature: Example
                                  Scenario: Showing off
                                                       Step: The following steps should be shown on the screen

                                                                                                              [    Given ] I create steps                                              # GSteps.feature:7
                                        [    Given ] I add step a                                                # GSteps.feature:8
                                                                                                                                   [    Given ] I add step b                                                # GSteps.feature:9
                                                             [     When ] I run the scenario                                          # GSteps.feature:10
                                                                                                                                                         Runni...
                                                                                                                                                                The rest of the test output was removed since it exceeds the threshold of 1024 bytes.
```

# (VSCode) Terminal
While in my terminal the test is correctly formatted like:
```
1: Running main() from /workspaces/hello-world-app-docker/out/build/Linux-gcc/_deps/gunit-src/libs/googletest/googletest/src/gtest_main.cc
1: [==========] Running 1 test from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 1 test from Example
1: [ RUN      ] Example.Showing off
1: Set Up
1: File: /workspaces/hello-world-app-docker/GUnit_HelloWorld/test/GSteps.feature
1: Feature: Example
1: Scenario: Showing off
1: Step: 
1: 
1: Tear Down
1: File: /workspaces/hello-world-app-docker/GUnit_HelloWorld/test/GSteps.feature
1: Feature: Example
1: Scenario: Showing off
1: Step: The following steps should be shown on the screen
1: 
1: [    Given ] I create steps                                              # GSteps.feature:7
1: [    Given ] I add step a                                                # GSteps.feature:8
1: [    Given ] I add step b                                                # GSteps.feature:9
1: [     When ] I run the scenario                                          # GSteps.feature:10
1: Running...
1: [     Then ] The following steps should be shown on the screen           # GSteps.feature:11
1: 
1: [       OK ] Example.Showing off (0 ms)
1: [----------] 1 test from Example (0 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 1 test from 1 test suite ran. (0 ms total)
1: [  PASSED  ] 1 test.
1/1 Test #1: hello_test .......................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.15 sec
```
# CMake Test Explorer
And when i use another extension for the test explorer [CMake Test Explorer](https://marketplace.visualstudio.com/items?itemName=fredericbonnet.cmake-test-adapter) the result looks like this: 
```
Start 1: hello_test
1: Test command: /workspaces/hello-world-app-docker/out/build/Linux-gcc/GUnit_HelloWorld/test/hello_test
1: Environment variables: 
1:  SCENARIO=/workspaces/hello-world-app-docker/GUnit_HelloWorld/test/GSteps.feature
1: Test timeout computed to be: 10000000
1: Running main() from /workspaces/hello-world-app-docker/out/build/Linux-gcc/_deps/gunit-src/libs/googletest/googletest/src/gtest_main.cc
1: [==========] Running 1 test from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 1 test from Example
1: [ RUN      ] Example.Showing off
1: Set Up
1: File: /workspaces/hello-world-app-docker/GUnit_HelloWorld/test/GSteps.feature
1: Feature: Example
1: Scenario: Showing off
1: Step: 
1: 
1: Tear Down
1: File: /workspaces/hello-world-app-docker/GUnit_HelloWorld/test/GSteps.feature
1: Feature: Example
1: Scenario: Showing off
1: Step: The following steps should be shown on the screen
1: 
1: [    Given ] I create steps                                              # GSteps.feature:7
1: [    Given ] I add step a                                                # GSteps.feature:8
1: [    Given ] I add step b                                                # GSteps.feature:9
1: [     When ] I run the scenario                                          # GSteps.feature:10
1: Running...
1: [     Then ] The following steps should be shown on the screen           # GSteps.feature:11
1: 
1: [       OK ] Example.Showing off (0 ms)
1: [----------] 1 test from Example (0 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 1 test from 1 test suite ran. (0 ms total)
1: [  PASSED  ] 1 test.
1/1 Test #1: hello_test .......................   Passed    0.03 sec
```
----
Since CMake Test Explorer also uses the native test explorer and all the while does output in the desired format I think it's fair to make the assumption that the issue lies within (my usage of) CMake Tools.
Is there anything that can be done for this issue

### Additional Information

Running in dev container using docker and windows 10

**Comment by gcampbell-msft** [comment] 2023-08-02 13:10
@TheKayneGame Thanks for notifying us of this issue! I suspect that you are correct regarding it possibly being a line ending issue. We will investigate and work to get a fix in our 1.16 release.

**Comment by yhgu2000** [comment] 2024-03-06 06:43
Me too. I'm looking forward for this issue to be solved.

**Comment by gcampbell-msft** [comment] 2024-04-23 20:57
@yhgu2000 @TheKayneGame Is there any way that you could provide a minimal repro project so that we can investigate?

**Comment by yhgu2000** [comment] 2024-04-24 06:05
> @yhgu2000 @TheKayneGame Is there any way that you could provide a minimal repro project so that we can investigate?

Here you go: [3274.tar.gz](https://github.com/microsoft/vscode-cmake-tools/files/15088499/3274.tar.gz)

**Comment by v-frankwang** [comment] 2024-04-26 02:50
@yhgu2000 I'm using the program you provided but I don't seem to be reproducing the problem, hopefully you can give me some advice!

Here are my test results：
Test results：
![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/30088dcd-d8d7-4cfe-8f26-bdeebcc60242)
(VSCode) Terminal：
![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/f4546d93-644c-4cd3-a355-63b585cffed1)

**Comment by yhgu2000** [comment] 2024-04-26 04:18
@v-frankwang I think I know where the problem is: it happens only when one ssh to Linux machines from Windows, and there's some thing wrong regarding to the line endings.

I reproduced your experience in my computer too. The picture below is my observation. The VSCode on the left is using VSCode on the local Windows machine. The right is using VSCode on a remote linux machine by Remote SSH.

<img width="1280" alt="Snipaste_2024-04-26_12-09-59" src="https://github.com/microsoft/vscode-cmake-tools/assets/49391101/dbd1b7a2-3f96-4e3a-bb35-a85b0ce1674d">

In case of there's something wrong with the CMake version. The cmake on my Windows is `version 3.26.3`, and the cmake on my Linux is `version 3.22.1`.

**Comment by v-frankwang** [comment] 2024-04-26 07:43
@gcampbell-msft @yhgu2000 Following the steps given by the user, this issue we can reproduce on top of the latest VSCode and you can get some information below:

ENV:
VS Code: 1.88.1
CMake tools: 1.18.29
C/C++:1.20.2

Repro steps recording:
1. Download the project:[3274.tar.gz](https://github.com/microsoft/vscode-cmake-tools/files/15088499/3274.tar.gz) and open it in vscode.
2. Run the CMake:config command.
3. Click on the Testing icon in the left navigation bar.
4. Click the Run Test icon.
5. Observe the test results window

 Actual results：
OS: Linux
CMake version: 3.29.2
<img width="1431" alt="Screenshot 2024-04-24 at 5 03 56 PM" src="https://github.com/microsoft/vscode-cmake-tools/assets/160998958/6bbca270-ef0b-4ac1-9997-179759d71db2">

OS: Mac
CMake version: 3.29.2
<img width="1428" alt="Screenshot 2024-04-26 at 3 39 51 PM" src="https://github.com/microsoft/vscode-cmake-tools/assets/160998958/f67ce495-473f-4a71-ac3d-c6227446b2be">

**Comment by hippo91** [comment] 2024-05-12 19:07
@gcampbell-msft i think this issue is probably solved with #3752

**Comment by v-frankwang** [comment] 2024-05-17 06:37
@hippo91 This pull requests：https://github.com/microsoft/vscode-cmake-tools/pull/3752 hasn't been merged yet, I'll wait until it is and then I'll verify that this issue has been resolved.

**Closed** 2024-06-24 15:26 UTC
Labels: bug, Feature: ctest, Feature: UI, suggested

**Comment by v-frankwang** [comment] 2024-07-03 02:35
We verified the issue on the latest version and it is not reproducing, so close it.

ENV:
VS Code: 1.90.2
CMake tools: 1.19.13(pre-release)
C/C++:1.21.0(pre-release)

Actual results：
![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/a66c6004-4ee7-4cdd-b4e5-f5a152071db3)
