### ISSUE TITLE
GCC not recognized anymore

### ISSUE THREAD

**Issue by riri** [microsoft/vscode-cmake-tools#1821] opened 2021-04-29 11:20 UTC
* OS: GNU/Linux (5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux)
* VS Code: 1.55.2
* CMakeTools: 1.7.0
* Installed compilers: gcc 10.2.0, clang 11.1.0

Since yesterday, when I scanned available Kits, GCC dropped out of the list. Setting cmake.loggingLevel to debug permitted me to see GCC is not recognized (sorry output is in french):
```
[kit] Bad GCC binary "/usr/bin/gcc -v" version:10.2.0 output: Utilisation des specs internes.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Cible : x86_64-pc-linux-gnu
Configuré avec: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Modèle de thread: posix
Algorithmes de compression LTO supportés: zlib zstd
gcc version 10.2.0 (GCC) 
```
After reading issue #1575, I checked the extension code and actual gcc output and found the failure here:
https://github.com/microsoft/vscode-cmake-tools/blob/d5fa7327a0ecde7dfb86c96263d089c04cfb24b0/src/kit.ts#L156

gcc help (man gcc) explains `-v` is not used to get the version (although it is in the output) but information:
```
-v        Print (on standard error output) the commands executed to run the stages of
           compilation.  Also print the version number of the compiler driver program
           and of the preprocessor and the compiler proper.
```

The real flag to ask for version is `--version`:
```
 --version
           Display the version number and copyrights of the invoked GCC.
```
An actually using this flag returns what the extension is expecting:
```
$ gcc --version
gcc (GCC) 10.2.0
Copyright © 2020 Free Software Foundation, Inc.
Ce logiciel est un logiciel libre; voir les sources pour les conditions de copie.  Il n'y a
AUCUNE GARANTIE, pas même pour la COMMERCIALISATION ni L'ADÉQUATION À UNE TÂCHE PARTICULIÈRE.
```

I suggest that maybe you add the flag to put in the command to the `getCompilerVersion()` function, or systematically use `--version` (which works for most programs).

**Comment by andreeis** [comment] 2021-04-29 15:28
Thank you for opening this issue. You are saying that this started to happen recently, like a regression? Since when? The extension used "-v" instead of "--version" since always, we didn't change that. The referenced issue (https://github.com/microsoft/vscode-cmake-tools/issues/1575) was fixed for CMake Tools 1.6 quite a while ago.
We will investigate and fix of course. I was just curious why this started to happen recently. Maybe you got a new gcc installation which doesn't work with what we implemented in our version analysis?

**Comment by bobbrow** [comment] 2021-04-29 16:03
The extension parses all lines when invoking the compiler with `-v`.  The compiler version is at the end like the switch documentation describes.
```
gcc version 10.2.0 (GCC) 
```
There was a change made recently to try to look for a localized "version" string in addition to the English "version" string.  The regression would appear to be related to that change.  We don't need to change the switch passed to gcc.  In fact, doing so will change the format of the version printed and will break the current regexes used to parse it.

https://github.com/microsoft/vscode-cmake-tools/blob/4f2bf2163f8e78ad59bc0c43dfd3cdec804089c1/src/kit.ts#L172

**Comment by riri** [comment] 2021-04-29 19:04
> Maybe you got a new gcc installation which doesn't work with what we implemented in our version analysis?

@bobbrow is actually right. A quick test on [regex101](https://regex101.com/r/vvEvtr/1) confirms that the regex works if `versionWorld` is `version`.

**Comment by bobbrow** [comment] 2021-04-29 19:34
The regex on the next line down does use "version" directly as a backup, so I'm not sure what's going wrong.  We've run into issues in the past with compiler outputs being translated.  I spent a day trying to get GCC to spit out non-English and never got it working.

I think the right fix is to set the [environment variables that GCC supposedly looks for](https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html) to determine the locale whenever we invoke it so that the output is always in English, but because we can't repro it here, we haven't been able to test that it works (especially since it didn't work the other way around).

If you'd be willing to clone this repo and test out some stuff for us, we might be able to finally solve this problem.

**Comment by riri** [comment] 2021-04-29 20:23
For gcc outputing in something else than english, you need several things : being on a complete shell (on Windows, Msys  wont work because they didn't implement locales, neither Cygwin). If you are on Unix/Linux:
generate the locale for a country (it is distribution dependent, but I suppose you have the glibc locale-gen):
1) update `/etc/locale.gen` to uncomment one country code... let's say `fr_FR.UTF-8 UTF-8` ;-)
2) `sudo locale-gen` to update the locales database
3) run gcc with `env LANG=fr_FR.UTF-8 gcc -v`

For cloning the repo, why not, if I am guided (I never used an extension from outside of ms vscode marketplace).

**Comment by bobbrow** [comment] 2021-04-29 23:26
I built a VSIX for you ([here](https://github.com/microsoft/vscode-cmake-tools/suites/2617691844/artifacts/57356650)) that you can install with the "Install From VSIX" command in VS Code.  If you download and install that, you can skip cloning the repo and building the extension yourself as I mentioned previously.

Once installed, please set the `"cmake.loggingLevel"` setting to `"debug"` and then run the "Scan For Kits" command.  If this method works, you should see gcc logging in English in the "Output" panel (there's a drop down to select the "CMake/Build" channel) somewhat like this (search for "[GCC]"):
```
[kit] [GCC] Using built-in specs.
[kit] [GCC] COLLECT_GCC=C:\MinGW\bin\mingw32-gcc.exe
[kit] [GCC] COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
[kit] [GCC] Target: mingw32
[kit] [GCC] Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
[kit] [GCC] Thread model: win32
[kit] [GCC] gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
[kit] Detected GCC compiler: C:\MinGW\bin\mingw32-gcc.exe
```

If it's not working, then the output will still be French.  Please don't change any of your language settings while testing this. When you're done, you can use the "Install Specific Version of Extension..." command to revert back to 1.7.1 if you want, but if this version works for you, you can keep it installed and use it until we release a patch.

**Comment by riri** [comment] 2021-04-29 23:41
Installed, reloaded vscode, new cmaketool version: 1.7.0

Ouput still in French, here is the complete output of the scan:
```
[extension] [8319] cmake.scanForKits started
[kitsController] Rescanning for kits
[kit] Scanning for Kits on system
[kit] Scanning directory /home/riri/Work/go/bin for compilers
[kit] Scanning directory /home/riri/.local/bin for compilers
[kit] Scanning directory /usr/local/sbin for compilers
[kit] Scanning directory /usr/local/bin for compilers
[kit] Scanning directory /usr/bin for compilers
[kit] Scanning directory /usr/lib/jvm/default/bin for compilers
[kit] Scanning directory /usr/bin/site_perl for compilers
[kit] Scanning directory /usr/bin/vendor_perl for compilers
[kit] Scanning directory /usr/bin/core_perl for compilers
[kit] Skipping scan of not existing path undefined\LLVM\bin
[kit] Found 0 kits in directory undefined\LLVM\bin
[kit] Found 0 kits in directory /home/riri/Work/go/bin
[kit] Found 0 kits in directory /home/riri/.local/bin
[kit] Found 0 kits in directory /usr/local/sbin
[kit] Found 0 kits in directory /usr/local/bin
[kit] Found 0 kits in directory /usr/lib/jvm/default/bin
[kit] Found 0 kits in directory /usr/bin/site_perl
[kit] Found 0 kits in directory /usr/bin/vendor_perl
[kit] Found 0 kits in directory /usr/bin/core_perl
[kit] Testing Clang binary: /usr/bin/clang
[kit] Testing Clang binary: /usr/bin/clang
[kit] Testing Clang binary: /usr/bin/clang-11
[kit] Testing Clang binary: /usr/bin/clang-11
[kit] Testing GCC binary: /usr/bin/gcc
[kit] Testing GCC binary: /usr/bin/gcc
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0
[kit] Bad GCC binary "/usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0 -v" version:10.2.0 output: Utilisation des specs internes.
COLLECT_GCC=/usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Cible : x86_64-pc-linux-gnu
Configuré avec: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Modèle de thread: posix
Algorithmes de compression LTO supportés: zlib zstd
gcc version 10.2.0 (GCC) 

[kit] Bad GCC binary "/usr/bin/x86_64-pc-linux-gnu-gcc -v" version:10.2.0 output: Utilisation des specs internes.
COLLECT_GCC=/usr/bin/x86_64-pc-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Cible : x86_64-pc-linux-gnu
Configuré avec: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Modèle de thread: posix
Algorithmes de compression LTO supportés: zlib zstd
gcc version 10.2.0 (GCC) 

[kit] Bad GCC binary "/usr/bin/gcc -v" version:10.2.0 output: Utilisation des specs internes.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Cible : x86_64-pc-linux-gnu
Configuré avec: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Modèle de thread: posix
Algorithmes de compression LTO supportés: zlib zstd
gcc version 10.2.0 (GCC) 

[kit] Detected Clang compiler: /usr/bin/clang-11
[kit] Detected Clang compiler: /usr/bin/clang-11
[kit] Detected Clang compiler: /usr/bin/clang
[kit] Detected Clang compiler: /usr/bin/clang
[kit] Found 2 kits in directory /usr/bin
[kit] Found Kit: Clang 11.1.0 x86_64-pc-linux-gnu
[kit] Found Kit: Clang 11.1.0 x86_64-pc-linux-gnu
[kitsController] Saving kits to /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[kitsController] Saving new kits to /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[extension] [8319] cmake.scanForKits finished (returned undefined)
[kit] Reading kits file /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Successfully loaded 1 kits from /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[extension] [5560] cmake.selectKit started
[kitsController] Start selection of kits. Found 3 kits.
[kitsController] Opening kit selection QuickPick
[kitsController] User cancelled Kit selection
[extension] [5560] cmake.selectKit finished (returned false)
```

**Comment by bobbrow** [comment] 2021-04-29 23:47
CMake Tools version should be 1.7.2 when you install that VSIX.  I'm not seeing the logging I added in here either, so I don't think my patch was installed.  Can you try again?  Please also run the "Reload Window" command to make sure VS Code is using the right version after installing it.

**Comment by bobbrow** [comment] 2021-04-29 23:54
One other piece of context is that the reason this is failing isn't because the version parsing changed.  It's because of the `target` parsing that was added.  Had we added code to translate "target" to "cible", I don't think that would have worked either because it appears that you're using the English language pack in VS Code anyway.

**Comment by riri** [comment] 2021-04-30 11:31
My bad, I instaled the wrong vsix. Now I am on **v1.7.2-63ccbad** and after a scan I get GCC

![version](https://i.imgur.com/iaXqHTN.png)

Here is the output of the extensino at debug level for the scan:
```
[extension] [6246] cmake.scanForKits started
[kitsController] Rescanning for kits
[kit] Scanning for Kits on system
[kit] Scanning directory /home/riri/Work/go/bin for compilers
[kit] Scanning directory /home/riri/.local/bin for compilers
[kit] Scanning directory /usr/local/sbin for compilers
[kit] Scanning directory /usr/local/bin for compilers
[kit] Scanning directory /usr/bin for compilers
[kit] Scanning directory /usr/lib/jvm/default/bin for compilers
[kit] Scanning directory /usr/bin/site_perl for compilers
[kit] Scanning directory /usr/bin/vendor_perl for compilers
[kit] Scanning directory /usr/bin/core_perl for compilers
[kit] Skipping scan of not existing path undefined\LLVM\bin
[kit] Found 0 kits in directory undefined\LLVM\bin
[kit] Found 0 kits in directory /home/riri/Work/go/bin
[kit] Found 0 kits in directory /home/riri/.local/bin
[kit] Found 0 kits in directory /usr/local/sbin
[kit] Found 0 kits in directory /usr/local/bin
[kit] Found 0 kits in directory /usr/lib/jvm/default/bin
[kit] Found 0 kits in directory /usr/bin/site_perl
[kit] Found 0 kits in directory /usr/bin/vendor_perl
[kit] Found 0 kits in directory /usr/bin/core_perl
[kit] Testing Clang binary: /usr/bin/clang
[kit] Testing Clang binary: /usr/bin/clang
[proc] Executing command: /usr/bin/clang -v
[kit] Testing Clang binary: /usr/bin/clang-11
[kit] Testing Clang binary: /usr/bin/clang-11
[proc] Executing command: /usr/bin/clang-11 -v
[kit] Testing GCC binary: /usr/bin/gcc
[kit] Testing GCC binary: /usr/bin/gcc
[proc] Executing command: /usr/bin/gcc -v
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc
[proc] Executing command: /usr/bin/x86_64-pc-linux-gnu-gcc -v
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0
[kit] Testing GCC binary: /usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0
[proc] Executing command: /usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0 -v
[kit] [GCC] Using built-in specs.
[kit] [GCC] COLLECT_GCC=/usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0
[kit] [GCC] COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
[kit] [GCC] Target: x86_64-pc-linux-gnu
[kit] [GCC] Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
[kit] [GCC] Thread model: posix
[kit] [GCC] Supported LTO compression algorithms: zlib zstd
[kit] [GCC] gcc version 10.2.0 (GCC)
[kit] Detected GCC compiler: /usr/bin/x86_64-pc-linux-gnu-gcc-10.2.0
[kit] [GCC] Using built-in specs.
[kit] [GCC] COLLECT_GCC=/usr/bin/x86_64-pc-linux-gnu-gcc
[kit] [GCC] COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
[kit] [GCC] Target: x86_64-pc-linux-gnu
[kit] [GCC] Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
[kit] [GCC] Thread model: posix
[kit] [GCC] Supported LTO compression algorithms: zlib zstd
[kit] [GCC] gcc version 10.2.0 (GCC)
[kit] Detected GCC compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
[kit] [GCC] Using built-in specs.
[kit] [GCC] COLLECT_GCC=/usr/bin/gcc
[kit] [GCC] COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
[kit] [GCC] Target: x86_64-pc-linux-gnu
[kit] [GCC] Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
[kit] [GCC] Thread model: posix
[kit] [GCC] Supported LTO compression algorithms: zlib zstd
[kit] [GCC] gcc version 10.2.0 (GCC)
[kit] Detected GCC compiler: /usr/bin/gcc
[kit] [Clang] clang version 11.1.0
[kit] [Clang] Target: x86_64-pc-linux-gnu
[kit] [Clang] Thread model: posix
[kit] [Clang] InstalledDir: /usr/bin
[kit] [Clang] Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Candidate multilib: .;@m64
[kit] [Clang] Candidate multilib: 32;@m32
[kit] [Clang] Selected multilib: .;@m64
[kit] Detected Clang compiler: /usr/bin/clang-11
[kit] Detected Clang compiler: /usr/bin/clang-11
[kit] [Clang] clang version 11.1.0
[kit] [Clang] Target: x86_64-pc-linux-gnu
[kit] [Clang] Thread model: posix
[kit] [Clang] InstalledDir: /usr/bin
[kit] [Clang] Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0
[kit] [Clang] Candidate multilib: .;@m64
[kit] [Clang] Candidate multilib: 32;@m32
[kit] [Clang] Selected multilib: .;@m64
[kit] Detected Clang compiler: /usr/bin/clang
[kit] Detected Clang compiler: /usr/bin/clang
[kit] Found 5 kits in directory /usr/bin
[kit] Found Kit: Clang 11.1.0 x86_64-pc-linux-gnu
[kit] Found Kit: Clang 11.1.0 x86_64-pc-linux-gnu
[kit] Found Kit: GCC 10.2.0 x86_64-pc-linux-gnu
[kit] Found Kit: GCC 10.2.0 x86_64-pc-linux-gnu
[kit] Found Kit: GCC 10.2.0 x86_64-pc-linux-gnu
[kitsController] Saving kits to /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[kitsController] Saving new kits to /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[extension] [6246] cmake.scanForKits finished (returned undefined)
[kit] Reading kits file /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Successfully loaded 2 kits from /home/riri/.local/share/CMakeTools/cmake-tools-kits.json
[extension] [2133] cmake.selectKit started
[kitsController] Start selection of kits. Found 4 kits.
[kitsController] Opening kit selection QuickPick
[kitsController] User cancelled Kit selection
[extension] [2133] cmake.selectKit finished (returned false)
[extension] [7708] cmake.selectKit started
[kitsController] Start selection of kits. Found 4 kits.
[kitsController] Opening kit selection QuickPick
[kitsController] User cancelled Kit selection
[extension] [7708] cmake.selectKit finished (returned false)
```

**Comment by bobbrow** [comment] 2021-04-30 16:03
Thanks for reporting back.  I'll prepare the PR for inclusion into 1.7.2.

**Comment by andreeis** [comment] 2021-05-04 18:40
@riri, if you would like, you can try this vsix (https://github.com/microsoft/vscode-cmake-tools/actions/runs/811030625) to get unblocked with a fix for this issue before we release 1.7.2.

**Comment by bobbrow** [comment] 2021-05-04 18:45
@riri I know you have a build with my patch in it already, but since the final fix is slightly different than the one you tested, it might be useful for you to try the one @andreeis shared just in case...  There is also a code page fix in there and that potentially has an impact on you since you are using another locale.

**Comment by riri** [comment] 2021-05-04 18:47
Just tested, it works too (now on `v1.7.2-7fd5128`). Thank you for support, I can continue with g++ until the clang++ issue is fixed ;-)

**Comment by bobbrow** [comment] 2021-05-04 19:55
If you are blocked by that other bug, you should be able to manually edit your kits JSON file with the "Edit user-local Kits" command.  Just fix the compiler in there and don't scan for kits again. 😉

**Closed** 2021-05-06 19:27 UTC
Labels: Feature: kits, bug, fixed (release pending)
