### ISSUE TITLE
Failed to generate debugger configuration on version 1.2 

### ISSUE THREAD

**Issue by n-fallahinia** [microsoft/vscode-cmake-tools#910] opened 2019-11-12 23:38 UTC
### Brief Issue Summary

When Trying to run the debugger, the following message appears:
 `[debugger] Unable to automatically determine debugger corresponding to compiler: {}`

Although it works with no issue on version 1.1.3

### Developer Tools Log
`[build] Starting build`
`[proc] Executing command: /usr/local/bin/cmake --build /home/navid/visp-ws/projects/image_track/build --config Debug --target image-track-barcode -- -j 14`
`[build] [100%] Built target image-track-barcode`
`[build] Build finished with exit code 0`
`[debugger] Unable to automatically determine debugger corresponding to compiler: {}`
`[main] Failed to generate debugger configuration`

### Platform and Versions

- **Operating System**: Ubuntu 18.04
- **CMake Version**: 3.15.0
- **VSCode Version**: 1.39.2
- **CMake Tools Extension Version**: 1.2.1
- **Compiler/Toolchain**:  GCC 7.3

**Comment by jaylotw** [comment] 2019-11-13 09:10
See https://github.com/microsoft/vscode-cmake-tools/issues/884#issuecomment-551915939

**Comment by jaylotw** [comment] 2019-11-13 09:10
Duplicate of #884

**Comment by bobbrow** [comment] 2019-11-13 17:45
We should have a fix for this available today.

**Closed by bobbrow** 2019-11-13 17:45 UTC
Labels: Feature: debug, bug, duplicate
