### ISSUE TITLE
Build and clean rebuild commands ignore CMakeLists.txt changes

### ISSUE THREAD

**Issue by davl3232** [microsoft/vscode-cmake-tools#312] opened 2018-02-13 21:03 UTC
### Brief Issue Summary

When I build using the commands "build" and "clean rebuild" from the command palette it generates a build using the initial CMakeLists.txt, so the products of the build are not what they should. This seems to happen when I copy a folder and update the CMakeLists.txt

### Expected:

1. Open directory copied with vscode
2. Change CMakeLists.txt (for example executable target name)
3. From command palette execute clean rebuild
4. Check build folder inside opened directory: the executable has the new name given in CMakeLists.txt.

### Apparent Behavior:

...
4. Check build folder inside opened directory: the executable uses the previous name instead of the new one.

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.20.0
- **CMake Tools Extension Version**: 0.10.4
- **Compiler/Toolchain**: Apple LLVM version 9.0.0 (clang-900.0.39.2)

**Comment by Randshot** [comment] 2018-03-01 12:56
@KoeMai @vector-of-bool Does this here still apply to the refactor (beta4) version?
I have looked at the code and there seems to be a variable that indicates whether the cms-driver state is dirty (https://github.com/vector-of-bool/vscode-cmake-tools/blob/57eee9adbf98c45bea53c86d01ba2145d70de850/src/cms-driver.ts#L189), but is never used anywhere, so I assume that this is still a problem. If it is, then I would suggest adding this as a beta5 goal.

**Comment by Randshot** [comment] 2018-03-02 13:38
@davl3232 I have investigated this a bit and I can't reproduce your problem description.
Whenever I make changes to the `CMakeLists.txt` file, it automatically re-configures when running build.
Note that I tested this on the latest `0.11.0-beta4`.
Maybe you can also test it on the above mentioned beta and report back.

**Comment by vector-of-bool** [comment] 2018-03-10 23:59
Moving this to the backlog since we  need reproduction info.

**Comment by bobbrow** [comment] 2019-07-24 16:43
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.

**Closed by bobbrow** 2019-07-24 16:43 UTC
Labels: bug, more info needed
