### ISSUE TITLE
Complete recompilation at each build.

### ISSUE THREAD

**Issue by maximecharriere** [microsoft/vscode-cmake-tools#1768] opened 2021-04-15 09:13 UTC
### Brief Issue Summary
If I run the `CMake : Build` command, the whole project is recompiled, even if no file has been modified. 

### Expected:

I have a C++ project with librairies, pre-compiled headers and source code. I want that only the modified files are recompiled, and not the whole project.
It takes me more than 2 minutes every time I do `CMake: Build`, even if I don't modify any code. 

### CMake Tools Log

This command is run by the extension when I do `CMake: Build` :

```
Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/maxime.charrier1/SynologyDrive/Document/HEIG_VD/Tests/HelloCMake/build --config Release --target HelloCMake -- /maxcpucount:14
```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.20.1
- **VSCode Version**: 1.55.2
- **CMake Tools Extension Version**: 1.6.0
- **Compiler/Toolchain**: Visual Studio 16 2019

**Comment by maximecharriere** [comment] 2021-04-16 12:29
I asked a question about this topic with more informations on [StackOverflow](https://stackoverflow.com/questions/67095889/vscode-cmake-extension-rebuild-all-project-each-time) .

I also tried to use GCC and MinGW Makefiles, but again all libraries are recompiled at each build.

**Comment by andreeis** [comment] 2021-04-16 21:28
@maximecharriere, I am not sure exactly why this happens and I would be happy to dig more next week. Right now we are preparing the CMake Tools 1.7 release.
From what I know, the extension will always invoke the build command and CMake is responsible for skipping any "up to date" items. Do you see any difference when you build with the extension compared to when you build manually from the terminal? The CMake Tools extension should be just a wrapper over the manual scenarios. Also, can you recommend (after you test it in your environment) a different build command that would do what you expect? Maybe we can help by tweaking the command a little bit, although I would be surprised.
Maybe your project has makefiles with targets that are always seen as "out of date"?

**Comment by maximecharriere** [comment] 2021-04-19 14:53
I used the Hello World project given by _VSCode CMake Tools_ (the one generated with the `CMake:Quick Start` command) to make the following tests.

With the `MinGW Makefiles` CMAKE_GENERATOR using the GCC compiler, the project **isn't** rebuild each time.  
With the `Visual Studio 16 2019` CMAKE_GENERATOR using the MSVC compiler, the project **is** rebuild each time.  

If I open the project directly in Visual Studio 2019, the CMake Tools from VS2019 use the `Ninja` CMAKE_GENERATOR and the MSVC compiler. With this configuration the project **isn't** rebuild each time.  
However, I can't directly configure CMake by myself to use Ninja and MSVC. CMake tells me: 
```
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.
```
(When using Ninja and MSVC in VS2019, this error isn't throw).  

The resume:
- Project generated by `Visual Studio 16 2019` toolkit rebuild each time
- I'm unable to use VSCode with `Ninja` toolkit and MSVC compiler  


I need to use MSVC compiler in my project, so for now I have to use VS2019, but my goal is to only use VSCode in the futur. If you take a look at the problem in the future, I'll be happy to hear about it.

**Comment by andreeis** [comment] 2021-04-20 21:32
I don't know right now why with a VS generator your project builds every time, I will use your repro steps on my side and investigate.
Also I've never seen the Ninja+cl error, I will try that too. Until I get to do that (or to help if I don't reproduce it because I've used this scenario in the past with success) please share the output channel content after you set "cmake.loggingLevel": "Debug", reload your project in VSCode, clean re-configure (the command "Delete cache and re-configure". Copy the output aside (because the build will clear the output channel), then build and copy the output again.
I am hoping to see in these logs something to explain the error (maybe vcvars not run properly...).

**Comment by maximecharriere** [comment] 2021-04-21 07:59
My Ninja + CL problem is not due to the CMake Tool Extension, but more to a configuration error on my side.  If I use cmake.exe directly, the problem is the same.  

First, CMake Tools could not find the Ninja toolkit by itself:
![image](https://user-images.githubusercontent.com/51918753/115511740-7dcd0080-a281-11eb-9fb7-dc86b1b87a89.png)
So I added this lines in the `cmake-tools-kits.json` file.
```json
{
  "name": "Ninja & CL",
  "compilers": {
    "C": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29910\\bin\\Hostx64\\x64\\cl.exe",
    "CXX": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29910\\bin\\Hostx64\\x64\\cl.exe"
  },
  "preferredGenerator": {
    "name": "Ninja"
  }
},
```

And the output of the CMake configuration is :
```bash
[main] Configuring folder: CmakeToolTest 
[main] Saving open files before configure/build
[driver] Removing c:/Users/maxime.charrier1/Downloads/CmakeToolTest/build/CMakeCache.txt
[driver] Removing c:\Users\maxime.charrier1\Downloads\CmakeToolTest\build\CMakeFiles
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[driver] Start configure 
[driver] Runnnig pre-configure checks and steps
[driver] Using compilers in Ninja & CL for configure
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[cmakefileapi-driver] Configuring using kit
[cmakefileapi-driver] Invoking CMake C:\Program Files\CMake\bin\cmake.EXE with arguments ["--no-warn-unused-cli","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_BUILD_TYPE:STRING=Release","-DCMAKE_C_COMPILER:FILEPATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29910\\bin\\Hostx64\\x64\\cl.exe","-DCMAKE_CXX_COMPILER:FILEPATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29910\\bin\\Hostx64\\x64\\cl.exe","-Hc:/Users/maxime.charrier1/Downloads/CmakeToolTest","-Bc:/Users/maxime.charrier1/Downloads/CmakeToolTest/build","-G","Ninja"]
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\cl.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\cl.exe" -Hc:/Users/maxime.charrier1/Downloads/CmakeToolTest -Bc:/Users/maxime.charrier1/Downloads/CmakeToolTest/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is MSVC 19.28.29914.0
[cmake] -- The CXX compiler identification is MSVC 19.28.29914.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - failed
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - broken
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: C:/Users/maxime.charrier1/Downloads/CmakeToolTest/build/CMakeFiles/CMakeTmp
[cmake]     
[cmake]     Run Build Command(s):C:/dev/ninja/ninja.exe cmTC_f1f8a && [1/2] Building C object CMakeFiles\cmTC_f1f8a.dir\testCCompiler.c.obj
[cmake]     [2/2] Linking C executable cmTC_f1f8a.exe
[cmake]     FAILED: cmTC_f1f8a.exe 
[cmake]     cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_f1f8a.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_f1f8a.dir\testCCompiler.c.obj  /out:cmTC_f1f8a.exe /implib:cmTC_f1f8a.lib /pdb:cmTC_f1f8a.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
[cmake]     RC Pass 1: command "rc /fo CMakeFiles\cmTC_f1f8a.dir/manifest.res CMakeFiles\cmTC_f1f8a.dir/manifest.rc" failed (exit code 0) with the following output:
[cmake]     The system cannot find the file specified
[cmake]     ninja: build stopped: subcommand failed.
[cmake]     
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:2 (project)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Users/maxime.charrier1/Downloads/CmakeToolTest/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "C:/Users/maxime.charrier1/Downloads/CmakeToolTest/build/CMakeFiles/CMakeError.log".
[extension] [8220] cmake.cleanConfigure finished (returned 1)
```

And the [CMakeError.log](https://gist.github.com/maximecharriere/1d0e24f79e75b74f25a08344b5504d24) file.

**Comment by andreeis** [comment] 2021-04-21 18:45
I think vcvars (a script that sets up many things cl.exe needs and which I see is not run at all in your case) is automatically executed by CMake Tools only for VS kits. This is one thing that we can consider fixing in future (to trigger this automatic execution for any kit that uses cl.exe as compiler and I may open a new GitHub report about this after we analyze your original report on all sides).

Let's see if we can unblock you now.
Try to write one more custom kit. Open cmake-tools-kits.json (you can use the "CMake: Edit user-local CMake Kits" command in the palette), start from a VS kit that uses the cl.exe you want, copy paste, write a new name and change its preferred generator from VS to Ninja.
  {
    "name": "My Custom Visual Studio Enterprise 2019 Release - x86",
    "visualStudio": "c5421408",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Ninja"
    }
  },
I am hoping that this will run vcvars, your cl.exe will work and your project will use ninja and not msbuild.exe.

Then, if the idea above doesn't work, another workaround for you is to use your custom Ninja kit but open your project in a VSCode instance that was spawned from an environment that ran one VS vcvars script before. That will set up some paths needed by cl.exe to function properly. 
For example, on my system, these scripts are at  c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvar*.bat. Inspect those on your side to see which one you want to run and with what parameters. Let me know if using your custom Ninja kit from an environment set up with one vcvars*.bat script works for you.

**Comment by maximecharriere** [comment] 2021-04-22 08:56
Hey your first solution works very well! Thank you  
Now with Ninja and CL only modified files are recompiled. Perfect

**Comment by andreeis** [comment] 2021-04-22 16:11
Wonderful, I am glad that you are unblocked. We will keep the issue for later investigation.

**Comment by andreeis** [comment] 2021-11-02 07:11
@TheMasterMaind, does this happen when you build from outside VSCode? Or do you notice any parameter missing/wrong in the command line that the CMake Tools extension is calculating for the build operation?
If you want to easily see the build command, run from the palette "CMake: Show build command".
This would either be a cmake bug or we generate a wrong build command.

**Comment by kc9jud** [comment] 2021-11-05 02:36
@TheMasterMaind @andreeis This seems to be related: https://gitlab.kitware.com/cmake/cmake/-/issues/17330#note_1050167

**Comment by TheMasterMaind** [comment] 2021-11-05 08:45
@andreeis This does not happen outside of VSCode. Also running the very same build command that the CMake Tools would run does not rebuild all code every time.

@kc9jud Thank you so much! After changing /bin/clang-13 to /usr/bin/clang-13 the code does not get recompiled every time.

**Comment by andreeis** [comment] 2021-11-05 18:34
@kc9jud, thank you very much for finding that related item and for unblocking @TheMasterMaind. We can close this report now.

**Closed by andreeis** 2021-11-05 18:34 UTC
Labels: Feature: build, investigate
