### ISSUE TITLE
Can't debug any program after 1.2.1 update

### ISSUE THREAD

**Issue by piotr-szuberski** [microsoft/vscode-cmake-tools#905] opened 2019-11-12 09:41 UTC
After the 1.2.1 update I can't debug any program. The build is executed but the extension can't determine a debugger corresponding to the compiler, even though the kit is selected correctly (tried with GCC 7.4.0, clang 8, GCC 9).
The problem dissappears after downgrade back to CMake Tools 1.1.3, so it shouldn't be related to my environment.
I tried on 2 computers with Ubuntu 19.10 and 18.04.

The rest of functionalities I used works correctly - I am able to configure, build, execute program with selected kits.

### CMake Tools Log

Output after clean reconfigure (the first line seems to be the most important):
```
[cms-client] Configuring using the "Unix Makefiles" CMake generator with plattform "undefined" and toolset {}
[cmake] The C compiler identification is GNU 7.4.0
[cmake] The CXX compiler identification is GNU 7.4.0
[cmake] Check for working C compiler: /usr/bin/gcc-7
[cmake] Check for working C compiler: /usr/bin/gcc-7 -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Detecting C compile features
[cmake] Detecting C compile features - done
[cmake] Check for working CXX compiler: /usr/bin/g++-7
[cmake] Check for working CXX compiler: /usr/bin/g++-7 -- works
[cmake] Detecting CXX compiler ABI info
[cmake] Detecting CXX compiler ABI info - done
[cmake] Detecting CXX compile features
[cmake] Detecting CXX compile features - done
[cmake] Found PythonInterp: /usr/bin/python (found version "2.7.15") 
[cmake] Looking for pthread.h
[cmake] Looking for pthread.h - found
[cmake] Performing Test CMAKE_HAVE_LIBC_PTHREAD
[cmake] Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
[cmake] Looking for pthread_create in pthreads
[cmake] Looking for pthread_create in pthreads - not found
[cmake] Looking for pthread_create in pthread
[cmake] Looking for pthread_create in pthread - found
[cmake] Found Threads: TRUE  
[cmake] Configuring done
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
[cmake] 
[cmake] 
[cmake] Generating done
```

Output after clicking debug after a successful build:
```
[debugger] Unable to automatically determine debugger corresponding to compiler: {}
[main] Failed to generate debugger configuration
```

- **Operating System**: Ubuntu
- **CMake Version**: 3.16.0-rc3
- **VSCode Version**: 1.39.2
- **CMake Tools Extension Version**: 1.2.1
- **Compiler/Toolchain**: GCC 7.4.0, GCC 9.1.0, Clang 6.0.0

**Comment by bobbrow** [comment] 2019-11-12 18:12
This looks like a duplicate of #884. We have a fix for it and are planning to release an update today. We're sorry for the inconvenience!

**Closed** 2019-11-12 18:12 UTC
