### ISSUE TITLE
Show a quickPick of all the CMakeLists.txt inside the project (if not in the root)

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#533] opened 2018-09-06 05:13 UTC
### Brief Issue Summary

CMake Tools doesn't detect CMakeLists.txt automatically if it is not in the root directory on Linux (I haven't tried other OSs). The CMakeLists.txt is in a subdirectory of the root directory and cmake.sourceDirectory is set to point to that subdirectory.
If I execute the command to configure the project manually it runs as expected.

### Expected:

The same behavior as if CMakeLists.txt is in the root directory: when the project is opened CMake Tools should ask me if I want to configure the project.

**Comment by jimbo1qaz** [comment] 2018-09-13 01:10
Building a CMakeLists.txt in a subdirectory (Windows) is a pain.

First I have to go to VS Code settings, change the workspace `cmake.sourceDirectory`to the subfolder.

Then I get exception "[rollbar] Unhandled exception: Unhandled Promise rejection: configure [cmake-server] Failed to activate protocol version: "CMAKE_HOME_DIRECTORY" is set but incompatible with configured source directory value. {}".

To fix this, I have to

**Comment by vector-of-bool** [comment] 2018-09-17 04:12
VSCode extensions have something called "activation events," which they register in their `package.json`. Most activation events are when one of the command palette commands is invoked. When an activation event is triggered, only then will VSCode load the extension and it can register itself. CMake Tools has an activation event if it detects a `CMakeLists.txt` in the root directory of the workspace, but any subdirectories do not work. It is during extension activation that it generates this prompt.

There is a special `*` activation event that will _immediately_ and _always_ load the extension in VSCode. Its usage is dis-recommended, however. I would need to be careful about using it, but it may be an option.

**Comment by mwheeler** [comment] 2019-02-15 12:58
Doesn't this just require `"workspaceContains:**/CMakeLists.txt"` ? (though `cmake.sourceDirectory` is still needed to decide 'which' CMakeLists.txt to use if there are multiple)

**Comment by Zingam** [comment] 2019-02-16 15:37
cmake.sourceDirectory

Doesn't seem to work now:

```
[cmake] CMake version: 3.10.2
[cmake] The C compiler identification is unknown
[cmake] The C compiler identification is unknown
[cmake] CMake Error: Could not find cmake module file: ./CMakeFiles/3.10.2/CMakeCCompiler.cmake
[cmake] CMake Error: Could not find cmake module file: ./CMakeFiles/3.10.2/CMakeCCompiler.cmake
[cmake] The CXX compiler identification is unknown
[cmake] The CXX compiler identification is unknown
[cmake] CMake Error: Could not find cmake module file: ./CMakeFiles/3.10.2/CMakeCXXCompiler.cmake
[cmake] CMake Error: Could not find cmake module file: ./CMakeFiles/3.10.2/CMakeCXXCompiler.cmake
[cmake] Check for working C compiler: /usr/bin/gcc-7
[cmake] Check for working C compiler: /usr/bin/gcc-7
[cmake] CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
[cmake]   Unknown extension ".c" for file
[cmake] 
[cmake]     ./CMakeFiles/CMakeTmp/testCCompiler.c
[cmake] 
[cmake]   try_compile() works only for enabled languages.  Currently these are:
[cmake] 
[cmake]     C CXX
[cmake] 
[cmake]   See project() command to enable other languages.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:7 (project)
[cmake] 
[cmake] 
[cmake] CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
[cmake]   Unknown extension ".c" for file
[cmake] 
[cmake]     ./CMakeFiles/CMakeTmp/testCCompiler.c
[cmake] 
[cmake]   try_compile() works only for enabled languages.  Currently these are:
[cmake] 
[cmake]     C CXX
[cmake] 
[cmake]   See project() command to enable other languages.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:7 (project)
[cmake] 
[cmake] 
[cmake] Check for working C compiler: /usr/bin/gcc-7 -- broken
[cmake] Check for working C compiler: /usr/bin/gcc-7 -- broken
[cmake] CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "/usr/bin/gcc-7"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:7 (project)
[cmake] 
[cmake] 
[cmake] CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "/usr/bin/gcc-7"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:7 (project)
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] Configuring incomplete, errors occurred!
[cmake] CMake version: 3.10.2
[cmake] CMake version: 3.10.2
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.
[cmake] The C compiler identification is unknown
[cmake] CMake Error: Could not find cmake module file: ./CMakeFiles/3.10.2/CMakeCCompiler.cmake
[cmake] The CXX compiler identification is unknown
[cmake] CMake Error: Could not find cmake module file: ./CMakeFiles/3.10.2/CMakeCXXCompiler.cmake
[cmake] Check for working C compiler: /usr/bin/gcc-7
[cmake] CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
[cmake]   Unknown extension ".c" for file
[cmake] 
[cmake]     ./CMakeFiles/CMakeTmp/testCCompiler.c
[cmake] 
[cmake]   try_compile() works only for enabled languages.  Currently these are:
[cmake] 
[cmake]     C CXX
[cmake] 
[cmake]   See project() command to enable other languages.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:7 (project)
[cmake] 
[cmake] 
[cmake] Check for working C compiler: /usr/bin/gcc-7 -- broken
[cmake] CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "/usr/bin/gcc-7"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:7 (project)
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.
```

**Comment by akanakia** [comment] 2019-02-21 21:01
Would love to have the ability to use CMake tools in vscode from a sub-directory of current working dir. It is particularly painful when using something like pybind with cmake where it is necessary to put the CMakeLists.txt in a sub-folder instead of the root to keep the project structure sensible (see below). 

/root
|
|- /cpp
|- /cpp/src
|- /cpp/include
|- /cpp/CMakeLists.txt
|- /python
|- /python/python-setup-stuff...

with the above project structure, the extension cannot find /root/cpp/CMakeLists.txt and so we have to do all the building manually.

**Comment by HunterZ** [comment] 2019-05-14 17:36
CMake's Eclipse generator requires that CMakeLists.txt live in a sibling of the build directory, so I've got an existing project with myProject/src/CMakeLists.txt and a myProject/debug build directory. This all works, but I can't seem to get vscode + CMake Tools working with it.

I tried opening the folder configuration and putting this in settings.json:
```json
{
    "cmake.buildDirectory": "${workspaceRoot}/debug",
    "cmake.sourceDirectory": "${workspaceRoot}/src"
}
```

But I get `[rollbar] Unhandled exception: Unhandled Promise rejection: clean [cmake-server] Failed to activate protocol version: "sourceDirectory" is not a directory. {}`

**Comment by bobbrow** [comment] 2019-07-22 22:18
I submitted a PR for this.  It should be included in the 1.2.0 release.

**Comment by Zingam** [comment] 2019-07-23 15:55
@bobbrow I just found out that: "Maintainer Changes (7/12/19)
vector-of-bool has moved on to other things and Microsoft is now maintaining this extension. Thank you vector-of-bool for all of your hard work getting this extension to where it is today!"
And this is awesome news! I don't know if my nagging on the VS blog helped but thank you very much!
Please consider next adding support for CMakeSettings.json, etc. to equalize the CMake features/workflow between VS2019 and VSCode.

**Comment by bobbrow** [comment] 2019-07-24 16:05
@Zingam, we are tracking your issue #529 and do plan to do it but we haven't cooked up the timeline for that yet.  When we know with more certainty, we will assign it to a milestone.

**Comment by bobbrow** [comment] 2019-11-05 22:46
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.

**Comment by Zingam** [comment] 2019-11-07 20:31
Can this be made to support more than two levels of subfolders?
Folder3/Folder2/Folder1/CMakeLists.txt

If I select Folder3 get:
[cms-client] Configuring using the "Ninja" CMake generator with plattform "undefined" and toolset {}
[cms-client] Configuring using the "Ninja" CMake generator with plattform "undefined" and toolset {}

The reason why I want to do this is that I have:
Readme.MD and .gitgnore files inside of Folder2 and I want the `build` and any other VSCode generated stuff to go into Folder3 so that my sources remain clean of third party generated files for easy maintenance.

[Concepts3.zip](https://github.com/microsoft/vscode-cmake-tools/files/3821537/Concepts3.zip)

**Comment by bobbrow** [comment] 2019-11-07 23:36
The change simply activates the extension if a CMakeLists.txt is found in the workspace.  If your CMakeLists.txt is not directly in the `${workspaceFolder}`, you still need to set the `"cmake.sourceDirectory"` setting to `"${workspaceFolder}/Folder2/Folder1"` (where Folder3 == `${workspaceFolder}`).

Are you asking for a feature to automatically detect the root CMakeLists.txt?

**Comment by jaudiger** [comment] 2019-11-08 09:46
I was facing the same issue this morning. I tried to set `"cmake.sourceDirectory"` and it worked, thanks.

I think the message displayed is not relevant when the CMakeLists.txt is not found. For a first approach, it could be updated to point to this setting.

But the best approach in my case, would be to automatically detect the CMakeLists.txt in the workspace folder and prompts which one to use in case more than one have been found.

**Comment by Zingam** [comment] 2019-11-08 18:59
@bobbrow Yes, I also would like to have CMakeTools to dectect automatically the first root CMakeLists.txt
jaudiger's suggestion is also plausible.

**Comment by mcandre** [comment] 2020-11-19 19:03
Hilariously enough, the plugin prompts the user to "Don't ask again"... and then proceeds asks again, for every project.

**Comment by bobbrow** [comment] 2020-11-19 21:30
Yeah, the "Don't Show Again" button was intended to inherit the context of the question: "CMakeLists.txt was not found in the root of the folder \<foo\>. How would you like to proceed?"  It was only meaning "Don't show again for this folder", but I can see how that can be confusing.

**Comment by bobbrow** [comment] 2021-04-16 17:41
Starting work on this feature for 1.8

* In place of the "open file" dialog when the user chooses to "Locate" the CMakeLists.txt, we will present a "quick pick" drop down that contains the paths to all the CMakeLists.txt we found in the workspace.
* An additional option in the list would allow you to "browse" for a CMakeLists.txt which might be outside of the workspace.

**Closed** 2021-06-23 21:37 UTC
Labels: Feature Request, Feature: configure
