### ISSUE TITLE
Cannot navigate to Qt header files on Mac

### ISSUE THREAD

**Issue by Mactarvish** [microsoft/vscode-cmake-tools#2766] opened 2022-10-03 13:24 UTC
### Brief Issue Summary

Hi,
I'm on Mac with Apple M2 Monterey 12.5, my Qt version is Qt 6.4.0

When building Qt program with CMake, I've found that VS Code cannot navigate to any headers formed by <Qtxxx/qxxx.h> (But the compile can be done successfully), even if I added the file paths into `includePath`.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/13399458/193584476-29f9847f-b13d-49d4-97d3-ce6b743fdf78.png">

If you need to reproduce the issue, please download Qt 6.4.0 and directly build the `40000 chips` example using cmake (actually any example has such issue ~), then open the project using VS Code 1.71.2 

### CMake Tools Diagnostics

```shell
{
  "os": "darwin",
  "vscodeVersion": "1.71.2",
  "cmtVersion": "1.12.27",
  "configurations": [
    {
      "folder": "/Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip",
      "cmakeVersion": "3.24.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/clang",
        "CXX": "/usr/bin/clang++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/chip.cpp"
    ],
    "responses": [
      {
        "uri": "file:///Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/chip.cpp",
        "configuration": {
          "includePath": [
            "/users/mactarvish/qt/examples/qt-6.4.0/widgets/graphicsview/chip/build/chip_autogen/include",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtcore.framework/headers",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtcore.framework",
            "/users/mactarvish/qt/6.4.0/macos/mkspecs/macx-clang",
            "/users/mactarvish/qt/6.4.0/macos/include",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtgui.framework/headers",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtgui.framework",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtwidgets.framework/headers",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtwidgets.framework",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtprintsupport.framework/headers",
            "/users/mactarvish/qt/6.4.0/macos/lib/qtprintsupport.framework"
          ],
          "defines": [
            "QT_CORE_LIB",
            "QT_GUI_LIB",
            "QT_PRINTSUPPORT_LIB",
            "QT_WIDGETS_LIB"
          ],
          "compilerPath": "/usr/bin/clang++",
          "compilerArgs": [],
          "compilerFragments": [
            "-g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk",
            "-std=gnu++17"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 4,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "chip",
        "type": "EXECUTABLE"
      },
      {
        "name": "chip_autogen",
        "type": "UTILITY"
      },
      {
        "name": "chip_autogen_timestamp_deps",
        "type": "UTILITY"
      },
      {
        "name": "chip_other_files",
        "type": "UTILITY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

```shell
[main] Building folder: chip clean
[main] Saving open files before configure/build
[build] Starting build
[driver] Start build clean
[proc] Executing command: /opt/homebrew/bin/cmake --build /Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/build --config Debug --target clean --
[build] [1/2  50% :: 0.018] Cleaning additional files...
[build] [2/2 100% :: 0.071] Cleaning all built files...
[build] Cleaning... 9 files.
[cmakefileapi-parser] Read reply folder: /Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-24840389755d01bb81c9.json","cmakeFiles-v1-8432aee024388efdc10a.json","codemodel-v2-f7cb5c720952e4486534.json","directory-.-Debug-e241209d76be366daec5.json","index-2022-10-03T13-09-35-0710.json","target-chip-Debug-3b8e5902f90353da2c48.json","target-chip_autogen-Debug-4d94d2126a5abc6bac31.json","target-chip_autogen_timestamp_deps-Debug-dfd551424bebd020da47.json","target-chip_other_files-Debug-e02bc509fd8b1bdce4fd.json","toolchains-v1-cfed9536ba57e7a15da1.json"]
[build] Build finished with exit code 0
[cache] Reading CMake cache file /Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/build/CMakeCache.txt
[cache] Parsing CMake cache string
[main] Building folder: chip 
[main] Saving open files before configure/build
[build] Starting build
[driver] Start build all
[proc] Executing command: /opt/homebrew/bin/cmake --build /Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/build --config Debug --target all --
[build] [1/9  11% :: 0.443] Automatic MOC for target chip
[build] [2/9  22% :: 0.478] Running rcc for resource images
[build] [8/9  33% :: 0.739] Building CXX object CMakeFiles/chip.dir/build/.rcc/qrc_images.cpp.o
[build] [8/9  44% :: 1.674] Building CXX object CMakeFiles/chip.dir/main.cpp.o
[build] [8/9  55% :: 1.778] Building CXX object CMakeFiles/chip.dir/chip_autogen/mocs_compilation.cpp.o
[build] [8/9  66% :: 1.804] Building CXX object CMakeFiles/chip.dir/mainwindow.cpp.o
[build] [8/9  77% :: 1.842] Building CXX object CMakeFiles/chip.dir/chip.cpp.o
[build] [8/9  88% :: 2.717] Building CXX object CMakeFiles/chip.dir/view.cpp.o
[build] [9/9 100% :: 2.838] Linking CXX executable chip.app/Contents/MacOS/chip
[cmakefileapi-parser] Read reply folder: /Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-24840389755d01bb81c9.json","cmakeFiles-v1-8432aee024388efdc10a.json","codemodel-v2-f7cb5c720952e4486534.json","directory-.-Debug-e241209d76be366daec5.json","index-2022-10-03T13-09-35-0710.json","target-chip-Debug-3b8e5902f90353da2c48.json","target-chip_autogen-Debug-4d94d2126a5abc6bac31.json","target-chip_autogen_timestamp_deps-Debug-dfd551424bebd020da47.json","target-chip_other_files-Debug-e02bc509fd8b1bdce4fd.json","toolchains-v1-cfed9536ba57e7a15da1.json"]
[build] Build finished with exit code 0
[cache] Reading CMake cache file /Users/mactarvish/Qt/Examples/Qt-6.4.0/widgets/graphicsview/chip/build/CMakeCache.txt
[cache] Parsing CMake cache string
[extension] [2931] cmake.cleanRebuildAll finished (returned 0)
```

**Comment by Mactarvish** [comment] 2022-10-03 16:08
By the way, I checked the real path of every `#include` that vscode cannot find, and found that `qtguiglobal.h` actually is not under `QtGui`, but cmake can still compile it, how does cmake make it?

**Comment by bobbrow** [comment] 2022-10-03 22:16
The issue is that CMake doesn't tell us about the framework path so we can't tell IntelliSense to use it.  Issue #2324 (which I see you commented on) is the issue tracking this problem.  I will close this as a duplicate.

**Closed by bobbrow** 2022-10-03 22:16 UTC
