### ISSUE TITLE
Export extension API

### ISSUE THREAD

**Issue by tonka3000** [microsoft/vscode-cmake-tools#1364] opened 2020-07-11 15:42 UTC
Hey,

I want to use your API from my extension [tonka3000/vscode-qt-tools](https://github.com/tonka3000/vscode-qt-tools). Because I saw the file `api.ts` in the   `src` folder I assumed that I can get your API via `exports`, but when I get your extension the exports is `undefined`.

```ts
const cmaketools = vscode.extensions.getExtension("ms-vscode.cmake-tools");
if (cmaketools && cmaketools.isActive) {
	const bd = cmaketools.exports.buildDirectory();
	console.log(bd);
}
```

I check the `activate` function in `extension.ts` as found a [TODO comment](https://github.com/microsoft/vscode-cmake-tools/blob/bc9fc00ebdf27fe55c8d04ed9632c568a45ba3ba/src/extension.ts#L1134). Is it planed to export the API.

I have a [feature request](https://github.com/tonka3000/vscode-qt-tools/issues/17) which depends on that information from your extension.

Greetings

Tonka

**Comment by bobbrow** [comment] 2020-07-13 17:14
Thank you for your request.  This is a duplicate of #494.  Please go upvote that issue so we can track the demand.
 
It is on the backlog but not currently planned.  It was disabled when we took over maintainer responsibilities, but we haven't prioritized re-enabling it yet.  It was removed in anticipation of multi-root support which we later completed.

In the meantime, there are a few commands available you can call that may provide the information you need or allow you to drive the extension to a limited degree.

**Closed by bobbrow** 2020-07-13 17:14 UTC
