### ISSUE TITLE
settings.json "cmake.environment" not picked up in CMakePresets.json's "$env{...}" directives

### ISSUE THREAD

**Issue by commonbreed** [microsoft/vscode-cmake-tools#3525] opened 2024-01-04 23:01 UTC
### Brief Issue Summary

I find the vcpkg toolchain file using
```
"toolchainFile": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
```

and set `VCPKG_ROOT` in the "`cmake.environment`" field of my local `settings.json`, however this is not picked up and instead substitutes an empty string. I believe this is incorrect behaviour as the description of that field is "Environment variables to set when running CMake commands." - so this should apply.

**Comment by gcampbell-msft** [comment] 2024-01-16 14:39
Thanks for the issue. This is a duplicate of #2243, so I will close in favor of tracking that issue. 

However, we are currently working on making this to make it more clear and usable, and to fix any bugs. Thanks!

Closing as duplicate of #2243

**Closed by gcampbell-msft** 2024-01-16 14:39 UTC
Labels: triage
