### ISSUE TITLE
Stop prompting for kit on every project

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode-cmake-tools#1564] opened 2020-11-19 20:25 UTC
Please and thank you.

**Comment by andreeis** [comment] 2020-11-25 17:18
We are planning to fix the following related issue: https://github.com/microsoft/vscode-cmake-tools/issues/1007.
Before closing this one as a dupe of 1007, give us more details about the projects you see the quick pick show up, because there may be different scenarios than we are aware of.
Does it happen for projects that are not CMake? We have a popup that will give you the option to ignore the whole folder as being CMake and keep the extension in limited quiet invisible mode.
Does it happen for CMake projects that were or weren't previously configured, that had or hadn't already a kti defined?

**Closed** 2021-03-01 12:44 UTC
Labels: Feature: kits, duplicate, more info needed
