### ISSUE TITLE
Customisable location of the global, user-definded 'cmake-tools-kits.json' file

### ISSUE THREAD

**Issue by mbrunnen** [microsoft/vscode-cmake-tools#761] opened 2019-09-09 11:17 UTC
It would be nice, if the user can choose the location of that `cmake-tools-kits.json` file.
In my case I want to track all the vscode settings in a git repository, but this file is not trackable,
since it is completely elsewhere. A symlink could be a workaround, but then my setup cannot work out of the box.

I think you could keep the old file where it is and add a third, user defined file. Then there would be the pre-installed file, the user-defined file (maybe per default in the user-settings folder) and a workspace file. The user-defined file should be never overwritten by the scan.

**Comment by bobbrow** [comment] 2019-09-09 17:42
This sounds like a duplicate of #731.  There is a PR out for it right now.

**Closed by bobbrow** 2019-09-09 17:42 UTC
Labels: Feature Request, Feature: kits
