### ISSUE TITLE
Disable the extension when no CMakeLists is present

### ISSUE THREAD

**Issue by XsongyangX** [microsoft/vscode-cmake-tools#1578] opened 2020-11-30 20:55 UTC
Hello! I like this extension but sometimes I am not working on a CMake project in my workspace and this extension starts to search for kits and configurations right away. It would be nice if the extension would not aggressively start on every workspace in VSCode.

**Comment by bobbrow** [comment] 2020-12-01 17:00
Thank you for your issue report. I had thought we disabled the extension in cases where there is no CMakeLists.txt found, but we will go back and look at the code to see what is missing.

To help us understand better, are you opening a folder that happens to have a CMakeLists.txt buried in one of the subfolders?

**Comment by andreeis** [comment] 2020-12-01 21:10
I vaguely remember that there is some kits searching logic triggered before the project has the chance to first configure. We need to fix that, of course.
@XsongyangX , as a workaround you can select a kit, doesn't matter which one (let's say 'unspecified'), then you should see a popup notifying you that there is no CMakeLists found, with an option button to ignore for the current project. Press that and you should not see any activation happening after that. Let us know how that works.

**Comment by XsongyangX** [comment] 2020-12-01 22:25
> 
> 
> To help us understand better, are you opening a folder that happens to have a CMakeLists.txt buried in one of the subfolders?

I was in a leaf folder. So no subfolders.

@andreeis I'll try that next time.

**Comment by XsongyangX** [comment] 2020-12-04 19:28
I believe this issue is linked with #1564.

**Comment by andreeis** [comment] 2021-03-01 12:46
Fix in PR now. Duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/1007.

**Closed by andreeis** 2021-03-01 12:46 UTC
Labels: Feature: activation, IMPORTANT, bug, duplicate

**Comment by JanHildenbrandBosch** [comment] 2021-04-21 12:02
Can this in any way be disabled over a configuration? 
We are having currently the issue that the cmakelist.txt will be created after the extension is loaded. But then the extension bar is never loaded.

**Comment by bobbrow** [comment] 2021-04-21 16:02
@JanHildenbrandBosch this issue is closed so I moved your comment to a new issue.
