### ISSUE TITLE
Earlier preset in the inherits array not preferred in v1.17.16

### ISSUE THREAD

**Issue by voltamund** [microsoft/vscode-cmake-tools#3610] opened 2024-02-22 22:22 UTC
### Brief Issue Summary

An existing preset that I have used unchanged for a long time does not configure / build anymore since cmake-tools v1.17.16 has been installed. v1.17.16 uses the wrong value when multiple presets are inherited and provide different values for the same cache variable.

In the example below `preset3` gets `-DSOME_SETTING=value1` with cmake-tools v1.17.16.
When I downgrade to v1.17.15 `preset3` gets `-DSOME_SETTING=value2` (the same value that is used when I run cmake directly)

```
{
    "version": 2,
    "configurePresets": [
        {
            "name": "preset1",
            "hidden": true,
            "cacheVariables": {
                "SOME_SETTING": "value1"
            }
        },
        {
            "name": "preset2",
            "hidden": true,
            "cacheVariables": {
                "SOME_SETTING": "value2"
            }
        },
        {
            "name": "preset3",
            "inherits": [
                "preset2",
                "preset1"
            ]
        }
    ]
}
```

**Comment by jmigual** [comment] 2024-02-23 10:23
Sounds like a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/3603

**Comment by gcampbell-msft** [comment] 2024-02-28 15:13
This is fixed in the most release. Thanks!

**Closed by gcampbell-msft** 2024-02-28 15:13 UTC
Labels: triage
