### ISSUE TITLE
I keep getting "Not all open documents were saved. Would you like to continue anyway?"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#2889] opened 2022-12-07 00:22 UTC
### Brief Issue Summary

I keep getting "Not all open documents were saved. Would you like to continue anyway?" after updating. I'd like some way to stop getting that and default to Yes.

![image](https://user-images.githubusercontent.com/19859882/206055836-e264d7f8-77e7-40da-89b6-9567f3c48c65.png)

**Comment by elahehrashedi** [comment] 2022-12-09 15:48
Do you want to skip saving files before configure? can you use this setting? `"cmake.saveBeforeBuild": false` ?
Or are your files already saved and you are still getting this error?

**Comment by Manewu** [comment] 2022-12-13 11:03
I have the same problem. After pressing "Build" the changed files are saved automatically because "cmake.saveBeforeBuild" is true, but  then I still get this message. I think that behavior is relatively new, maybe came in with the latest Update (7.12.2022)?

**Comment by sean-mcmanus** [comment] 2022-12-13 18:40
I get the error when I'm not doing a build, so it seems like the `"cmake.saveBeforeBuild": false` setting may not work, but I could try. I don't care if the file is saved or not -- in my case I'm typically changing a source file, so it won't impact configuring.

Yeah, I only started noticing this a week or so ago.

**Comment by elbrandt** [comment] 2022-12-21 21:39
I have the same problem, and it started appearing around a week or two ago as well.
My hypothesis was that it has something to do with format-on-save, but I have not tested this hypothesis.

**Comment by my-name-is-already-taken** [comment] 2022-12-22 14:26
I have observed the same problem. For me, it only appears when I have a diff tab open that contains unsaved changes. To reproduce:
- Open a Folder that contains a git repository
- Modify some file
- Save the file
- Modify the file again, without saving it this time
- Open a diff tab via the source control panel
- Compile the project

**Comment by Manewu** [comment] 2022-12-22 15:03
Yes, I can confirm that, changed file has to be open normally and in a diff tab at the same time. Good to know:-).

**Comment by elbrandt** [comment] 2022-12-23 18:50
FYI, I am experiencing this with no diff windows open.

**Comment by TheJCAB** [comment] 2023-01-04 01:47
It's happening to me too. Diff windows open are a pretty normal thing for me, so likely related.

Note that just hitting build again does start the build (because the files were indeed saved), even if the message is still there. Seems like some sort of data race between the file save and the build proper.

Annoying but not blocking. But annoying :-).

**Comment by notskm** [comment] 2023-01-06 12:06
> It's happening to me too. Diff windows open are a pretty normal thing for me, so likely related.

I do not think diff windows are the root cause of this. I get this error constantly regardless of whether I have diff windows open or not. My guess is that we're triggering builds before VSCode finishes saving files and CMake Tools is failing to wait.

**Comment by bobbrow** [comment] 2023-01-06 18:29
The logic that pops up this message is based on the result of calling a VS Code API.  It sounds like something may have regressed in VS Code.

```ts
            const success= await vscode.workspace.saveAll();
            if (!success) {
```

**Comment by bobbrow** [comment] 2023-01-06 22:31
I've tried to reproduce this on both Stable and Insiders builds of VS Code, BTW, with no luck.  Is everyone on this thread using version 1.12.27 of the CMake Tools extension, or is anyone using the pre-release (1.13.*)?

> I get the error when I'm not doing a build, so it seems like the `"cmake.saveBeforeBuild": false` setting may not work, but I could try.

@sean-mcmanus Can you write repro steps for this?  I see a potential problem with running a build while there is an unsaved change in CMakeLists.txt which will cause it to try to reconfigure during the build, but that shouldn't cause the save to fail (and it doesn't fail for me in my testing).  `cmake.saveBeforeBuild` set to `false` disables this codepath in my testing too.  I'm on the main branch though, so this testing does not apply to 1.12.27.

**Comment by sean-mcmanus** [comment] 2023-01-06 22:47
@bobbrow Yeah, I know my repro steps -- I'll send them after confirming it still repros.

**Comment by sean-mcmanus** [comment] 2023-01-06 23:13
@bobbrow I'm not reproing the bug now -- maybe it was some bug with VS code? If you can't get a repro from other users you can close this.

**Comment by elbrandt** [comment] 2023-01-06 23:20
This is definitely still happening with me, please don't close it.
I am running CMake Tools v1.12.27, and vscode 1.74.2

To me it feels like a race condition as notskm and theJCAB commented. 

It doesn't happen all the time when I hit F7 to build, probably 50-75% of the time.

**Comment by notskm** [comment] 2023-01-08 08:45
> I've tried to reproduce this on both Stable and Insiders builds of VS Code, BTW, with no luck. Is everyone on this thread using version 1.12.27 of the CMake Tools extension, or is anyone using the pre-release (1.13.*)?

I'm on 1.12.27.

**Comment by elbrandt** [comment] 2023-01-08 11:49
Also, this same thing happens to me sometimes when I do Ctrl+Shift+P -> CMake: Select Variant -> {pick a variant} -> "Not all documents were saved..." warning appears.

**Comment by elbrandt** [comment] 2023-01-08 11:54
As another bit of perhaps relevant info... I am working in C++ projects, and I have a .clang-format file which is used to format-on-save. Perhaps this task is still running when cmake tools tries to start the build? Are others who are experiencing this also using format-on-save?

**Comment by edwardbr** [comment] 2023-02-03 15:29
done a fresh download today still happening

**Comment by my-name-is-already-taken** [comment] 2023-02-08 09:08
I can confirm that I also still experience the problem, using v1.13.45.

The problem still always occurs when a diff tab with unsaved changes is open, but I also get this error sporadically without any read only tabs open.

Also, I do not use format-on-save.

**Comment by rjra100** [comment] 2023-03-15 10:34
I'm seeing it too; VSCode 1.76.1; CMake tools 1.13.45 (not sure when it started, but I'd agree that it's comparatively recent). My impression is also that it's most likely a race condition - I can reliably reproduce it as follows:
- Enable Save Before Build
- Open a file
- Open a diff window on the same file
- Make an insignificant change to the file in either editor; don't save yet
- Hit build.
- File saves, but "Not all open documents were saved" also pops up.
I'm also seeing it when all the files were, as far as I know, saved before hitting build, but I can't consistently reproduce that so it may just have been that I failed to save something.

**Comment by kupix** [comment] 2023-05-18 08:27
I get this several times a day. It happens when trying to build if both an edit tab and a diff tab are open on the same file. I'm guessing that vscode counts the number of tabs with modifications.... e.g. there are two. It saves the first modified file (which also has the effect of negativing modifications on the other tab). My theory is that its logic is: "there were two _tabs_ with modifications, and I have only saved modifications to one _file_ ... thus I failed".

**Comment by roddypratt** [comment] 2023-08-16 14:00
Same here. VS Code 1.18.1 on Windows, plugins up to date.

Often happens when I select "Build".  The open documents do get saved as expected, and "Build" a second time works without issue.

**Comment by KenSykes** [comment] 2023-09-22 15:41
This happens to me daily and feels like a race condition between VS code and CMake extension. Could easily be a regression in VS code. Don't remember when it started happening but still happens on VS code 1.82.2 / CMake extension 0.0.17 / CMake tools extension 1.15.31.

**Comment by tonygould** [comment] 2023-11-09 19:27
Happens to me frequently -- to the point I've gotten into the habit of Ctrl-S before F7. I develop in dev containers, in WSL or ssh-ing into a linux box. My computers were 6-7 years old, and often it would take 0.5 to even a few seconds to save with formatting. Just got a new, fast computer today and hoped the problem would go away, but it just occurred again :(, working in a dev container in WSL.

I'm guessing the key point for me is that I have format-on-save turned on, which slows down the save.

**Closed** 2024-02-13 20:30 UTC
Labels: bug, fixed (release pending), blocked-by-external
