### ISSUE TITLE
IntelliSense using cmake-tools configurationProvider does not seem to work

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-cmake-tools#2573] opened 2022-05-27 04:25 UTC
### Brief Issue Summary

I have a multi-project repo in which code in one directory links with libraries (and depends on their headers) in another directory, and have CMake projects set up to build each directory, with their targets exported and everything so they can find each other.

I got a multi-folder workspace in VS Code working, and set up `cmake-tools` to be able to build my projects, but if I set the `configurationProvider` for IntelliSense to `cmake-tools`, it can't figure out where to find my headers, and basically breaks IntelliSense. Is this `configurationProvider` thing supposed to work this way?

I generated a `compile_commands.json` file and that made IntelliSense work, but I was hoping that IntelliSense could get that information directly from the extension. Am I using it wrong?

I am not sure what diagnostic information would be helpful, but I can get it if someone can guide me.

**Comment by elahehrashedi** [comment] 2022-05-27 16:51
Can you please give us an outline of what the project structure looks like? and also which folder is open?

**Comment by leifwalsh** [comment] 2022-05-27 21:57
I can't copy a project out but I can describe it:

Suppose we have two directories in the repo, foo and bar. foo contains foo.cc and foo.hh, and cmake build rules to build libfoo.so and install foo/dist/lib/libfoo.so and foo/dist/include/foo.hh, plus cmake config exporting those targets in foo/dist/share/cmake. 

Our outer build infrastructure knows about a dependency from bar on foo, so it configures bar so that foo/dist is on CMAKE_PREFIX_PATH so it can link with libfoo. I can build both foo and bar as separate cmake projects. 

Now, I open the whole repo as a multi-folder workspace, configuring both foo and bar as workspaces, and pointing cmake-tools at the configured build directories for each, and with the buttons provided by cmake-tools, I can use them to drive the build of each (modulo #2569, which requires setting the legacy communication mode right now). But if I open a source file in bar, it can't find foo.hh and gives me a red squiggle saying my configuration is wrong.

**Comment by bobbrow** [comment] 2022-06-03 18:43
If you would be willing to share a small example project that sets up this import/export the way you want it to work, we can investigate and see why we are unable to get the include path from CMake.

**Comment by leifwalsh** [comment] 2022-06-15 18:40
I've been struggling to reproduce a clean room version of this, but I have a question that might help with intuition here. 

How is the header search path determined for a header file? In general, I'd think the search path would be associated with a translation unit, and depending on which translation unit is including a header a.h, headers that a.h includes might be found by searching different paths.

**Comment by leifwalsh** [comment] 2022-06-15 18:42
We are using the new feature in cmake 3.23 where you can associate public headers with a library using `target_sources(... FILE_SET HEADERS)`. The old way to associate headers with a library is to set `INTERFACE_INCLUDE_DIRECTORIES`, and I have a mild hunch that cmake-tools doesn't understand the new data model, or something.

**Comment by bobbrow** [comment] 2022-06-15 18:47
You are correct that we do not have any code that understands file sets yet.

**Comment by bobbrow** [comment] 2022-06-15 18:54
The way we build up the include path is by instructing CMake to generate some json files with the project/target information in them.  We pull the includes from this section of a `target-<name>-<buildType>-<hash>.json` file that lives in your build directory under the `.cmake/api/v1/reply` folder.

```json
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : "/DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd"
				}
			],
			"includes" : 
			[
				{
					"backtrace" : 2,
					"path" : "D:/test/cmaketest/sub1"
				}
			],

```

**Comment by leifwalsh** [comment] 2022-06-15 19:07
Ok, here is what it looks like 
![image](https://user-images.githubusercontent.com/46406/173905073-0e09f2ee-4af2-44ef-a545-78138aaec83b.png)

My reproducer is at https://github.com/leifwalsh/vscode-cmake-multi-project-bug and you can open it in codespaces (make sure you open the code-workspace file), but it's a little fiddly. If I open the project in a clean codespace, build (and install) the lib subproject, then open app/src/cli.cc, it can't locate fib.hh. But if I build the app subproject, that squiggle goes away and I can navigate to fib.hh from cli.cc. 

Internally, the squiggle is persistent even after building everything, and I'm not sure what else is different between our internal code and this reproducer.

**Comment by leifwalsh** [comment] 2022-06-15 19:08
Ok, that's good to know, I'll try to poke around in that directory to see what the api responses are. Thanks!

**Comment by leifwalsh** [comment] 2022-06-15 20:48
<details>
<summary>Diagnostics</summary>
```
{
  "os": "linux",
  "vscodeVersion": "1.68.1",
  "cmtVersion": "1.11.26",
  "configurations": [
    {
      "folder": "/workspaces/vscode-cmake-multi-project-bug",
      "cmakeVersion": "3.23.2",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/workspaces/vscode-cmake-multi-project-bug/app",
      "cmakeVersion": "3.23.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/workspaces/vscode-cmake-multi-project-bug/lib",
      "cmakeVersion": "3.23.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "CXX": "/usr/bin/c++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///workspaces/vscode-cmake-multi-project-bug/lib/src/fib.cc",
      "file:///workspaces/vscode-cmake-multi-project-bug/app/src/cli.cc"
    ],
    "responses": [
      {
        "uri": "file:///workspaces/vscode-cmake-multi-project-bug/lib/src/fib.cc",
        "configuration": {
          "includePath": [
            "/workspaces/vscode-cmake-multi-project-bug/lib/src"
          ],
          "defines": [
            "fib_EXPORTS"
          ],
          "compilerPath": "/usr/bin/c++",
          "compilerArgs": [],
          "compilerFragments": [
            "-g -fPIC",
            "-std=gnu++20"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 3,
    "executablesCount": 1,
    "librariesCount": 2,
    "targets": [
      {
        "name": "catch2",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "fib",
        "type": "SHARED_LIBRARY"
      },
      {
        "name": "fib_tests",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```
<details>

Also, the directory `.cmake/api/v1/reply` doesn't exist. After I build the app subproject, it does, and then the squiggle goes away.

**Comment by bobbrow** [comment] 2022-06-15 21:28
`app/build/.cmake/api/v1/reply` needs to exist for us to get the IntelliSense configurations for that target.  You have to configure both folders before the folder is created.  Doing a build forces the configure step to happen so that seems to explain why it appears after a build.  You can also use the `CMake: Configure All Projects` command to set it up before the build.

However, the squiggle shouldn't go away at this point because CMake Tools didn't provide the configuration for that file - at least according to the log you shared.

**Comment by leifwalsh** [comment] 2022-06-15 21:47
Let me be a little bit more careful about when things happen.

When I first open the repo, it tries to configure both subprojects. The lib project configures fine, but the app project fails because it can't find libfib's cmake config. This is expected, because I need to install the lib project first. So, I build the install target in that subproject.

After this, `app/build/.cmake/api/v1/reply` still doesn't exist, and I get the diagnostics I posted in my previous comment, and I get the squiggle on `#include "fib.hh"` in `cli.cc`. 

If I now use "Click to select the active folder" to switch to the app subproject, this re-runs the configure step, and now that exists. Now, I see this:

<details>
  <summary>`cat app/build/.cmake/api/v1/reply/target-cli-Debug-dd273dbcafce3c1a219d.json`</summary>

  ```
  {
          "artifacts" : 
          [
                  {
                          "path" : "cli"
                  }
          ],
          "backtrace" : 1,
          "backtraceGraph" : 
          {
                  "commands" : 
                  [
                          "add_executable",
                          "install",
                          "target_link_libraries"
                  ],
                  "files" : 
                  [
                          "CMakeLists.txt"
                  ],
                  "nodes" : 
                  [
                          {
                                  "file" : 0
                          },
                          {
                                  "command" : 0,
                                  "file" : 0,
                                  "line" : 10,
                                  "parent" : 0
                          },
                          {
                                  "command" : 1,
                                  "file" : 0,
                                  "line" : 13,
                                  "parent" : 0
                          },
                          {
                                  "command" : 2,
                                  "file" : 0,
                                  "line" : 11,
                                  "parent" : 0
                          }
                  ]
          },
          "compileGroups" : 
          [
                  {
                          "compileCommandFragments" : 
                          [
                                  {
                                          "fragment" : "-g"
                                  },
                                  {
                                          "fragment" : "-std=gnu++20"
                                  }
                          ],
                          "includes" : 
                          [
                                  {
                                          "backtrace" : 3,
                                          "isSystem" : true,
                                          "path" : "/workspaces/vscode-cmake-multi-project-bug/lib/dist/include"
                                  }
                          ],
                          "language" : "CXX",
                          "languageStandard" : 
                          {
                                  "backtraces" : 
                                  [
                                          1
                                  ],
                                  "standard" : "20"
                          },
                          "sourceIndexes" : 
                          [
                                  0
                          ]
                  }
          ],
          "id" : "cli::@6890427a1f51a3e7e1df",
          "install" : 
          {
                  "destinations" : 
                  [
                          {
                                  "backtrace" : 2,
                                  "path" : "bin"
                          }
                  ],
                  "prefix" : 
                  {
                          "path" : "/workspaces/vscode-cmake-multi-project-bug/app/dist"
                  }
          },
          "link" : 
          {
                  "commandFragments" : 
                  [
                          {
                                  "fragment" : "-g",
                                  "role" : "flags"
                          },
                          {
                                  "fragment" : "",
                                  "role" : "flags"
                          },
                          {
                                  "fragment" : "-Wl,-rpath,/workspaces/vscode-cmake-multi-project-bug/lib/dist/lib:",
                                  "role" : "libraries"
                          },
                          {
                                  "backtrace" : 3,
                                  "fragment" : "/workspaces/vscode-cmake-multi-project-bug/lib/dist/lib/libfib.so",
                                  "role" : "libraries"
                          }
                  ],
                  "language" : "CXX"
          },
          "name" : "cli",
          "nameOnDisk" : "cli",
          "paths" : 
          {
                  "build" : ".",
                  "source" : "."
          },
          "sourceGroups" : 
          [
                  {
                          "name" : "Source Files",
                          "sourceIndexes" : 
                          [
                                  0
                          ]
                  }
          ],
          "sources" : 
          [
                  {
                          "backtrace" : 1,
                          "compileGroupIndex" : 0,
                          "path" : "cli.cc",
                          "sourceGroupIndex" : 0
                  }
          ],
          "type" : "EXECUTABLE"
  }
  ```
</details>

<details>
  <summary>CMake: Log Diagnostics</summary>

  ```
  {
    "os": "linux",
    "vscodeVersion": "1.68.1",
    "cmtVersion": "1.11.26",
    "configurations": [
      {
        "folder": "/workspaces/vscode-cmake-multi-project-bug",
        "cmakeVersion": "3.23.2",
        "configured": false,
        "generator": "Ninja",
        "usesPresets": false,
        "compilers": {}
      },
      {
        "folder": "/workspaces/vscode-cmake-multi-project-bug/app",
        "cmakeVersion": "3.23.2",
        "configured": true,
        "generator": "Ninja",
        "usesPresets": false,
        "compilers": {
          "CXX": "/usr/bin/c++"
        }
      },
      {
        "folder": "/workspaces/vscode-cmake-multi-project-bug/lib",
        "cmakeVersion": "3.23.2",
        "configured": true,
        "generator": "Ninja",
        "usesPresets": false,
        "compilers": {
          "CXX": "/usr/bin/c++"
        }
      }
    ],
    "cpptoolsIntegration": {
      "isReady": true,
      "hasCodeModel": true,
      "activeBuildType": "Debug",
      "buildTypesSeen": [
        "Debug"
      ],
      "requests": [],
      "responses": [],
      "partialMatches": [],
      "targetCount": 1,
      "executablesCount": 1,
      "librariesCount": 0,
      "targets": [
        {
          "name": "cli",
          "type": "EXECUTABLE"
        }
      ]
    },
    "settings": [
      {
        "communicationMode": "automatic",
        "useCMakePresets": "auto",
        "configureOnOpen": true
      },
      {
        "communicationMode": "automatic",
        "useCMakePresets": "auto",
        "configureOnOpen": true
      },
      {
        "communicationMode": "automatic",
        "useCMakePresets": "auto",
        "configureOnOpen": true
      }
    ]
  }
  ```
</details>

and the squiggle is gone.

But this isn't quite what's happening internally, I need to switch machines and poke around in that environment next.

**Comment by leifwalsh** [comment] 2022-06-15 22:12
Ok, internally I don't see the `.cmake` directory at all, and log diagnostics says it is sending requests but hasn't gotten any responses. I think this is because I'm using the legacy communication mode to work around https://github.com/microsoft/vscode-cmake-tools/issues/2569. 

In the legacy mode, is there a way to get more diagnostic info like that? Or should I wait to see !2569 fixed and then try this again and see if it's still a problem internally? 

I guess I can try switching to legacy mode in my repro codebase too.

**Comment by bobbrow** [comment] 2022-06-15 23:00
The legacy mode doesn't provide IntelliSense configurations.  I was looking at #2569 and the fix looks trivial.  Just need to add a `cwd: this.binaryDir` to the execution options object.  You could test it out on your machine by patching the extension's `main.js` file if you feel brave.  I'll put out a PR after my next meetings and I could also produce a test build of the extension if you'd rather install that instead.

The `main.js` should live in a folder like this: `~/.vscode/extensions/ms-vscode.cmake-tools-1.11.26/dist`.  Search for:
```
this.executeCommand(cmake, args, outputConsumer, { environment: env })
```
and replace it with:
```
this.executeCommand(cmake, args, outputConsumer, { environment: env, cwd: this.binaryDir })
```

**Comment by leifwalsh** [comment] 2022-06-15 23:44
I'll test that out tonight, thank you!

**Comment by bobbrow** [comment] 2022-06-15 23:44
It looks like the cwd was added for the legacy driver but not the file api driver in this PR: #2292, so this behavior has only been around since 1.10.  Is running from the build directory the expected behavior for newer versions of CMake?  I would have expected the cwd to be the source directory, which is where I normally run cmake from when I'm on the command line.  But it shouldn't really matter because we pass in the paths to both the source and build directories.

In the issue you linked, you mention a tool that depends on the working directory being set a specific way.  Since working directories are unstable, would it be better to have the tool be based off of the source or build directories instead?  (I'm not actually sure how your tool works, but if it runs as part of your CMakeLists.txt script, I would think those paths would be available for you to use)

**Comment by leifwalsh** [comment] 2022-06-16 00:57
Yeah, normally it doesn't matter where you run cmake, I personally usually run it from the build directory and pass the source dir as a positional argument (old habit), but any of them work. 

Our tool is actually cmake itself. We have a framework (which we're hoping to open source at some point, but it's not complicated) almost like direnv, but not quite, whose goal is actually to make the configuration of ides (that shell out to well known commands like cmake or mvn or yarn) simpler. 

We have a monorepo, but that doesn't matter a whole lot here, what matters is that which version of all your dependencies you get is fully specified in the code (to avoid "works on my machine" problems). Depending what you are working on, you might need make 3.17 or 3.23 or something, and our sdlc systems know how to find one for you. What we want to avoid needing to do is learning the config format of every ide so we can tell it which cmake to use (in fact, in JetBrains the SDKs are not per-repository configurable in the way you'd want, but VS Code is usually better about this). 

So, our system installs a bit of configuration in each project that locates its SDKs (again, stuff like cmake, gcc, and so forth). Then we have a sort of trampoline script that you symlink as all the sdks you're going to use in a directory early in your PATH, so that trampoline script is actually what runs when you run `cmake` unqualified. It starts up, looks around its environment, finds you local config directory, and reexecs the proper version of cmake instead. 

So, what we need is for the binary found when the shell searches `PATH` for `cmake` to run "near" the code it's operating on, so it can find that config dir. In a multi-folder workspace, this means inside the folder (but anywhere within will do); if it runs at workspace scope it doesn't know which folder's config to choose. 

I know this sounds like maybe a bit of a funny system but it works *really* well in practice: command line users don't even notice it's doing anything special, they just don't have to configure paths for anything. And, using the legacy communication mode, VS Code just worked with no manual configuration. 

For administrators, it's also a really nice point in the trade off space. We don't have to learn every IDE's config to figure out how to aim it at the right tools, and we also aren't writing wrapper scripts for the tools (for which we'd have to reimplement their argument parsing at least a little bit, for example to parse out `cmake -S` to know which project you're configuring).

So, what we need is for the configure step to run either in the folder being configured, or the source or binary dir, or for it to be (globally) configurable (we'd choose `${workspaceFolder}`). Does that make sense?

**Comment by leifwalsh** [comment] 2022-06-16 02:24
Yes, that patch helps: with it I can take off legacy mode and am able to configure, and even get hover and navigation across headers in different projects. I did observe https://github.com/microsoft/vscode-cpptools/issues/6149 again, but I killed that process and let it restart itself and was then able to navigate.

**Comment by leifwalsh** [comment] 2022-06-16 16:33
yeah, that would work just as well, thanks!

**Comment by bobbrow** [comment] 2022-06-16 17:36
Thanks for confirming.  I will close this as a duplicate of #2569 and get a PR out for that soon.

**Closed by bobbrow** 2022-06-16 17:36 UTC
Labels: more info needed, Feature: cpptools integration, Feature: multiroot

**Comment by leifwalsh** [comment] 2022-06-16 18:37
Ok, either way, thanks again for talking me through it. Knowing these diagnostics will be helpful too.
