### ISSUE TITLE
[rollbar] messages

### ISSUE THREAD

**Issue by decimad** [microsoft/vscode-cmake-tools#505] opened 2018-08-02 07:16 UTC
Beginning since yesterday I'm seeing multiple "[rollbar] Unable to automatically determine compiler" messages, one for each custom target, when building through cmake-tools. Is there anything I can do to hide/suppress these?

**Comment by vector-of-bool** [comment] 2018-08-02 18:19
At the moment, there is not, but it does indicate that there is definitely a bug in CMake Tools. You may need to work-around this bug, which will suppress the messages. Can I get more information about your setup?

**Comment by Randshot** [comment] 2018-08-04 16:36
@decimad Can you maybe provide an example project that displays the behavior you described above? This would make debugging this much easier!

**Comment by vector-of-bool** [comment] 2018-08-04 18:58
The toolchain file is a likely culprit. CMake Tools uses the cache value for the compilers to get the language compiler. In your toolchain value set the `CACHE` flag when you set the `CMAKE_C/CXX_COMPILER`. That's a known workaround, and I want to look into the bug because it's actually quite common.

**Comment by apples** [comment] 2018-08-05 09:55
I'm experiencing this issue when using the Emscripten toolchain on Windows. Easy to reproduce.

CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.12)
project(hello-emscripten)
add_executable(hello-emscripten main.cpp)
```

main.cpp:

```cpp
int main() {}
```

cmake-tools.json:

```json
[
  {
    "name": "Emscripten",
    "toolchainFile": "C:\\emsdk\\emscripten\\1.37.36\\cmake\\Modules\\Platform\\Emscripten.cmake"
  }
]
```

Output:

```
[cms-client] Configuring using the "Ninja" CMake generator
[cmake] Configuring done
[cmake] Generating done
[rollbar] Unable to automatically determine compiler {"lang":"CXX","fileGroup":{"compileFlags":"-g  ","isGenerated":false,"language":"CXX","sources":["main.cpp"]}}
```

**Comment by mmanyen** [comment] 2018-08-06 15:32
I ran into this problem as well. Went away as soon as I got the toolchain right and cached.

**Comment by vector-of-bool** [comment] 2018-08-14 04:48
Looks like the source of this bug has been determined, but the best course of action to a fix is an open question. I haven't forgotten about this one!

**Comment by gcampbell-msft** [comment] 2024-03-27 16:13
@mmanyen @apples This issue is very old, is it still presenting for you? If not, I'd like to close this issue.

**Closed** 2024-06-03 21:03 UTC
Labels: bug, Feature: configure, quick fix
